apiVersion: v1
kind: Secret
metadata:
  name: recyclarr-config-r2-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:bZ2HAqFXK2JjsPUtpUhjEwzQ9GhcAF/v7C7qlVkxgrxZ9qAu4IJYvIVWZpao4diQ6araCnZcOL0jkWWuFSyoU3+T9SzEFd7ZSNN6BeBbJyBWGlMBpO7EdVFrLuuN9izGyFG3JJXOXZQ=,iv:WxSZfoM8y4MNXbMSzhq4t8DViNMPpR+WAY7n3OgNTgw=,tag:6Fy69z8fQzKh3JTgz8yKhg==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:M6ndiJbKBFa0U/MEpsPgNMDoQC9PWOat0ML0Pcx5N9AeqIOTm7NB6/f3DvA=,iv:EVxdU47Xr4dw8BEWRh3irQJfLk1KWqlX7vf6mGTTK9U=,tag:qoFL9TfKX2ATUidAkFLHGA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:bpBxGH5bYfLlSIoRH57Jm5gtNy0lu6rFYBFD/XJwTkg=,iv:TQm1nwXAR329uCumZF0wkpNP7Ze0fqfQW/TIrcaAl+U=,tag:wMrEjS+dIj0yzy+2lbzdIg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:lSkfd7Pl4jEmE2e9HKXyIVWvLQ5x689/Y/Ce2Eez5+UMb807jMaWhfCbm8AU90AYslCfzuzz7iZKeoklzBw4bg==,iv:yD+UVfyJ9NnSNlrkKUzaii1BrFd1ofsnQ0irsQV5O60=,tag:n/LhgfMhSoxc/bixHM4K3w==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:P1ptow==,iv:uqvWMXFRV+OWtQL7M4k+UUXsqrZHY5/cXtMZbxmHEec=,tag:Ke3qNrvwro+1hsQyeeoJxw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtd0VWVjRNVzZhYWltaURS
        OVhxT1JrTzh6QnlBTFNrYm9EM3paNnZPZ1hnCm15cjRCcXVKS3JVZHFseWtxU3NQ
        aGFwWXhydGViazRxTllGem5ESEVVMFkKLS0tIG1UQUI4MVhwZ0xSNC9hbThnU3M2
        YkJvNjNEZDU1bUNrSW5ncXJxZnM1bHcKTjCbpH/l+1g39iH1BqBdtlU487TVOXly
        VdUURJkyn/lRhYdOjSG5V5eOgqFG9RA2Im/4NDnMVG7rzz92xxHkSA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-27T10:36:53Z"
  mac: ENC[AES256_GCM,data:S2lCsMpjOlDBB4h2aeI/L/iOoXEngPT2GSdYwSachnd4PWMBnJqf2NkUByhwRLKY3ykHdXopxiNdkWJ/r4t2CqcK9OHZTDe2DSL62iNR7ecy//fnciq9dHl1gVcs59bal0Gc2qRwrWZXP00x4atKBvZvk5mHz4qH7xdq2/hmRnM=,iv:tOhZxqQHpojlXYQqf96ZrsiZn4C9aAISOEgPM+ZfxfQ=,tag:kgZpVzJm4Xlh5q6IYBFY/w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
