apiVersion: v1
kind: Secret
metadata:
  name: recyclarr-config-r2-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:0riYnujYEd/zlbxKRdA9cZF2TiDTGIoEJ0HnGLqAaVzc0gqs11/aZNYWF2+0nmPTsr/oQvNLl/N0wiBSY9GAMhTnqXI2AYnrDxn1sr/tiKMxeOCo+ix5GoUqtFF6MiarNqYK6wdpYvk=,iv:++b7MkdA8ClugyoCYhRJHtaq+smdRdiVjVDMZIIny+w=,tag:5dmUtKGyEc6hFo4CfDKjww==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:XNK+qMlBb/zBEo1m5do5B7uGmKJQmukzEFsywbnYR+lzfaoNymTKYQ3O/DU=,iv:ERHAkT1rntTL1vPQvKCaIxRbCnoc3RhaBVXrZ8C4mVE=,tag:6lNNIhDIZCV02HLWbAGUUA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:yNWsQgrsoeVXhaRC156YDQxfgYSzJaXJ/2YVX+Qm0p8=,iv:RAXusyxYUCE3XFgXyLU6iT/a0D+gN/wmVoNqX67iop8=,tag:ixlv7eRR7em7QCep/edUeg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ehO52xFRw9w7Jaaxl0Bljoe1ICe5AR1RhS95RcPooVZ4dnrOesbCqm/swfsSyy+cSkSDX1+zWGIGflOaY5HIFg==,iv:MeOcymEm/I6FZyUejpZEo5OrJhTc/hoCCZy80ZWqliI=,tag:YXIgDzueW7mg923V5+T7uQ==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:9z2fXQ==,iv:l/U1yNFQ7oGx/ZraLyT/d2i2lUcWSkbh77ze13H16WU=,tag:vt63ODvp3GOdR8xAqM097Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWE93ZlJBcVJ0TkFGR0RP
        bDdONHY3Sndsc3Z6b3NPM2pEdjBFc1VsUzJrCm84UTIwaVdXbDdOdW9ZM1g1bU5J
        cVR1ZHRicmwrdkxuWFp3eWJ4TUlYck0KLS0tIDVYM0szTUUwaTAxeEZhclJDVG1Q
        WWZCakdLcjBmREJUK1FYblNpRE4xY2sKa9+szW7F2VfsvjuqmJ0HRNf0FGiqizMP
        do1V/duOfs6TQccg/h4csxptk7SVkB3hHZkIiOZdzPBW8Ls6ddA5TQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-24T17:01:23Z"
  mac: ENC[AES256_GCM,data:/73RxbIn4qdDg9zX1CNFGlTDx5Se1NgmhtpkgtFdNXGmFzvRlhL4EedfD71pzdWvGlHhutBjnNjsgqqR4AH6eGfU4GagBbAgkWR/6p/XTGQBryUFVxormJN3TSaXJZ6NYqN7rvofuh5mcTVIYn8pmnYcM9lmUiekLNooj7n7dZ4=,iv:mOEnJioCfjUwf0k50tY1f+BZ+yy5HIwURrM8RfwajhE=,tag:Q02lN82xWDj9IvX11nb9rw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
