apiVersion: v1
kind: Secret
metadata:
  name: recyclarr-config-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:e2+LSx7JJYC/pK2Ozfcl0AfRGankhjIebWdb17NyvkNu4kA+4QTCHRqtHMvcgDsSiYd9GY/mgYEJQwbxuNihbSQcPrN5Ky8Z8TtrONNLEsOHu1I=,iv:+RIDnQZwaJtu2LvGhii855lhwZasr+we24UWne22j1s=,tag:CR3srEcr0q9Xrdu+b0srZA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:2cJ1p5gguxvMYArWpBiEnMdbf9Ggs4rihng/Nxiaazbfxr0zLKUmmL5WsYA=,iv:3QynXkjWd5W7QCA1Fk5BdTCmXaBRaXoqc5AvOX+O5/Q=,tag:SRqr9qhG3JdRMYTzFARgpw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ivYIlhF+K2Hn1NI+uv1aVkaDR3QUczZoEPo=,iv:O/WzR5UM3FWCogCyZi2HRSJ2fkNATaC3wiXFHkrRMOg=,tag:owqhIRzZ7k9VF6y7+B5bEw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:eZHYutSR5CmawGXkEgvA9AXF5SgGBLXJyNGen0xmCajqM3+4WWPPSawzjA96z03dhXxUMbfpFWDqHgdVctQg7Q==,iv:m45E4AwtKHDEEoADwBjQdCUXtMmXTKBNuF+XGrbq+lQ=,tag:uYvK+fPcwL+9wzAwWUNAfQ==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ckRXTFNhcS80eEhoakJG
        RkRuRmZicUFFaVpHUHVsRTRvem52dEN3Q0dVCmdnTWpNUXdaZGRncy9mNkJXMjVa
        YTArZVUzN0YrTWcxNjljYUMzT1ZNSUEKLS0tIERrb3phUUdaeFVNU2kyV3B3RVdS
        MU94eEs4KzIxUFFQdEV0ZmlqeSt3dkkKys3NgB9CcDHWlGqmIJFLXfMU8ReYskQU
        lgI5JG/Spohq764/cMIWeVTCuW6KWc/MQ2WyZ5esugSm+HH98RXbAw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-21T10:14:08Z"
  mac: ENC[AES256_GCM,data:uqpb7nNRL6/DCfNFZ6+sInvJkqZ2YqeIFjwez9gLhoR2plNOVPF4F1MnSn15K6O8qBPLpy6s4RSxjVbrwWOyQSojRfpc/XlVJhCfyX4/6LNGpK2O16KuM9hP5F75m/zD+wigCsW0aVGK5+zXFsYsnUQjrFNolpsO/Xyfi7FJjkQ=,iv:q3N6iC4aA2EfDv32D+LbWcPeDcEKeKQiu4xScau5ODE=,tag:z5djS/Dc6pPWBJvu88ODSw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
