apiVersion: v1
kind: Secret
metadata:
  name: recyclarr-config-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:ariX5wXRcLik9Heh06CMOjOT/s8tcTkxfnDViZ48jbHx5MWSJhpsRiEKDQLuAsnYpTDd+jYBJ/MbgEgmK3Z05DVdYMk8cJi1lHnioTf96xcHxjrRzpGhri0=,iv:kd8+vgaO751zrp0d4mLh+yTGufDf1ZPMj9MGJ0Mlnmk=,tag:fPRd5S9+tI25ElyxnHvNlA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:JLC1Gs3voKdTFjex7OTggSArHP+D3LOvVW/446/5beUGXaAq5V5LKrR0AnE=,iv:YcsdeoYwlqzr4HDbxADM9JrLOTrszelB9BQKbnd6bzc=,tag:U3Znyc9A6LcZqP+kRveJlQ==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:c9T4IT4/cetxR7i6hUQgldHrVUnyWpuY,iv:ijg1AwMalssF0uAraWA712S0E509+hDtyPKJbnOecrk=,tag:NReffrNleLmUvcLp3ACkWg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:oggAQbFFTQLGwy/97AEU7V9W4dS3o0+CR9LLhrI6IfHma1e+rXPHRcz6TP4yiWit8rae9vD3cg/PTLzFoOHT5w==,iv:uMcfMzE2cWWY17FlFIGbMvuCfca7rqrf8FHG20WGmrk=,tag:TmLw89wKsC4PGyPdwjJk3Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZmt3QUc2R2Z6bHJrT0M5
        dkNFcWl0QkN0NE9ZV2xxWG9WeHdXeXVpemw4CkdwTW9kWTdtSHRtYmFxTW15L3Fs
        UE9GS052OGc1eW1BMW1XcjBOT08xZlkKLS0tIC85NWcyV0g4djdIZGg3K2JzRkw1
        Q3NCekt2UGpnWmRsWEYyeWhaK1ltaVkKXLsXaX6lwV1A+Ken14YP837uHaAiaTQt
        z3snsYqzrXFc1JdeSNqnrBrSeGmOcAZoxd+FAW4HVreFZnyt72/LvA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-04T10:39:59Z"
  mac: ENC[AES256_GCM,data:FU3SWdyctsNlb4jQyKt5hXK8600kwjyQgilCIY1cA9BxZ539GUElt3JMoLEHUyywotDW8lIzTh6B1AW1DFqVb4vhamACQPVtX+FOAhOLhEw57gHRwKj4t+G249Y6p/l1T4AIKM/uxy6K7HYsXvFAjWtbWgM9BnwDwy2E9HHMol8=,iv:ZQNBpBseU/8XpIgSF2TKHXppJ8T6hliCtgSZswAr39M=,tag:B84z9c5h8q0zmJlb3RplOA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
