apiVersion: v1
kind: Secret
metadata:
  name: recyclarr-config-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:cxt7WTNeYzUgrKp8PCVJxWbN1WV5B1jW4ledMjACThiT4z94e7h7iz60LRIA6HkrjSYtm/Z+jREsv9acc+H+s430LKVT86WC1WBw0I88N2l3M+GkZz6HVMc=,iv:t0qe4/oqRcQPbYoXb5wFK2IQFHJMBsyVA3/gFyBwV0g=,tag:51EnzXD81gpjm2iW4L0spA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:GfXc2K2LPWf63YoNHfkSOdLrKz/FHluDo64ocId+nTg5v+KkeDIUoCyvLhs=,iv:gss/R/tRl17cCWQ+iW6DFeSC8WiShTvBYLKdJaPMY48=,tag:YV2V4A+pfnqTHr+Ooo2KYA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Yzk+NPNz5g2hapV7UWIuc8+GTy4QAZL2,iv:sLYkCE+XJE2CQm0t08bni16FZgNiA1KOhVWkJik+C4s=,tag:Wu6syw0VWTaAlX1dv/B4rA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:vQz71JI/+vcrp4aDL2RQ2Snn5CxqgvDQEqWdu/Fszjd92knH6Z1meRKujaWgNmSPo0GpW8mS6nEtifDqMcazYg==,iv:ctIwo784rErY2ubaz5qI72tKgncUmOmM7t74OvMebuA=,tag:/IQPeDHpP4FPXC8Dbj31Ig==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6OVBSa2x5QVJQSVN6Mm9y
        OUNoNE5saXNjVVNzWHFPa1BFYzZFY1NHSzM0CnBVWVVmSnNydEVmNXROZlk1bCta
        dnQzNngvZEd2SFY0S2lrVGhqQWgyNmcKLS0tIGpKRkpsZUZWNndoUmZ3b0lTMWJt
        cE50T016akEyWVdTVngwYjJ2eVE2R1EK3m3um91w0HrmWhwCA9kBr3ptw6Fqk9aZ
        ObPjbKeOCzwAwPp1feadZQfPpY9pvxuEH55RymSx8cdYwe5DPDChng==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-10T12:07:30Z"
  mac: ENC[AES256_GCM,data:XMWPbTXpN0e1+lo4zMfzX14c7dYzlNWqiMp5vlPKtNglsoxCBWRBYYvTiWPmhtd/Zj5OLV7ytN72CbbShQQ75ESmQi6wpBYb4IE3hfpI3WhH5rQ7HdGIS3Zr0WzYc3okx9uTKv4mzCjTDwAWpXqQE3JAhsa8oy2MJDx+ueUMJqA=,iv:y6mD7M/g5K2G1RzQBLnr3kUVNgblRWclnYrYeGsWaHU=,tag:3Qj/vScXJm6S13y1pamiGg==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
