apiVersion: v1
kind: Secret
metadata:
  name: recyclarr-config-r2-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:NQ2yeZZz3gK0vxuuXNAFbVBrAHJXsAYKEbpQhPavXegU7kwScBr/Ye+hmg4ziaBMSMvSGfK7GZCzfdVw/mWEOZQdELY0IHs61uYDQZ+VXsF6O8ZwXpjSLcBFH3gjA5TpAG9Ue4qawJI=,iv:fdccVWyHtaRorAX6OMyw/P4v0Jxrx2Z1757vlPxpdLY=,tag:gdjhSyYhq0agc2QvNHOvHA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:VEHLinbS6XY8Jv0YN0ryaEfWsgWKLmS8O69KzRsY7F2bNm6nqsGm4/eW7R0=,iv:LUCF6oZcuDcssEQvat63ofogj6uf/KoN7O9QAki6B7w=,tag:g3yZJpyXvU7gT+m/kqhHvA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:lGoHdDYvVVMJ/TY6hYFI+BF24T36F0IMckA55gr65Xg=,iv:8cz29zjLjyhB//JPHQA36Kr2scTHPQYSdimQF5I/MTc=,tag:PC/f9/cJX1tFa3BYlq0Ldg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:b1rTiaXLReIgZUlvRRrPhdiCnAU78aKWzaam/p3PmVHeVn+aweGM0ffHsNgY8S50RXDS6Fg4pKZwDUd/GlhDEw==,iv:aEfwmfqDVKh8uiTIylJbFt8xN32NYemWoIxVHbdtE0g=,tag:kGJ5/PCK+o24FuHAX/3Yyw==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:kCG2rg==,iv:/1KXelyrROqpEWiiUuL4mTcqm09Zyxa01pkLzzuAQH8=,tag:8qasuxIrcl1c8JEmGwcUBg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeFlTaG5SaFl0RGFhWVN3
        RHc1QVo1RjdZK1p6ZWFUN05qR25CWk5BTkJNClFBMlRxUlNYbkZFVnFaRDZYaUdh
        Qm1LdkFQLzdhRCtQZkpLc3VCMktna0kKLS0tIGxodDh0U0s5bzhyVHJHYlI1S283
        SnJXTDhyWWpPMDBWWVFMTlpaZ0kxN1UKj9qSrr9TJZg3ZuRt+23O91JX4/mNxUzp
        /qk7TvzifFAtvCq1SxzyRWIYtdcFAEcWuJdXBt6Yj4l06tjoGLb8Aw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-27T11:54:15Z"
  mac: ENC[AES256_GCM,data:3kYS3f642BgvkwmIta6KNwH39LcLn7vh7q7dmGRhX1eF357XjJjVZFy1Jxo6h7JkCS6B2PnOSRtdkXIDMQBoKr9dSuLsoYJMcFdpNQDm6KPId2MSg0eAaVGkjl6AWhIYsD0YxMwGS51+gkPHnfJNRP6uiioFP2Az74TW4GJCzHE=,iv:wIaSgHY0r5kdgqiKfTNqVw5Bx42Kj6nudCtx/+7OGo8=,tag:s1D7+JwRcEINUdsFIVW6yQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
