# S3 credentials for CNPG (barman-cloud) to write WAL and base backups to SeaweedFS.
# Leave empty until SeaweedFS bootstrap is complete (see storage/seaweedfs/ks.yaml).
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-backup-secret
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:kapyFGuP1r/h4KGtOX0WtNSFSjThX5TT,iv:bRy3bA8W7l6Yq+w1RFE4NxoYfObYEhKHyRO/aeiQeQc=,tag:2ZDEKcF3u3nKCcZREq881Q==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:wAUDq0x+bzrzzpsmNpzjIWcYcvr9F71gfbPkXmQ1xHHpbWX8/xROnVtS4PjERS8himj3+CWj8YyJifbU3M2rxA==,iv:De3AbzomOOTslrrxyOaP+uduTdxBLutTKimPybCFmZQ=,tag:uB8s8Eh5EYV+j2yEDvRXTA==,type:str]
  AWS_REGION: ENC[AES256_GCM,data:cRC1OhpOjGJV,iv:e07OOXcCBS0OWjNRKgnjTojTj8pKop+535MSDG9JqyE=,tag:e0sJpd1vO6+a30pVyKyCfg==,type:str]
  AWS_ENDPOINT: ENC[AES256_GCM,data:OQ97/qrrorEP18fVmin3NRG20rlsUoRC99YhgpeZu859tCPvNoIF1PDxjqD7bOrASQiHW0Y=,iv:oxXjAlGq3ReamW0KjEVTJDvsTDMSbkDCMinRi243WeE=,tag:LUlJmtStQAPJzaEJo9P7lw==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUFRuMVBqYi9wTDh5dUhn
        dmFxcHZXTFFOcENRekpVUmxhSDJFVGRKc2k4Ck51WjQ4T3Z6c3NRNjRKZFVEeUFZ
        b244SzNjdzh4WGN4NlVzQjNJUkhvdzgKLS0tIGFsU2V3NGlWRlFIejdLK1BDRVlr
        TVRqMDhFdEJOdDFHMTVvdEtraFJnbTAKtka7PUciQ17JT72nrI7dvFv2nYxS8J6Q
        rgFd73vzmEq2UwHctOfQ15XnBYx0sbuXosVx8nLQsBjj6N0DUmq4dA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-09T09:26:46Z"
  mac: ENC[AES256_GCM,data:sYc3qI40pz1X09j9jA0wGQYIG5h0KRU84vzg8K6XaH9uR1noi7+0dKhc9meqONRkQI9UUY/sidklFLE9VcEU9E3j/ll6qU7nuW8Xe1KciANIall7MmF0pXi3T2lw+sfOOn35TyVtCgPvIZjwrsxXrTOaSllhA02Kt6EkYB4m+M0=,iv:jiKdncmUf22D79sGO8RlK+FLFyp/8OD2IbAzWgk5IdA=,tag:2CWGwgvF+fimzaJAY0v8WQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
