# S3 credentials for CNPG (barman-cloud) to write WAL and base backups to SeaweedFS.
# Leave empty until SeaweedFS bootstrap is complete (see storage/seaweedfs/ks.yaml).
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-backup-secret
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:92aU+xwf98HW160nObtNU2ZMR0aAlAXf,iv:UY86n6axPw325xHjO9KjeRW/hUucjrhHSyX/unS7LJE=,tag:w/SH2Yi28891le7YlFy5sw==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:hipbrtiKSC9+/JKe6MiTX5LYYFNVgcxMtphud+ZFXIyoweSIq4y+ieK4n/hHTw/LOGDdRbykIBKbWAx5tkXF0g==,iv:aWU4966BLhlmmFfGXWfv8+qMJ6MgoHarP2w/ZbEdNa0=,tag:FY8nkNNH5J3BU9q9XnuUDQ==,type:str]
  AWS_REGION: ENC[AES256_GCM,data:30Vb3Ltvtn0o,iv:wXW6gZOkPErcldaNwPrRzaooEUPCugrqqqfVTQerzt8=,tag:5yv6C/ByFtSAGKJOJjiubw==,type:str]
  AWS_ENDPOINT: ENC[AES256_GCM,data:JTAh0H53x16EwtpThLIWvP6CFl6GecEf+AztMefrEsOeOeoaqU9Q9AxT3Qx3I74u0NTlZKg=,iv:vXPUH9JKoASxt0Ro1AD0rTeLg22e3BjJ0uowem6kG+U=,tag:G9YydBBKeHTG8wSlBlCBAg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndzg3cEF2TjFlS1gwMUxK
        VjVRTjlVYmVldlV1a3JraXBiekRwRk9Ecm13CkxJT2I0NDVGSlVwYnd6Wk1Ya0o4
        QzhDSnVPeFp3SldYeko1MzFHMWM2TFEKLS0tIGQxS2tzMnRneld1Z3hmcUt0dUNp
        OU02SjR5clFLWnZwa0FOT1RtdVRSYlEKoRFcEfXsfcAFNiJTxmLp2abZ0IhytLX/
        HBiKu437LacRyn1zRpI8rT+SN8c2q5333NEI+LjKK06ewB7vVZ08Gg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-18T09:43:16Z"
  mac: ENC[AES256_GCM,data:aafQOfs0bIHSMCw+O5k+lfK/KUSjfKpmnnrXdeUmaU/od1VTRuuVgKKOYLw/sNEG3yHinghcr+9p4bjNtpXsuJkLGX1Frru/mOPGN+htqCwK5VH/k0xqj+2SDKcsL/gcnJGqKuSLxuvjZC+ft/jeTkte3aVd6rgbkfqrZQ1NgHo=,iv:oXB+uh0rB7meb3TTbnfdOQX1/OMowpSQMyKTNjc3/Nw=,tag:+6xhXhlPRLs4Tmf+7DhXDg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
