# S3 credentials for CNPG (barman-cloud) to write WAL and base backups to SeaweedFS.
# Leave empty until SeaweedFS bootstrap is complete (see storage/seaweedfs/ks.yaml).
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-backup-secret
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:m36KYUgc9xiFWZStFoeo4bRMzKnao2B9,iv:NVP+oiBjzNr6DgHr+HkexLjn+sk2pQNsEke8nNwKbQM=,tag:2LSKd91OBjwrup8wa99xVA==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:Y39AYsSM12IUcD1QCzNeRJ6p1bMDIuW24VhdDapAGmsB9HooaHZiNtqCQhVdtPW0xoe60zuhHOymBaWrngD6oA==,iv:zbb9vxsBCnyJXNY70F20BI3EQM0fxoZE4aIG7BWKfL0=,tag:11sEuXPUGArWwHzrVisZSQ==,type:str]
  AWS_REGION: ENC[AES256_GCM,data:+1aBiF1uGFBI,iv:V10kFQWM+4qpObn3/cRbCEcg+tQZl6z/kaBhDclTUpw=,tag:UQoqCJqWzQhDNYfgMHA+Rw==,type:str]
  AWS_ENDPOINT: ENC[AES256_GCM,data:QPjtPiPxNbFCMHaoT3Vl3lCxAIHdVRjX6qOE/wMPMIRG9DHlYg8nf4H0+OHxrmNlPHt4ogQ=,iv:I8NzcrU4m3Xu/gppbeLnPj1kRKzsXrlkwSZHofYCQiY=,tag:bllpUxlyD6XIs0+/LswWbg==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cmpRQTluMFA2VjRvdEV0
        SU1ZZGUxbVJ5WEQyM1UwenZ2WmNDRFlVdUdVCjQ5R1FuNENkMU1Jb2RjK0dhUUNv
        VExMQnN3Sm5JN0lYdFR4STJwOTlBbmsKLS0tIGErUm1Sd29CVTVhdWcvcEZpQ1NZ
        TTBILzRoU2pnejUxYWFMbm82WWU5bGsKlV/KuGGrTtMAtC8TAw2M05wGgkI6xRRG
        Rh+K0i7gHugcKk/YesfyJXX56U6A7GwNU+19GDuWResf94Poa/xgfA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-06T16:23:44Z"
  mac: ENC[AES256_GCM,data:VsKY8iQwz88tXVTaYN3xxL8++8ac3wxG2zTG+VAMLYEqmBiYLSwxY+Lf1JmJ9ar2Lg2T2pU5RboZaeAKKPDpf1JtaKYnXjtkx1a803GHZamYxpc6RiHQx/ZMi+1g65ZwHmXdIzoFq9SiG+KuavBxShLcNTFP5lkACIXJEmkRZG8=,iv:IzNV573Np0DWGpEENIoWWpMxLxJ3GJqdGQ+zHICN8Mc=,tag:e+TTaEoaEX9D7bwAFk5v6g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
