# S3 credentials for CNPG (barman-cloud) to write WAL and base backups to Garage.
# Leave empty until Step 3 of the Garage bootstrap (see storage/garage/ks.yaml).
apiVersion: v1
kind: Secret
metadata:
  name: garage-cnpg-secret
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:OAxV9AovuDk8yLne9QNEBrK6/JJP8KaLUj4=,iv:XhNsZlXa3sy7+WsMnHvIOPRq0S+OfGFOaxd7OsoLBRo=,tag:pksxrp1DnIhgs4L6lUNHoQ==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:jiF4TRIRSSNFCVuoW7cYo4vji9iMwoX7eAZy9Perecp45R9rcH7MSiGb+F9ZcO1G3mDeQkNBH3EFhbjhXiJp2Q==,iv:8onpHGvicrwAN3S2SH0Z/rF9UrDt5ObIr0nfPh2KGcw=,tag:abVhzTJo4nz5L9n3mDvdYA==,type:str]
  AWS_REGION: ENC[AES256_GCM,data:Cx4sLFwG,iv:M/dctFgPy1nPpiYEzrosuQkSjZ+2dmVQm/qi/YWCN0E=,tag:Z4OAFFz9XWmJYcB89Cwtxw==,type:str]
  AWS_ENDPOINT: ENC[AES256_GCM,data:DlIlQKgSWzTJgMvhN8uA36NeTwtPxWgi+AGJMpb9Kr+3z/SMGmCcJ43E5kaDIm4=,iv:cDV0NYKujlu/BkbE6iS6OXzz5alAj4e3MBVxbq7Y2t8=,tag:T5MqHy4RsjpkvvOMg93WbQ==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3U1VKTGExdm9sZm45cTN0
        Z0diUGxxZE5XQmtCWXNiVFdkREFpSXVSaVNnCkpKSmxvSUgzcW5RUXExTkNnSzQ0
        cnczTWlQZ0FNWFgwcWdQcTlHY25ydE0KLS0tIGExMUtFMjNueEJDVlVOVks5V1FD
        bEJyMnRaYjBWd20rdnBMcTAyUGkxYTAKsc5I0AaoWwHX6W8/Wf1F8Dmt4VijOjKs
        U11sUD+z+f9dHvHHiJ68NhP5/OjUevvVNe+R+3RCAcxIr8NO83mIrg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-21T12:12:09Z"
  mac: ENC[AES256_GCM,data:8zgQx1+0p+oyfGEi5lel3oAa5adsimVDAk072JzzkR7q83stj01iAQDTN5YmJ+SCpnAJUiHeVeJYLVblWODnY04M13zjN82PVCosdjsCJwRvGWVo6KOEKz3eSENgKrYaviT5bzt9UJ52uYrkm/Z/3ivODBPA2tJCz0GoUaw0NCY=,iv:GNAvH/Sx5lsk1g19xXmVdR8AGCa6xSA8UPhWrGPcqOw=,tag:U1JAZHzV0ZH/Tk9mIevs3w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
