# S3 credentials for CNPG (barman-cloud) to write WAL and base backups to Garage.
# Leave empty until Step 3 of the Garage bootstrap (see storage/garage/ks.yaml).
apiVersion: v1
kind: Secret
metadata:
  name: garage-cnpg-secret
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:hLtiI7tCISDbtLg7Em+WQo0CWvUNy4QoEX0=,iv:0kaQnncelSzZ/QdQJdxZEQvXHzDUq96SBLlZ3otgJXQ=,tag:0e6rI4G+lPOtMUfDKoTItw==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:C13leAi7ZFv9MJpAhZuCf51kGcWN9vGDeLEBhxPsKg3jT5442EQmw70J482eM6P44EyzXjrb7R/TmgcLArIBhQ==,iv:TtsZK3lnU8z4r1nlU5xdS5UYfe1wOIFxF7H+/QQ9Kw8=,tag:Zs7yK/Y11TeQ0SF913WVRA==,type:str]
  AWS_REGION: ENC[AES256_GCM,data:DTeQ2789,iv:Ev05i2JQCtm2CzDC9wngX2za9i/hL5LD4g354NRxDa8=,tag:CNugdqvoKHkb3pBKcEJTEQ==,type:str]
  AWS_ENDPOINT: ENC[AES256_GCM,data:xpGEdg0JqGnsyvQJm2677YOQEmU3Y2kGDjzXm6yACqfIjHhkQhjd1B4Pc9hGP9I=,iv:qjIVvPZimBKB1UWYomZyt8CsfAsJy4uUE39cOdNrKOA=,tag:wwJGp9J+O9gMlWbIKFn/zA==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjc0RkTzZhZkh6OVdpL212
        OVBHREV0OUx4em5NSy94bHhkb1RMOGN4VkhJCkxuMGYxa05tQWR5ejE1aG93b2Ev
        czRyU3h5RTEvMWNBRlNjYWw3S1VNS1EKLS0tIE5kSUIwandVdEQ2UzhKR3lMbmo3
        WW8vUk5pTDhwRHJWUkp3VzdjWWxkMlkKMUPGSZNLS3LNTyHJFtc/4MTFbck41d7b
        9icx0ZKtPSg9/23IO5mrj/sU2PM4Y7As+BeVZ1LxssBeh0oxKP5IUg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-24T08:38:33Z"
  mac: ENC[AES256_GCM,data:Joc88gDhK/Yiz+K3JcYdMsX0RDf53yhZqeDBWe58Bp2EpWSj0ftHtwb7fihFROLJ7gCCHoNUfTfIh4foW5HA8a3SECbVluYiwN0b79xnt4Lnx0IlWZWL0D9shZ3+IIQWYaXR72uP/DbHtf0YlDd2BGVTCyaGcUzeHnwhTMajQcU=,iv:0XpxMThykrqy/OEetqiRjK8utuh27czErvWYJOHg7hs=,tag:CMCIqlAuJ6pVyfWgSg/vDQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
