# S3 credentials for CNPG (barman-cloud) to write WAL and base backups to Garage.
# Leave empty until Step 3 of the Garage bootstrap (see storage/garage/ks.yaml).
apiVersion: v1
kind: Secret
metadata:
  name: garage-cnpg-secret
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:K7V8WM3ZQ6Eccc5cmQiF97/m2cdtOqjYSEM=,iv:U1Hcp81RAXbw9Gs+LE4HSBFdwqaCbUMSya6Ng20h8Ts=,tag:SrGYOvPC/e1kA9eGd6he5g==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:niT2SS5b2l2T6OIDZpZOnYweX7pwnwR9oXxmUYaVh/uQ7Y/bt+yeYXOILh/nj4Bt2QZZh9Q5qnWSNY6chOa3Vw==,iv:5dMsLJMvGGLbsQpWSuQiXWMh22nQLGcZanSV066/6mg=,tag:67wm7mVSxUHL76aCKrQZNQ==,type:str]
  AWS_REGION: ENC[AES256_GCM,data:8Zk15i1a,iv:d21nvUz76qAGjdKhbYPE4YXTQJfo4O4eqyxitcx1jzc=,tag:Xe9ZXwW3iLYj602t9gw+wQ==,type:str]
  AWS_ENDPOINT: ENC[AES256_GCM,data:5WnjLFA2aJKYV3sMOTWOYss7VqUhUQYEwd/cL14+XVJrzktrJOKE4ys3WS20nuQ=,iv:bUjNTfajU3WtOFR94TjLvwl/FoVKgAy2vwraqeGhL1I=,tag:pIlC16ZSQpM4+eN0K5p23Q==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbE9KdS9SUkxkN1ZtNHlN
        cE1LM2oxNXJTTEJ0d1JqSFI3cEtLbkpiVHd3CmkvM1FiaWtjOGkyaWV2bFJuWG01
        eHE3bzJZV0owK2tEa2gzVTlvT3RVbXMKLS0tIEdyVUNwRW55RkdCa2MxQzJFZWRm
        YkRuWThKbGdZS3BWNzJiQU0vZWhSOUkKURfzMKOE1/xOOHk4lXN9Pa/CEm2gSbr9
        WPM9fHe+lHujXuhMMIuM5EqinkwBrW0tziD6eFnqJaQGPSPtob8D6A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-21T08:26:46Z"
  mac: ENC[AES256_GCM,data:5sL2m8PwNdWspPaQzRckDwgtzSwDS9P2DdG/13T2udYrOyQhbcM37C75Ek67zaPw1uXDvEyRUCjSdkRsBRe+JupgOI3J1361rq3P0z85hfhWyt/GDLWolGKLQysUNbYJaUdti2TQv0y7yehzuU4xqdOg68uSh9DGArQOKnTrKKg=,iv:7R4VYb6Rz8z9WKGAF5coE3G1LJWrSXSW6UH8GnXPLxU=,tag:d5hDVJqUOFZVOt/G2gOThQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
