apiVersion: v1
kind: Secret
metadata:
  name: grafana-restic-secret
  namespace: observability
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:wN7Ci41a1jb+P9HEi8D5yN7GxkxMbHWZKV6BqZ/ZVA3c8vSA5oaJIiOnKzxSdXGUtVuz/Q==,iv:gTLdcTSNQUf3PYdvZgMZLjQxoVhuoBMiRRExIgg2RUU=,tag:kXrLzUtxdKJWQcRiECuF/Q==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:Cg1ZCum5bPZyFp2b0OtSbpzN2so9EVDsjzfTI4ZJEbZTUg5k0t9cH4Nm3SU=,iv:sPwmgKQDEi16E2sP91OFCTgx5++S2oUraIoOM94JHrY=,tag:mMNzO1e1cQqhAZBRkUw/fQ==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:O8lRAcTVpJytXXcSrBp7FSBaaCxMijM08BY=,iv:Re/0QEXBBJ5D3L07HuEdmN4y12XyCuNqhgKJmQSgkPA=,tag:9t6EP8KHCAeEpMtkQlsq1w==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:XihigB8HpgbJBliRNS39WKOtE/5jI5xXe5NtOVFyYdJ7+wzISZVPvSZFXUU74vLkro21BWEKRqZiRCCV5hgYUA==,iv:QgVitMtz1aNvAVGHzFzle4/AzeKQzM2ok1MGvhgQQJw=,tag:Co48MA8jg+zVXd9xZeIrIA==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UWlXTEVESUx6N092eEcr
        cG9NWWVEMUIxUkZYYkxBMkdZcHNYOXByM2hRCll2NWV3NUlLTDZhQjMzK1VnTzJo
        bnFRTEZadVg4OXZQSTc5RXlnYllTUGcKLS0tIER5SjJwWUFQSS9mc1F6NUZvRHU1
        UUI3MXJCMlY4VlkzSUdwc3RvNllqbmsKNx6TZ4455DqHtgWgnsSmlvuoG1PO+JRW
        uipPSzV7M5eajZ9TUERiddrH1gHO8RYWDBHSm3ZSpDinl955OfXtlg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-20T11:26:38Z"
  mac: ENC[AES256_GCM,data:p9XZ9aHEe3Ibaj1DkecI3vh8wjFZPUPK+SJa6nuEpdVR1ixnVZKaI22VZMjWW0s5DhIsBcD2ZpZWcroT5AKlmlo9OJAjpPUl4neJZ5s+6Kf48mJ0DodXzpGzx1rWhvIwOW7uYu9R+kJWqQMm3TP6oL0DtWU6HJgXna6iGUVMkGU=,iv:MvU/akA40qbP8FCTwTFGARIiylZC0Ehv2uW4UW+taiQ=,tag:nrGKj3/dt1YdyFh5AzHsow==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
