apiVersion: v1
kind: Secret
metadata:
  name: grafana-restic-secret
  namespace: observability
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:EHj/CF/qIiaLQIshLzyGrB0jIK7D066BQ9FlFI/4ZpIuIjxvfaYtAbBVfcjebZRilq+UOw==,iv:OfX4a2TKENrVftc2WM/5fHOStW3ZqtTki6j62h/psfg=,tag:TiueNGLK+JIsyKD4b71B2g==,type:str]
  RESTIC_PASSWORD: ""
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0R1NTZytpenhtemZYdStI
        S1JxdTk4N0VTaDhIZHFwTHRMUHFpSzlZMmtzCmxoYlNlRGJpQzZ4UnlvVTNuUVZD
        UXVDYnJGeElmczVJT2J6bjV0dGRlSkUKLS0tIE5IUzhUajZzaHB4WnBZYnoyNi93
        UHdrdHJuTkJiQ1ZWRS9qYUR6WCtxeDQKJfyW1J0VLV07IXcYzsOq5w78Zg/8+5Vm
        2vyjUHw7yIoMjBUIEqkjaG4J8rq6nHCaj4w3JOYXXmn4YmOMFo6j1Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-16T17:09:26Z"
  mac: ENC[AES256_GCM,data:ckQhuw8v6oTmpnlcfGaCt6ydzUmGWMDX1yh3dDzsq84atrehszUHI8AbYrgJFoGjvInZGZJ3sMHGzGr5oOL+JHEI1lCDPUe1MdwJZ/hkyPmwcFCpdexXjl/F0EPi/tBLOlBp6k6YdSG+MzsT2RGvgHsAXOa2d9rH/Hgw2rEHp1k=,iv:S6DKUdfgO95hB1IWc/bXZeT+JztDOPJj9pZyjFEs5s8=,tag:KOonZOoKZmQKaNvL3cX8XQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
