apiVersion: v1
kind: Secret
metadata:
  name: grafana-restic-secret
  namespace: observability
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:iIxTJk2hE5/Y+dZjXqyWla4FpAdkhxtxRUf9MFd+YltNv6YJjzoVlpKwNIxlyXVIVdweVjF7oLQA3Cjl1ss5e1IP1fWxhdPbbk4=,iv:aH1mzTvFl3v5Dj6P92Qg5BYF4myJEHfgPjG1fieGedM=,tag:AsC6SLl7FsRK5umCaq38WA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:fbKCGRLKWVQbd79pxfZ8nMjhWoApaFAM/qi+tvst0hHEp9XyiqclKwPjckM=,iv:5EodLyiJKFQnNRnmhOYBSbM/5lwviQIUas3K9g9xRdU=,tag:y5hP/i6kmGFZVIY0EJ9WrQ==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:BKPDKIJUfa3wpIwtiGcL9iiC+bzjz2ipuhs=,iv:gaT/XKI+KGgOfqz567+uOMjQtbxtd3K66UIjoAQcNYs=,tag:rcCsgzZRXxPTD4JTA+4oiw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:zlveiuZPjw814wEAuWdZBeCAis/UUtkNoPLiEELNOd/5xknbXj94/a0sA7vasvnullrvBYruV8KS4PK+sQz+Hg==,iv:tK2yNNNx9eL0dj15EuehJMNONp7vzR3gnyvKjXFMJRs=,tag:+x9kLXWQ/ZU/vEOyEkviXw==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWEpOY0M5Y3NyTVZDdDJy
        WDNRaGs3Tk94MUF1aHJXT0lQNVM3Ymg3Z2lZCmQwL252UHBDMENHUnBZRm9jSjR1
        eVJMKzNqamlqU094aEc0RGZsSVBreDAKLS0tIG03MTRXeGsxSTlCMUV5Rk5JdkRX
        M2EvY3dzRGN2d3Z6bzBhU2M1VEJuVXcKgxE6hC5hZqM/STLUASOnoC1gj8dfDnGQ
        8Nzzg4m9CoVziTrjQIzCYOmfAJYOd0F5sY1Y3bnL9UXCOFbriVWHNA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-24T08:54:53Z"
  mac: ENC[AES256_GCM,data:WnPIuvqbFWmJn58mgJY5XVvEhKOatDK3uNbcB7gmAuHJGS6C1dmlzxI9Fx5dkvslQBV3jGYHT3qnyw/4nIPTmi3vh9sfHMn4ImZ6/eM6LiwLzf/4jeDfJpQqXv4/iQFdMlwajJMeadfnONSIy7op2XrgW/iySwHf3RpI6zkwyDU=,iv:3kVfoAufN//sTTto43UAfuTNRfT4dpi1/9klFZIO754=,tag:yV4A0uqLvX0frgLqKfeQFQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
