apiVersion: v1
kind: Secret
metadata:
  name: radarr-config-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:YuqqlVQPYs6QoILTk06Ud+NJzwevfPyjYpi+Pgl+SF97obiKXAtu3rUWhxhyYE4iJlqYcdnoqKeXM8PGFUetMBwQ/JRtbYgS78aoilXKOlM=,iv:W/INSLRClWakfbB2W0ToTVXSrYFF2FZh973UyEgz7w0=,tag:Iuw5Igp6w9whEK5rM0RZlw==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:TJ8q7nwIdFhobESfe1+9l8kq4nJE/BTq1rGXXwTLQ3oTbtRm7XRB/2mT57A=,iv:jyIEGw/fV08EZVHU/vK76P6x9wIEUbNt5/Ys0NjCzfI=,tag:k/pJbLFdenzXsA6QRS1rog==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:/Wj6V4n4VQmLnKpcb52OughBJj1QytF/1dc=,iv:gxNv8ULIXjf7qMdNegMIax1BBfZlscCYWtPy3CyFogw=,tag:h4i0mHv8OgmNELheaDcveQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:hEik4kkP2P/HSI35lOdClw5FM8/h8Ahzf6THc9apCNOmQW7RteQe2ytTE6VzjyDshHoGB/hepz1EVoCFJkWEfA==,iv:Mipsxy0zuZhMjEz6ad8Wsd/AppUTgROzQt2DIQSyJwM=,tag:vpx19Lcd6PW4t9n9yjWkhw==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncDJOU3YzTzZUcnF1ZitU
        YzEzVEthZEh6TVFYWjBZcWlHK0o0UXdROUNFCnE3L0JnZUFKYmwzZFovTExkWWZr
        NzV2b0hhWVhabmdKWlBuTlR5ek1HOTgKLS0tIFlWRURKK01VVTZNRmUyTmZIMkNh
        U2FicXJNNmhoSEcvZzlZaXNoc01MMGcKs5eoc6KdhoiPuTlpRVU7qoAxAf0t+I0d
        JFI8CZVAUH69tDeF/w+xhIbg2bs15PZNT2FX8Weyp038zOSOgWs2Ww==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-21T10:24:39Z"
  mac: ENC[AES256_GCM,data:NsH4dehDY7cKT8MkeaYwRCV08HbKKcFCgAQEtY27yd0lRDBXUbTJIlamk51vDRjDbYXjjSGnLS1TkdaJ94gOHqmpLWwrZOSqUeZY7EYfWQHZppw8fn3ulUxQJ4N/PjNrLwDXBrvFaQ1Zdn2M1++qPf08ABmW7FNWsA7ERXoTPV0=,iv:NXx8JSy4qihjLgR7pAD/Qc4y8brlL5uyZeiWYoaRRxk=,tag:IC8808bqkXfSsfDCgVL9rg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
