apiVersion: v1
kind: Secret
metadata:
  name: radarr-config-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:bbjY+hzfvpmBP9Pd92wyqpWxcnTaRtzyCxII8w6b+ECpq/OqwXDp3fXOANFYcpzD5sJKiPKYltQpryefEGsrfC+3aFdGxp8bQhK2MVzeWfw=,iv:ThLNdIGcTOLR6cTj47NZIF9Sad84NtLlwUfg6oO4+Z4=,tag:2bPBCeQXRmLGeTX3R5QxSw==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:L0ovPIk85+gvoYdM3gc6qyj74WtHXnRi0Q1w0Jj7Q8dLM928afBX/FzTefU=,iv:bor4F3dybOUd8UVlvl4CafPp4nKvwJcPtJlrwWOlh5M=,tag:AatoPRmz9p+kznUJeEfZiw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Fst22QG3/JQsrFgHAWtgIX5z+wFdf9WQPfY=,iv:BAsXUj73YGl6GuDa+0mDcpBHiAGW9NJxkrabLo8/ZVE=,tag:MVWwbBYMYfvosT7qOIjKbQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ylu8yydj8T44jhOOsBLjljUw8NpNwpv6x1AfZHkugDbJBhZ54oEgBOrIeFncbOv9iGQqvMC3ofbbVFMmjAaApQ==,iv:wWNJ4Ky15XVTRqBEnV7vKrIJtgcGw2771Subcwz+UHU=,tag:qBPNksgKgkJHPdjnalX8uw==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWaWlmdXIzTk8rMG45SHFj
        ZTdudnprZWlDdU0zeGhPeFprZVZMT3B0TDBVCkZ4Tm4vL1pXbE1qTVJkM0VSSlZ4
        SU5JNERRZkNSeGR6YW1hcGlXMkVzVkkKLS0tIGxUcHBQTnlMdzhnNUViUk9tK1lZ
        WDZoNXJma3dJTS9MWHQyYWJIV2U4UFkKk4ElRoh4zWqkJNAazJBwMqSvK6xlAXj0
        B1QAMwQ/5oSaqQg4UakRffc7KumMxV4829w4IRTvGL4d9XDwMp9lyA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-21T08:26:46Z"
  mac: ENC[AES256_GCM,data:UY9GLATt8CL9Apv84XOTJt5v9Oql91y1L7EKb6e3ruuH7ro8V8ya0Tr2wdlaOieeutDT0+Ruttg7LTPBwcZ10JOhOJ0tp8ErmCPwHHkUFxFDZWhw9hbf8DQHK8kRRtkoYFK2Yp2OKclrRsWPagQtCpY+9adY+ytHs0rMKDCkFnQ=,iv:gZYRC7Y1Ly7DSGRSzmTsyhQEDyosBGzrROCIqpyklHI=,tag:cBTLxGmuKyXM9yejfBartQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
