apiVersion: v1
kind: Secret
metadata:
  name: radarr-config-r2-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:TFrSqNmydoW0fmfXN0jaFuZCfnF/5UY3MO+Qs3qBWHjte1Vvlr+cq3vgCUpbkHE8pHUzQDOnXiROBX81Zi4safcGbHE5plYFVFX6nIK7FmmXA+Nzx+Ao1EIkHFSUpT62nMEQzV4=,iv:ceY531B59zsgSaqoVSE4nX9n+FDz7qqxrQk0yEJ89Uo=,tag:d6A/q32vP1sr9E39d4HC3Q==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:dLTohaWcUwSNSxQ63gAbfvbO6sBpPV1RPiO9PE4tbeOcpaBqTKTNxSLg06s=,iv:ujQD2HCJkV0mievJTOcciK/lgvCKg4eIe3G+u1RLUAc=,tag:y4t2vHO7S9R5ivz1BWZmDw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Mns+aJXf1rzbnFbaU8HSYXtQvZsmi6140o4V5xlk81E=,iv:WbBoGcKgomCgO3Y1RldSh45u2zNChIlJuLzHGj2jo7E=,tag:XOIDYxHU+rfGxrL7lztbhQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:woYBothJLVt13HuFexe/8IhGkc7jfTT1qS0ICQEqgqs8uK/Id7MXw+GL0tGX+2Bwkx/WkcZ25BPvYG0HTukTKg==,iv:JoEOm6JMBg66W2OA+I6no3APAtg+hljG7Am0WMFxWCQ=,tag:I8ga4haFkPFN/80nssNC7A==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:9b6jbg==,iv:QNQNnOZfQUl1kc169RMXSt1fXG2WGefY+T2KN8Zgmw0=,tag:HmVhyt3x6jAF1Nf0B3Wl0A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqeVVLTko1SUJCb0t3bEdx
        ZWZNVFd0UEtRYVgxN2ZlL253bEV5dVAxK3dNCkRQVmxmQncwL3FXSndWNCszSkNk
        bVBJSnh0eittdlB2ekFyU0hraEEzZDgKLS0tIGhIWElPTFBTSzVJY3VyZmV2TnRB
        QW1oR1Rlbkl0YzFxNk4zc1VSaUhFdm8K7RAbZpbU4MgtDUNQEe4V4A8aNKMBBmfO
        2xlg0HP24dwPiLK1vwUj2+KmixmM5ZfswqIkiYzhy+ZuaC/CKfvWYA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-29T07:29:38Z"
  mac: ENC[AES256_GCM,data:py15Qo8kjdpjI4XV2wEtlMKelYAEZryTTUaQKR/zCCTaCl/IC52lJk/HUDQ/n1oiVRwmaEVCVhyTMBqi60qIe1n7qL4bkdPjew44g2frGj1xoGvT4nrfLaU9VutriwIXYBI6Eg8bgPnzsxK3eqj8PDm9Zi/se75zg6jdI5EVft0=,iv:BaudJ3DNh8Kths2YeQnSPf7uHtuxulZxpmfBLJ7vUzE=,tag:V9xDrkARMNpL2XKNtDeGXQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
