apiVersion: v1
kind: Secret
metadata:
  name: radarr-config-r2-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:8CPuhijHvaIHktVMUc1hIv4ByoWx98ZtMALwgwhWfwUPt3f8ke9rmnFkNjx5mlADwYT/umlDgqu5NJ1MXkRtkyGnggL6vbsxZ9Q8JU9lVsaqmE/NNGrlvJbOYyEfvkmdEt0fg1U=,iv:J22+FCt+qrGWftymRooiEJD+v+sYQ5RPNQUYw3RNAzc=,tag:k2LeFedi8sD8Atgv3t76Kg==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:7agfuz+BSK7Nkd7WaovidpMqjMIY08hLM62jZzuekXIu/J/tZquUk2QRDdA=,iv:BcFHyggUQ3oNai3y24qJ1Swr1iu+BCkfixJuZtPgqQ4=,tag:B/0jnluVpD9fAIl/dBjaPg==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:tDsX8/0HNz9ZMPd4D8BhtB3c8pQQjwSJmrNvDVng0DM=,iv:agr0CY4Oa26TqQK8ULcft7KJ0L07kRzo5P5on0FkDZM=,tag:pwhdMxUKSn6Is/uCDbJpEw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:QsV8ElPwNsAdTzPOoK1bs840Kvo4Yez7/j3FaQnn2had+q7/4c27Dt/Uzg3AxWiIMffKoivR0sDTulyzUzSXpQ==,iv:iWynrSDJL6J31YAgLm2quNkgVlAAg28eCqXVccyYcBc=,tag:zPd3EHeWDFS+zDBuTY2jKQ==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:3glC8g==,iv:DW2FzyafkbM3BaNqEfcuFSWcztThL0lRF3G/Fn0fdzU=,tag:V7ghbjyr/Qabsl/OsrQ16A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6bFdTa01UMnNwQmc2Mklv
        cmMxWVVMTlZES1IwM0UwQ1llQ3F3ZUtxRFdzCkhESWpNT3VJd1ZzQ3Y1ZTZFVk8v
        YUFSY2F1SmxnblU4QkN2ZjlqU1FMV1EKLS0tIGFZbFNNZStYUGpsV2UreDhmSmxt
        bVRWV240NHRobWlrbDljK2g2R0NhWUkKJeUR5XPdiUqsWeo9jZWJ3sq83StDGyLN
        XuuawzLvD1PayRHmuML8fOrWdlXbbxOnfVIPVVhCKK9MHS0y7wPYlQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-25T08:51:48Z"
  mac: ENC[AES256_GCM,data:AoiHEWGSZ+msgi80hgPAAvhs83qU2EH+Iwxh/BB+lSzLBENc/02vNlH4fcFpVRI6WdHUthxHOi30JPdGjz7+FuKKRShjMAvUCvd2/omPUNqXOaiFV9W5uvUEECA0dsyyN5A9tv6dtNxd0cCTKJ6QDZ4F7KtqvlqDz9hKpya3MVg=,iv:i8HZPwaRe3hfiw9Uj8v9+tx9uUl/KfASa88SOElep9k=,tag:UOCmifGFJRpHP//xMpvThA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
