apiVersion: v1
kind: Secret
metadata:
  name: radarr-config-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:h//pNYxOP8VJzExGebvF5lGcyCe/iUbd8JO800zh1L71yseWd8DBUSViIIn9XA18EUxxwGqNZUswdXuA0hde9ykrt2SWZTHQ3Mwj8/mcMJlGdTYTdNc=,iv:crtLYJHV5hzFAj6BLg5oHyp6Iw2D+I0CMHwN61g0JkE=,tag:5xHUvdg9+4becfo6+YH/XQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:g1X0a0k2QIMoGFfU1uJZwGpz0qh7Dp+Nqu0vlP0wUpPA532FqrBaqBXiF2M=,iv:MJr8m8lxNariHbMC+S+vpq4NZtKMqYEdHvCJ8qSbWuo=,tag:OyFAd2HvxqwmyQNeexWWWQ==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:I1A7/1qcH/d1V9Ul9Q==,iv:lW/ef/hOxD8LJhQDY33Uu95cCLlpM8orTcN0QXicP/o=,tag:2HUnBXQmxroz+Ly+XOSEsQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:kMcYOwd5kKaqa+eZMGcIGYmmbhlqW2fM5heNUfrcmB9hNaKtuRbvQVPCF7ZxzAfBxkaWlJc7Cb7IzawC5CDkbg==,iv:ZV/iVRaBIElMNted+60rOunlcuNg4YBHtUYn9B4gXtg=,tag:gAqEeTHmdnIfY7SJ18mXrg==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjLzZCR3ZJaEhGdXNyWVY5
        S0xEUEtxYkFLcFVQek1zS25Ga2cyd2RnV0FZCllzdEN4UVI2RTVHWVd5bTdZREt0
        QlM1eGJLQVpoaHgrVnZGTkVMM01oc2sKLS0tIFUrb2U5VGFJM0NneG93WjB0NzF0
        SVNxdTk3UStadGpvbXlJT21Ua01qdWsKIQ/U2br1/+5D+DmkBKXHmlmau5pH/WkT
        ed8FlVhLVccAHFQyY01cpmQnaMkSkTxP3n8jkHb0IIq22rf89vJ2Tw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-04T11:23:02Z"
  mac: ENC[AES256_GCM,data:GajQc+xL4oLX3ukNNnqby+a79Mi7Q+LBewaSeVPlO5XPEc+W4QJv85GYXf/MsXmkU/tyamPpmHvG/ORraECpSiEmH5CVwOuNt4Zhee9Tme82DJSUJqn//50xeMXkO/UJWz33mzgnNJKU2dNW8FVjwjRdCyf5uZttF52pwQQTkTc=,iv:hjosoL1FHtquEc+U7l7RMF+mZ1Ec1DRx5Umc+c+zXgc=,tag:xRhrl34HEUzzg5GANvdYlw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
