apiVersion: v1
kind: Secret
metadata:
  name: radarr-config-r2-restic-secret
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:Dr2pc/R2vHDSAA1JiREYiLreefc/Sji46pG0UFMQy4xfrCcL2r9LgnxSW1LKTQ8fFs6pafTlUki2cA+vrqSEeNXT/wTQyg3LaugeiBWVE9QDI3rlX7UDDUFKOFQQ1g+qAuDJIbA=,iv:Br+OWCyW2q7eAKrSyDqWPWGtNHlGuqd/Rw63q9TXHZ0=,tag:Jru4YEQIEToQhSbxdhzpIQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:meuW4GrTaK2f4E4QCCKtdwP6DX8W6YrpVl3gEfG1NkfN1RRBD2r5uzk+2iQ=,iv:4k9Ag78LtBGYM6iwkRqtfS/oIgaPlPipOmcUgBmHIL4=,tag:s2SNM7Q1JCGRHilFJg2l3Q==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:sNRqMGFKQHD7A5P/ZZRHUZstwhDY9Mnior/pDYmLbXM=,iv:JRQORzurjhKjYOi5wTu1Q9WxRWGmkSF8DQDI6h3AeZE=,tag:pYOGTBkUHf/AZe5cFudk+Q==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:QlqSXpHJdQ424BInsAkfPBYFXgVmKKY4WgCJXZaOZE/32BpYuYHMmyaOBDnbghNfn3EbTocXoFzHsxhqL+E8Ag==,iv:RG8n3sgLfeYiAmSMHbovy5Yc2L+zMPRA1WHi+rGgsVc=,tag:WVuMPlv/Up7M65355DwGZw==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:EEiA8Q==,iv:4PD67a2OY6FtZbBlZcPGiPPIouXdYQhlccstQeVkSEE=,tag:IyLh5HaUfRUSfYwMzIKXZQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQXNqUnMxbG9aVkFxTzQr
        TnVhbUtXWW1GcTl1UHNJeVljM25Ybk1Vb2pvCnJ2aWdCQXQyRnJ6aGNwVGJuWmZ0
        L21jMGJ3MjAyb2phZjRYVE01d2U5UEUKLS0tIGlmOE4vNi90R0hodCtCRmtMeVpk
        ZWdCNWQ0S1VQZHA0VjZHWGV4WEFidUEKqf6uG5X7cFBEZygz4pH+zAc1ai3uSrap
        KBfTQVDwSSE+3zWG6BIz6mBDIoOEqLnPq+rgfxkiIqKcgkj2LgCzvA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-24T16:34:59Z"
  mac: ENC[AES256_GCM,data:tS3oq7lWm8vWsbOIEysZ0sFLh9gu3ho4TCkQog1T5rRgynyYIHp3MetrmMgJkVeqh3sjm6pUUg2zaMbX907W3o1blIHho6qYi/xYQZXNqZ44Y2TY25NCPyrDKR+GsAwkVBZ0WQCoZpTQIeZZgFcE6ZzzT5zCwqzTxYPmEQcWgmw=,iv:pT3eB3JIJl0AQVl17agJx0duXyXHkd6nIOfrEwzlYZM=,tag:48LpBRHtaWifD6ldTRf03g==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
