# S3 credentials for CloudNativePG to backup PostgreSQL clusters to Garage.
# CNPG uses these credentials to connect to the Garage S3 API.
#
# Requires garage_s3_access_key_id and garage_s3_secret_access_key to be set
# in cluster.yaml after Garage bootstrap (see garage/ks.yaml.j2 for steps).
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-backup-secret
  namespace: database-system
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:TdWZXiK0RH8wtCI0OA4ZFAoYN7f/ujM3j+o=,iv:SPwJzeot7XhewJdTKsHvL18Th2/ERDff+fA+kkDQ+yE=,tag:sD1cWsQgl+I8NN49bjPPEg==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:AjPzJhO1TigCueEQcg/tiXr9rQFBMJJ55Wmzl2Aindw3l9DkO05wQHlQz7hY1eYM2/9XWuUvhhmtCZrelpWIOQ==,iv:wpMP7bYdEggBeSaquAXGEvCh4A92jFVSqRzPkGZxrc0=,tag:j+DBJpMppw/zpQ7K/+MbTQ==,type:str]
  AWS_REGION: ENC[AES256_GCM,data:bOMA9cBI,iv:O9PpEb3GGjmvfqENmqoJ8rpfhAxSN1isl3Eonq/1e+c=,tag:2vSidxft5Bqy5Xrt+3G+3A==,type:str]
  AWS_ENDPOINT: ENC[AES256_GCM,data:eX0esPrlgRZyBh45FRaMWQdTKCqCDKVez5mJLawG5o+6csAdMEtp/gmBq6yH8P8=,iv:2i4ps1qB4XlimgxTkxSge6NMI2lneyaUPaUI56bz2Z8=,tag:+pS+TpvM4hz5MiobZgqHnw==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWkVvWDdLWFJESUxBejl3
        S3lXWXRWK0VoNmJUSWVocjBrRnQ1ak9aZVZnCmZzMXdtQ3dzc2RiTzFSYWtFc1F3
        OVNtc3FxWXl6ZmFjR1VZQXV3SVRiWmsKLS0tIDg4M2lwN0ppeER5UUNsTjhvOUdu
        OGwxOXpuWkFFcm5BTW9FVVh6OTRvUVkK4zJO2JeKamIPtXnr5+wkBiDbRNevrce4
        fl63Z+Ua7UY2rTGGihDVWio6oESE1YsmKxMpImPJDHTap7HaXPzaNQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-05T07:01:11Z"
  mac: ENC[AES256_GCM,data:UxKIQH48w1Led08iJ7N1TiBUvW9VF2Ps64dZYDa9E3LEu745jT3ekvdeTJfzBUn1dMwQREgnswDscCVi+EILz/RsbV0P8JksCBt2TRU1Wq+lkZYUXEzJ4Emao4Ls7azL7wIU7bULVf31VBSYYtGMS4SzurUvahp5Cu2L8UYoC9k=,iv:6yviMFVJX8Eg5en2BrBufLY3eb3T8ixFVQXzPVEeUkU=,tag:hEVthxoLBH6jQCFvX+7Qfw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
