# S3 credentials for CloudNativePG to backup PostgreSQL clusters to Garage.
# CNPG uses these credentials to connect to the Garage S3 API.
#
# Requires garage_s3_access_key_id and garage_s3_secret_access_key to be set
# in cluster.yaml after Garage bootstrap (see garage/ks.yaml.j2 for steps).
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-backup-secret
  namespace: database-system
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:2vsfrHHnNA/OxCgXKlkHX8sKV1EZmebyz0Q=,iv:fmKfqaAS7Bu33jnfKgPLyB5dzZcDD/dqAYLPir5yWzo=,tag:M8SHgzOn2zScZECbIHxaoQ==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:ncOOYCAYz97ywlE9zBOechEaB9p5AHnAnTNxlxmOgqZIwNRMvtxslKPTMgt2nkGfBoGKiJ8XY/tiqiWdQCTDAQ==,iv:Z+H1KuhNwtfJFO2LaZhcNsAQUgOFwKfg3G+LSTNUDLA=,tag:hu6H3Gdbmdlu64WIkvcnKQ==,type:str]
  AWS_REGION: ENC[AES256_GCM,data:boi3PLh5,iv:49AJIQUTnASaEE4srYhacMjuPG49D0sizaU2oIbipXk=,tag:uYvWJYHN7upXm0R/70k8Nw==,type:str]
  AWS_ENDPOINT: ENC[AES256_GCM,data:yy30nrpijnvkwVXpAPH9Y0Yj9InO9FuHK9iRZmxGVBWA01c7rdO4j5UfJEo=,iv:s9H4sfbEiICyNRCG/zAXLRJWXpbAoeTpGyNdFbUFC04=,tag:sKMV91aGcHyPazSkacO6Hg==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZXZLQ1B3MitLRFZuSVNr
        NWNJU1VpbXN1MGQwbTNXdFZvVm9CaXJlbTJrCnFySWF2dnBDY2pJSlZLa0RIRHdG
        ZjJGb2tESnVDb3FBdytvKzk2VnNJdHcKLS0tIDVGcjlCYTcvamR5SmJTeHlnV3Fy
        TG11WEdRaUx6K1J5dVdCOWpMakV6aUEKrIBfvR709B/B3LDApgn123riapGRrE6w
        QJ602u1ajxG3r7BcX5LFVXc91i3trfc23iAmN7wxxQItLzOSwCWCbQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T18:42:57Z"
  mac: ENC[AES256_GCM,data:uhbdY9K7lxFE3pWukq0tr0fnE7cqTroM7YUF7n7SMmgwqgNJjXWn/uhgzD+011BgP5MUOZtfT8UEcfWOHfVr1gm+2KFyBuXBpZJRFknO0Krza17bv6FKRF0pN0MDzALy8uL/3RlHwFojIEitt4auozJDzJ+CeWNJAFd7PkODLSs=,iv:hZH/USd86Rj6O8zjlpEK3RVAtVGgr9iqSFMcEtzdTjQ=,tag:jA4VpGGg6ukDmCojqD9kNw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
