# S3 credentials for CloudNativePG to backup PostgreSQL clusters to Garage.
# CNPG uses these credentials to connect to the Garage S3 API.
#
# Requires garage_s3_access_key_id and garage_s3_secret_access_key to be set
# in cluster.yaml after Garage bootstrap (see garage/ks.yaml.j2 for steps).
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-backup-secret
  namespace: database-system
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:P9Nl+kys+Qd4WxLbybwJp3dcbDqnl/YXDqM=,iv:+MgKtGK5UUAevkdSm7CVU0BUW1urlvDR7DRjvy5qxxc=,tag:5Sh+E6xElKaYCbK/ooOvIA==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:oW4G5ehVbZ5twniAV3qCZDE0ZtSVMqs+53jCXArHFwlUZ0ATkOkQqCvyBSx/LVp4C4V24gq7OSXMXpVHJKThXw==,iv:jEc4Pl2+3OWjHmvqAAt6XvUIJfXR3naWfFMY21bvG0U=,tag:/p2hdL/ufMxGcBAJDVHbtg==,type:str]
  AWS_REGION: ENC[AES256_GCM,data:T2kUz4sA,iv:CypZl5zk0PPLfeeEz219TcpiWzQyoo+NOR0fAqiC5Ww=,tag:so+2x/AdtgvC5jqmgdxtrA==,type:str]
  AWS_ENDPOINT: ENC[AES256_GCM,data:lo+yIl6GTKXOu0PCOVO8rZf3vM1oLpCvWWWGI1emZV5menYCJoMnbGN4EyiFp90=,iv:RbmJWTK4pnMv0BXD9c4vUh+PtnOskaIce3QpqUlrFfM=,tag:z/07RswRCIOLXW37LbrK8g==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbi80cFdrZDJJWkRJMlEy
        eCtTNkU0WTM5OEJobmRkTmwwL2dKQnBBNFZVCnVRRXZYUUdQc00yb01MOUZNZ1Fs
        aGxyaklYOE1BRE9tNjltbkdLdGFGWVkKLS0tIFhoTFJpNm9meWpRdGxLYkJhUXlL
        K2xHcTdNbGNTR0Y5WnVpYVdFdVhnVHcKnWrkJqtcxhHJBLzWvQCo6CIC/a43n2vD
        PzKYmZ1svYBy7sRdQdSYsRIdxHakpOXNOlBQfQXgWSGAiNzNystqyg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-21T08:51:54Z"
  mac: ENC[AES256_GCM,data:cy0nb+tsCj5gNgYR/6kPgVhYB2rigFM0HQAqW7yWCZdYAFJhU9gWPxa4SxLwQb0Y4RId8wF5Blo0wKLKZ5eWADNF5TostaK2G6WdzY63Hq0Np0w6JV7ereP31MdZG2ocvvxFnkB3QLmoSqqVMqUQ44cI7hiyULjzLi/FwBWVmt8=,iv:GNFW1m8xZH0vhW2VTs5qTFYnY4gqjWy6FBQjbJTDc68=,tag:5GyG1V9elJJ/MAFhecWoIg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
