# S3 credentials for Longhorn to write volume backups to Garage.
# Leave empty until Step 3 of the Garage bootstrap (see ks.yaml comments).
# Longhorn reads this secret by name from the backup target settings.
apiVersion: v1
kind: Secret
metadata:
  name: longhorn-backup-secret
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:KzYgju8nH43scclriQ7+xpDv5MjtyLSHevs=,iv:nncXvQbeMEsaTxNkUl+muNEqzfPsvQJvWVhj1CyGrGo=,tag:9e3KVs5t6tQeap6yrgn79g==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:wt8uyvCTN8skH3INK9uLJywpaAVqSVo7tun6XiyIkXm9ILxstJ9wt0Dd+3u4GcbgQ7YPRQjnV/uaSkQhrZ0HsQ==,iv:mzGwsNkxenWG39+JcOpevAsAyQ+3TsJrsN7GRzQZ5X4=,tag:N+LBEzDBJxDXzIceyN/5KQ==,type:str]
  AWS_ENDPOINTS: ENC[AES256_GCM,data:I1hQPdAjBtm4UcfZWL8sdlWGCzI4LkqTraxPrBqed7MGnQnRmkWXh6BuQxqVSFM=,iv:A97VZy6eGNKf3Q9Vbd4Lo69iRAyA4uWm960r58XgvfM=,tag:nlpWLolNVFPYMfgb9/7KLQ==,type:str]
  AWS_REGION: ENC[AES256_GCM,data:1245WXNN,iv:wowUO8WsxFm0abOObnyE4DRfWhuLcG34a1KWy06TYQI=,tag:BQjyIBmqQtMYL/qHt1JIIQ==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkYVBLMmVWTU9HMnFDeDh1
        Z0xweGVHRHlNMTZpcGg1RXpMeG5CenZBWmtNClZlcHFtVEtVZ09sYThSS2c1WE15
        MXdGMGFNNDlrQ042SUpEdHR2WWdrYk0KLS0tIFdsU1kzdHd0UDdHTzlOS0kyTnE0
        QXNnYTFxU2tJSzNFY0k1R3VvdFpSSkkKCTRYNeZieAbP1kDbLoeeLv8zD5GHKgI9
        uMdvyVBUgqTsrbqJJLcIaSlvCuEVP9O8SMmXxHQXwleGK6khw6u3ww==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-21T09:22:01Z"
  mac: ENC[AES256_GCM,data:8skezE9SOxMG5NZju/Dk8Su9vMVaYDPBtQ8kvcv06LKF78RmdSwjEnZExQZ92TmLjf1FLfgucoaupiJ3nmIBP2Jalq26V6oTOHyLoao7yous8pY5dcmenhux1gq3BKh4R5vhgwvwDxhZ3j4x+IN8ZqJi4oZj9LLG02iK9FL3vHg=,iv:KsL4G8IOmlJ4DlH+s5IRrtjr5xXtQ+M9NzCSdtPEZq0=,tag:fg0YdftusNcRn/1Myvf29w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
