# S3 credentials for Longhorn to write volume backups to Garage.
# Leave empty until Step 3 of the Garage bootstrap (see ks.yaml comments).
# Longhorn reads this secret by name from the backup target settings.
apiVersion: v1
kind: Secret
metadata:
  name: longhorn-backup-secret
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:YTFtQC2mpgK85I70Ju/9uh5zy5fq/fkj4ZQ=,iv:Q3ovjIpAJ80GbTlZuxZ5yTg4UHSO85br4TeAaySS7ZQ=,tag:iwat5boTS9QzUjixOMq2bg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:5T2lCWLaYP/A56hMq1jo01Vrb7srEsq6HGOf2yzg79fACkTZXg9OD/WuI5r86snRLPXhoeBgm2RklLIhVtEiyA==,iv:rXNWspkAHNGMNfCgQCuSZKEgQNnif+mek/fyi29QR9w=,tag:X9sP8/u9YWFRPvHVyIlZcg==,type:str]
  AWS_ENDPOINTS: ENC[AES256_GCM,data:dZgiVYCNutlH0uNh3IEw2Sx9edIFXQfuOvuQQZU+jKk2LPUdhWbR/HsB/yo=,iv:CsfnGmdc7sy+xkdgJuWOq84UfHCkwi5pqCIKbqA2gWg=,tag:jHk1VWneiCSKisSGMaSWng==,type:str]
  AWS_REGION: ENC[AES256_GCM,data:ENCUptKC,iv:NXupjHWorQfoKb1GZkJEhTXYN0ACi2xhXxAdGY1l08U=,tag:rGQGVed+Y3sDJCH5UqvtDg==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxVERuY1FLUWw3TW5NTzdK
        WVFaZTdvUFZUejQ3M0J3SGZ1bVl6M2VzS1hJClNxaFlwcUdLUkZqUXdkSWRTTmI3
        Z0gwb3J5M1ZBL0hyOUJ1QUZDOWdibEkKLS0tIFVmSXNNbnJuSC9kVTlRblg3OUhl
        SU1adWYzRlFKMFVvWW1PT1VoWStpbk0Klf8qB7H2+lf2LvK1BmxkPG/2NKueUUQr
        SDtnF6T4DbfWLQiXwNVXJodQq9JTiZwAe57rAqBMHYcKqVDtNKhIdQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T16:38:05Z"
  mac: ENC[AES256_GCM,data:FfKBGtfBS4LisJUCeDjrlcjFXumsuAFvDJsOc/Eoy1FnT+yZKt0W7uwBBV8KlEV/O678T/Okrmwz25YQ3ez3LE/nYnL6ysV4Ddr8IcAc0vKzakPcUBP3+GPRaiMLgzp/gzPP5pwhmwOgkIt+5Gfb6uCG7V9aa83TDH0ga4a2+mY=,iv:2PH9FNb7gSmqwQ//JcHfNEhP1F3vLygwDdiG3mXG7WI=,tag:GSbMS9K11pkBFScU8KElaA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
