# S3 credentials for Longhorn to write volume backups to Garage.
# Leave empty until Step 3 of the Garage bootstrap (see ks.yaml comments).
# Longhorn reads this secret by name from the backup target settings.
apiVersion: v1
kind: Secret
metadata:
  name: longhorn-backup-secret
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:m24QtDvqGRIDIrjSj27/dQLitdIKg3DRUpA=,iv:ILeOTjaCEEx4Lt3VRU9d1mxp/yz7fBfDiy6I5asp5tM=,tag:8x2D6t2m1iMtrHbNNYjp2w==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:/ZnPF8nnZnpWe5t3wsZ2vpdq3EWTNCRR3DBIRpCCRN7IdqJc0vavu2MzXmxFx6gL2Vmxs6OWuh8EZgRzZCMVfA==,iv:otS1Q+0ZCEJ7qAr/hKvFAKmPzemLMpJPwV/elL+LuCg=,tag:tZ0g3JMLDnR0l57XMrmm6A==,type:str]
  AWS_ENDPOINTS: ENC[AES256_GCM,data:uwVhEca+BJoLyYzCitcX/L3y6CxsCyezrGTnfeHR9CDNVy79M4Z3Jqu3/8A=,iv:HphPePFqaojF+E4Gy/5aPO2yiResBCH4DylP0LoKuSA=,tag:6q0nNlhY3IdtzN6/gHiptQ==,type:str]
  AWS_REGION: ENC[AES256_GCM,data:cq6dQM9W,iv:8Sxz4P/TDvCwEv9Y0wY7TgZJAMYxtX9ZzS2s7aIadUY=,tag:McCGyMPf+ncwGEZKE7bQuw==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndHB5RGRramhYUXFnZS9V
        ZXVneUl5Q2huSzBlM0o4ZGpFUkttZWh3QUFVCmd3czhUUzFoelFyeGZaMG1OZWJl
        ZFV1SGtEQjU1R00wSzVycDFNeERrQ3cKLS0tIHZ1SkZONGpBMFA1NktTZk54b2ZG
        V3JrRnNYRlhjMnU2U0lJZmQ3UXdVUnMKS269x1Cbr8ncFzku7CFX5t2MDg1hqkRM
        oplNwm+YLG+KWZtUceJVzWOB9HMXhZmA/oB7Wd9ozO5ypp3UQtrNWA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T17:51:07Z"
  mac: ENC[AES256_GCM,data:qwU9HGj6k9k9sWG8jmIlUWUUrY8cqpjX/n+Sxpe+pAHVo+MUEsTS6mrQCiSAMFla1eb98EhqTaAKVda8UIoEKVCgsYQGxKtjfTt0sf2jhV/6SlRMqnaazmHCJd3VJQIq4Lbmuq1ZaDm/AKZlx2MEfxRIU/Yi3eLRvqYAgC9DR4U=,iv:OnlckpWdNVrC/NWZuBKnt65SvM2ME13uvSau8G+zOAo=,tag:ndo1RGiAjGGXbz7LBNrIYA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
