# Garage configuration stored as a SOPS secret because it contains the
# admin_token (secures the admin API) and rpc_secret (secures inter-node RPC).
# Both are sensitive values that must not appear in plaintext in Git.
apiVersion: v1
kind: Secret
metadata:
  name: garage-config
stringData:
  garage.toml: ENC[AES256_GCM,data:zi1UQp1vu3Eb5h6mhAMDkNCtVa3PDScVBajaNDIz6BizPrEnPfi7myFVmTjVrGC3AnXXXJobkzjgbZ+6kdEcu84/N2khmY9O/mLxfLARQEJmRXGRR9JP23XlqB01Vv39IpEYr8SxJFhOGF2WViO1sHq1IvNp90PbqFUsEms749ew+C+iJP+VEr6Z6tZFS+TGfkod2A3MDkOl2UalJR/ujXrv07o73qFN0fZucZOyi/HgBDiJRT0exn2mFNg8aLNt9l5tlZJCitXwxEjEzYvYDplnuHZpYEo4IlnY/NxDM7RGrWLQsltKitnIDkEzkjcwWg9hYZvxTEgEY9T88G72+LGrDedvAwJIgnCEwzzcLImzN1b39wHdHny8erK5XM9DNRRyKE2BExxppToEK4mQt34Pc0aVa/TRLh5a/ZptRuOO2lqqw6mRzkXtb6/1+Sd2RRt6rE0FZGFXWHwgAWL629AbEM4lQyzJ2E5ueairCKKVoipqPPp8bz449L3yoh+r75RRVxfcchjeHqkv1Jwk84WLWDf0JVLdIqJegaLhZLJVfoIo/ItB+UPIFwPKzTozg3/QQ4qF8WSO4JsoO2jl0CsNwUlN8bos5FvuHVLoNEjNwYjQ+ngnKDiix8Y964jNGsIq49VXVqhGlFPqRTMwCJpHsp4FwVtn1+GMbAQtXq+ApEMD45XPAFEkr+s0zxyNqtKAld5Fcbn4Vca8bm78ox8STBB4h3L1+5hjsziQItOwlczfy6FxrA9b+ZNfeWeijZAIMAurwRFltu6bci81TJC83p0CsI2DZAYJAFHUx0+df/kED5Kh5QxYFqroE62EgbWeUkiOuO3vIkSRoG+tm7uIvZKvwQ2B,iv:Wik0O1pLNmOrzM9sUGxp8suQI4UyLpSemDCvSMcQ+Mk=,tag:4VK9OAh2GGDn7ry4ElSTTg==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdTJlYmVCMlVtN1BZZFNG
        VDV5S0ZROVhYNTVIdklwTjBmdU9nVFluV1ZRCkdYTzNvaWV3d0cvbXhxK3phYThS
        SHVPQzBNdjNGTWltdGdiU0ZCTkRzZk0KLS0tIDNUUGJERGVZMDRqa2NmSVpWaDli
        Rk1vNEhjSEE3NlZGeUhVRkVWL1FSZUEK5H5tQr694u/a2w8ab6Hk4ZRQ6WZ11nvp
        AYYE9FRken9oDEooRO7aVAg2LnDdegk3LZ3jV6w0yvMuV8li595JQg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-15T14:04:17Z"
  mac: ENC[AES256_GCM,data:C7PreXgfj1B+FmvSM4SLkSAl2IYnvtZKKXZkx5OwN4OM8XPwcJL8ojXYF8zoyiFyY1p0XYlY7KIPByYoL6jNa6x3ATjqa/kaePHZklTBeqaufQ4tXA06pgFbBdtNWtSaObuidhv4XVf0wB+mYgjjzKqxn5hCvjSwb9T+Mn7PgN8=,iv:Pl9y72lTV50S1T+KFtjkbwkNixsBaFh1Y+HSbQit1Jo=,tag:VqSEgAeiWmOtp7R65NMTng==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
