# Garage configuration stored as a SOPS secret because it contains the
# admin_token (secures the admin API) and rpc_secret (secures inter-node RPC).
# Both are sensitive values that must not appear in plaintext in Git.
apiVersion: v1
kind: Secret
metadata:
  name: garage-config
stringData:
  garage.toml: ENC[AES256_GCM,data:xwLfJB7sm/UvR+ABgKRqCZajKtCxCaaYdl3iENRhh/+zyx7V3bd/QQ1NwYJ5X1ouKijHbgWejqT4n6AGCYl93c23Mh5uFVT+5cqiL+hGa/3GWwJe8h+UW3q3T3WNJtuOYtGSktsLkrNv/h6Aw3SOFvcaP7e/MCUHfWUqfoLBtAFLYobl2qLmud2kt92HjB6j6PMyH+SyGEMHmpCjyXljJvp0MjNEP3Cdp8H7muPbPbxPtqhY7HywTGLNKComz9LgMUCEKdugKyClJjcFUGKGib8OcuPp+mZwSr9Rom/1tnXGnpvhT4Li+RE3RjRaGxOBtW5Y4XWWG0yWbOmWACT9FXuTK/9x9j2Kffiz/qBYkjW2SGEvXbglte81JXtQ1dNKTbAzbinPx72dj1n414je+d2nwRWGt2GNtshmA3KL4wel7HmHp/hBdVpJuyXlf5DSam8aHJHsgP6WNcysLnJDYkhQlL/BPqH5gHRgPxq02Wa5J3bsvxS9XtTkYzeC1gu1DkU5ZfaWd+bO27nfzA2g/WiCVgolPMIxnzU0O/SWJVnR5f68q15OQkY1/ryNNq05dRmo1oTa6gha9OYBAULV6AVLcN6UxF08scDXW/+4i/NH8POWtX0BZpPcsqk05ISuoj72HQ7M96Uu2+jIoULgBMyQxxw9n7YRVTxr5wUtZR4MivUUuvc8ASHrWuXSPGPK+6IXQaEn/dO91eYM4leCJzaoNLALNPLJF8j2uz5D88W/ZpE/lyhLzCaArkY8ZKZVR7P+cGYyMJYm5ZAu76EizQju1OUJlY9+YpX4cZ8cq6fsT0LL6shayZjPtrhSW+FD/JyIm+XzLLRF0rmE6nkH+6EcGmBWhJzF,iv:RrIurNCqGkMZgCpbFfkTFGu/CeEueQSkNEzOFHZ2qHo=,tag:qXpU3LglnW8GhSERMOT2oQ==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDcHlMSGgxeWxrNWJURXYv
        ekR6a055MWR2b1lsVFdxZ01uSW9CU0lzL2hjCkFFK1piSlhidHgrdnczZCtoQk9O
        aG9EUFBzZDJQb2hXY3J0aDdnMjVMcGMKLS0tIE05NGdaYnVOR2J5N0JwWk9Pa2M5
        ajFRTkMraHA3ZFpBcW9lc0ozKzZLY2cK3XVZZ2ncOrlhvWBUsezAho7XrSbysJ9p
        GnKDGRH74XnP+LY8jgXTs4m2ltLji/xKjhSqQTZUOjMY0AWXwFHOIg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T18:00:58Z"
  mac: ENC[AES256_GCM,data:aBRGRA5l11Y8iLORU5yCopz0++PUB1lQjHlFYPiq8BF86L24T1neROy+5LpF0O6ThNbo7AZXcbOFLYtXfPCLltWVEs73VdVLpzHtdH2Iupoc9xD4DtpJGQNT0MUFmNW+QRsGe349y2A4KYMIxu/Q8OMu8ZBl2qK1Ev3Sx9yDa0E=,iv:T6b2QNg07SGjJ1vCPt3aEuSbyAvvni6NwSwnNm0e6hs=,tag:L+um4UHIqcOR/vivf3Vo1Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
