# Garage configuration stored as a SOPS secret because it contains the
# admin_token (secures the admin API) and rpc_secret (secures inter-node RPC).
# Both are sensitive values that must not appear in plaintext in Git.
apiVersion: v1
kind: Secret
metadata:
  name: garage-config
stringData:
  garage.toml: ENC[AES256_GCM,data:h7M6NvjG7QHYWQhdzuNQGmYzblefyVaZ9P9E7o8p86aXiMFH7gR8EmHSwxrOy+dJrLge210ddbngrfVdbOorcdihrqAwTcwtgLgYKftSJcNreB1ZDe8lVQug7SE4g3eZeFNE73fz6xksfA/+a9vHbSHPe6nFNS7+sys1vfoT4tJuLLlNOHWV9LjpxZ2U4676zIdkhW/u5sBVM0iFJgcWAPit4nYcOhO6lwgTYgWEvn5mjZMo3JqoFVU0KdsTm9LSByKPHPBAyLcZ0mSyodOm0to3dgH5tZptXbWoz+Sx1WJEVjQJ8l5C3C8xvaqPJCgASPPFoiRM+y5m2gcRaIu/Y4ksCPk73Kq+utUL80Cn12qk8DVG8LF1HODzeyzJHGjuIyiJSbKp18paUe6RoztDLYjP1itwH0rS72kn/dD194UGA4Y4241OwCTR9PwIO/7EaLuu59icLtjd/QWVgWZ6BBqLz5IILvfIuBHst/Epm+wxGXm7PEjHMLqR/Jue/V60rHX+JG7SciS+589jBxgm2MwZByUkEccP3j9m1KYLysg7kahZcVQNuVd21zNxs+HZ7MPj/gOve5mfy4TDWlV4ZK7t4pHkSEC2/6+ty1I/GRXg4Z6DxDJLlr3AhUeINL/pib080AI+gn2c1SoruChABP4Sz5upBOfaCqbbzaYgylubIv/9dXrEIiRoFSmtczo6jZcfCVu+gqVipLvf0xSlhaTnxEa/BFt1v+aT6602UXKkOPtK6ISpQTz8eNw88g3mOVH0YINiO0KyhiE2cuU1rZnVGXab3mQbppwZoEtKhRe737jD9w6isC0O/OwuskIsktPTzR5ESEQxJo/0cOMEB7ngTrAdetd4,iv:xID9ld1jeT239/wQVail5pTNUyuewfKmyJLU+lf+S5c=,tag:0L+e6zUqymZ8Dfw2h98e/Q==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1aXAycGtKV25jZjBBOGd6
        MVVLMnc2bVA2RVdsZ3ZYYVNwRENrSGxsSUV3ClpxbFFvTWN4RmcxM0YwMzJ2cy8w
        S3FIeDl1Z0lod2E3eURlMEVZUDB4N3cKLS0tICtyZ2VMbG92Z3RFTEZBeFZrTzU2
        RHRuTzFjdVRRQittZ3pZSlBkcXkvbEkKam2q4ZjxChLk5PeehgnPLI5Z1d46h0Eo
        KTLcqoy3UcaWNLDhXpA7UrvCzJ1B9I5qL3NaQlvgfW085CfRZNc6Jw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T15:31:22Z"
  mac: ENC[AES256_GCM,data:X4GUFxAVcGE1x3A2KjMe/JQRxbLxVqnm0fQ3Ko5h3ezRho3VXJZ7ei8Thd9/QSsMF1Dy4ct4Z4cwS7qd7maeLQ6HQ0I4IFqfnFkVlGwirNMDd98lDuHo40TdRom8Gsm3HA36aF5wolEHsIVorD2hB1dpYSAW9qShoxnBhE5NGDw=,iv:iQPj7NXKVPsS1P8hufya+lwrS6LXO3vKqvVtfV+o778=,tag:edqaaBBtAlC34kRZGMrZfA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
