apiVersion: v1
kind: Secret
metadata:
  name: linkding-secret
stringData:
  admin-password: ENC[AES256_GCM,data:rqCTYayfkfMB6ioejDQhVV3DtqSaCHu0CaZNJPL1Z33UJRHc0jhdQXU=,iv:V+4+GcyvR50k3r3pYeI5hwPM7BEKHVVRBdQiWLcLl7k=,tag:tocDqI7qUiwz3hqIZvJK9A==,type:str]
  #ENC[AES256_GCM,data:NrR24czHHKfcIhJw3t1bWs41oIy7f7ZY/BwIAGGgGiRQKjweEsRHnJS6C60=,iv:56WH594tWP97j1tuNBXIqrXZXQwBsbLmOLEXmoQT6DU=,tag:97Zu3bBGXR50/fkjUl5uvw==,type:comment]
  #ENC[AES256_GCM,data:aibPn8tqzz3N0yfnBbt1lcIMN/HJTCPKEGGqPMEO1VucxwyCIcee39RWrpdIv4djU+M2OUrWWW26wgYpq8+jX3YsYa4Cie6aKMjfx1vDKWs=,iv:Lg5Uz50Hn0LqEuhfFQnGiclXI6KDj/o7zwZ0WrzIOPQ=,tag:tm++BcgeDhR5XydngNy1mA==,type:comment]
  #ENC[AES256_GCM,data:qOh1Q03SxfSxMPNFILYTwaF3e3Geij99YZpuAyQ4m4YiOxoqRDg6G88Kl4MjnAWCpt8fFQzJ2A==,iv:mvL1pbVba2CvFemcFprW23DW/c2Bwk9qXWCPASKr+Mc=,tag:z+k3kCpQoylyWwF96n5SJA==,type:comment]
  healthcheck-token: ENC[AES256_GCM,data:1OdazzQzlDUW+wVChgNRhcQ3qwKIqt4009KR03f8KmXi7bYD4k7LcA==,iv:nmGCD4bNrCzQLBH37ziGTiWwVrBX30F+nfss9yyDSCQ=,tag:lvjF5zv/YP1htkegdHmM4A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQXdtQVpZSUxjN0tUaTIz
        Z0x6RnpCUldMT2FGTkxvY2tKNDRlSmUyQVZZCmVmUlNaY1ppWHF3NDA2VGIzeEJI
        bXdxWFBScUxYbXBTUTRVbWJBWmVRVjgKLS0tIEczSDBmaUgvVTM0VHZJSVZVczNG
        TXJFT1BuQ3F2NVVLa0t0ZWhWQXlFZWcKgwTAS79auNsE32IUSArYml2lMPbuyvJk
        yGq+Qb6N+a2pq2jDcPn0HShA9cJayj/sk9DtMV3P4uzyFsquXiwo2g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-24T14:56:48Z"
  mac: ENC[AES256_GCM,data:P7gfeN3tMaDVUmG7roUW+UPskLABPnut7MaiWL4rmGPNq6Sha/IFb+0Qe4mIy1DnVviYp2JzUSNXAMcs5/kG7DsVELLs6a/X5gLLqIARB3t9bkG7HXXmsEZLjljDN8pK8Tdz6S1l7XerpA/Zen1DJKJ7sAhVR/HnXqeTZlgW1qY=,iv:76DHswXsHnf6saRKHziwl4fb6Mjqenli6zrp/lyVqzg=,tag:8eIJgawa+Z/dprP9DHwyew==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
