apiVersion: v1
kind: Secret
metadata:
  name: linkding-secret
stringData:
  admin-password: ENC[AES256_GCM,data:9rfVGQGB5OiWenibsl/dqu8aY/YgNV9xB5Qr1bNyxGNtGxh/8gAPCwI=,iv:Tv10M/qzpSPxMO8DW/ULZ54sKZVVZ36XcgyR4m0hVQ0=,tag:UIseGHTA0mKHHdzrDwBYUA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TDhQaGs0d0ViN2ZTNDFo
        TVBKdXJvbnFRTldwTXBkbWtyY0FSckxxVmkwCmcxR3JhcmtmSHY1ZDIwaE1GMjVV
        MjZQQzYxbzlaRTFaeTBUanBEem04V00KLS0tIDV4ZUVKR2U2ek1tdFliZENoSDh4
        bXhRL0lBbk44emNQTFY2ZEJBQkpSS2MKL1/xEBjCk/b9aRNcXYEA7quISPuIJQiI
        +4Ohlj4w2gtfF60/yi4hsKvXSNzKlzfsecLRhumhk3Vardcl72VNgg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-31T13:06:54Z"
  mac: ENC[AES256_GCM,data:w0UaD7XB1eBmNZqbfcTEC13wHCPjb27lctYuWBFHW/kRHkzf5QpZyH0ZQnN6kv8AYV0npA3vr1FSScJEFwZk+eEifqrAUMB/rgEsRZwYmrorn+Is91VvTX2J08d7xCFWrSis+4ooA39OrliHLxU38xc/RdTocAQ838+qoV9uM8M=,iv:RgfnXvf8xH1/4c6zMxIKCXzvD2JKJkzKKnqbTmdAAgg=,tag:yT55+3ga3/lmfMT8agm8aA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
