apiVersion: v1
kind: Secret
metadata:
  name: linkding-secret
stringData:
  admin-password: ENC[AES256_GCM,data:ecmRctMb0r+2KYaU1YKLshIByo+VEEGxYJ6z2VtjYSd+dHZSe20QySA=,iv:ERKF63QxymihU7m/TmCg8/2erGrzf71Pst236ILCr8Y=,tag:qzsxbPjwuDSWqpwBgdEcnw==,type:str]
  #ENC[AES256_GCM,data:lzDhDDQSHfrVxLc+38TAJ5ngIiHr8HASk1DzZMz/lEWLj4E4XgMUvWVDAJ8=,iv:DtF9y1Tjid7JvPF5Al5a4VGCoCf1/+0Wtro79XllAtc=,tag:MfMAKufYQYEPmWD1zcf8Gw==,type:comment]
  #ENC[AES256_GCM,data:OS4GfYo0wuVnhJZPQ0T7k19PNqh5XyP1VPzpfwA/E+sbeiuS8PIePEUE4lSDxDOnMOe/jx1S2t8Doy2pFT4HDZznapVdg/0zbuvsHa0fVMo=,iv:6Vq8z+DiLnUsbV4c1xIL6krNzVbKKPJsQrVvX/G6xak=,tag:Z7GEzvOXtc64Y9K2oBl1tw==,type:comment]
  #ENC[AES256_GCM,data:gCZQckbR7M589d+ES1S9qIjnVQjVjl8AbZy1H+/7+8018Km043gDWFc+U4I5bK9oxPaUdo0fXg==,iv:wLOeKXeav/mBBT2CPudwG/evdWQRoFrgLkWfkZP6uro=,tag:8d7K9fL9lqwr0nUbswrNNg==,type:comment]
  healthcheck-token: ENC[AES256_GCM,data:lqyxSAGq9euV5KLQK2DHd1/RnZBGgC/umJJhwt5Jtb5fserGR78bog==,iv:EELpyLAGLmx6Ey8RI4TyjroFfD0NHbJEt1oS5N8OSGk=,tag:x9EiVDZsagDxzzsUuTrIHg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBseDc4eTB2WHU1K1M4SHBp
        Rnl1R2oxVU1EcGFabXdBZ2lHbnBzRGYwNEhFCkNPbWpzMnBaUWllbGJIR2tIWHNC
        MmVzUTR5Y29FbDRjRDl3UGx3c1l5aXMKLS0tIDhiTjgwMk8xTUJPVHdLUVB4MWNH
        UURJcUpYSTFRNUdqeHVKUmRybEtSQ2sK5/7vizewK8J1i5S9WE0T8/S4dgigaFYF
        Gpwfkdy3HJcdTJF+37gqSBDlQAkojd6QytHdQbK0Z1yZiH6EmlPmlw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-23T16:10:57Z"
  mac: ENC[AES256_GCM,data:lamf5WRYD0vzGsnJSREoWjxyedfjygEru3fEpTY/Ya+GwdNUXvaessbw+mfzauP91nqqRCe/RmGqJKvlqLodPZx5kNT0cnlLELByCkayJ5T4Ap6b7KLOH9A3qmVC5PgQTQy1K1sNSSjPLEpBtT0EnrfNY5YIgvE1kjkx+6c5kNU=,iv:G+Ainie/ooTpT7vQodjYoKCI2mN54M8gyOMWlpjKHoY=,tag:+ORSW9UJ/BvF6ysbtdDKNA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
