apiVersion: v1
kind: Secret
metadata:
  name: sonarr-config-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:bC4RErfnFHGXAgNGOucq1tvBUvWZuzh+uN9wnzlyaLLcS85Je0pJaet5HmXU5Uz4YaJHhDmsI4yUTQ==,iv:EygPM1UniZBwQPTtKQuzMOUaAue2oFaBIdeemBVaSYQ=,tag:7vibwIGoecwkcWJhbb69+w==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:yE/H7me5SPAU9OegrR/vkcEYzz8/q/+IOJIHQsgUDfRxrpy9iPNtSZcbOIg=,iv:/vvk0vGGG98OMV/SPI53h6NUkhHXplMqrMjk93MM0kE=,tag:lAmwckPYUbkZlpy+jghUNQ==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:OyjDfKMTFeJbOc/w9aCiEkPqeBYjIpz0w30=,iv:AajS0XbeEGmRUmX0cBaOh69VfGtiJp+WIWdybvQjWXA=,tag:48uyixuei+3xCrXxYrKeJg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:9BeEhEtaw/NSpzkaoBNU42dFNGUIc5LI9yGn0UIZXV0HJvSl374x6nkCWTGMX/IKjxINyfpta+5uUMwMUkW+Pg==,iv:7jq25ZYfI1+r2GqzONWUrjx6KyiAEfUxnsJclvFNaWE=,tag:pEtYbBfErJjkl0EeAiXXOg==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjYnp0ai92ZlRDb3ZZckJ5
        MmxkTE8wQzd4WjZ2a0ZxYzNjeituSlgrSjIwCk91a2pLTUk5QVFud3JpMVoxa00z
        REJYOEdaL1ZHamIrYXBnaWhWSGtiNncKLS0tIGphTkhpQkdpMTV1dXQ1SUF1eXhk
        dkh0ZWZYZjNrR2o4UDREbm9PRGpaa1kKuxZ2qpTWiTvxlLkk2cmtiG88Vulbw+Y2
        +2nQrfn9lJIE+A7LdWdCBnz6pC/CI4g5OOPv/iZKymzoT+6kuzOVVA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T18:47:28Z"
  mac: ENC[AES256_GCM,data:DKvWvE1g0Sd/9lJxs0dOx+1nBKuhcz9LMPrNiNtzqQACNFKCNvipKzaZ8i1Nb35ktMGmR1K3QStebunSdrZ1dAy2mIyTEqU2M/XYgTyrSKaq7rdBsLxfE4VeNTJDReEquIfPxfQAUi+ORT6zgObJYnnul+gx/QP2u0qUuyvAStI=,iv:NbWNLzcajQzFC4tDV1FeD+Y7e3PrRMc1ZJNgWGPB1bo=,tag:gJhE0IfpFaGxiNbiKtELeA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
