apiVersion: v1
kind: Secret
metadata:
  name: sonarr-config-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:EdE1rzgUB5uBHrMAzi3DNVFxszcf9gG4yoWpYNrRLjsvPlrFwH18RyFRjr40+svwer8W/5ie7XqcupQ8ZPGhpgQsT/56ZY1kjK8+InFw4jcPbHHfB/k=,iv:xFTa/CH4LhOPID/aB4Qd8owBijRNDVV/xK6QN+nk0xw=,tag:FSM8u+7busW1UbR71vRGQA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:6GSXCJkXIEpW2yjBlmCwUYLlamt8+/cWFYYLZGjPq5mJxaZkU0AzMhabpLM=,iv:h3KIeFezdFCty5szAaMKAtT7N92gqoWNuCR6SplYkGE=,tag:oNKlAYdZYGU5Luw3penTTA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:My/1Uh7LNi05PwHUDg+6+N2i3V9dJBYt,iv:qF0nRW4y/M1xvlVYMp3RBuPvPTKKaPT2whw7Y0/GHVM=,tag:ektbHDQiPMFfrEbJ+5buZA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:64EpuA1tDhmrosKQzLD0rz3LymXuOorfTuHdQzPxI8YrHasnh6rXZmq4tW6PRKU+WJaTj7dt+4EZruPWjcL16A==,iv:vdKT3BtIPqTYGdRxQtF9GJZww+0+xnzQ41QsbnmTcDo=,tag:hR3wMskFxh3WwrxV6M3hoQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6YWMwVjFIczYrYmx6TDBY
        S2g4OVl3MVRsUHpKTUZNVDZRakd5ZkxzTnhBCjloZGtid3hBYTBuVTdJSG5PeDJ3
        M3FJZE1iTGIvTytCSVJ0Y0hRMG5QVTgKLS0tIGZ5VDJQWVoyNWh0L0ZQL0pJNTR0
        T1h2QmdkREcvRG15WCtLT0JsK0grWncK0nkK0JY5ZKkPRXzhJuY8TCmdvsalDpnY
        jUL/YlHdWONw+AtvTwJAhXOkGq1E2KGQ4byYbChEgZZDN2jitUs3oA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-24T15:01:50Z"
  mac: ENC[AES256_GCM,data:BnGrDieX6CrAh93YTyKOdDaQeZ7Dg8b40+zsemavcV3dZxZLfbmzBVpcu1FW+G0BwQ7YJy9tiMZB2eZoRtjLUT9ns6rWee6O6uTjvEBo16GdowW03h8pCXRFFr5acnjB0enX4cpeACflKT/c6ImPoQdw275rY+Vb5aze6tIesfE=,iv:ycOzNJXzv40iwvE5U7WpzAryz1W1Ly6FlcmhsShl2mY=,tag:E4KIsv8jYyLqJuvTW4Rugw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
