apiVersion: v1
kind: Secret
metadata:
  name: sonarr-config-r2-restic-secret
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:rR78682h9rCkiT8WhgbTRkqWTQlS8YB8ApbH+AYanvVBoskh6s/gfW49UjVLtTJu3XNlrQm70ePy8S7dhRekaYnYghemkQc16AYyfAjp+LFvvDfmGpl02zs2q1EqNLdQrXHbihg=,iv:XunELOufYJh0U9alUOO5pAkU2p+34jQUbzgW9hVVA0E=,tag:GoCuxFCo7gwdF12zftGwIQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:kAJZRaQaf93RWM3BAFseoWLKH+p2rJvhYd45LKJqy/uMaDwZtSnDEbg6+F4=,iv:iAWQi2zhdAdOWFFBJK7nz+HRYUcbM4MUbp0+MmkcsRQ=,tag:Ghxr7abfAoPIhuUAz4juBA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:SvP6BowLs5M8drxM5UjUwbuQaeIBNSnzKbV/BSV/itI=,iv:oM8jw+7dSO9WeybCVJy30Iy2LfYl6y/cjqeglMXDfKg=,tag:/H6g22laUrhFTrwZaXLV+g==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:UzkWw0Vuwm5r31lKMdoNgyyasTh5HQBJn3slSPRBy06kzryZzRw4RnwShq619uasEYZ1GAxr6qqxnFxWCign9w==,iv:y++rjoj5NEqc5QH6ThZ/BybsAEwZ0DqqRgEm3lM1YX0=,tag:aBR4yzmAU9+i/y1pnPYUFw==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:uOTSYg==,iv:UF95M+sF2GJfr5HwRxMAwF4Lgw/dfkwIKUxnKoEfAk4=,tag:sl0ipSLUqaeqWA2bCsIFYw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0N3JMK0Q2N1lGOHpnVWVK
        bnR0OTU2ejFVc2M0cURFWUVSd3ZxYlBpMXlBCnJ2UUo5UHRMeGpsRSs3UTFzNVpu
        MHRyV1JUK2ZYR2tHZWNpMjdCM2I2VXcKLS0tIDNORlhMUkhxczNJblREVTc5RjMw
        bzJUQVpWRTZzcVVhdDUvUmVBNVZTLzAKZ2DfDMO5xTN801Rxc8JEcYE7HMyaLzWs
        bwY+2lmb7gPawlgFiL3Otx7XA7AvLuJCj+sjPmsuN7pxcF28Ohvv5g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-24T16:34:59Z"
  mac: ENC[AES256_GCM,data:JO9QFhEHa4YyXtM0RWCqGF6C5ENIVIL0ZEukeaMrcPKHD/v+sOpDc9R0ILGVaA8qGrawq15Z8RKwCbjLIGeiYl36OTUqNimzVHTMh2Z1xr+O3T4xK0iVdgCzxbI+c7HcEoZjupetw473cYfqUNdlRGdNE9gyicJQWkC4TXQVHeg=,iv:lUWLQzEt5XsXWYx3mEMRDP8tY+QEp8dlmebzlYyfJEc=,tag:AXkP6UkyhB+Ak8peMokcnw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
