apiVersion: v1
kind: Secret
metadata:
  name: sonarr-config-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:5iQyAQrEYaWhFFunk3Yu6C8xCPgk2fa694DthmLQx8rZD9B+OrTw38XvZK1lMGDko2qarbV3SzXFaYdnjkkMWCnJCn6JvUdfiKBxCn1V+yk=,iv:UcpVm9Rl+HXQJ2cwyr+vtntxQSqomXle9YpMh/m3vok=,tag:OE2PFK1KYdqcC4cvG/Lztg==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:3wFlpVxSDAuKFDk7300GPe2eNyyo71Nt8Q0gVbn0LDHElLtFSjBLsqKzz1A=,iv:2x42Joz2K6WoKxv4xaaCleUE4kI9KQT6T4iH3KLeSFo=,tag:rvKMfTgbT7zcB+Zvt2uIQA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:aPmBFNrsQi1mj0qOeUulEkhTBXb7NRw1fqc=,iv:prNrd23mGaBDBVWwowjwi+i1yhTncnidSJTlywueHd4=,tag:geW4aADouLeZ1O1U2S4rbg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:A9Dd86Z76qfmg3BOCikSkWmm8FtCM/uE4/bVjIkDufhzdFxB9JKBIQ5WQS2kP1WHmutMYERDICwlreO/PB6eKg==,iv:qHYmOtfuifs4zVZHcRMjSliKlId/JUpydCZRHTJOh4A=,tag:sSvDX5mSpVg7u11x9DnMNQ==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMlNScG1Td1FxMkdnWjg0
        c2NkWThZVmpYNWRMTWluYXZnQ0d2RVpibEQ0CkdXeFdzdVBxTFRiR3I2STMzRTli
        dUJKQm5BOUtncXJzbmlUT1ZZdFZKS0kKLS0tIGw3RUdJN1V4VnJEUmg0SFZST3hz
        ZERkdkhZOVFXcEpJVVdubWd1S3d2RlkKq+TmT3s9giCbuugRHQ2Dzjen1ZIThXm5
        dL7zrWg1YA3RsguFJWLsNFfkEp2v8gcmqywXi4/nqrB5FuRbNRRNUw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-21T07:34:27Z"
  mac: ENC[AES256_GCM,data:xrhF1ec53+PdPH4o2hAzy0bOw8jx9fNcoulNhfa9NejumIHkeKKeDZxdjpGX6ijziTVqjtiM3Goc+iKC2Ifdq1oc+9G7Q5TJtK07mmGCFOKvkb2/6WWq8Ab6Gt/UyG3eJbGI5rLn329bR6byKaj0ki0ZerLiLrSaAY1fBBIBNok=,iv:0/WjyLxTdBCh6fWrqE7RRvG+dO/Ud/NKhKyXKZw2SrA=,tag:BkAOzKUb4yvZK9wPNgKoQw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
