apiVersion: v1
kind: Secret
metadata:
  name: sonarr-config-r2-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:Cm8k/C5TYZlbqjkhwSM95MSKMfW93MboytseYaqBcZwwmKP91GLvV/8+NmfAhyQ3taFVYW2mrsasfwcFo09C2Kgopn2yNK5iRcLmAN803CM0JZUJn1BN10g8hUIC9VVeE2TdN+4=,iv:femOKXPsMaeEeoE80hbNmtgz7pn0y1sA3wMuKylajRg=,tag:a2XGW1ea6PkY79YbWkeHnQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:VWlLJRXodpNE2oNHCC93hvJURCofhE2JmGo3N+LvItBA6eIvNBQBBLpv+KA=,iv:Yoi+1GhFWnvF7AKjmwryLf/6lhDV/BOxYryUpTdVgts=,tag:4MwCEae+ilFNSTrA4VBo9Q==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:FTSJuc9PdEuALXgreqBDqR0/5m9Kn9qPGehA8O8q8Ac=,iv:/X+psg6PY97ti8Q0+LZgBM1YvL4Dh+i46tUFn/8KY28=,tag:vZPDbjtbpkG235qRtaU6bA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:BRA5CYex6UewaWQerN1ZDb8zM2x71OgEN/R68QOpc0hjpVQU0S8iYJRGxIhssI15mExCCj7CkNgiKEn+9ABZ4Q==,iv:VMrGpysR8b3BNLL6RHlB5lJaaP7AX6snLaQELI2L60E=,tag:zmGBpwkR2LecYu+rerL3oA==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:C2ws8g==,iv:tdVaT6L5/JLeS5VMG9rAIOGpjzIi/5/QJPn8F+lxTxY=,tag:S96LViyiyODik4OUTAFdJQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMzdWb0tYZ3AzbVQ1Rk5K
        VGFQUUlJT0VnK3JsaEhVSHFaM1pSOUhVZTJjCjZNQTVpT3IwSm1mdVRxZzIrNDFq
        TlVVS25SK25kNDRDMXVzWDNtaTRzb1EKLS0tIEVRTVBneFNSbEFMZk9DZjBLdDlh
        V2NmVTRkVjRyM2dZYjVRNlhhK2grOWsKf2I/c5oS6llQMhR6C4wtt81q9Hj8Wb5X
        qPX6ggpPrvMiusfuQfGC/fkVfIxxDjttK4bddgTRxzk+sDwgql6BvA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-14T10:31:56Z"
  mac: ENC[AES256_GCM,data:speXgXFbhei5RoKbCp2QrzwAqeG3gNdJJpZEPgX3EevkIV/ycoOT3vt+ad0NNLNj6r+mJddZ+ibhoz/2XJV1Es5VlZDpwjAY+fgAYFpPNTi3XZon2sbyBJq3nyWLrYLsR2lgyZf8JCrPaIaat/c8dMCmqSvRUTsttb0VEZS5jA8=,iv:xelSYWIH3B2cKpOe9DYjdkH2QRG+in/oLRIzxQ7hiDM=,tag:Lmh3GMD3TRwMuN3U8ACDNg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
