apiVersion: v1
kind: Secret
metadata:
  name: sonarr-config-r2-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:58/Kr/Z+nYgbTNR6prY35XMSt4JCZ/YMoBYJismI/y95ngkckg0XxdkQEUEOrL911wu638oTHizdEeL5JFu2BslyUgAi3ge9tM9/n1X4DLzzOWBhwYFgsCqmRzEpP8yregBFciY=,iv:kiY2Vw0z8+pWN4fQwqBnlmPL2PDOyLHhH8bHeDk0tTY=,tag:3CS+N4h+z6GoviPCG7+rrg==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:rB+bKpTvsTn30IvzccyoWl4RQ+rXNiEXjtCdo+YihrV7M9RUq3Yng/18UBA=,iv:u7sMYp0VIvK+Ozw2kRPYYEwHShjL1ajQENK1PJTYOM4=,tag:5FXSIErVP1aw/gnvdwut6Q==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ZjB1bMufxD9NTabLlEO9HnO4cXUOOpQ9JdbN4NwAspI=,iv:wkrW3dmsm7dsoefTKAB+Ijaydw1ycHCSJ9pXjnMdTGU=,tag:rbdzWI5EdG9c6m/93E9lWQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Kh3EWC/g14qZfhi4pXcquITHg2EzNL99fQ6CDX+hjD+QmAVvoeMmppmqwZ0pF9K6CjGNehzf6R/ptZ/abPI9dw==,iv:hkrSdEa40EyEqlI88hcfeEv72Oh0+enGuwD5rGKg7ME=,tag:j3o8uvG55a+rC9GBbdXs0Q==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:EMHLVw==,iv:fQ04dHeBPUDsADpMtWU7Tltea41nyYs73975nYrZxdM=,tag:8RypVly2MXADDR8BoH5dfQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMjdzdmJSSlRCOHBVZTlZ
        ZktONzJFT1RiMnFrbDNJM2pMQzRIMk1vSWdnClVWMmFMQjZJMWdpbGZ0aVV6djNz
        Z1IyQ3NPS1ZuTUI0NEk2OWRLNE1TclUKLS0tIDJRL0d2MEg2UHlvbVBSTWFTWEla
        MHdBRW5pejhaWlFURDRtTjVCd3VLUUUKs5dIjFpAmpdeKa+hG0u4MgM2yfwHxb4y
        yJtz5e4/4GAVDctT/wAA16XIsQWkUSTEb/XIT1lRqe1p0U1SzoZRmQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-16T15:11:13Z"
  mac: ENC[AES256_GCM,data:2EcTTYTHFi1kFIYpxOcCeFkoBPsGM9kxeE3f1u9aZcHddKi+S2UT93i25Q2capNwUO5DfJ6xMg/26R1FZ9Yyw8teXrmdhYE+sX6x+gAoQ/SLrXMM0oIiV9FSKy5UpmkTdjTXSGIn8+1kqVFVu5a37bb6WBqfML0rScSin1d+Frs=,iv:JbyBQpaDtDhr700tSvnGbPknPGm2FBGOG47oixJjIVE=,tag:e2ETQjbuy6JqaawUuX3rPg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
