apiVersion: v1
kind: Secret
metadata:
  name: forgejo-data-r2-restic-secret
  namespace: forgejo
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:z9g9gfTIcQIG2iy/jITknPcQ60v20bF0Ed/0X1uryMOnPkrXYcRaGJHoUI2ZrcijCbbeQXFCeqvWBM223o/VEetIl/WKIwQEl3lDNY38sWb1mEgK6nRQrrhfu6XOD8tjTKUaWw==,iv:WWlfWK0bk9n+eXS34xQpA7p/ik7n+XGBna1deEQQJuU=,tag:eYlDlS0e7MWziIXhbdmQtg==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:aSb+67RH8Hy4CRo2ErU3d0Ds6SF9QIxBLdsMixj2iwAeR3TjtnOYDbNy/oI=,iv:msdZUW2q5d97R5RTk1S0mpmmU8QwDnFJ8dWg3Es1yBU=,tag:K2/5mc7wQTAiZdsAWHcTgA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:37jNQH1oZt00vGiv2NcvzgsE/b/6Lb8HtH0z2RYxceg=,iv:v9cW4D+WevGjd12P08+c7egUifogDl2rnoniUQtat9M=,tag:O7Lqt8oOb7c9Mf1nH4egvg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:0KAy7d/FC0XHdV3KQo7uz5iQ9i73LcwJ9k56oMOq86ib7qoso6djNpuXzZKRZSevwhkGpJ1RxY2+bZxv8SF/Lg==,iv:7Ik1U9fj19/N5aROP05L0RPQLDXEhnWPJAH1A+9ZwmI=,tag:6Kxp7BGZ7MSkoQ96oR4ZcQ==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:ur1JhA==,iv:yhsQ/iMxzuSXUjFxNZhShAUwe+LLnJuqemaC/Y8pfxA=,tag:6dhdOG8f63Bmb2rkcxrvkQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UnVZYWE3VzZqNnhucW1o
        ais0blRjY2FzeXVFMWNMeVRZK0cyUUJScGhNCllIb0p1eFF3VUVMS3hqMWwvMHJD
        Q0xHdGVMak91ZkxwNEpYUE5FbWdlWmsKLS0tIFRkNkMxaXdBQVN0UlllRWZaWWxu
        aDhjN1gzVjlEcDFwYlRKUUYyOFVlU2sKcScyblmqVqw8ZQWg6iPR6GVH3+u2qMX3
        2D6wi6mDsptc/h8AD+IMg3KLxukrJBu/X7Fj4s64JPAfq7kzM80nBA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-04T11:06:03Z"
  mac: ENC[AES256_GCM,data:xphsmdpKey3NKhFc+/DJhWMysEVbTd6GWIDKNKgAW7CzKUZw/6NOcVAho2EDchGLQ155j7UbxSktxHgCZakG1XoIR+DUD0LmJ9i1WjrR0zpy4o960oV6OiRSmqNEHFTNqJKk/4MeubJA3NiceNzjsdo5v88joZDFX8NwesecXWs=,iv:HLwLQZgJVnxQ9tQ3CAvwj8sBWJSPwhkzZBxYBpxNnOc=,tag:SqDyXoBomZXRljs1MNvQKg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
