apiVersion: v1
kind: Secret
metadata:
  name: forgejo-data-restic-secret
  namespace: forgejo
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:d4jr2x6idTFKiZ2IFgw7e25QRS6WqgNIAUMfKV/cIpODv5cmKobtA93nZQXF7gkvL75wGw7PVa+ztNwi4Nlb0dKtdQDGBBR/yiSqqv7qARCwcl0oeg==,iv:sfLF3+lg8/a1txqlNjrOUTvz6Qs2hZN0Vx920LRUsZ0=,tag:ZKUwoZSEAlbEY4lcQ5zf9g==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:8vn5lglGMYioMAf5EuBv6YTSl+VdP2+LQmQ4lQ2zWUyeVu62M6kWNAkZu2E=,iv:P+qNawqqPvb6b8nBi3QkaGc4nBPft6YYvyso01p9bio=,tag:+zAHFp8SaDTm4XxIGDXiTA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:tCJtQq8WZpC0iRZoD4IpsIouBJkJpVzz,iv:Mf8TCz0StFktOpDJGLHLtF1+N6de7D8i89Y7NZciFRY=,tag:P2qvRiBJ6hAUSPDM9mc4hQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:YNCdjUSfw6hfrkO8G3ALlfzg+lpLOUi/wIaaJdaMeYYpPORylZGuVzxMMg1+N8AVdijkoMrAH0EufmI5/q4erg==,iv:uSJuyeaRcIjlIIFua4Y5ML8MRUFjgqLrNFMqk4XfTc8=,tag:52OEdtvaO15+ZTs8yoaHnA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzU1A5LzhoN0ZVbVdQb2w2
        S2ZPQ2tBS0RwV3hMTnFXSUJlRHh0Tk55Tm5VCkQ4RUJrZFlvZXU5dG5peEN3VDFl
        cTVYbjZmQ3BodjdFcWdwRWg2R1U1alkKLS0tIGZOaGIzK3VPWFB3Ny9BbmFEV29U
        c1RHY202YVZPcDBUUFU0bDVIbXZnNFUKm8Xx5awPplmaWbI7TVbvbMYWU8okCiO/
        SPlrg4oxU9xk7ekFiQTmKtm//7iead85IjPjRUtegtc+FzdYkPV5vQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-11T13:48:06Z"
  mac: ENC[AES256_GCM,data:vIWcTqmefXl6juUlHz6kT5LP2gM9jgG9MDx2ttPuIB0+ZdJ4xzvg82UtfHWRZevJf+rWvzBXCyfej9fLULuc51XAVUeulurA716Ka+j5sptsuGf/k+LkQbxP8CoaU0Hfjf7X4nlXuJALJBNEUafZBzw5YIdNDk5Xe2r/KmQX33U=,iv:2btwzRhgiFyZe8ORXE6m6TgBzFoQgd5A/Afp+NE3+hs=,tag:gvKp2WiJsUBteozBL3aQKA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
