apiVersion: v1
kind: Secret
metadata:
  name: forgejo-data-restic-secret
  namespace: forgejo
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:2nVA4E8IQXDX3dOs/myXjHvanbhC7IEinVwoKTC04o5h+6aUrXpPPfsV1NhS/R8zxFZNy8M+Fb4jpGEBu/v8tPbrc8PQIstEMFlQc/6DJX3IbCEd9w==,iv:VBeYL594hDWft9H75fcWxG7MLfpLIRVPINh2KSO+uec=,tag:pEkNtHR2nQkgNS5bpCkC7g==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:VNI9qraZVQ2BIADBrFAlY6qgCqffrpU0SM/v78aH56kiDGahOp/DJjOSF0g=,iv:KVI+TlHpP1LgnTofmETkJcWTXJVX7M1bhbPPeUMX3jM=,tag:Q+vUVK5JswWxdXmGaC8O7Q==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:kn8Pmir2Hjx3cUFvrn6sVK8ZMTJsKmIV,iv:uk3cFZc349F7i0IZixBTxEpw6CV5vhY1ypt5ARzuqxs=,tag:XDbWiu+ue2BwCiZKT8zhPw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:DFWYdySxFYUAEdFTAZYpcNG7BhbbZ8imP57RWItdchD/h27l7Bzs3zmxCnSBzi3f+EAy9v6JZ9TWtj6XE29R+g==,iv:SUGRmp9zfY8aUbyVa7p0nUdx3p1tO1EpT3UQKLYRfG8=,tag:3wGhI+17a7qnzh9yi4B86g==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDWE1seHhML1l1V3V3eGYw
        L2s0QWxkdVE4SHMrWGVFeTdEeUxjZ0JmSlV3CjVjcThkeXIvcm9ZdXJ4dnYydXlv
        Ym51clJ2MVREenhpeWNWMDlWd000U2sKLS0tIFZ6cFZOcTlud09DSmtaeklrc1Fl
        ekxOWTcrcFpoMStUREc0aDE5Q2d4bkkKdrPBK6KeyeXNXEViTgKrGCfBAqEfPQEw
        BjeekUb69Fg4gyg/vRVz5zHIbJ3ooMQct0F73/Outh1dPhH/ypNKSA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-08T12:01:19Z"
  mac: ENC[AES256_GCM,data:x4U3wQv7uNVeVb7MuUB3NkzSiNoSFnwS/KDp36BX5VyFaePRhv2fwGboAlu2s2AcCuYe16oZtmBGCNdEXxjXoCYzJrXYwoUnLMiTmMJ82JKMa/vgqyGyb+tfU+I6B5Hs9N2PHXm4DLcAySNZoAOQmPSU4JhHZq/Y8C8htmyM5s8=,iv:e+Ay4x5GNDL90OIOI3QkBdvvB+4pve32xt8OHDD1w14=,tag:C5SdcA0/xHoRyC4evY4dnQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
