apiVersion: v1
kind: Secret
metadata:
  name: forgejo-data-r2-restic-secret
  namespace: forgejo
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:bHPZfg6LdKLpzCvahhM/K+6i8RqxvGWZcaMA8+n3Igm/FpFcCUfSGO1YqjwTHBfm5vwvLFgLBK0DoTzuWIfVNQ47Xp472UBF8EnZG0qp9caONEi+56boDqXRxGpM5s106Yy59A==,iv:p7lDQpq7YJows9LbVpJGRZ+N/6B42RoD/Bl8PRD6404=,tag:TRyWolHBwk35WhmjxJjx9Q==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:SrhZjq54eQjRGrMHejUMts/OArZK14DwtmaAGvDXYy68VZR1wCfHea3U/zU=,iv:q0ENRoAsQCOv988ObY1F9xQbz+uN5y52rbyNkRda6rY=,tag:GXNk9ody+jGylcSwOhn/ww==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:aW3OOU4aYXtw2S5sO0iUsXjZrPZAcc+C/B+2jgRRcKE=,iv:aeRFZwnpAV1G+ta6Yczqood0n58fqbvjrt4jUe+S4ag=,tag:46VRvdWlNZ4lnx4jUk8spA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:uP0K4ilOQ3oVvdeZzWMxyV3hPRNCSuK5/OQweBfmzc9Y44c1j8FGLCKPeHMXnOSXTNAYI0KjkX/0e5Znq/DKrA==,iv:6AQCBH1yDV63t3cfH7Y/9MItUKiAjLhzwty3kHhYK/k=,tag:kJs+irZIu3kX6IDOSBlY6Q==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:Wrj76g==,iv:vQfewpDLIexFHCRJsQqBF7PBcjQfsD9XYi6WE/EgyyM=,tag:OsFSAlA0FzFCNl/Kyvn2KQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4aHI1T0dPeko2Qlo1Wk4y
        SW5BUk1sWGVxNnlQMWh5OHh6eC80STczTWkwCnF1WlFVejJ0MkZ3TUZOZW1FSysw
        NW9CTmdsSTFyck9QMSsxVDkyUG5LeUEKLS0tIGdUWHJPaEJrVXZWV0VFM3JoYmpO
        LzVBNU1naGpoVFpjWjN0MTA1TEU1RncKI8WNA13xIwK5KA2f/BUuqFnjowg4TWS6
        VBA9p+vVbmu0xezb/k67exnp803oIT+jHwgXGSWNgUvJLehRU2d1Qg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-29T07:29:37Z"
  mac: ENC[AES256_GCM,data:nY5X5sHLEPI3O774K6asYg8IK4dP6UpEwwm4ETCE3Utx05a1WH1n84wzvkviYXL73btwTshXIRRxLivyeXSHCNPlwnSTp9P9VB0HVw6tnz25/UCFICtM48RjzJt/wNr0HkDEs5aUgAstGmZEi1qFORoH+8z4GKVhv9WoW2PZFEI=,iv:kl5bhSdFZO7mvznqX4XJ5Tsko5W7fEQBzwFYQoWpsgU=,tag:2tyZKoZnM5GNYPJvHJ1o7w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
