apiVersion: v1
kind: Secret
metadata:
  name: forgejo-data-r2-restic-secret
  namespace: forgejo
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:ax3yJaimYPlTmnqEGopQ3yCtX8K37uHmtmWbWvQuqDPLz1LSRXUw4ENP6jHjkvHnV6k9oww/LYg6YA7dL/rGZWsDT+HWA2tp3zRs6q7rKbraruPFs+ZFd2Y0251AUxwZDKh+ng==,iv:SwN2DHf0pHmhTbcZ74JaVmVXZaMZznZasLX6bQpGj3Q=,tag:WtRe1xZu2jJS+H5U7XyhMQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:TwRVXY9HXAm5P1ogpLScmZ/OwSdtJjTRZW4dAKgCFuvNQ4HIiabJI38uKps=,iv:t9OGxdy90LdPirKrklfafVcJ4cQmCjKrM4HCLPDdgJk=,tag:GakiqmqQkL4dpO5UaGB1KQ==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:udW4zCX+va4wMdlRHB6aXaaB6JtSgWB7lnvpe+N0BMI=,iv:28Hxia32Pk9bPi85kIwmukKpFFB7Rm3o1jAL8dhjV6s=,tag:gMC63A1XzHw91M3FvJ1+KQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:XNGleSH6MrCjhPumW3zSesCK09Ijbuq64pR1ZRCjrv/b+fId1g1i1yirM9uxtpgHPHi8gg73tthaAtlcpUFx5g==,iv:6wUTGAL/jJnTMvkipPfAuIBsQLGLjKh/uPBiQzU/1JM=,tag:s7qXfAYDaxh6V7fWKL2TfA==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:aLHiOw==,iv:uIWGnIEYKHYWqN3hdG17RlAv/06iUJ4rgW2XcutDyfE=,tag:DH0fNDA2CWLAKL33mkIOSw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMy9LNjBESTRzUnQ4TzJD
        eE9TTFcwTzVXZkRwZUFnNHNnajJWU0ZPUjNNCnViS1VZTTZIbjlNVWFsQ0JBdkxr
        TTBSd09QNllTRUVhM0RKR25rKzhYYlUKLS0tIENoc0syektlU3RsaXNIa2N4dTkr
        UzhMUTd4TDVrSUhOVWpPWDRMRWFiRjAKSC9UHa/TBUesqbfYmNwrYpX97FYfWYs4
        JUPD7Dm50EtXtukKBBxxRQKHnLkOvi/IsQmtFLuaCwNSW9Ss7BEtnQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-04T10:28:13Z"
  mac: ENC[AES256_GCM,data:zkXP8yjfKznqhOV0Wyx2i4tehWa8iOKZJ30EyrydMz7MXWRMrO8RcAM8JLf9/6sFgM+F/naua94pvGwAzFkAZjtwSd2MTbQPzG8BwS5Ex7iOZ/WqWbweq6pEPK7le1xK/dSY+OM/eFlEeLuoFLk+omyO+LHQb6WVwZA1Yyu9V3w=,iv:5VzkalZ13M51e0fN+CafpCeItbhuXfPqTToRLY8qHL8=,tag:NMXgNs/aTy4h219GMUZDEA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
