apiVersion: v1
kind: Secret
metadata:
  name: forgejo-data-restic-secret
  namespace: forgejo
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:thHbWJn29M60NO2i124bUTvWDGhYb0wVc/e9LyXzan0+ErIAf+BWugGQ7WJy5OATsKd9FqhUSfqifr5lz67DSjxhMIjZDesDJCOaC3PwXSnjD0bcoA==,iv:l+JKuiqtyqSfTeWPNtlxphXGH9/MC1FHfT2nk5USKMc=,tag:9GaJ0IO8DBw1zBeRGRkTTg==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:/gQoA2HV5oiOphW11db+CgidoiuwiduR2SO1eYq0FaVNE2Uxf5p7BOZRTuk=,iv:jJbxuAAqXKm5UA3wBpiwZpLMWjQMIMuv/0VaurttXzY=,tag:A9Ctk5Mhxh7bkM4stScPew==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:VBX2SyaaM/x3KMpRVpVqrCZ2GaiFa5sL,iv:Tyd+OlRU9EfkOe8QpkkkI5R0DQ7ga7MjE3pHK8hiaHk=,tag:82qa4diWYd4b5ydJEkXFYA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ygnyadUIeq7o32Q3mOHErqwya6tzsVGzue5t9nOuxXouHRpIFYuMhCjKrydzSC+p4xRwjrNA8UHONqLwe3QzVQ==,iv:GEwCCl4uymWaemUy8XpI64aOubvi4vNnszQrp37IqkY=,tag:NC63yhtYUrVPlzh+3+X7zQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBScVJld3pZRFBjR2Y5N3RK
        Vjh0RVpVVXZkUnBuQnBMVUF4cG9xb3BQUlV3CkVEY1RlSnJ5RlU5UFR2Y2Zrb1U5
        WjRJM3R1VWtXQUdGcENSNW5CMlN6QW8KLS0tIFM1WHRWQjdxOTgzNzBiRnJnYjN3
        K1MwUlJWN2wvenNVVHRTUUhpeW1FalEKe52GFBeyt6LzRFcuqVFPHtrJlYE0xv9/
        fXkyjksW+dzlTKvDQvH50XLuR2JJ1DAzcwJPDcGGE/g7i1WJD58NcA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-17T11:12:09Z"
  mac: ENC[AES256_GCM,data:fmLh7QrIaMwTNLPgr477jmyvAHolIqxfvQ0qgEgcuhLgmSuHy8AiTQ3C9+zyAFqoNfBAK6V/hp8hnh4Iqh7RAAPj4cZmQirXD8Ej5Z27FBlsnK1jWIsW/yUSOERrm27QZwNO5/lPRfRnd5ssmqnn+8vD/7bx0EplUXZBbl7aErM=,iv:T50WDAGxBqhOLvrzWq8/IVJsYKGtfk9U5rLpyeUMcwU=,tag:Mipid5YMOjgGWOCGdi4pKQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
