apiVersion: v1
kind: Secret
metadata:
  name: grimmory-mariadb-secret
  namespace: entertainment
type: Opaque
stringData:
  mariadb-root-password: ENC[AES256_GCM,data:zkynge4+tSvjH0bDQoUa7NdNJkQ=,iv:5BiP6uh3gblBFN/Z48ZbsPn7uffp4dRMd82yG4rq3Kk=,tag:XDqvhyf1LqXbj/CRM4RCQQ==,type:str]
  mariadb-password: ENC[AES256_GCM,data:JZmkCDjauUg0mRmi8zlRtXS8yWM=,iv:I6+untleIxI5rUoSTLy/j1BVNATM0uLegGcsRKPVLgE=,tag:ngoyO9KXKDl1Y1RXxK4Bhw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TTBSS1AxNHJoVGhTTGJs
        Tldwb3RtVGZHdCtYQURNSVliL0Vhcm45TFM4CjlCZnV2c1NxbEpUemYyTStrMG1k
        RWpCRnlncFFWRHExcXY2bGthR3Bubm8KLS0tIDEwLytReEpzQk1DaElGc2pVKzNE
        cDhvenFMMWlybTNEWGZacXNjWkJkT3MKTglZgH2oX6NdgxgahhSpvxQ9yXHL4+sU
        qS4dKj6tc0LDO2K3P8l3xrdR9f28YVfJQ4nJt0n+hFlDCM9O4iYc3Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-20T09:29:21Z"
  mac: ENC[AES256_GCM,data:Dy7xP/M+H2X9JkVVgs4FbLlheA5ZMiyB0ERksho/3onof+RWAQfARaWzdBhEHJRBPVR5/qkz5ZJ7VHBUipAgno1PamxlyILv/HfAHRW3nvm+Oi9QC+PGn7lxpH3KFoP4mqChaTPxEEsmDvIh+DlKB7LknLZbeZ7s7r6PU+ZwhZQ=,iv:7iaDPwlSw9WrbQgZlL+M74dn0gwPTNV27YJpMEDgkp8=,tag:B129MXbyS3Sj+52PGlzgLA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
