apiVersion: v1
kind: Secret
metadata:
  name: grimmory-mariadb-secret
  namespace: entertainment
type: Opaque
stringData:
  mariadb-root-password: ENC[AES256_GCM,data:epDljXFHJgvyLMc1HU/RQtf5ar4=,iv:3too3zKy219NW8Xv2pe/mNFnYMFdkISohKiD3Wwdc00=,tag:f/X2RmbTEmLzWg25j1VX8g==,type:str]
  mariadb-password: ENC[AES256_GCM,data:H9hHvVIBwBxVeNHqFN2qLzWnz5o=,iv:f7yjjJdNj4t6cwEBcCKJnABbH1AhzFCNbtUc/SdeaqY=,tag:d4JK6QFb5hl8J2BKgmx0WA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsd3djM045SnVBRzZhWTZL
        MEtENzQvOTB1c1R5N3d1Tkt0VG50RHFLRDBvCm9FS3pPZWZvWExROWdsaitKRGFk
        cE0ya2QzV3JtMDB3MnY4WC94OTlZU2cKLS0tIHZxZmJ3VncxVUR2T0d1S1JvcUUr
        bHdwYXRTRHFrSXQvUU1hUDdhODR3TUEKYlzykKJktL6uWelUeLjLBPCG3hy5y5YP
        lavnIgX/+SGSJLce8XV14fzzO6Y9LNTo57FLuVyT+WIjdS4Tl3oyNw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-24T17:01:21Z"
  mac: ENC[AES256_GCM,data:ePreUe76Lw4i1CMyt6IY9Pwbb5WfuWP+b1hQqpFMbQMUuXeuX5VTFO30dY+L41ux01/n3eaFbhCFfQiSilStdkf+R+PMcwHpVXiRJYJboZBen1i+uPcxzlmkDgmQfY/FigPGa7Rj4/VqiLVwdG5qDzV3SYYIJpOR8RW1db9n32w=,iv:y+U8ux/T/DzpxQ1ccaEv/ym9XWXU5BrOsgdK19os3Xs=,tag:djrCrh3sKZoeP2HFmE3zxQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
