apiVersion: v1
kind: Secret
metadata:
  name: grimmory-mariadb-secret
  namespace: entertainment
type: Opaque
stringData:
  mariadb-root-password: ENC[AES256_GCM,data:XsO3c8oPzagg6BZ0S70DZIn4xAk=,iv:DntnYQnQHLtMilvZXZsrzdq9zG6LmQI8yfpV4PKujgA=,tag:HfN5YzfSohKvzo2fl2tfMg==,type:str]
  mariadb-password: ENC[AES256_GCM,data:M0kQpDbm5EJ2mL3ozJHsi/CfuTE=,iv:xISsViI8zU8WRGd/Xh7HisJDeh4SuMWEmgVroI2Y31w=,tag:JkkdMs65+4glIpxn16c0bA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSlNpY0lteUlzZlpMdE1F
        Q2llczdFOHNjZUFKYUlZR0tYWThsWDRJbEJRCnlIanlmbGpZQzIvRHJBU09GMEcr
        eUVzSmNRdWVidDQwS2RHcUNHaDlVQW8KLS0tIGZJS3d5UzR1TnIvNi8rL3BFWUMw
        SHFPMWlYLzFWdVdGVWlkc2hrNkJvMGcKVlGFgn5GQq9w5GV2TRvvF7/08oN0Siob
        NTnmYkG10kNCSzN3aBhML62pgdYxbe+TqKjnN3L6Gu+wBr0aIC8SYg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-04T13:21:48Z"
  mac: ENC[AES256_GCM,data:Ph2ERg89AvAriEQXKUODUFxhefRVb/Fg2N8kOd5+DRXoXSNTHv/mjax+WLdyn983fPu5m0XGesFEb4FCs7AT9oORCGCDF6ZRQ2pyBtuI5c56gVCMhUMMyY9WEPiL/NVhXO4dlTcK0qomcIT2z9hzaY/1qKiZ2k+IVAAAmEim/Ks=,iv:cI0fdMnqIfAvnFdmNUmSBEDPVGqAg4fn3738Bj5KMzw=,tag:SE6eucclg3McJAdOBrw3aQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
