---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: snapshot-controller
spec:
  interval: 1h
  url: oci://registry-1.docker.io/bitnamicharts/snapshot-controller
  ref:
    tag: "5.0.1"
