apiVersion: v1
kind: Secret
metadata:
  name: prowlarr-config-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:JsOdRf+jPcHfdCP+jsigjttliPinzaymD4EQatViBcuQrNO+3bU8HOXfeCjPP7MsMRTfrrN1XNqVP2ROaDvMso7cIeZMAJPNIXCKzhFYcJ2+uVBHN0/dow==,iv:Dnl4juRCUDaoZS0cofd7SLjd/3490q/XJO+WXa7csbE=,tag:8Wf4sv8KgpppdDKqnd2Gyg==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:I8qN0zQMKyPwYhcIKmpox+l0Dvtxzxo+ywKjYxNXb2HGHIb0yTN5HYHjlZY=,iv:MeMMKNqsEnJry2i1T8oczAEIsZTV/166lyKDOiDPqNc=,tag:p11o108gDkOSoRr6fxwBLA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:j2m2F+Gj8NCHOElICFnsU+KUuQbltWiJ,iv:J+8At0Y7W41fCI+H1nsc5g6xysRFrV7e5q7Zqme0Ufk=,tag:zTyHvK7Y6YqcXkFqxzlPBg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:kByZA6bwtn8phuy3XpBsmP10c5bjMtXfh54Yk5I6CrGmUxRPtNgVVjk2t0aje4UgD1BUNfWpFMJvKzVUZBx2WQ==,iv:zQHwpnkeCc5thorywVGcGz3LGLLCZ2/xOoSTunBhn+U=,tag:AzIbgMx6E1pY9/C/3H8bKw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZDQ3MGZNRGJxaUE3b29w
        K0tYSUJZdEdvL1dNaStwMUlLRTBsN1RxQWxrClI4MzdFcVNHa0EwN1MwY3VqdXpW
        L0Nnc3RjOERKS1Y2UThsbjBrYTlKT3MKLS0tIGdzRWNuTXEyZFJPck5mQjZUN1E5
        blNOcThNY0xXeTc5ZjJ4amZ1eE1tVG8KjzgFF/DbnjhFePJLSvDbdnz/M8mleDaD
        opmh1Ahqxi1V2q6l/oDT+0YJtc520E+O0Xa9KsxRnC/BYImA/U0faA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-10T12:03:32Z"
  mac: ENC[AES256_GCM,data:xi9NtG3XAApV+LvuS089lk4Npoi6SOnxIlRUI+fjdiu+FhfDht5RX68UsBEHwZRxGVoqbuQjSjz0pSt9noAHFG9tWtTEKtZcS298x/CwtuLYZyX++2zzPsF02mhuTbZp8Kw3RhU6m1yvhh1IPZyBH3wn6Sxa6G4+nAP6B06L/+4=,iv:ysM+5jnTMQPsqXyEbptwMqIcTevtjU8SXhIz9/pcork=,tag:3NrP6bWRVxcC5LbuN1glZw==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
