apiVersion: v1
kind: Secret
metadata:
  name: prowlarr-config-r2-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:gp9eCBfeA1i1gbqX1QwLp9i5w9Ahm2v0WIkkealoZOUCdNAucPqtnGFI67/iK0ffjph/+o4Cje77u/7SBEuhaPA8VwZhw/ctp59EFHvIdJKqYLEQY4niylzacXIWpOvdwtxZ1adbSg==,iv:sdUH7GlYW8ZedQp2g27zEWrQ7RQIBfinAlkqyJ7JXq4=,tag:KxP0ZMLIlwAPKhbCyyFJSg==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:1+5fj3YeFygmhipfKgrXkwIuecACBox+PclmUCU4+1Y4lhNxGpWHJM11WlQ=,iv:NjkRaooYThltTZGWIn1x0qikywIHm5d+/ns2fmsv6V0=,tag:ZHhMhbrmhdCj358cyvRYXg==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:cI4bC8MqvRld6WdfAvViGv7TQy/L5qSX/Ka5oYqwsHo=,iv:vqY2+THmwSlScZvJ3sQCAMxHj/znvcLKoNxKQEd+QJQ=,tag:ltERSzun7rHmBcGCyJ6LPw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:rhecdxirwHhBISWxrQecPXBe3iJwTEgrDEqSrT10Ke5UKLCpXoDJ3aOOUBTwzhS73IIFi1AIrhpiqyBwh9opYQ==,iv:zU4+cyek41boK41vJLcYF/nF0zpgfZBdRTl7izr94Zw=,tag:BzIZbboSVVq7KbYnUMNhIg==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:DS1Eyw==,iv:eO7x40pYbfoD4DP5PrxsaYi+qva59qB1Phlw7RcjwKk=,tag:7OO9MQ0uXLAK67CUpQj5aQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrU3Bna2l0WkdrRW9kUktE
        cTVSNlBTbmpXMERiY1JSMXAxeU5OZERhcXhZCmZmWGRQeW1ZK2diQkpLRUZCNDA0
        WGY5eDNkbGsybXBTeWJYWEdwTGUwUFEKLS0tIGRUWWUrZmxac0hmaGxycHpld1Q1
        MjJvSm56bGRhU095ZC9FL2taMktRak0K9Q113+EAr5ngyjspso5RiC/fTqGRuUES
        1gUH/wU5fs3pqhOSKEc9PZinNoTxQXjOIuFWn40cIhfSUZ26Z1NgiQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-27T09:59:42Z"
  mac: ENC[AES256_GCM,data:ExNF2TGV+VbpX8uFvV1AKsEPXqL8ELXb40errCshiYCHhK3OBqt3ndWkGtCQeduzlCxS14aafcGRUJzmCwBCWTq1h4rNJbMc5n72LaIciNl9MGW677hROVG74FkEElYWGY3N83sSVuxPkWGBk8FAoGl1Q6FbFA5WvmXdekEgv0E=,iv:TpG7aibTsPU0Pb736hzaASMnly/SrsshUB0B0yZdP50=,tag:WwNWSdYlpGQgZuqTtDFJ8w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
