apiVersion: v1
kind: Secret
metadata:
  name: prowlarr-config-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:qfIuqp2TcMg10/3hgDWBRTD1srEAlUResif6gNooNTU7K41Kc9/6/rgqJK3V0pQeMv87AOY8LuYbt0Zzxjh0VVXc06BOMZnS0WSeWgHl/552cbUtwdYNKw==,iv:K9QNs9CSXfbRA6Hb2T5z1C3JrDcou0MGkbpabnXARjs=,tag:VwHGZ2YxgUY9ymToROs6PA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:OvOy99KwGso0lWbBMPBxC3ao5tO8SJE/Rp/ZIfA2cMsZYAaYmunbEhEX2kc=,iv:wOhmV7lRDtKIDozaNVa3M6xKLqfXwCi0pTnhnBrCWOU=,tag:dyZu5QoazL+axLCyF79cUQ==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:2wB0wXu08egocpbnRLt8i3miJhHRpTJe,iv:1WWrvc0hotybkRa4CuKmUf9fcNM6paKl3wqeMzdgyLk=,tag:LzAKt7NCclkaYhq2gjhNTA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:xq25Ye2G6ykLUAuQdLInhMDjcFQRFKBOlltvtvyXnCE0Cr56Eau8/SDPaoXdjCiCZuZt/P+eOM7Zc5YCpxgSmA==,iv:gulLj14jmfvvdV/4GuhB/k44GHHGsNHX08LUXcIPm3o=,tag:oA76kdjeP6AciNbOc99MNQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQ0RKSjNoQ2k2My9QSXhY
        cXlQd2o1TGR0SFljYVkreVFtN0swWEFwVkZRCmJzU2xQaWJhZElIY3NDQ0YranNx
        OWxjSDJ4OFE3TGp1ek1PdE5mVG53c2sKLS0tIHhOWW8wbXhWdm51Qkp1VEJQbWlp
        V0pRSW04eWJCem12OWVobit0d1NZcW8KtrucRq9QQ7+ufY20CBKOnHFXvyJZprGZ
        fr+Rp8RzgFThhJdYqS9QsPlB+eUthrrJuZ75XtOCzcp/W8B3Yie5gQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-10T09:57:13Z"
  mac: ENC[AES256_GCM,data:6f7IiuK8SyiM6BtntY41unM9CPNX64ns1HWu2p3KOuJ1GJevKZ3ZCQ9OkwwWMP6FNQw71N3sXC04tMvOjwjKV89bntKPVymL127WeVdioJlJ7E28lNiuTURfaocRGcgJhzk24rjRr9zBQyTHp+3JEC5YIgXEPSo38zRjtLPQBGA=,iv:rIPv7McO9fFlv4NHtgRVHulKlBiLfLdUZANp5RHId0M=,tag:J2tZhS6D//w8Dpabfc/6AA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
