apiVersion: v1
kind: Secret
metadata:
  name: prowlarr-config-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:LyH7Gcmbm+XT26ZWACUdP2zBmp5RQ5YlpCglor1H5xpGFD6iVabdjluML2QgL4SADLJdWuAjhytVXJ0jKo1DIeqPcYAZkxDdaCE+aQdkAKNWNtFZCo3heQ==,iv:afWES+5l3/5BKCRDMEdOdMTPES144w/yNzloClB9k08=,tag:hqaCm6x2prnMJ8nAIAtJPg==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:Axyr5Q7QYlRflzJ6QG9hwP5RWlgcko01y9m9BOcRJhJNQ0qyuebGmvZCPyM=,iv:Wi/zcki82zoH318UKALWA42bXkNFwEA+8jEYIpW+AV4=,tag:YHNESdZCfsLjypGkT2LD+w==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:vq6HqYbs2OJO72mIbLRs5WlVcQxQu0Ok,iv:iIUIXoWeBq3dN6iqmT4+X1x6FuxikrKrabEY7SEUavk=,tag:T8J4FfWaVlwcRFl7HnABGA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:14/VB5cP9njGB8ac0n9ETEDgG/YNgp31OQtfXm2mMMsCbqylqHLwph0FZY++BMp5NXOeT8eSpMiwcpy8fawq9g==,iv:xEuvgelIYpxHaDp/FdckEGRGusoJY8QmtQnxznrJYUg=,tag:RF34T0H/kNw0poYei/ZBZA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBidkduT3NuWXJ4bmFoMzJi
        aWRDWWxYQU9qR3BYcmNZYVlSb0FlK1B6VTNrCkRWSFZTK2dZV0V6eGxJMkIrbTJM
        NGtDVDFyQW5yUWJ4OU55RVFKRndWY2cKLS0tIHJ6aGRRY0xDendoZzlvOSt5a2Nq
        TVg2YlZYcjZRL0JUQUo5UHQvRHdHQU0K/fUKpG5XiQ4hFxfR3q2A81XSsiSO6kHh
        cBLSoNpPWWENDABqq7rCNeAzLunr6tgnK1gX70MgypLKU+o2hP+OFg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-24T15:38:32Z"
  mac: ENC[AES256_GCM,data:Qo09qNr3r9dJx/+pGqAmBti/dWp1xQ6CPYNvn48yAti0nYh8uh+r4CYwPIVX/pFNal6pTu9MfaYgjeRCWlVfIOlUt3XMAs+Uy1C3Yl9RgWjTWXbxnERrk80ej74KxfgQnCDTOSoOYHI3CNDsPSPZfqkNS/lZYxsiRrUoAxMFAHo=,iv:RgvxIWb9/MAR9Nq1PWXI0whDbAF0Y4vtwSBOzE8R/2E=,tag:C2+KJPhLGi93bj9w0MdQTQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
