apiVersion: v1
kind: Secret
metadata:
  name: prowlarr-config-r2-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:XHGndnfTgCLdj26J+aQm8/1DB7x+PZ068b3Jyl1jgkArTpjscwuter0VHbNTvJAjv62KFpLo87nz4uGO5Hoaaxzet4I3dsw2EcTFf78ORm+TrXQ1mUfzR1v7yfpiSeeGusTK2tAjmw==,iv:BL5UDg8EviTqAekZQOdA32tLMGaFAmcneh+Ui+63Q8Y=,tag:WGbsOfhUqYj3Y3tbac/m1A==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:DRouXz/kiGJ/Ct7kbfk+hlgLxPOAI1HK80dAX3ACuJCTh/3y/b8OoWLV4No=,iv:oGJWWpmdpVvpxZ7gKRPLXhXua9IGsciHv8Xrr0C2Lng=,tag:d5WEfLGNAEMEkXYtdjv3DQ==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:4MVr/j4GtimFQ/zZ8GYBWoazplfimVu1/fdk0ekOwuc=,iv:QPidepSLhJVBzqE5aY6bmml9gHaY4ZCrBrZgIUhRYfs=,tag:r1WdNYL3z92E8//UgXTjfA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:NE00QsBAWsfV28swsH7ODucN4ZZ0HvgSJRBbmyHo+wam+f5qivqrhW/oPeC6A4vbt8ZXfiMSEYI+A49HWguwRQ==,iv:jFh1s+v+brn0P8DcUh9Uf5dH+HjRkKoKOeiW4Yz9vQM=,tag:x5rHqoxA3RbvrJbyj85PUA==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:TUBazQ==,iv:gwzNDVBJL/dwMQELb84J0c+qwRKZrAxcy6PKC+PGkRc=,tag:slSSV391kqV9cYj/Ls0LEA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkYXN2cFlzSXo1L2x2SXpv
        VlJHRnBjd0hiYnRPdTlNNVRoTURTNC91VzM4ClFnNlJka1VxcWt2cTZUeitDSVN6
        SXdpbnMyd2ZIZXhoNjVockpWbGtxMkUKLS0tIFROOE43T29uckl1VlRXKzgwSm5r
        TkhTeVoraDNHUDEzNlRoaXhEclhDVlkKxOhOxuSOOoJhiLw7Q+9DuCleFITpxCxW
        NZ/suBDabW/ghABUn4Aux/dtK/8r7tNdN9X2+1WfPkb1SKfkQFKU9A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-04T10:21:25Z"
  mac: ENC[AES256_GCM,data:S4Hl+j4EGURZfIDvaWh+yZNEY9FO6wbUlzT9Cbc+gbzfhRTqN+YItH/NPpVIcoyxlSaNki1CG6T6OaTbTkQV2HRQn8KLtw110fHOb90VRUUjln31KikiI8Ly4+hCGlrcqZc+hX1W6Ep7MTgjYN6wDDEJs3UBzgScMSffeizyngg=,iv:uflxGatvwQsAQ8KyrSGLU6IPkSAYhR6C5umVol2Vrgw=,tag:n77/g9gDq/MsmiuyIu8ONA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
