apiVersion: v1
kind: Secret
metadata:
  name: prowlarr-config-r2-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:Yu5fJP66JzH4IcwoSHaRyXY8/MS80AdfiJfGP0yYP4F47WniYpQXPmVo7TIxaoe9qXxDXpJzsF/8uVeYzTnlqqAf4w32PEbELRQ9IZCK25+FRYgwl5aWyVQaC8F/Dn94GBOTHKq/KQ==,iv:jDjWFdmkTWxXKI2E0OwGHA62XlpIbjw6L5ChJQT9mlI=,tag:H5UQJowtI84+akIyH+3liA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:HUu+/PcihZEPwVPiSRwplVgih19tuQf/kuOIDZnBYpQeE1XcjN739sykxhM=,iv:7p+IwzZZpfNOjziW32pdqaecPMB5QPEi4hKtoYX3Vl0=,tag:KwnIuqV0dK+hziWIhvsrkw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:/XBrr9q41N3vFbXnUzok6wSQFJiKDSIhX/yTfmsSb7c=,iv:P/NBQL23UFG1WHM0L6z6coUBBwRtEv4FqSkOBMfa1cY=,tag:Q1Chp8tjHmlJXnKxf4oG7g==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:wPly76pUsIywYT2TNHesw9Y6QnhJw4K6haQ548SKiKHYK3yC4tkk0Hbk57Gx4KImNP0Z/hKDlgy1CMYCDQtmLQ==,iv:8mCPeYhUGBX+e+GJtv9sK+rhwlQnjbo/vyoyioYGssg=,tag:wFiF955inRd/dBvk9DEZDg==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:YR+RdA==,iv:TNyTlBP9xv2gsSZOHvPnfrNgwsuWCmp+4MBBmTAvB3k=,tag:113jyZ2WIAPmuep/5EgBTw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVnErbzgzUWpUTXg2OTJF
        S1o3VHF0SnRKVkNlV0laaVVqY09SdEYzYjJzCjNudHhkNXJSUVUzL2x6bVkwMGsx
        Uy9ycjBjU2NaV21ZS242Y0hKVHd3UzQKLS0tIFM3U0gvQTd3VWhyZDZCb3I4VXlq
        SVhkQ2VhYm5rY2tOcGhFODlDK0lETGMKKLAWackDpk5TfqqMCHvSEdelU7N4tGis
        08DvngPX42AQzeranEXVzOeJxo0+Oc85YaE5brZw1tDonCBO7fF4lA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-27T11:54:15Z"
  mac: ENC[AES256_GCM,data:Rs9ESkV43eYj7EmO+eMJvds2mqVhOfpmEBqUpMone0BGSR/p29XWfbBMMbpa1ezhK8y0EvN6CbbpBo7U63NWmcbDHg/eVi/tmi9t75UB4kQH7PS1X0+xzyTk+au+w7/lHl+DE1GvBsYmekYGfC+KbYPC1OKPxvFY6Cefw3hjTj4=,iv:xTxGrHvyHAtAMqtqX6MsXW1AeMeKFniG2v8UjwV+YJ8=,tag:meA4+Cw5lJ83J2d9+uxY/Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
