apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:5jXCvwTrIdIO8PJbQUA0EXB8teebaIhVI9+kwUKyKXr6Me2ZccFzEAwhuY9zASSy75g00Zo=,iv:1t6L32TqZAsel21TppuAfDIkEbhsSRajENX96qqn+iU=,tag:za3qQ2R8N3sq2serCx7rIg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVW1jNTZ4OEE0d21DTG1i
        dW1lTjdtOXJ3MzNqazFoRnIrSmRDWjlDV20wCmdwcm1zZDB3UkdSaFJHaDhBTmRw
        Y3BBZkdBZ3pLeG5sVG9QNngxTEFhZEEKLS0tIEMvZnJ0VXZ6RFBrODlkZ1VId3Ar
        aFN4azJqSWs1UyttM09Ub3pUR1d0c1kKhfsziz9p6BSy2oBE5U6L3OU6F9xnjM0B
        yrteNzu8lUw8zgryA5hfKaCT+TyRFBj42oriF3wY22EwlyHCu5soXA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-04T10:07:15Z"
  mac: ENC[AES256_GCM,data:UXcdyJ/7fSVSs/8iI6C4xO6GEPKjLZuH9dxnGylHC9IB7WZTc9SypCPTtmj21YcJAOSb6yQMnHVxNIYlezdnMiyCBUgAECsIEeUT9nrT2/LxW7ZMrSK7oIy97JoQakqiJWARQ8xpuiYJmRqxutaS01UKoxijmTSIkPyOxh5NTwE=,iv:uCsOrAorl7vEMtYzHwAM5I2rQP1jJTCZ2PlVdsLWRBI=,tag:lyD2AixeI5jqqbCqKyFpRA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
