apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:0g53GvT/NL+GXP/enKpl3ub3ErvDu25gRvmViM6txfMF3fnpf4WbwACDK5ZlIwqP+y3FHPU=,iv:A60KPhASrGBCERLoibMS9x4LDqqP3akUQkjA6t06PNI=,tag:JkjFrr34+g6g4Db5TQS/YQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZOE9SU2luc2k1WWg3S3lW
        QnhOM1o0NTlmeUZOK0M1K05GQUs1enczTDFvCm9qdXV3aFRkOGhuaEZkM0FRT1kx
        cjFBYU5pampMd3BXK2g0VkdvSXpZMTgKLS0tIFAxTmluQ3loSlZuY0xLS2Y1UzRE
        UlBuZHNiN3lML1N2TTkrZDB0K3BkYUUKJxpltt25Vvh5RN+6RTDDloNPdSbTsXU0
        muES1wHYUBCTMo968BDOKeucQvx/kH15o4GYNDcG9taRdJx1ZCBiNQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-25T09:27:31Z"
  mac: ENC[AES256_GCM,data:wmGfh3VTTq8KIyFuu6ZgYU6LVbIKwaYJ+XDMVAzTxFo7AWrKK0aNq8ieglQFgT+IPNnO0iVfvE64JYBrXYW4xlTV5+tDmN7ifUpn/q8rkSp+nRgmL2Q1xa6gA32+KTUfWs6UgtWBiEtz1v4JGAwKho6lItrn2H3YRRzNYXtHtEw=,iv:sPKBEnsJPUc/gouA9eNbe0cl6+v+1vBGpTzi8GqNlI0=,tag:kIhd/v7uilmwxRNBlRPdSg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
