apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:hyz00ApYi33Ie9ugUHdsldfSy9d4jGhjqsL4LD2iNCIJNEFJxUYHvUwCVpwNEsm7oRhaQ6c=,iv:EtlNi1QcbAYHodkUp/iHAgRCGpmbV7XOt0nthHnxMz8=,tag:Zos8GLfUJJHUF/OYKhXVfw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHc2V5bzZqQXdoS2k0Zm11
        VXZtTm1TcHNROGl6WHhFc3hVbE5TK0hSUTI0CjRYcWFhbTloZTg3ZUZYUkd2aEt1
        RjFQNjdKTjNSSjJnMGx1UVQyTDFzK3MKLS0tIFQyU0R5U2ptWVRTS1hVbU84UjNV
        SlR3eUQ0SUViblk0dW1rZ0g4L2U0c1kKkp07pvSzYLBevv3Meipxs9NAJHamXfgs
        eu3MbSWBgch8gxmowIHFIy2e1C021t6Yu+sHFIMcKVDn0hzZ2OtYgA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-25T11:25:50Z"
  mac: ENC[AES256_GCM,data:f1N4cfv4PmNNzY3vOIZcHItqJNMqu5zOp5i4+KXdcVa/kVPhAVOWAATX4UpqzDWcNd/uUCsFX8d1jW+7DkKnpd2mQX3id93FUozeslIsY5ALVZKELjN5D2qE5iKri1FIjYBDIc1e74PPbFHYH06U9aiMlBZhLQ7FrKLnTtdQBAE=,iv:MDEbSAk9QOLcmtvGReoWGdfcwgFo1PyGWD//QfU/SL4=,tag:LK9VPJRHWjLwHPzhdeiI0w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
