apiVersion: v1
kind: Secret
metadata:
  name: watchstate-config-r2-restic-secret
  namespace: entertainment
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:4UDbiBc6hMTRspyLJkoHrZsObzJtDgE/sTE6nY2cOQ0bX0yOk1bXukCRCnTWoQu6RovOOSRt0LfNiYx2QXQ/2VG9mx1AkqeU4FAH9az05Cd/cS1albKMqvMscbW10GmWrDN9lguyToBL,iv:tac+XXfBuNAzG2R9rhmifdPCiKkh9dJrYgbn0lrzXYc=,tag:HnjX+hFtqN+QNx76XWkfXA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:4fZF3LqacKOg1RMJBNloeZIZl24nlMqpqwHwz1SEUOxMRLzbz+jRL8+gliY=,iv:CJdAAjGd+Dd49NI9NtGSBKrN9NldakOvvRn83OaYCUU=,tag:Y9c0xzem579r+EnI4st7mw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:nAQc0G2FgHmnXiFDmliezXzTbO01iNszOzAGrKSVJSk=,iv:I4b51QUDl3eBbw2qPZmq3v8RNx2C07EJfVdwtqO0tEY=,tag:zfpMCzGGjZHDxQW9M+uQ9Q==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:yMaUrR+vnXJ4ptIXXLV88GQNtinaNbrfLbt2/7mndu8WFgx2Vai5U+4u9fB39uM3NEIbvUjza0yf7iHpAx7Fnw==,iv:w5MV8gWHmuUtXfx3tEv/GFWOO6S0eZ3LRXTsHC8KK1o=,tag:litRIRtq5ct9ls8pZCS0uA==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:hdaHng==,iv:iMZ5p18LM1ghaeFUPv+FBlBmuXiJZQWJ8j59zq871BI=,tag:dMTsAp6VEoh9NyLjvEvYcg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4MU9vWEhuK24vSUltN015
        blZ4MlduTXEvRGN4NVhmVjEzMm5mMnkzOXpjCkl2QW04bW82YWFhRHhWZ0JWeXRv
        MTlCZGE2YjkxZ1JLTVd2U3JUdFV4bGcKLS0tIHFIc001SHRYVVcrNEdESHN2b0o2
        Wm42bDM0Sk5CQnVVL25HcHFaa2dLeUkKcEgTxe3fByT302mn7nsPcGEiBv1Vx8Ah
        GbhY6TwWFakDlXGshp6nP9epc5lxXOTSLNY7KNrI3hrxJ3bSzlunYw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-16T15:11:12Z"
  mac: ENC[AES256_GCM,data:YWglVwZ33C1WhB3OpVbFDCMG3DvanwNXxBZH1QmL5u6acdGz5JOnkxBjZ557L/GlKLxfJItbdirgdMjQLXRl4ZQQlHU5l2So4y6/dtqtQ34oPEmCSNRrOKbP+rnFL3u+M4UPrghKZZtweOcIzAiqcOlhUi6pMzAb6LiBzyS6wVI=,iv:kwBdEbeOQC5FcB7jXhVO3U3toc2Wg1TbjUBM1650LHo=,tag:13+MikoNGrfKrvNKOPSOHQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
