apiVersion: v1
kind: Secret
metadata:
  name: watchstate-config-r2-restic-secret
  namespace: entertainment
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:AbjGxkbI3lHNxIy4371G/skyTETsYPqDgfpZQxVmrWArlxd+z5GNoX5Xt8rHUTd9P4JcyBcn7275OCEPnRnLuV4weoHaabDNMZDX8Rq3lmfFWwloo65zKAjVCvgwjf8sV2KRDhKi2UqD,iv:F31q2tDlQ5ljOaPX23Ekj+Xt5sFzoSoWvmeqQCkGs3Q=,tag:SlmawXTfQkbdZ5ojqkg+bw==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:Avo1x8EHDLojx+gp+hCQ7Uw9ocy0vTXQ8P656VfTd+2WdjV8+R6NS6kvHe4=,iv:auTzoKE8Hl1kb9/ow2aaGel4QDl1alt78JbFTCp9VFo=,tag:ieR+si+i+kxm8Dx3Rezsqw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:s4O3PSY5c2hJ1Q+ub2h/4gmytyXLiYCXXKq6Mroh5WQ=,iv:6nVMbkCCdZn/HdwjjCf1Xz0Xb85MactIhmqP47ude+I=,tag:96HktYOPP5CViu4PjoKxFg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Lsvp6zdslTULivCSvVv9BZ5x1efEwYPHMcem0HkiABoXpGVKmAV2YbgOtboIGhmu8BcjMNQD63RElIUTWr7F7w==,iv:Hb6ED+GXj7GBgsUawkm5Q6kyKbg+GuJPT3FfOU0n6ak=,tag:USTHV9I6WhyNFQMths0Few==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:Nc+3Rw==,iv:wnA47y8MijSn2tQRTioM2xqIQ7LbjPq4HHnpi5fodZM=,tag:LxNfvXUG+aKjRd9NOJsUhw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMmNWeTFsTyttR3NjRVgw
        ZStmTEhlUFpJV295WmlqRnF2ZzhJZWlKM1RJCjE2Skpwb0srKzFoNEhZa29wTE9V
        emhFV2s3dWdYb003QUxUK3M1NzRXaHcKLS0tIHBVNG5aN2RUVStSTHBaUXFzRjNQ
        akF1eXlSRTdySElBV2g2YjFqOWxRajAKm3/42jfuYMuOa28hmXefJYyPKADpIQR5
        my1qzcUFJHn22EGcRGxASwgDR94Q2iNTDRSHOsOOexdhYn8UtGKKDA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-25T11:25:50Z"
  mac: ENC[AES256_GCM,data:zPRUtnv4KcOVbafYhp/NvRMs5zMPjhqQd0+7U+rhyVRY8mTikrsOqGCweCIhF3KWVQJz0PzZZTdBsIkFR1KUHmSx9Vb/h/+SbjfviOghMvkO2HLP13o/e0LqQhlLCsWl1XAd4Bb+sk+mtoFiCaBvuMyF4dr67TZ1irP1nYL0rM8=,iv:5IdyQsWMAxvN4d8AuZI2Qjhx49PABRC/ct9liEgpmr8=,tag:MrApEpQ8V5W1gri0daQ8QA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
