apiVersion: v1
kind: Secret
metadata:
  name: watchstate-config-r2-restic-secret
  namespace: entertainment
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:kYnouy1sHXFby9sptltTpcTgAzCEGDx/Mv+lrL0THFZvCTnL6QwTpGfQXqCETYt/IR1wYs2QQoPH5JjHfskatFpdSFCJE2Jngf2tJb8ketptrKmxKHhq6+2LpD9SsZe8CsLypMbht2Ym,iv:oN6oyrbqxB8Dbt7OQnQUOSyUx1CNTkqlldmdGQvaZcY=,tag:SjbU2Z2jzeTDAlNDWqAb7A==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:EdV1CPdPNkWA6abk5We4DBFPp5tMAb1sNOeKHUtkTKgdl6TrfvwIt4H1mVs=,iv:Jwioqkt9Z4LwwRT8gChVimL8Bjtc3Xi3Nhz7p27tIyw=,tag:wpVEatCaMhtmtMRD9n12ZA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:1SxFC9/VZb1B3kE0kUXIk11fVx2Exx2Fef2BQ/BM8lA=,iv:40wFr4hquyXSXg5rhwP4rg65sDdG7mlFwKUL+KpLJJ0=,tag:kIteev+LcnJoPzDexDAZQA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:C2/lRpqqIwtqr2E/S07YPlFXwODPmCixYjV3UyQP2QmksrgLrUnj2JPKhjG0Be+uf751SxFcmLzYvBHedfmMHw==,iv:xoT0z3Zy60Q+LItSBwIWTi0B1lJpqA63An1qbHzE3E0=,tag:nFyweE0Lv6ulvO8FcoDOdA==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:vgQcXQ==,iv:i3mmhPpfa2DGx8abWO4PJRMPeoyBMwPG6YT54TUHXp0=,tag:jVoC2LRRwewLtVg9wFGBqA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdG5sdXZmY3F3UTUzSW9l
        bGdPblFHVkYxdU5VSkowNUUzaDBlK2Vad0NJClQ2UVFlc3BDazk3MEx6eTNWb2lo
        TVFnR09BbWNvVEZPY0QvSDNxWENUYm8KLS0tICtMK3VjckxTSVRLQnhra0xHTkgr
        Rm1PaVh3azM1Z2lpSE10VVF0L3pPRmMKMH2YxO86EkakkFZLpbS+nQqPferyxIgM
        xCp97N6VZYFeMdi/Vgd9CB/TT8UFzEDL17KV3US+IU4dHjKffJCsXA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-25T08:33:48Z"
  mac: ENC[AES256_GCM,data:Wxnfd62SLbRUx2YceY8pMxx/bKNTzAWooLCvwivSFW9fUAvsqPbrd0WJW5z2Cv9N+2FxHekSwktP2hCIZqND9egadEQEdLDazJyKwhpVgCMwE9tww8TZ0w4fZp/YeDHSkZAqplYwNOV23CZj91+B/ziCoExlZqvPtu3fhuNn+O8=,iv:EpkYr5KNB7wNF2r+5u/bWq/UVPQ1QcuE1rfJIlOlgOY=,tag:2f6RKgHjrFx3fFHB7+PyrA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
