apiVersion: v1
kind: Secret
metadata:
  name: watchstate-config-restic-secret
  namespace: entertainment
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:JyPtlx0HiwWItYhdT2dcb2+yWbhlNQKLLX74mgnwoRafCc2eBX6yEfrAKNCWhG2ZHCH9+CXsW8WS/I8gdnB47EJlD/Be3h36U4iXnK3usNymKISsFDmXR9jZ,iv:bsWVKRH4DRIenQOEfN4yeTNz4tqz0UFhVglJ5wYWcUU=,tag:Q0HHlMGamJX6F77amvxUJQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:bTJ+vBPQYwo4yq7oDG9lw4enIBMGRSPzGWum9Y7DH9yvTUJvOm0uU76/n6Q=,iv:eOApp6TXy8xN5k/dwjQt0pB6t7CpLth3nnbbkkEkimo=,tag:H1Kv6FyLF06BRuUCaaeo7w==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:O5HEEjc/PuAqhyRfDamrtP3/WLT0e8yt,iv:Rg0jqKkVRyZcKRoaEJPBX0pbyGszoZEbHUr6EfPdQ2s=,tag:5vS/6S3pC7iTTDyLNmH3iw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:tmXYJTWhrSlHGVCNZJ6kzprbkyzRrgCWF7lss5z+riYEc5ax6ea8wkQVsz5wxqaC14wBUwDwbOlxktsJDr+9LQ==,iv:/SsshL9tWwwLpWriP13BCMI+8dNZ0vjasD6RdlCSLJM=,tag:RQVf80gDgJD+3ZQZTGR7AA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRU2wraThXeDlkZTEya2NJ
        eXZVc0JSeFFmYkg0RUFSNGRxVndnM1NFY3hzClA4NGtidFNuc1d3UnB1Z3pkaHRy
        eGgycVloUUdoa0NDb1VDYm5hZDZKVjQKLS0tIFhEZVc5Q29vU0hEVVNyNlNkcUVu
        S09VS1V1bmNZbUExWGtlTWN3NFVBYmsKcMMxqsbvK9vgDivAohwfA4XkpDRSTmYg
        4oFdQViUFyVRTbko4B5byxUwY5T2HP9Siq12238bsP0Y7dnNKBEXzg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-04T13:21:48Z"
  mac: ENC[AES256_GCM,data:7aoE+8gAH8nvj5RRkv8mSsm8Ey/UyhhbneFmH0cuwNwnwBpfs23ck+NpIp6AHXKEypU68/8zMWL0Uj2KBsdEYgvPt2rlcHI4zoco9OFiPW2vVV6fNa1Uk8Ce+GhfowLu/j4IYG3uUT7c9r6apTZrxPj+M0YLrLfWlJ33fGGWzE0=,iv:cj74Mizw/iZCMJ7+AsyGQj7EwUQ8n8KlYZIapT3FvIo=,tag:cjNBBVHjlzC08+0n0yGCwg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
