apiVersion: v1
kind: Secret
metadata:
  name: watchstate-config-restic-secret
  namespace: entertainment
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:x8l1m8j+Vrv9gwrk1kbnPvj+ulWfjoDkGKKgEKOUE2W5Mi71VfGtT0YOhoN3Cp2xlSSCZ5ySXkPumezyHe0W0ojI3TvpDO+OsByBmIOoq5n/z9l+XOOvBgus,iv:Rr3bMX1a2nCoJ185Au4DQdLuAOkxPRYIdrwIYlBlmEo=,tag:kZXHpXTId5UXv2ceKhiJdw==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:JP9+SBjLzoOWsU38JefdMV8zIVCmTnmJPbuRomtfuUYOt1eIxPF46RlLyWk=,iv:jkSZ0/k0eTaCJzKMuqaKYE7E4cqbEblIIefrRXQBG5g=,tag:OI5rVcpgfKfgKDVIJG4WwQ==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:cW2AzE9dAjoOhKi3oSXUTaKo/w1X7eyJ,iv:DwKKI3ysW5qzweD0qchl3bPSMgWDzBC8j99C6NrE8RY=,tag:hDg+YWMOJ2vv16dZRMY5Ig==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:YeFak6iK3i+WF3LNB/A/sbP7FrljYqzd7HVnoivy5F3eXuqLll9Av+pey/1EByJapXDDL/lXNSQP2ZOFRkpKvA==,iv:QXqBr4gpDD8LoCx1sQyXrHVmnmdJ5phBExuN5FtnA3I=,tag:sPshXUuR38cAglhQTMbJYw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVlVPYjNjdzBwdC9jWlJQ
        eVFFT1hobDZOZ1R6UFZKdS9TWlpSYTNWWmt3ClJBL25tbldxL0VJSFBOOGpDWlhH
        bEFRRE9XbTJZcURtQVl1V1dLR1c4bzQKLS0tIEMzSWNxc1VRTkVTREJTRGtpK0gr
        N0MvekxXdGdIQVZ4OU4rNEN2Tkc5VWsKG3Sc/Bt2iut0LtKHCqgJeKwf5y0kekpF
        UyrhbOOP+zM7RqXV996Rb0gRoXRWAgMctpWzRhY4JDF7xhLzs1JOXA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-30T16:27:04Z"
  mac: ENC[AES256_GCM,data:JOAeMiwkI2Irpng025J19vdSqSuskoFPkqOYa7WKHGKhSdL5lciWWKm9NtfFA4Ewv9ibd33rqnjtbcouOJl19g3M1Ydy1EpIBKUQziDknaKAMOFJrjKAG1nNLq6kX01oSJPllVUbR3FMl4UGFqXshumJhamLYiYrCSdHZEjEok0=,iv:YEKMdifZw5GFLDMhW354L5MXL4ZmlvW9sBT9dr3Vypk=,tag:VJFivcG9Okpnm3zw8bk8ow==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
