apiVersion: v1
kind: Secret
metadata:
  name: watchstate-config-restic-secret
  namespace: entertainment
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:7r7db98muz0qsmy6Px+zxdd5VzvfGGZRAxIqsRNWJ3YfdRXPQy78vRhq65o/zBKpwPVrqbJbf95y7Bbg+zzVO9rvUefSTc6sk1FJqOLoGFm1QmJp3EDZL9ZB,iv:KuFb/qSBM951IsD/9Enl8K7dNdF/ZjV9fIYUN5Mpzc4=,tag:fGPU+NDvSm2M5pzDkB780A==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:EXHgjuxDwQCPcufiBp9mVW2fn4/NGSYUiGabawij11BoXkB3zA96QlEGEQ0=,iv:blotbJwj4P9T2PrOaoEbl/ISzbmLtaM4Jbnz8U6Jx9Q=,tag:lzLMvGbSeDvgFHVA64+H/w==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:olKj82zoiZv4IOPt7eQouDsas/WjdUCP,iv:HCN/GF3Ic+BNtf8sID9Nn+BQVKdLUj3vxBNSOJrMDRs=,tag:nGmGvHnzUKw86rQdOKLRpw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:R3TObp48xe1CUlj2a5JPdMXabfTijF3YQqQQ+KsYE1bEBx7MxXPrjKNrLz0W8ZBo68jXwv/c55rEw7USO2jnlg==,iv:X0H3Rq6AB6xJwWKv97xHbvC5EI736iEZwkrKHeISW8w=,tag:NqduqNyqa0NzgQkkoHvTIg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSjNoZGF0VVVtNUpuQTBG
        blpxTm1VMTNRanNFNlVKbE9GNGxncnNZYm5ZCjBOVmpwRmFYY3IzMXJQUzhwSHI2
        bzlFelJVM2FZK3BIazRUMUpzN2ZSMWsKLS0tIGZBOHBmMVFka09KQkxwcmxlZmhD
        WW41RWR4Vm8ra3dMMDJCY3lzMGZnMU0Ks0UPWEPsD5TByYI3O6NKI+W9qjWU63kF
        PLYje8AISws1APAoC4ar06XBtnVCFNBaiulLW7kN4jtJjgyB5GRzPQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-23T16:10:56Z"
  mac: ENC[AES256_GCM,data:IOwrQAPAprqTGbH/Pu6YYGXcuruluX9HM1w4nrvNuLAFDsPCxRyQSxcSitu3WUXqFWXdh17FiOwR09AqTYNbFhH1M+E8SuWunXQ1mQoRrQB8K+mV8bFP0Zqrzf7m1EdOuRYl9RxQldxqJUHdUc0AGRctG/hVy1SEfswOe7o4miU=,iv:IG40QofinReGAhvKqMRXlyjvTmB38hBUVESVEiXM0LA=,tag:16wbEcOHk9a9TYHxxhUZvw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
