# S3 credentials for CNPG (barman-cloud) to write WAL and base backups to SeaweedFS.
# Leave empty until SeaweedFS bootstrap is complete (see storage/seaweedfs/ks.yaml).
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-backup-secret
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:V+PRz4MY+SiSVrT0XCmAWea93bUJMqiM,iv:iIbXyhTmRnkERdrVdR5epP8tpmu0j9/oTykExBgyIE4=,tag:GYz6czvWVraSlzjTYGTECQ==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:nS0ynuW51i6smLla3IpNh2PSilFufBSZbMgK44gbWjGtaO5slEz7FzLKiwKtGYSEgJ3Re5ZoIxfnHEWUekmGgA==,iv:EHJPnif260Q+pk2c+VOS+Zp7n67d2n50rpNenIJR2QI=,tag:WeQeEMYhD8M82EtWarYppA==,type:str]
  AWS_REGION: ENC[AES256_GCM,data:UkS/upun165A,iv:jHOhf1i4K/JjplRO6NSjJOkMH/Dbn/5ETfLRMBO7DM0=,tag:AN6rRa8M5TE6dI066Rzevg==,type:str]
  AWS_ENDPOINT: ENC[AES256_GCM,data:+hgM2XpUj9Wx5BmoxRuyI0KxJoNq4LRdi1sjvs1A2KftQcEFbH3hdffbW97i/soNzkVGv5s=,iv:a3whiBQqk2WTcxNgipe6+SSVcaeWv92BIYlD+lSttn8=,tag:dJRkKe8U9p6hp83iZyvQkQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUemhpSDRnQnJReGdGS2ln
        VjNSY1hiTGdhdTkzUm54a0FmeXZNMFQwUEZrCmQrN2lvaGVjbzNjaXQxZ2N2ejYy
        K1lPYTFXbFNHT0V1ODlsQTVGNCtST1UKLS0tIDNXaFR3M0l2YXZXSG9ZelBhQmNX
        NXlqYmtBMFBXYVZNeEtnK2luVVhLZWMKXNX6loSZgq55pJo2P/IK7BKBClyQe2g5
        KNY+iVXwuLQ+OaCTXDi2UFmHt8Zulhml+dmpYXvvdbJYCmKjMCOHFA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-13T09:46:21Z"
  mac: ENC[AES256_GCM,data:irNF/2Y18jbL4w8lLxvhIEbmJh3H91THSYU1qIejJ1yTHr5veSFjm6EOrSvRnTC+caSoG9bgwrObck5Qu2J0UKqjCvKJe/QxhXDwIAPVLolzs++4acsnzSIl85TgunAUln+u54PEhFqov9cK0BnFlvrnw5lcSPXx5oTuwsMjEs0=,iv:P72OFHn8mUsfadmg0pGxoDjMsfQDRZ+YdFagvOezx5A=,tag:ONhX1Dj8coq3VNFmcpF4rw==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
