# S3 credentials for CNPG (barman-cloud) to write WAL and base backups to SeaweedFS.
# Leave empty until SeaweedFS bootstrap is complete (see storage/seaweedfs/ks.yaml).
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-backup-secret
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:ejzZK6S0gfGuRsuJ8tJzQgBCXqPBRFtk,iv:dwmE3qZbrwVo3IGwqm2ofWNZYGp1YTmSZGffyY4OX3k=,tag:UvjnR+wD6SUfz5IITd9o3A==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:AtpGSyQyYjFI46NfSP52oCLvuui2/V4GrfU0PZTgp7jyhIeqIXVnLCeJtUW/9QB8WRPwKAhnNxgeBhGRCw+Dmw==,iv:zO+YLtIg38y/G/PnEHKoJwP7b9rAhzmwXJ4a6TLfmRE=,tag:MgaEQxpc9NpkuyVoG1r3yA==,type:str]
  AWS_REGION: ENC[AES256_GCM,data:gO54QK37GX5h,iv:vVi9hhc4X1IhA3pFuND4atdWrugL/BWSFXYKN6NjXR4=,tag:rTfTbSDYbzFNrF4mJcGNzQ==,type:str]
  AWS_ENDPOINT: ENC[AES256_GCM,data:68XbTSNBhg5r6WACM9ZheysFsJOnfZyj6gTvvfXT6tZ9cdLETpN1PsEtavV4+wEy2ikO6vQ=,iv:50BH9uBEZVftAn7z3f9OEon8Lf34LYd64g+xgowlOgQ=,tag:uBrb0uKWQEDzJho1eIBr9Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnREIvMWFrNHFLcFMvOW0r
        RnExeHZmTVNrSkpSOHljVHpaR3ZPYVF0K0RrCnBqektab1o2eW1zTzNCMS84MGxv
        R2phV0RYQzRvTG9SNnZCZmQ5YXp3ZzQKLS0tIFFuTk1qMk94Q1ZPU0hiSGFIaWZY
        TFVJcFVOZVFKaTl0UFlSdTlaOTdhUUEKTWfGKlHWJSzf1O301pbDQcqq7VzHIJjK
        IN+UR1bQ2r7VQEw7jQD64vJY8P/BHRqs29iCH81ZGgM/HkkS95roQg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-24T15:01:49Z"
  mac: ENC[AES256_GCM,data:4rBp2kJ8SLIDFQ01tpp/BEdjUv2xoMYa7VSYkxtvcKgHa9bu+LA3gicOnYllqask1+O2P0vvDyCzWvObFI104HideUvxh64JBbCRMqMHnppEYOb0mRdXinB/W7eH2ta0Ls2VLr2wPIADTEe/PQ05TyB4aLVFabNnW7g11r6H6K4=,iv:bp724Kv/fui1cBihHgvkL0vey7ag5l0OofE5XJ8d3Rg=,tag:K4PTp3u49RO1iM5/NvRibg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
