# S3 credentials for CNPG (barman-cloud) to write WAL and base backups to SeaweedFS.
# Leave empty until SeaweedFS bootstrap is complete (see storage/seaweedfs/ks.yaml).
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-backup-secret
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:OCnoCOo9lUxfsxUTeJwOV49rVmJdGhIp,iv:wU50YogrfR9iteN3n/JVtVHtY1igWzD7RsCl2wkVRGU=,tag:BAWzPKysIV+rWqKvlDA7Bw==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:w+/YJPL6uTlAxWqbvrvzhzM092wyNeSu+YyK1CEqVAOOceOq9vEQ+IKVKzPTI7eSYg97h3a9+0uiBMnOomA76Q==,iv:KWClw+XSW/OZ44eNl/SBgXN5QaVf7Xjyd2i6fM5Sw7k=,tag:dS9Mt/K7VuKtfS552Nrrcg==,type:str]
  AWS_REGION: ENC[AES256_GCM,data:RM70EFqc3CY+,iv:wCHQrke4b84wKWY/ot24TBe35qE67sQPxKr73YzKRHo=,tag:fOn3uUUFoUTNtqTVBN0wxw==,type:str]
  AWS_ENDPOINT: ENC[AES256_GCM,data:wyGK490RLbP4LXIKSMbjTzCHv0ok+dYt0onjVSV20o5UI7soZTsF0gn0y/wbAYlMg+8fsRM=,iv:ifRk/X/DsI/B0uc5InHfTPXaXNTWoRHd2S0HzjOELaQ=,tag:JRmkVmCSyd++kG/ZLFdDAg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSVptUjkzT3p5VVBZUEJG
        TEhpQlZTWnVQbVdHMThYc3hhaWdBV254c1JVCmsxdFc1UnVEWlNMYzhya1RESnhW
        QmdjYld2eU1uSVlQSU05cU5qckdXTUUKLS0tIGxlMTByZ0JNU0lLQUtuTmFGd2Qw
        cm1XcXhVTnFrNmg3ZjFxclNaYXVMRmMKfnpPpiUT1MnaEBkUycUMxBO5r3HkmBTO
        t7fyAstt1YZMuQnS34LAT/dylGa6zC7ZYkvDyJqkyxdhyGboJ3gZqA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-29T07:29:37Z"
  mac: ENC[AES256_GCM,data:lQWq1FnJiAFjid9u0aZ+qXMIOsK8gc/4hIkwsu/fqhTDb4ugnJ0yru5kYeK0zsWX71VCCDa0i+Jq7VaV+hknh8wdnaWkO/uMpiyDZE20wBbeH0S8r7nJuOHNFY7qNDOJLp8i+Ig5ALU67bgLAFbjBJKzqnAw3Cg10Afd3NKjRic=,iv:bX9G3857QvIUv2Cb4W8r39K8XFjkMQtxZvCbz8R3TVI=,tag:T5x/X+SDndniE/McnJc/YA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
