# S3 credentials for CNPG (barman-cloud) to write WAL and base backups to Garage.
# Leave empty until Step 3 of the Garage bootstrap (see storage/garage/ks.yaml).
apiVersion: v1
kind: Secret
metadata:
  name: garage-cnpg-secret
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:r5cP77YJ+EQGD9fB/9rId5YRod94P2JFT7M=,iv:X9YpmALb0XypyNpkdXjxtFq+E/oMop9NqFCMZd7pkV0=,tag:VpzIjPjGhD7UfwwsKWwnaA==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:NaSUbTlZMXUH//ZxZ1dV+YnxElcnjgAKyzQt8sUeoh/K+R6vRIlhcWib4HjhVya5tu1Lp5CdFn73pMoxn/fAOg==,iv:/HIiwfMh6yuws5INNY1mOSP+/7pHE/EBXSYDrHFe6kQ=,tag:i+cH09MGpGWB9urm5s9mjw==,type:str]
  AWS_REGION: ENC[AES256_GCM,data:oVSW1UWu,iv:C+tQGg0XJDy23Gkx9GQiJ/0gbbf2cvqWIP82qPQsssc=,tag:n7HUnDuK4XF+hFQEQtkIzw==,type:str]
  AWS_ENDPOINT: ENC[AES256_GCM,data:+QISmeBTXPGmM5yeZLt4JXafjr/EBCdfu6lT//zdat9ngc5iMYOReMMbMxYgSnU=,iv:nXQm1Q4obPfulkmAqvYehYs4eYO4I39NswheVSvCWGg=,tag:c2qTUHlYlXFgGbm2ClVQxQ==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmcEtOTm1BRTFtWkc4cFhp
        Q2tUaDE0bWxxRGI3NG85Z0hWRERqdWtqYkdJClYxTUttaDVOVExLSDVleWpDb1dB
        RUtuY3hFdGNIWVZQaXhLZWpwTEFVZGcKLS0tIDlUL0d4MUJzSEdvcDNWNmZoOEZr
        QW9MTmxJS1NrVnRUNWFzd0ZrNDVZTVkKCZcy5yhBhZ1NBkhM86EWsitvcOc5eZIx
        zfUF5OP9ot8IWJOEOdkAhgcAUaHBkHI35y/u0KN4lqkIvQjunzWwfw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-21T08:51:54Z"
  mac: ENC[AES256_GCM,data:2awkGR7gt3f35NGIXL5OvvhaJExjHjMgjHtac/kpeVRP6O76fsTRWxKtIEyUBb3BU+COg+sImj3zHwWQ+hgp2n+Hx5a/+9Vj+F0GkqWSTY5ufadwggI2CydrfidSfiOjhXv8Se6PtlzZrSuO8YIzkZR6byY1pRZJr/k2twazkjk=,iv:56VPWF0r/7oj7gnompAm8rZozSEg/obvQoHrWU16+J8=,tag:nfnC716OS1DYiBbDwIFXQg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
