# S3 credentials for CNPG (barman-cloud) to write WAL and base backups to Garage.
# Leave empty until Step 3 of the Garage bootstrap (see storage/garage/ks.yaml).
apiVersion: v1
kind: Secret
metadata:
  name: garage-cnpg-secret
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:p4ancurClWCodEKioRGNGGu2dq92OqkVOZU=,iv:eKm/vokyMA1TFKtLWn7UzuDm77OFeC0SaT9WZhgxnkY=,tag:loFY5yJqxDPDLJELLLOpEQ==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:MgNvdiKTKHLokGnY7XV7HktvOeeeihWrPfroXmt/bj076jR/6hzEu706BwPABwJJ/nKfhlT8h+hJBLG/z2bVHw==,iv:GLnlbM1tyhDEnEOAnS14hJHyJyGwhAorne4NtfAGTNY=,tag:TGTF6HDarsTlfQHRYrLS6w==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZFpteUo3Z1RITTFmSGhN
        WnNabkZ0SzNFVUgvenpMbHVmSTViaVNrc3hzCms2Y0loMGJCWVlsWWIrSnVqTjVJ
        NzQ4UkpZZWZkMElFZzR4QjEyNTVQd3MKLS0tIG9TWENWbXRidzZTdkxIbzZISmIv
        am9ONTg0RTQ5dE12d2pYcnBCR04vdWcKwaIjToswFqqspyFWpQBA0YWa7OkFWGat
        dBdvicaSeQg0AvC23XOQAEmno5+H6RI0ou0YWne73KrQf2/ADiiyJg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T16:02:19Z"
  mac: ENC[AES256_GCM,data:MFNjyCJL0sQWOe4nH30/si+OY24spNtYAd9Zzyq6Ehu8od/bIj1SeAWmVC1lyxEM5iCDwLD5K+1T+9HDijuCRQW6XQs8GI0a1q8+OJpMAf98169AKSyjq5r3F7d1LIwRiDX4hrtEVBEeBFUHeRMEJ8sGFNhJcyp1Ye0+AOwMb1I=,iv:T7VeXXU5USkhaGxML3gP0ndZ8s1/fIC40i1F+kdE9q0=,tag:fxTBi+TcsohdvtaCSuTmgQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
