# S3 credentials for CNPG (barman-cloud) to write WAL and base backups to Garage.
# Leave empty until Step 3 of the Garage bootstrap (see storage/garage/ks.yaml).
apiVersion: v1
kind: Secret
metadata:
  name: garage-cnpg-secret
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:+2EkL07Kp57whmHdKFUh58JTRXpwUdon2z0=,iv:hBVHP+NO9BqZe/6vhOLRueNaVGVvBqhyJ1sJyGVvJo8=,tag:xETIbEKS6Nt8klr6hldB5g==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:q8JkNYosv94S7w1EW2LWQaAJpkIhOyeDaRRA5K7dJn5S2Wku94JTEEgBq3oxGf8enyIxdRmuree1nx8z2i/6OQ==,iv:zzRbSDbujxwEo54eASrhHRlYfcxArdbmkFF6m6DoYT8=,tag:tkgP+Wu3V0agYTCyjy8R5w==,type:str]
  AWS_REGION: ENC[AES256_GCM,data:Pjxh+1Ey,iv:DH+MkB6oQgHMIueQQjAFrtpJ0tNR5OeTzlQQSquOB4o=,tag:lQ02ZtdKNC8469bdydA2WQ==,type:str]
  AWS_ENDPOINT: ENC[AES256_GCM,data:za5Em7NNswXuTKkfHCWU4hx33tap1CBlLAD3HovE8a++/UnFtSxmlabrfjh7NOI=,iv:o4hsHPuTCYwC1rChyMOeZcZpRuIlxLRb1Kl1ezTTlV0=,tag:xieCneL/ADmVWlZcHqtytg==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6NWNqVC9pL2g0U2k3VDB2
        NXVydXJobHBVTHlodU9oVTgwT21YdTFiWkFZCmZQTDdoNkZNWDlTMTg2UmZiQ1p6
        WVU4cGgrY1BGaC9jMXRXamJUdklBNmcKLS0tIC9iNmt1djE1YmxXQUp3VkhGQ2dm
        a0VLM0pTYncvRVc1bjExRE1rbC94dzQKBxUf2CjaoFGtxCUdA55kIvptqncK1P8E
        rt7I8Pnx2Udce9LE2jYw6R+PoUw/LWxq0U3vOYq1tjXsUdUOuJkVYg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-21T07:23:38Z"
  mac: ENC[AES256_GCM,data:k13tRJwLKIJMaoXvGT9cLC1AgqSaf9oJ9mRLFylS8iv1a1fD6UeTYLk6FoXN52cKHnntDxR2FSZjvWKZTZQ4/f349GDPtnvizrZP6jEebCzxXkp3PpQU1iOZn/p2hwAfOQ4cK8QsjCo06gFgOhodNaLnZnI4PfPaMqame1d1guw=,iv:fJPUT5RN8rfPhQ3rH8Ekw6l3tRqGmFx/uipX++S1jpY=,tag:DU3oLwF1nFpccKrMnloEGw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
