apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
stringData:
  admin-password: ""
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJM01IR0VxcUduZTA4N3ZX
        czdsTzRhN2ROcXJ5RjltUVFTSm1BVUpZNVRzClBSajZOVjFtZGlnQmZtOGZnd2l4
        WHJDK2l6aUpTUmhxTVpaa2VFZ3lTMk0KLS0tIHoyeXZ5YWVXeWszWWthTmhsTnkx
        bHdJLzlXQWZYbjdOQitaRTZVT2FSL1kKLLuIStKn37VYDeiRbfdQfrJyc6vuvfV8
        K2jaJ9dCOo+ucXooNoVJT7G3HyiuCTucSlNPNrofP77bUwIODoRoDA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-24T15:38:31Z"
  mac: ENC[AES256_GCM,data:q0JEg2vDT0tMMkborX1/XEGGOIbfW+5GfoBy6weG7DLXn0Gf+GP+3afldcOTiIpeeeoOdH9Ksg6iHUAObBUnCrAFT5VNeu0y+PGfRH11BTC66nIv6wJngFBE6FrmIciX3c2CdSl9nb9dBWsP0jj7ZPHU8aSkh5NAyZ3fC5oTQJw=,iv:ZhaUdIegS0QNoH7wjqIrhC/88ao9SznNORL1Ga6X68Y=,tag:Q7vcJK2P6nGfbFjb7tvMTw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
