apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
stringData:
  admin-password: ""
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzT0JWTkxrRUJNazJkamlk
        L0FkdVhydDM0Qm81bmRGck92bmlDQkNnbXcwCmlFQ211cnF0dmd6ZVhxREJBMmEx
        Wmh4M0tXZ2hSU2R0UEtBVUZEdllZdmMKLS0tIEhRRE44K00rcWtzRUV6VHNYMzlX
        VUVRZ2RzVzdONkdRaGY3ZzA1eFdkM2cKlsAOuGiTpZ5OWMotZ4ESIEugWXcSkAu5
        uo8qrE+1RzWtfdAJIu4sOXunim2IIvmN95CdypBLE5sD+hf23u+Iww==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-21T09:17:16Z"
  mac: ENC[AES256_GCM,data:UIiuF8eUT/xCwmvmfCXb68V1Z8LF91CG/drwW4y4dyVYj5FZ0SWjmaTZPx2r2GgZ4YPKvyQwAO+ZAl7KBqjvT2pWEIBema1QfSITvL95Hx1KdKtgF82Pf4hPj/MdetWrntSzkqp4N077yK5U5pN11xklSnPREFknHuaOvfIoYyY=,iv:to4aiaWp1L1aPPv5XMqyXlbcBB0RzXU7MCHlHq5Cu7s=,tag:FHgap/C+X1+3+7N43yPLPw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
