apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
stringData:
  admin-password: ""
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3enY3QTQzVmVRTDBKZlN3
        Ti9SVWJpQk5pVVpyVmw4d1B2eGFwQ1plOW5VCmpvMzhKajJCR0svNUsxYUdaR2gw
        Y09JSTNEV3UxT2lZbTNVK2ZCYWxtS0EKLS0tIGhYc0M2TFU1emordEMxV1FQUjAv
        a3NmM2dtcjczaytBaEliZGVTYjdKRFkKw2bNxmZdtRZ6eBcu5TwtShyqENLAVeRb
        lRAzXbV8Ho9aScArayNpQwfwV7cN03Aw0JYpfSh4/Bvqmf0Cq4ym/g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-05T07:55:07Z"
  mac: ENC[AES256_GCM,data:KGMTVj0+slslEo7inh4xcpME3i1TcNRbQITWoNSd/ejULOBxE7gjEQ4GAevAcJ3RsahEjhfK/SkYDM2pd6SVknoJeuIQeu8+iAfJw+OYqedzGCcIs7SwjkzFOdPx3Gp2CiSfn6kH3zZ3V6L7UjSehhPHPuu1OvY/3jfuSKI7hVI=,iv:brg5S+KujCtEDI7mEemV6IKBM19wAKxbV4JggHLd3R4=,tag:dqij8B70PT8v+tMHi2bKeA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
