apiVersion: v1
kind: Secret
metadata:
  name: health-auto-export-mongodb-r2-restic-secret
  namespace: health
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:Ly4ndBydv3/c2NhqKWUJzrI3NVVu91YOl41uPNuEcxtxCLTBoS3vTcp7rXrDPes6lPolLVfHslS+5AZv/NhSV7uF7Z4jjAB+IajlkQNyBsh0S3RzYu0vA0zD0RG7sve83Y/IEmZ92wKhlZUZ7666oUR1,iv:Wi9n6Ibr24Cl6jqJo//1teOWdvEfZEDdTWzqfulIZkI=,tag:S4m93ixwxVHdGHhH1+rcgQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:99XqQZN91FmpxVRcKR42v9+lgH/0xGfTejyo7ttD/CyzRaGrdwHHOGOltJk=,iv:D2nksUbHIFrhzNVIXs8JivE1IdriTkaBLRURpdmT+fM=,tag:z7jwApiA4yrQCuSNQwzxxA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:nJCANp6/9+3MQzjeXs4TKjHPUarLepwHvt5gC5EdREc=,iv:mwhLT12MXBV91ELjUDiDBaoRHuFQ2/Ikj/RJ8rCWNX4=,tag:Nr2EdaOsho/KZ0D+8H9yxw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:tR/L8kYJeSwIOWTsWfc9fBU7GaYDd23mEn0bWFMCaJDNakJz1muXZkjK6iI1MnAyeJxWFR8z51DJ5RZ/EZV+UA==,iv:w36FbdwqDDZV4RwKvA9AaNVKRYET24spU5pkkU8aweM=,tag:S2D9CyiOtLjwg/4dUQqgQg==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:hKKDhQ==,iv:MB9DWw7ABWB5PIDQ9TWKkv2bjLgFSZLLjrdU5+qvOlU=,tag:ds1Hl5GwpvCR7MwTELY9mw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkczNJbzJ2QS8xdzN0YXA1
        NGhYN2FhejlkQURaSmN4MUVKZTc1ZlhNcUNRCkY2d0R5SXFIUzg0akdSY2k5YmZK
        MWcrMnpYMHlkQzJ4bVBsYnM2UVUzRG8KLS0tIGp5ZGEyVHY1T2Q5b0tSL1ZhVklz
        Mlpxa0pyZW9SNlJaOUhqUGZwUmNBZjQKcXMHl34ki0TiZHn34m7nYYaB5gATJ3MM
        lKs65PQhTXG2sHZpym0nTYCTbZGgA+hOVS9flsj/VgYu+djpPaJL7w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-04T11:06:02Z"
  mac: ENC[AES256_GCM,data:g+68WjDtLMBKiHlEBLt6tGkYYvUtalcfRdB1Q8WL0NjFAwM1Wg01s1s1bC4nuK90ilbwGIW6pwsY98bAaW9Jj2PEvGvb/cUGrKaN1zYl6/3y0VJ9FbwthmOjwljyUbmk8tXsG7yZe4ss30SkF65BN000EBXpLDpoQIm/ZspfBXs=,iv:xhiGI0rYL4dL+D+Ve4eHsM3N3zKZQOeZZWrhRGHBuos=,tag:1bQ0GCQFvOTiivA5W9ByKQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
