apiVersion: v1
kind: Secret
metadata:
  name: health-auto-export-mongodb-r2-restic-secret
  namespace: health
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:6R+8BFW+yRJ8uMs3B4apyX4e3m5m+FOUaPS9YyzhMK6fDbWvuoNl4kKpKOxeIfwupxs5PZy51arkiVBlvgCjK6MCMKgtgrG+5nlVBnTMbcYL3gloqEYmVEdd85RSNb3fwxVmRP0iURHQd9YiO3/uEmTu,iv:KiZ1BNZV+OgPuVvyyGjQr/yMpuNdx28eVCI3rbr5SGo=,tag:myQ2iYCzhc7EzkOQhO+M9g==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:OtB6iske+g5QFTmHMKj2ocgLd3p9/dkHa9N6zgf58Qcibx7r8tqlZPfxO+w=,iv:En/BXmMfji+e++bOL86Tw++ytZI3Kofm7jJbKee2Ly4=,tag:iHLfV6zj3ViULA1MXBZpfw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:EiqVTHwuEYK4R3LOCIeSVfFU5IDey6Ehx5QymgUS1p8=,iv:XgX/49/r9nP62Y9ccRUuss5PFTzix0Xn5CWbKahms9k=,tag:npgAZ0nFu6AEjWsrZ62jOA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:0J+x0rVewN8+yncPoVDpFJe9Kf1CqB3MmyQqcBgR1iNB3BQ/J4T03pDRMstRBRkS79ds1GzqXmnHkuukuFTE5w==,iv:b9fnrJHlxI3wHiubphFAME/ZZP9/0c9/Ucn8eW8KYb4=,tag:85awUxJayhTf9R+swiSIxA==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:ildM9Q==,iv:3sOVI++pk02NPUXAf8P2dLYYBKjnciT5G7xaK6mpbWY=,tag:oFg3cB4/nym2ma09820ddA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWbS9NMk5RbVAvQ2hIRlE3
        YWlpYUlhOGIvaWxzazA4ZmNaYStDc3FqUGtJCnRKeFpKdlpMUjhPSmlBZkpzRnlx
        M3krbWFPalZPSjNxZG5CM1RSdVY3MzgKLS0tIFBVOUlheVJ6QlU2cEZJY3NoV1JQ
        VHpCMlk2SW9GUXU0MTFUN295cTcwZXcKzj2JcwcdripHy07AINtk5LyTspw4MDi8
        GTepQmbi6rBmVjsGGoVqEfnwIUPxVH5vhpAiqL4ym8byoSBuLhAR8g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-18T09:15:10Z"
  mac: ENC[AES256_GCM,data:AB3wwHwivJoHnNIHZ//OuRRS64S5r56DnYzx5uAKfMoFrYJNqMv/qs7w0CqLcEctHD9PI3wtj5bTLrO97qrI2IfTqJlh/dHAzkMwEMPdDG3wQ87g0AxqcKkPsW7qvkhQl6ldQNEHyLgkeKNpVRO6FkqqeGR0B0LuEsGLBOb7uVo=,iv:HfHLneqCThf7zhcOwY1VdwxDv3nDMfS/2NR2XoaLU9I=,tag:oeW1VsDNGaP2fTznMcpMxQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
