apiVersion: v1
kind: Secret
metadata:
  name: health-auto-export-mongodb-restic-secret
  namespace: health
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:u61+I1ptlp1pftDdM04mTcv+LFZ9SVGAYZMQ6v5wTBEOk+uNlLMgeA2LxPGssFsOP8r1GiK56Du6QKyPtI35BZq4pnZCKTINS1FQpkXtYRVYCa7bvEceJkrPTcOVBTAtsBEU,iv:UVhlqTTe+O5+e1oTvX2IULx2SBFr0GHkxllT3WQwN1U=,tag:q3nTBRbdwv2Br06ZJapdrA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:6qKw3maqDhEpp6TgETH15OSLrnQZuLDqLhpOrNc58OQk/et7iTYcahODmKg=,iv:3U94fTJodZkf48jlf439sVqT5SLBbNvYziOORQukr4s=,tag:vPHCOaz3f/Kg6ebXtZ8nBQ==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:LQTatxQfTCCTtUEAm8VUIQ+f54tr80Rn,iv:X3GHztXofFB0hebvkUwN6RZypLhKGQPoIkSwQMqqm/Y=,tag:Ho6FMH13c8SiKIM2BcSLDw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:+YL5Xq5JqN9DpJoN7HgOunk/LN5OsXypB6QirAPx3j5ih4OzejzxpojgRwf87rJvmBrEzIM9iq0DV8dv9jmB2w==,iv:oGb366ESimV/l0Mk6bw19c/4CHwQBX6eTOQOezdzs1k=,tag:gvcb8/VkOYIogqHeK2/owg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIK0ZVMkw4dy9meGJRODI5
        V1EzbkZySk9YTkdPOEV4NTN6SVFUV1dyUkJJCjc4LzExRS85cndhaWpJZjF3dkNp
        dm55RktrRTd0N0JtT1FIT2VYN2VLb2sKLS0tIHljV1AvUEdaUTN1cS9COGZqdHhr
        OVBSeVhMcDdVYjgvUG1RMU1hekhKNEEKPsBCAMGqU7AY1ljv9JUNAuJ08nMqXL22
        LL+mCuo86JT6CBL8ReO7WZWb3A5fP5QPgWB3HVLii7b0wtgMneFmOw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-21T07:52:12Z"
  mac: ENC[AES256_GCM,data:6Lx4l2AxxcEV9QvlujGeymsVN8+EgQ0B2pBj9BgLxEmj/yQrd0mTDbnYXMCDcoWBx/1n9Qm0BmAM8scKgbTPEeAgCmK1+ZS210eateOb6HtJwt3N9EtmZIUx9cpy9bDBIsLW/jCqqy0FL6m2GceQJi79xNmdPYOuEemJMbjqeYU=,iv:YalvDTI+2MtHJg2GsfEe1kd0UJDzspVVPdWUxIQbCis=,tag:GkTCvY3gafWCnsY9h+7vYw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
