apiVersion: v1
kind: Secret
metadata:
  name: health-auto-export-mongodb-restic-secret
  namespace: health
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:qIYIKNLoaOKooOHCtUI9291R3XIO24LRzXwsmu1SxiXnTj6hbNRFux8u5STKuP+3qnUo90sPOTfrenXzUWQx1yDtBVHSkqYwPn1jATNrR9KX0HieGdsezqLZe07E4D4E7Qp7,iv:SDx7yjhRWbUAQbdBEO/nOfTsegV29+97YDmFvXIjP8U=,tag:8tynn0DVVN/wiSZv7/EMZA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:NMyjrvBSMXNLf+t/JgCfPtR0h4/OeNh6xtrXT7iME//78bL/XJ896UBsH3E=,iv:54S+8Bi6d+q0M9ZmLy8DSfWDr4lfG07/d2IVphKNN00=,tag:mdgQjpaBm58Ep7RoARZemw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:yeXFrVc/c1oH0uISSRPU56tkyr/1h1iv,iv:Vm8+txNby/r3rflhKtMNApkUY77Z//FzGPX6SC1FzNc=,tag:4u/hAUfYkuPkcw459nClbw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:iR+RnCuHjMiAglVJK+5k+b4TYF+7UumGODczKT47FCJC11096oR1RHFg7h+tN5CvIcKT061x4z0QFIVPEHvQNQ==,iv:kepYsVYWNeYdeJKkp6+IzfPZT/FWGRqaOZFOHLkZmFc=,tag:EA1XbYSdaNKyExnVfDL1Mw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2eGJheElJWHBzeTFwVmcx
        cEhmeExDeExzRm9BckdyZGpBb0JUaXlWNkZvCllUbE1QUmlCS2FPS1FBQTNLak0z
        R2YvVVlER3JERG9SSjA4Vi9URzhTSEEKLS0tIEFXSDVvcTFQOUp1QTVQNjlBWlg2
        VG94YWZDeGJ3bWpGS1lqQ05UbGtZQ0EKuoESBtbvbkl/vO7imnLAGWcRPyxfvgvO
        9cgR4OncuOOjOFMcCxJtg1PZe3tvdwNHzTn3OoguFrjiH32leuav3Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-18T09:43:16Z"
  mac: ENC[AES256_GCM,data:yVHHVsLIwa2mp4CewhpyDGgfVqF7EmAT0ecL1I6+CAJc4N3P80usAR7y7qpzjyMckhnw28+fqDoOfwWepPgva1tvbRdANWDl5Gb9RwtfaM0WcL4e9PueiSqKtB/hujkjV6SldvclJjPFbXXMZyNt+eiVRpnx3W81wSLzR7CQTos=,iv:ttZihdocIgO2pxFZb8RQnD7HFEKqHuL5WAqjV2hqM38=,tag:4Dvf2VYSfkDtpKFf/n04TQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
