apiVersion: v1
kind: Secret
metadata:
  name: health-auto-export-mongodb-r2-restic-secret
  namespace: health
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:yFOonDaVtZfsAv/hxPspAF7SYPqZavMu5YOYb9udlhr8E6GKL02FzpVnbSj6BIWO+i6W1qFwX6L3HQVl3Pijh3uFrUoiqMsYp+i2E+dMGenyP6HYR3fKUQYlYVl7lqEn4ME4bBnwH7Q1wHji4d/UUDbU,iv:Zk8Q8si9telVUY657OyICvJ1JBZcV0bu4t0IFiKLsNg=,tag:HmrUHKP/+mMjLEW9fp2LlA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:aWZnbSiG6fEgI1KzxEnumWKKdHXpI6MotH44kLcG3Ohbgf4lrPmRlNkquSA=,iv:aFkOj1ALDdPr7hNKPpyc2eq2KoYUlJlLZaFSx3p4Jyg=,tag:2sWkK1+FMbqbu3SvfsJsdQ==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:95yhBLvAfzwsHfCMDDD2BYBsM2dvy0jloaY3E5V42iE=,iv:3xDOubW41+YJOHjvBVOJsppyzER7wfJR7T2q/TDHAc0=,tag:XlsOvTZrmPmhOT8mc/ZlLg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:A2XFC/SBB56tpt5vSWH2xTvnk3voQxQnyvAO7PgEfKASySksUeTxom9w3nG7+2InOA/46DIJ4RbB82HRZbgjbA==,iv:Mv3XfRoIMdOgX/txxPmfqK1UTkDS1CrTdRBiNGBpF8s=,tag:7RCIZwbkiqV5g7GxjQBFNw==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:0Vx05w==,iv:HROFf2/PAms/exQdoQt/SrSDqOrNd5H2x9AMqTEKrhI=,tag:1oYoNwwLDs6FBslacaNmUQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSdWl6MDVFMG8zZ2l1UVlY
        V2NNdnlBNUt5eEUwd0ZKd3kyUFhBRVRQNmhRCko3L2VFYjlmam1QQTFRVng1QXl6
        bkVVWkdjdnRSTHgvK1ZMcUJjcXJ0RTgKLS0tIGR4SkpxTnJNQkVaY3Juc3FONDQ2
        cXlhOTU0QmYzNzVUWnl0TTh0U2pjR1kK4p8pwSxQY6pIR/6JCn8gXkE00OEIC895
        bJHNFuzhr2IFd757B5oXx0yiCRkopbsnMJEZ6QrpHfFoOLgZZup4uw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-16T15:11:11Z"
  mac: ENC[AES256_GCM,data:ZCfeiUTy8078zeBl2GVW4LkKHw5EHbsLOagNtnfzYw4p4+zGId5FRKxgdR87/eqU9aFx8TQeTcS4bPVb9sdB+gdy0H/pMdwLZpojkNpbLoN7mlrlm3bCIfEdoreP0mVDASVoSNivbV0ehOgJ2ZjybNR7eZ15zwLyuL/U7O8F8fs=,iv:Ahz/dbKQnsFbzPhYbEPGH/ePtn09Sau76XoSPIOfMGc=,tag:MJGeNy86Z7uDEyhp/wLL2g==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
