apiVersion: v1
kind: Secret
metadata:
  name: health-auto-export-mongodb-restic-secret
  namespace: health
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:O98SuhUTNMBpFOSb3d5uAkNaU2z2WikJ3rSSCnfrSmNYlS+p3GSBLX4zvpJzCaUnSX4t66PmDPuNs1wNHFC8igN/RKpNi0NJWO9emylYXmt7Egrb/ZWGi5onFuRfsSB5PbTR,iv:AJO5dmxse84yOHakCmq9geyBlLzl43WMQZBJbN2ODAA=,tag:R6b6R22L9r/krn5a47cJyA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:JushKHoy4wiYGnL2AnnaO9qdNA5Z8pVK/gCDsl9A6zNnPqkAYkdtroxFpUw=,iv:3UtKwH3/rCoS0LPzpzUi+OXcDHR0kd+0Y1wVQ+EXaO4=,tag:hhwXd8jwBFMntdXcyBgzMA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:cFerL86qLA6va1rjUOkOM+xJzYXXpG7V,iv:T025kG7DnaHD+NxTtIWv+2jsOhzssYXrO2t0QaBh7Fg=,tag:Nr00dTL18WbCEjAkPDTVIg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:2oOjWeWU8rjxMRpoadjRX10LnqHgLxlik9/cjhP/Uv39q6Y/svAKV7buRPy0iC5LJuv2W3vP9QOVZIdut4IxXg==,iv:J5dw65daJCbWBi+t3noTgbwSBsuKjQQP42RO6SXeSZc=,tag:fnXzbDBtZiqFI+PoxhjngQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNG1DZmlZMVIyaGRvZnpi
        NDZjeVkya3NoSndMNEgrVm1FL0Vod0ZTKzI0CkhJcDB4Nk91dVNDZzdTYUo2V1Rx
        ZHJHY2NoaERQOWdpWm5ISm9STlhIbk0KLS0tIEEySjBLZzUzQmwvOFdZZjJCbGl0
        M2t3aXlmdkVOM3lwaGx5UGIvRUZ3L2cKZbqlA5wD1ynyINA0U39dPV5JpFJE3cqF
        I8rjjDN3KjJnm3gojtqigkWR5umzbMKTuF1kLpC0jezFptFA3lOkOQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-30T16:42:02Z"
  mac: ENC[AES256_GCM,data:ZI1a9VnUSxUOtnJ7mXXuzJfRumzsdx8fYlwGLkPNnEYkgeTO4Byv94BUMZYZMd6LajcMgr80Si8SoV08YAuvW0JCNld9CyFwu2Lx8Mdu18pbMRo6ObZQEnbEfUVnpI0MUwKGFYgBtYm+m5xjPp5r1W7Wdrp0lLC+zm38r+AvJqg=,iv:TMV+B8WGDDEfoP5vsKOF43vLIBKwRm711MXBGiswvAg=,tag:IauJTUje0pTG+A6nVWCeLw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
