apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:uqRq1+UXIr9OBw==,iv:NBCCD7QLnHeaXvQ1MC/NghM6yDL5t2WFOvQ91SdTQ8w=,tag:OPU/d+mHxk8tdHM8Q0NskA==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSnpsbXE4emJrNEs0c256
        WVdOZmxwVitIRC8zL201N2gvc1kwMFdRNzI4CnBzT043cHg4VVFrOE54K1d1ME5q
        ZEw4ZUxUNXhhRXBtV0lEWXA4ZVpqdFkKLS0tIGcyRVZub2VGMGtOQ29nanpwbTh2
        TzZ4eTFVVWJ6Yy9ZWGFMNHFvTUgwdlkKJwl7z3zu4v9fgLo6yD9GiLl+r3DHNE4c
        uJJ5YTw/+hZUS54NpzxSdqy2+ii/Hf8mJtYh4/0OM1F02jInPdPZUg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-21T07:34:26Z"
  mac: ENC[AES256_GCM,data:CDhe9zZWr47Jpks1k1pzyqsztIR64Dj8H5ar8zliihOQ5OTR1M3w92eFyqO7C3gr02z+ponfCnGURSRfqKGnmK9XlQ7MP+skXrRM4IxvbxgJ5Ycalohw1XuPr7clLT4dTz2zSF5p5x5a1dyhWtcP4khYsvQVPW8i3k2EOE14hVI=,iv:e/uS0ebzHm3VTfD3dO3vg0ZVbyaeZu8yREecdgUBWHA=,tag:TbYp94AuJioSWc3WBEMxBg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
