apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:ytZXPhQmwLmoxQ==,iv:js+5hGJio60DHz+wQyHX//rN93osilrE62TXXcKt1d4=,tag:DuFn1SmJYpFXDhbZPJcZmw==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbjlRR1daVWFsLzZFU0hP
        Uis3NWM1bVgxUDU5alRtbGJzSGMvRVoxSEQwCktvQ0MvSk5BMXBsRE93aHpCdDdu
        K2F4eTB5NkppWkI4cXdXZS94MGRZbkUKLS0tIFFLdVdEUjJ4OC9PWlNORE5KQnVw
        elVMMWhBcHEzMnZuU0RVL0NlRGlJeWcK199DZPRhStPgq7OoG50d5cz7gXyw4HT3
        7sIihgFODFCtCETDhW3fF3Cp+tOOfUV63nKWWFIl6UVY5r0/nxz3xA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-22T08:18:01Z"
  mac: ENC[AES256_GCM,data:CAmTZH5j9wppgn9fMhTLV9uS64u6iLpdBCMMFTPlAtuK4Bla2MWOyalu3w+LQAHhE/Xn1BVBT/0bSCR6EsojErjbXzmVutkkap8dOycRWsK69tXtxSE7LaNtZ/xcUH3rFeG8rAB+gPFnSs1vjiK6yqsgHFt4binYmdW3iNlrWmw=,iv:A6t8tjuCgor/DXI6avcx1H6M+2IBH4qmD/WxkA14GIc=,tag:NLK/E8Iyck01K3FV5svOuA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
