apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:xkjeQTq/EtbDig==,iv:gz76pXK9GLKhMRHXH5yl9TkNi4dSnfFllkcf4nt13Ys=,tag:x6ft814utcGQOQ3lJdOK8w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSnlhd1JqR3VobGh6VFBq
        OGhBTmFyazBGcGZnZzV1VWJ1djJhaXo2TmhVCm1va1RTRG5XdGtSYWFuRjNDMjUr
        Q29UOVdadE1IRkhBM2w5Q2kxdDJ4TGcKLS0tIHgyNEtLYXA2MjNHZ1p6Rm5mZEYx
        ZU1VOG5YTG1mRlRIdHN5YWQ5WTdWUEkKwp675sIGxndtQQ45nLmSxTaC9h59UXHJ
        s+R0ZoFkySBHcaMLcbZ5xXQQmYNlFoJowLIQE95S4oFwBJXqo6NT3g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-13T17:17:49Z"
  mac: ENC[AES256_GCM,data:RZ7CRaj8kcGU/7mhNpYcWn6nuOvOVJgkdQ1j6d/OiJzPGNMm05onclbpDMrcoOLA5ecHlpP/NzwkDOVX03uslclqxHARIPdf6pGScnXr430e5VqoRlS7pQj8G0qDoHiN5k2VEss9fDYTdZ6nsXPomjjvtxqSx6EbBt4fOmKDZXA=,iv:A7lP5vDnVZIhNbzNlGLwk6i6tBpYoIYhXrDMN3Tie8M=,tag:pwXidWzk7D00E/ZiJYC6Uw==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
