apiVersion: v1
kind: Secret
metadata:
  name: health-auto-export-mongodb-secret
  namespace: health
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:OCWFcHI=,iv:a5BDb0J3GOAdOdSQZ5TtQu4DOlOL/cKBUiGBRguV1es=,tag:tgPJm3GUS41rpXYUjgUkBQ==,type:str]
  password: ENC[AES256_GCM,data:uPCeUK5B5RIAFIeo+K0qR0k=,iv:z+S2tvoaco6WkHN6xtACOc18uyIIGVyqUsdN7VTVCzw=,tag:ANNFp9b/lY1MYJS2zkKjhg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBReGhRVXRYSzlYWG91dyt4
        b1ozOTIzbDJZMC95QzhOaXBHczNmWkdBUEY0CmQ3cWZIVGVJSFVieVRpOU9tTE00
        eDBHSDZWYytZanU2bU5MM1ZOandsNjQKLS0tIDI4aXhqY3J0VzhZcGFmZElDb3Jn
        bFFPRUJ3MWdNUUZ6cFVsMzd3bFNENjQKu/GwRfzbaIusk8kjFDxumX848+87gKF/
        iwsCvwvcHVFKJTSYcQf1GkhQ17EjtUGqtn1fX28u/JDLOeEHT6p0zQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-24T14:56:47Z"
  mac: ENC[AES256_GCM,data:dxA5aMlifHeAzzuH8dFhXeAnt3JdkbDr4POtJW8gH8WKbmoV7Fpp2YhwhrJB6SIJSgxfyGR8j6Uo1h+3lFDXU5TXIdTPZlRapf9oDD+9RXFIvBshtq3Wvw20/4ohO5PFOD7LsCij3tN6Cv8QOF0z9CwhcsUOZkOmuTB5VZXT9KM=,iv:0FyUr+EpRiYp+wF9wmTBjRVxbU831KA6ooLdvKtm4lY=,tag:7jlGQExco5TDTL8QPcwaYg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
