apiVersion: v1
kind: Secret
metadata:
  name: health-auto-export-mongodb-secret
  namespace: health
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:EPaDK58=,iv:451AZU5d7816T5Fhya/VVkiKix0LTgIJ+EtwNFLV3Cc=,tag:kMpJLsOb0LWpyWNad4L8yw==,type:str]
  password: ENC[AES256_GCM,data:kyTGJdLbp54Uwac4NTESxgc=,iv:RdTo0O9mDzlmb/hOduhTF5WdnXf5K+Q1b+DDotZNhsU=,tag:Uj9zBzg1c5oYA45J5qdUJg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUHdna2UrUE5WZUV5TXlR
        U1BLVjZTWk5iS0dnZkxxbC9PVSs5d0F3aVJzCjJmZTcrR2xkUUVZRHU1YnplR0tx
        MWVtOTlrb3owck9pREdyMWNuNmhOVzAKLS0tIHF3MEZ2TTlKL0laOHF2WlpPRUFt
        V1RQcEVvdjhBNGJza3NoajBPb01PSE0Kfbp7/MrIM3o5hLkOYqz72SvzBmKJ7XQV
        /TT/e3yvbqlhq0AK2sElDROpar+TZXH07S4LB18M2+m2SH/iVztwnA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-04T10:39:57Z"
  mac: ENC[AES256_GCM,data:djoeC7tZ7vGPRJrlTa+vPHoqvzrSDHO7q/SGPUjvoYynJ9349f7h4uVTaQNUp5em7vj+l5oTjm4ZaePMM7ji/MUAMZHFr5j/6hOuG7/IvoFEO6s8sbUq9kUYxw+84zKd3v1dIBLKxosg+VLFErOslW245SG8uqLv/rykLNFUcBM=,iv:CCUu6Drgu+Z3rhTJJXRCpeKgvnDP8JS9LamW8H72iUw=,tag:VqDhs4jKIMtXpt+PpGlC4w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
