apiVersion: v1
kind: Secret
metadata:
  name: health-auto-export-mongodb-secret
  namespace: health
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:RV4hDyE=,iv:b/gpCy+li1twOL8jx7Co6W0+/GJ/5BCZaUrlKiFqFO8=,tag:VzCH+CgM7EoAFxQxkEn5kw==,type:str]
  password: ENC[AES256_GCM,data:VDvb/zG+pgAifMNP3sH7wJ4=,iv:pHlg6JHqrcmddR+kWhUj1FxbZfdrqVBXQHdIbYDrco0=,tag:+b6BqOsY2spXvjIVbId9KA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVzZENjRyNkwvbVRBOXVV
        SlVSaWhIV3F2eVF6RlhTemtrMkt1aWFETVZnCmhKUG1SY0NkaTQ3MGUxdE9hbDZ6
        RmxWM2Ztc21zRjd2SFJ4bXpPK3Y4dHcKLS0tIDFRV3UzUGRIVTE5cGJHVDBjMmx2
        bjJDRDhQUHFGWXgwQmRLSFl1Z2NBMTgKU1UG4oAi4Mox3JQm/Ze+67Z4E337lTrw
        SVIRVK+HF9wdgM4Rtw8doxsuC8Ji0NWUNOeRYXjYrH+IIruk7ZfD/g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-25T08:51:46Z"
  mac: ENC[AES256_GCM,data:E9DdVX/FeoYflf09QhzLfSWQKI1UebZU+dGKsy/bo7ZV/dkrdCXPYiS1Qs7wKEAdwExYT7ouIIraFgSjyqMD9aE7YW89ziBnQRn3TOxt5GDxj+6WhzUbYMPYbK/M0+F2j5qNNxQkCgwcijnkKwimA8mjfbdPrFb3JYb8c9GVbwo=,iv:vhQ5gbbRx8/3k4a23gHh0J9qG4KV9VAjTlMox6R6jmM=,tag:O4rUUuXAuksRcEK9iR1WLA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
