# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: recyclarr-secret
stringData:
  #ENC[AES256_GCM,data:HzQxXpO9qsg8YALExQVJ9DGj1OlhUl7TkRMMsWV7dGWwxpzyUI3AyMtqYe71g240CpEamXgvm7YtZocfumrD5icMGpnEGQ==,iv:PN9Lz7taSQAnG2hI8GpywnL1PpuaBSajvdyJIeWFNrM=,tag:m6PG7DSmYds0bnq+9/rVKg==,type:comment]
  #
  #ENC[AES256_GCM,data:66CdVsiwzdXG/FI4brtCLL10G6n4U0OlskqX7JTYsRZZr7zTIv5eDk6rsIgZ2YbNZjfiCq9lq2VQzc4GtEYQXWrK2HBLnA==,iv:I208oXxvB9m5TqLxvH6RI4YhO2pTfCuXrHi9yatE7L4=,tag:5tdEE4talAzat9nVpRYsvw==,type:comment]
  #ENC[AES256_GCM,data:0NxFEgwoM7KjUOGJy7YjH2hAoGfF2K3r8c87km11rjC6xlJ+r/WY7zI1l2nkpPFlf4rFlK6K/8S5CXqgSMI2BiAJ/++GYPxe6g==,iv:38Q469imnzuUN9sOVo7pH3ZSzIBLxlblb8qE3j3Zc2c=,tag:fcoKMiFJ/Kqo1W7ClY2d1Q==,type:comment]
  #ENC[AES256_GCM,data:lvGd0Xeac4QOF3By9iQB+we8GTpXAV/xcRIMSQ4+gEwDMd6bUWHgZULg49uvxOI0beexkJ17L8P1xdMyzyb1,iv:Ckm/cV/QE/rg9lm0iWRJxLjZjT+5Ja5WIKDtIfulWgo=,tag:1CzPQSD7rfn8pR0ya4bVvQ==,type:comment]
  #
  #ENC[AES256_GCM,data:r5boqcz8YPpYLpwkoqWUNstcoiwqAA/JXJfhQNB9yOYki/TXxiCeh4pP8pjOknrwW/8AnS+vypBRy0s+2a3IKZEVWzlV,iv:5QFL5v3ZcMCt5NjVyX1T2MADYMH5QzVsnjm/awWOGj4=,tag:1eFxG6xwBjtqlTjHYfBjVA==,type:comment]
  #ENC[AES256_GCM,data:9UW2ZLBtETNL8HEOPcyjfB23HHJ3TuK9GVdK3LQDmY+nmok3Te59hpK7oBBJx0wykxprVwGrZkedrJtI4qpDxqnwSYKNHSyB,iv:DlJaopKTEoPd26HuwxXGu8MfgQwgiCDIIXqhmlUgK+o=,tag:r8f/Ui0xauNOg2xiFuZMgg==,type:comment]
  recyclarr.yml: ENC[AES256_GCM,data:J2ofErjoRQ+/VoOhRvWm3sigNhZb2w5HKYFM0so++ThsNizEKrDEuPOuYhx4ANCKn2XUTsKwplKDegMVxFE0qbXAXSOwTVZUNeTbkp8nKggF5V0b55MQ/Py4OHqInn+Kkl/LXCNpQ2JifCng76ffonjY8iYcp7e1U9XWExmlaSzcfg5XCYcQELAfK1jK3JZoFmFgbjVvppv+KZXUtooYmynpB5lxm/dk+y/78MFxedhOz4+mjTobjhQvMZLS0exxj62r3XEn0q+xMAw20cpoi0ZAqaLmnRtTBYZUbXQN/mOalyl1977hmzewYXp23J9PDzaKJlKicoVSPmv5bmuTLFFxd/DpNaDW+ZXqv0brX+vU7FDCSvzYFqQyEMWFw9pCB43F7vufK2g0mw+s1CCi8dSfscK1S8EQ4G/dst6dVfSx/4ZIEqlWyehw3ulvM11P3x47kpfZ1mjtVNxgt+EEXqohUrEnwcOCWIimKZWewFZ2U5mpvmwO54Wnc4LIfyTlLA+ouVyplu4qky6ToYBgr9JF5bBQiFHRaZR+Ovo8YEHfDSdpZneVAi4Q022aLSnB37+sDKD4L7U5CoznXcOle53Voo1tWT0BFgmrnJmVbd0r7bskFAr40tbxQp1s4ZqahT27MVHTeh1Y9hFiFjZTlYv8ES/bzkoucOP+VDOS67rktFKqj/UZLnj52LbNLcMU63czezvRfH3izief8ZPp//WMM15NGD2orjbpvAOE1P/reerKBqtF+EvqbEVWlT+W7a3PR16+y0bwX/KwErGLnmilMWK6fef4mGX3afArymZ621mrg6GTQGLGo6LZSRRd+N7+xNgXx3TKJ4NM4v4d/nPPLbpQ7Qwn+20n5b2Y,iv:2m07iAZ19PuQ1Gd6g0VaZhwYXzedN/1GOim64I+ny9k=,tag:8++jm6JD9zUawt92sjxtbQ==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVOC8vSE9KOEZ5cWJkNnVF
        WThvaUF3cE5LUndBUDNMVjNJbXpkcENVSURnCkgvZDR1Q3Rya2VONE5lRjhsdTY1
        YnlHWkhRdzRBN1pxOGx4RDRkL0JJakUKLS0tIFI4VDFpcFRCVWtRRVljMElhTkFh
        NHZUbitWYTczZDBWMnRNZUI5VzFRZk0KyWbc/VKX22rXsggt0petbj1yL3ITPfyz
        QgT05GyLKoguobAn5sHurXhJ7Z3XJmdezwAyGuAk+U4s5ktUNKZRnw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T15:30:14Z"
  mac: ENC[AES256_GCM,data:M9Oln4DP1TZ2P7VLPl2Fmpt1+T51vtagAmUfQyisbvJY7FcfRg6wAi5vV8B+45sBxk1OVAkNULIqGeaH7inHaPXlsseArveX4hZgBXmvvMH7PkGMyuQSWwftOVtgxfPM9JDuL3JBR+nmY0672KPe+scPUFP3Nhuti2cHkaPFeGI=,iv:4xpwDe7kjIys919uP+Jt1VBRWpsXRYLGyz8EsrCXO/Q=,tag:6RJYbc1uPA/Oawwcd5YSoA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
