# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: recyclarr-secret
stringData:
  #ENC[AES256_GCM,data:ZxcGce3xpk3TQKhKjmpGT9xC912vrA+k5sYsaQYsqWIQWDBWE1PrCjbHiN4BleLejhR/quC7d/zhv5iTlQ+Fw7td27FyXw==,iv:NCqhrbgbBU0mpWyLyE3GY8RyQPt/Uu92fGi4XQ1VIoU=,tag:Z/RVyKYD4xfzpSPkj3NMFA==,type:comment]
  #
  #ENC[AES256_GCM,data:U3ypy3FY8j9I7TFsc/19S4nJLFG+lugsWRogv1GW0EpYjRNhGpgVevr3g2uG2R+G0vaBhs0PHjUM9c1thVM4Sk/jmaC2Ug==,iv:xOzCgbBGAPcxTtFdm2i2wOoMvgKkQPNU5u/vrjiZv/8=,tag:RCU6nL6OupHzww/mYi4eCQ==,type:comment]
  #ENC[AES256_GCM,data:Ma8ETSFaSbphRnIk6KLCLLJD3oYdd6HdqlnaT42i2TdNa5Kvwtdg2XKBRGYoucbNX4pNq2Yjg67HuDasj0So6LAfnH1cqa80GA==,iv:0VAWy982Vq+tSu+GtMLw7myfLKOHv/zea9niv4/zSqo=,tag:e8Vv16e3Zsm6tKAv4xM75Q==,type:comment]
  #ENC[AES256_GCM,data:nRUjbc6dSObQhuZpa98P7QxfmbWtEvCb6aNTst8p86LGz1aKSpLDvg5nZbqwoTpg2QdUKW+hShwmZGnjjCS8,iv:/sT40O9iYtAWBan2anlKzroardk/aUN8isAfpa/DGPs=,tag:QrJCIS2PtQ5+HXj7Ag9CAw==,type:comment]
  #
  #ENC[AES256_GCM,data:7Yj9gEjAgRqHKIeAGFGqwev1knc7f8md1vDFenONVriScu0hYV4Q2S8PDErGTsP8fRLYx7MvEpPRS2CXOUHKHVSlNYaW,iv:XvZdjIuxA7NZQuj30cZ6kZ5Thka4irpLvV8cZAElmUg=,tag:EIExfXQs4BqMZnppEmaqPg==,type:comment]
  #ENC[AES256_GCM,data:duqFdXMnfS3fk3i5WrxBlMev1tQAKUbTwR7WLrCOjhR28BNsxILBG8KyC1PJFJ0XbLPtQEw2XTSC58kXZ9YEDIBoFZBD1Ke3,iv:FT5ZDt9QxlNtLjj3a3v5JhUl5njRdAO1lpeF+n6cz6o=,tag:JjArae5IRSeKifNqw1kLMQ==,type:comment]
  recyclarr.yml: ENC[AES256_GCM,data:1oPvJ1YbNG+tSaQk0CCF425wpsux6Af5YPCAVnPIphd75MsPGOeful6unFeYiBGcvDLeAVzqX5sZjhnSUbbZ2G2Ct7osYrRccxykID6k7PQ/2KTHkhfQykAln416eZffJizeJdI0qKBC+cPCpLu/Y3q/axBhRUxf6AieoamseX4cS8kL/4uiL/O85/7jmhzeoQjQjiPTKaF+tUSs03kedMbqSmn0E5Dt/q8OngrTRjZUdp/z2jrNrjUJ0HavuG9DOU3ocCtdLAAYM+karSYsItrN/evYU+D+lkID9BizIrSzjuRRPs8hqsstQIKZZXKSebgLsD2kCQV3+n8K1my6WjqV/GK4pjkaG6uRKTcSTeQEIYNi+/64/15ocTMXEE/ttLIbpDrK5Y7Ak9qOJwPAb0dORUU6Q/Hz3AzuvQCRDY4E+xF76ODNYaSWKILQ0VQ2OBWMokTuoXXAmneN++aQMKqMTSKdoF1FH+6amnCKg2Pu7s8c+Hj0o97+FsUEHqDT5yq0/YBCffs1sLXk5j7sLQDDWoL5aN6+2sR+fXpJRvi5yGQpNMJC9jjvKKfOmSFnm+nDYUPvIJeW+5fiYcGUU1Id1lQh4xwEu/Wl41DvtHrrBvLX/VARvkCK63dE6RBrbbuP8XR5XG7Y3qX2t3sDpBxoDg2plzsLZNWUctl4aVItMKVykbWxC3MSMqzaWjgTZucFVyOZP9azlTwuM0lCXuO90bJsq3HDE//Zgo0srkR1D4uHDxPpQpbKw7OO0BkenUWz+F+6IMSqlSH5lDbd/NmYlMoksSCzJbMwXwU+AqkGhNKlzZkoeNkapa9fEOURwGhToQaG1l8NUhI7ABmK1aUP/ecqJSkVaZvCi5myfAw4ljxLPxOH+tr0sMzK/mV/5M4hJP04+pcwcD0JnbsuoJUtfvpj+yRzMs3yzkAbdQvZKEnjLXU=,iv:JVAoFCr6AdzuLVRFbFtdRtR0ADyP2g/gGKCddgPfgek=,tag:w4R5CWmsuItD4rztmc9cBg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUHd3dEUvVERDSkFkWHVk
        d3BQaHNRSlQvU0VKUENDZGRWeCsrcU5GTFdjClJNZVhNVjF6aVoySGdCazJyQkc5
        aEg5NGgxQWZiZ1orOHhZSUpTUC80cXMKLS0tIFFlKzNKbTFTVklIVFVVT0FIMEtB
        RzVOb2Y1MXZLdytCaGt5UlhNR3E2REkKmwsGeRhMaMSHtvytJ0BJ7raIGqWc6Fl0
        kzhoqgEbFBCo5+rZEpDBn4L2Ff3kHZWX2Zb6EgeKU6eRbIsx66ORWA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-11T11:52:01Z"
  mac: ENC[AES256_GCM,data:tevB/jNhEiPJzjMYOV2MiPQxNxDi163FT97Am8Z09h6T9sQaxwA7YUZBP3NCHAxWJgAT0lJAQeG3DQTp/PDWXQe7hnQxQP/XNmUotnUnrPOuWQCSqCbrXs1Jev23ceu8fsEHKbZBuw6mG53qvFW5YliDfEaJBy4iZS3/mWrLwx4=,iv:U53TABGqwVx/rHY6TzzRw7JxvDJGgKoC+78ejZo/OTM=,tag:9lB53fBzIIP8tZlusn+q2A==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
