# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: recyclarr-secret
stringData:
  #ENC[AES256_GCM,data:8OlD5irJdKmsDXRuVfLDc+jkM3hECz3jsXUq4PoB4RCHDP5dDJRnKcdr/k8U8dPBGfZeqmk6ybyQch3DlmLiEdXez+3tUw==,iv:eLM1sV9gBb2rHQHpxquFZMZ8NXj/NhrCIEUuoobMyVM=,tag:LEq+0W/kpfYo55VdstogwQ==,type:comment]
  #
  #ENC[AES256_GCM,data:Nsv3EmQ9LfeWRunTyPyOOSK9NDwh2GsKwRQFAzb7koX66Z3lBvxhcu3od0Mp9EzzjTD3gBZgwFC8isRGQ3zkAxLDhryoZg==,iv:0uzXaTvAkiUqhYUtaje1tYolrAQ2xUqTSykDHI8/3zE=,tag:sA+2xhrGYbWWgNPq26XbIw==,type:comment]
  #ENC[AES256_GCM,data:XJDXYv0c0I+GE96iyUlCQHVQnIsivJkg9BiIBG/6JP14/KT3xUWXyP8VbcdGUMqUEwFjiLqju20PNYvHecwEPjgApipYvS39fw==,iv:qohY8hyhoF8UUftYiuY4wt1iLEvrzbpTLfAtZc2hJwA=,tag:3rPMislGK4s58CBHFxm0XA==,type:comment]
  #ENC[AES256_GCM,data:TUsnG75Lx6eqgRLJY3Kuo6Y+BtDhyw89eoYZgr8MSIZSYHEhsTWMSXSKDqyOKUttdVHJj7b8T+YyQNXqdx+e,iv:20QvItWgMp5T9b1huT6gtePY/NrJqrX5uKwqqGIdIwE=,tag:Dfdm99fxFrkSGHANWeHIKA==,type:comment]
  #
  #ENC[AES256_GCM,data:AircU4ny+B+5T+H+5UrzFRSIU+Vh004o5o1ovj3NPTN6PzdQfesRmmKv4pvACuAHW/ZRkm/xq3yWvBHM5Pb5CAIyCMkC,iv:YBYLSGoWECOpsfYZ5qHtq9/X1bNRvb5RL7QDAS0jrk0=,tag:80riWV8ZGS7f9XdM8poP6g==,type:comment]
  #ENC[AES256_GCM,data:qwyL+lX91eHlRhUYnRf4QeTeAVNVR+cixxkCvbwhQx8ER/llbcbk+JbS9zNclZ87dl9qYv0gQyd+UUd2EsMOX+lUOZ+2I/+N,iv:8xoEerqq1qtqxo6ZxjU9MgG3GbRqhX2f4axQGSwKcsQ=,tag:feP9kRl4cZ/XKXCjHtWUrA==,type:comment]
  recyclarr.yml: ENC[AES256_GCM,data:vlT2co0z9mPu5GE0kLMPDLyg+3MPmLoCbxm+kACNcXOw3IJlNgusz4oNSWD9QJsvIfD9rOU7eFahJ56Q8GooSz+VS3KkM4fqaUI/VNr27QpUNV4+BdwYL8vtHuiyRzYrstEnqQ5O3e/NRNKHF9MKs5Ts7NbU2gR26tQwbMOLXDLZgwuQFZw4Nj+wP0tfZ6ze8LvL6TtiR9x6WZHfJN1AbH+fcZ0u/dTjwOCQ7hPVmt71vCdwHgrwQDoe1lfeRasxX3v/AfP9v3XLHsCsylmIcqIvamZDBBQjn23qOqWcusm79lUL+uVfh37LJDfD0anameisrVrMyrjHirjxaOHjCg/HefPbT7Ffl3OzZLHvC6PN2BLstNhXIQtdQ69rkSZ2wrkRqaW1/BM/xLDzI3abDIgf2tWl3NUVgSK8+ChduHBQzqxSmyNDWSLtbWn+c12RdimVrZW00eaEiELjsZfxwqBT1gdalfAp/nxGnMYWz8Qc4+5IS6uB6yEk7l/7V5szP5rZQe6WaSeauNKxyr3hJbkhyrWE0QedspYiI63GsH2KGjIIsbqbepEOVB6T7PRWeqdOzS84lzx76MWeQCAZ0xbx4c5jzOak31DvS/qBdYI+KTv0ncAJN132KHQjK4qoezJgXWo99dII7C01pR6oeR6pyUvSrtX33QsX87KLopRKTZpvbzJ/Rvuzomh6xK9PD2o6lle3SJ5vbd6fz1h1LjDKxzYRIbb5gOGCw+Dfef5L0N2QbxhRKb1nLvIOrK+KI9jD4lbjoK75rMNQMQK/qeYqIpxK2ACai2Y5qGE/I4XszAypZRoDRjWgBAYndryqKoAldSbhp4VOprOU1wfM4CDpYcXRFOypoVlFq5fnjhfOXvcA6tX8NjUNdIkwQP6kQmCUXTBwoxefDO5k0G/25BWnU5DC8X31R74N/Wp91JWQzDatBz0=,iv:+P8UWVT6F20eAqrvqHuA79crckkTQIjj04dthGRPT94=,tag:QDC2/sDcZ6JQ645pFXcp/g==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MVpMSGJkdnBTK2JBTHg0
        WXNha0YrUGFJV0orL3Z0ZXJRb0VvYlcxRGswCm5Qbk1GMWNGL0NrS1VtT3NnbThL
        aDdUaU1qaitzVHVNTXM2eXltQTdzMFUKLS0tIEtCRVM2ZlZ2VExWUXFYV0V6Q0xo
        VDBuNzEwMHZQekNWbUpGeEQ0TUE2R3MKDWolfP0sUxrodUi9HRUlBu3XpA0rtm/1
        psePHT0H81p3dy7MmQRt7ZXDUcjs9R3KyMyWjH3x3sLH326MzZFrSA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-04T12:12:34Z"
  mac: ENC[AES256_GCM,data:wNoN7sdzy93fcvxC+SH2MBkwsEXnO6hL132th1lIyba6UFVx1Dpekho3dBF5tK2ChhBaZBebuVmLz0A4VWf1HEM42CbPkZThxyB1L7ssLiKclhP9rWiD7/IkvruT2VeLAkmEPYGIQRA74KZyiL7ZtpfEYL7RcWPxON1IlBKZvwk=,iv:JxugQDJREnljci83DBvlDqaJfw4UMDXF7ySr62I4pgU=,tag:laTDmhsy/SYGfacar6zejA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
