apiVersion: v1
kind: Secret
metadata:
  name: authelia-secrets
  namespace: security
type: Opaque
stringData:
  session_secret: ENC[AES256_GCM,data:4utyfnlB1ntsP60eeE4PRmw+3ZGbjEtI36W+CZq4mvvGhPXZga2FAEU4G5nw9FDtk3tCq0/RtwexEA7cd0DtYw==,iv:qjvgTVMOrzB4SP0oG0WCJmR5AEqfDbFfG+ukvZEmsc8=,tag:3wk6YNiRoKYc6bE1VNFjWg==,type:str]
  storage_encryption_key: ENC[AES256_GCM,data:8bBNiHJvGbYlZIvoWlPh/topzyJ1juCdyQNrM26LRGoOQQx+1LFakQAIo5NeAEfNUu9BA6WkS64EKb3NRQq4Pg==,iv:IEFNu6GN+SNQSWtg14Fhzvejzq4eU0WlfspApHD9jkg=,tag:/Zn7uZMt5N3UpCu8ubgjhA==,type:str]
  jwt_secret: ENC[AES256_GCM,data:2GDk/c3sNZt5+fKVKSf01HCBbpKYtNjCqhwZ/8HA6Lv8io7gH91onyViQtpSgD9K3G40N95IMnJbNRe7jSsBig==,iv:trK95Ng0uSObORG3RFj9asoZvZxExSXMVEQuVHDN6YA=,tag:IAlfQRrDjavsU0gGkn/Baw==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkeGpUcDdDeVIzUnNpT0tN
        QXdEMndJdU9zekp6bGoyUlBRYjhTK1RLMFZBCjZxYjlGTGRCdGFCRmlwWHZvN0tl
        T3Y5U0RXVVppZ1grRXIreUQxa2RRWTAKLS0tIEovbU5IeS92dnJBVFpIR1VwVGUx
        NFQ4WGxwdTYvZkRZYWRkVmxVK29GVEkKm+c2lPO7hBmCe4SdlbWapzCGX4JXJgRV
        CrqgexySMT+vxRjjbwKlaJr0xbROcNib1PZvvOZgMgiX2+RvcCjXIg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T19:07:08Z"
  mac: ENC[AES256_GCM,data:oYqLE2l+IcJCdpFksttZtZG4dMugCH1DPHczXOrVfm0rdDbrG4kVx7nB+iOZOvAxZRk2lsombqjTvKUl8xSHq15yPk5J+UwaNZAuR7lOCti+6B0uTZhiKX1XrMxWwUIZSEIZQ4GR2/se4tld0/9hntOdMOHFnL42o0fhYfOyop4=,iv:vnOwM4fF9C/fvexpPvSJx+s4nrJhdz2b757v/kqk88c=,tag:9jcDxekDHrVy5ycB7I/taQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
  name: authelia-users
  namespace: security
type: Opaque
stringData:
  users_database.yml: ENC[AES256_GCM,data:uVGhHaaB6SFUE6+sERUrwOCTfmHzIPL/BL8d6iFc2Pgtq9njYi264W+HPOImWI/R+qt5FQOwBOANzafVODLYmScMuqRpIFd4QKjvsNUQm9gj5SGOdUOdnnLY1NocjuOZUHBglRK6lhY8W/AluoHfK5KUyhors8qwh9d5hfYXgxOooOx39gnvYmw/yrJ2pMyLEvDGx43UV8UXIqcAAiCRtj6TkHqgFJgTsZudrUd9lnuCjZKl5AoSoPjr34nerIvM81V4/z0fmtzGd6gcnVkC820VscodkyEkeHKUksSi6MCzblanJ38T0hS6,iv:qAmyuthadYbSvl5G8jLmEutb64IXU5pkBYDy0dGualM=,tag:bU8KHZZasNxE7M7vCYiYHg==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkeGpUcDdDeVIzUnNpT0tN
        QXdEMndJdU9zekp6bGoyUlBRYjhTK1RLMFZBCjZxYjlGTGRCdGFCRmlwWHZvN0tl
        T3Y5U0RXVVppZ1grRXIreUQxa2RRWTAKLS0tIEovbU5IeS92dnJBVFpIR1VwVGUx
        NFQ4WGxwdTYvZkRZYWRkVmxVK29GVEkKm+c2lPO7hBmCe4SdlbWapzCGX4JXJgRV
        CrqgexySMT+vxRjjbwKlaJr0xbROcNib1PZvvOZgMgiX2+RvcCjXIg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T19:07:08Z"
  mac: ENC[AES256_GCM,data:oYqLE2l+IcJCdpFksttZtZG4dMugCH1DPHczXOrVfm0rdDbrG4kVx7nB+iOZOvAxZRk2lsombqjTvKUl8xSHq15yPk5J+UwaNZAuR7lOCti+6B0uTZhiKX1XrMxWwUIZSEIZQ4GR2/se4tld0/9hntOdMOHFnL42o0fhYfOyop4=,iv:vnOwM4fF9C/fvexpPvSJx+s4nrJhdz2b757v/kqk88c=,tag:9jcDxekDHrVy5ycB7I/taQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
