apiVersion: v1
kind: Secret
metadata:
  name: authelia-secrets
  namespace: security
type: Opaque
stringData:
  session_secret: ENC[AES256_GCM,data:UnIlBSjvNtVKwFTRfrbuvEfPLxgULnmyVnFumNQIPh6uEbWYP40Sa8iLTokpVYbe2DVZinIGdPvGG7E3vrfuew==,iv:Wut9VoksWHbcpH8guhxMXAslRZqs/3JC3uqb5KQeea0=,tag:w8tRatnMgK8Oj2l4GgJn4w==,type:str]
  storage_encryption_key: ENC[AES256_GCM,data:dM/Ts8SPyraSTR+slrTzR4M7Kvm6Dz0INlGfDxwaVxCMAV3r/vVWtz1U/Aawwmm7BOT2bVL2xNhO2caIUhj44A==,iv:qOZYnNCbUJR78923QI3747Q+aFqyNrA/TdARtAK3R7I=,tag:n811BRYnaP+jF9YZjB7HgQ==,type:str]
  jwt_secret: ENC[AES256_GCM,data:DqV4yeFFq1MFNRp4ViyMN99jNtnpFBt+AaDL94CIjEXccHKlGbIRwrTvSW9n4vCdo0ePo1P8VlXve6C2WS/S1w==,iv:KAjpS+tPjWW/bGt6lut7jpbWR5LjCeoPAwo9MRo6CGo=,tag:iixXyEYYGouiAGQmB/OCFA==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtNlV4bStaeUppdVZ3N0Z5
        REg2aDdma3F1R2FmMy9ZRU9Bd0ZZNUttK3lZCk9NWTJmSjIvUjMzWXgxQVRvakE0
        RjhKaWVKZkcreHNyYmk1akY0U0xYTkUKLS0tIEh5MTBmcG8zSmZLRld0WXY1N3BP
        OWRCY045L1l0QjExNFRGMTFVQnNKbFUK446JkB/aDcq5OKFAyVWoOZPbByzbU51R
        Aetg+wimkMiajCyuarm8z+SIFXkopm8QVjP1cTCT7vR7XNbmIJDuEg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-17T17:18:47Z"
  mac: ENC[AES256_GCM,data:0bfqLjwPMYJM5T/jfy0cuwDtWbyBPZifx5d9vijTFOHTUNA1VgdkcnavzoLP/K4+zR/OCtAvPJVgKR6aRFKSEtOaplaF+Su0lzFNMh/hRIHYWIaIiZ/hN1lig01MtEUMLtUVg2kcN6V5U8oWiB4XKh9rOdxUtCEPyLC8sTufdvI=,iv:r74liVINLy+XeoB6tH83vjX2VvlSQCtt4jXlXVFuu0k=,tag:ATfn1Dy9+0KrGe2KRsMsrg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
  name: authelia-users
  namespace: security
type: Opaque
stringData:
  users_database.yml: ENC[AES256_GCM,data:lUlhq9ryqEHFqMPK0Q93AakUxpRn+McrrWgCzDjdvq3HEWXTqCfg3NfGgoyNIYkpSmsJ+BGJSJbm7WbSzdHkMb4B8KYBT4+cmobXG7n4GSEdBy71HUbQqDCPcmrLYRYOb9CPGrHvYQ00V1m/80Yt8WHGwGT7+/c35EUZpAB4ItYV0JnLX7nFUKnhPXKoakTgJBLLGTt5yiTfyHlAbYKVVL3QzNBOFcH5f6Ccrz07vDLMQfPgxKc0kgjBRy5nH289xPFwKtJrOIXtVFTbE4Ne7qGOYVEYfJNHsnSy6fFLTFetK+AOBzMKfSAy7QmGQQdQMg==,iv:kx2jNnesuz5BnXVHaGh5eRPvkg4HFE4znltDj2QSSc8=,tag:SN3Z9grch0v6/IFM42/1CA==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtNlV4bStaeUppdVZ3N0Z5
        REg2aDdma3F1R2FmMy9ZRU9Bd0ZZNUttK3lZCk9NWTJmSjIvUjMzWXgxQVRvakE0
        RjhKaWVKZkcreHNyYmk1akY0U0xYTkUKLS0tIEh5MTBmcG8zSmZLRld0WXY1N3BP
        OWRCY045L1l0QjExNFRGMTFVQnNKbFUK446JkB/aDcq5OKFAyVWoOZPbByzbU51R
        Aetg+wimkMiajCyuarm8z+SIFXkopm8QVjP1cTCT7vR7XNbmIJDuEg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-17T17:18:47Z"
  mac: ENC[AES256_GCM,data:0bfqLjwPMYJM5T/jfy0cuwDtWbyBPZifx5d9vijTFOHTUNA1VgdkcnavzoLP/K4+zR/OCtAvPJVgKR6aRFKSEtOaplaF+Su0lzFNMh/hRIHYWIaIiZ/hN1lig01MtEUMLtUVg2kcN6V5U8oWiB4XKh9rOdxUtCEPyLC8sTufdvI=,iv:r74liVINLy+XeoB6tH83vjX2VvlSQCtt4jXlXVFuu0k=,tag:ATfn1Dy9+0KrGe2KRsMsrg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
