apiVersion: v1
kind: Secret
metadata:
  name: authelia-secrets
  namespace: security
type: Opaque
stringData:
  session_secret: ""
  storage_encryption_key: ""
  jwt_secret: ""
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ZjdldFBRN29hek9aQWpV
        L0xvOVFQVVd5YmNvQ2VDTlFRL2NXL3NmdzNJCndjQmY1Z3JtbEtENW42MjZVdUgv
        YkFFMndCOTJKeVNldHVNTlpKZC9xcjAKLS0tIGJ1aWd4VEZFdGNVK1JMbWN3d25R
        UDh0SkJ4TDlkdjJEdE1ibzEyYlR3dkEKl2ciehVviXW5f1nU/aHRVw3GX7EzJeS2
        Om+juKjRuathn7sOhiLKF3v66hXYSBzLWNXfXt40y0/0wfmX1oXQxw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-17T15:45:57Z"
  mac: ENC[AES256_GCM,data:O41pnunAqutpTYnraH5eCVdAkBCpcGX7eET4GYnm22S4HIdVNfF+q6fwOcqeeZVurSsDUIOnIT6HW04fiugcrSHACWRX4g3MfGK8lALFIQHc1/RmYlEkGZDLUgogC0hMa0xMtK0Nd6HmlDK25xscY+jHv/bCuqDG6PdqCbvojyk=,iv:4AnHaf/VvmxHor+66v5nxI0P5k+tbWSFMl6DBnoEKeY=,tag:mPqDVimctIlz4bwUCG13Mw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
  name: authelia-users
  namespace: security
type: Opaque
stringData:
  users_database.yml: ENC[AES256_GCM,data:2kOMjNsG/1TJpko13btQIJUnd6lQ0pfDuzB0Qg+u4MF/xnGBv5VQwjOPEGpXFCAz9Zbt9Fz+mad4zT9pJYn6w/bCm6ny7BcMt2+iHg5oceUV85YiFuz8JMMBk3Jej1iv0Eh0ZdpVZmLAndr7WWNgTC+aMKbuNocXVFfKK/WDRnrDsmln5APR3Ke+2EjbKwjW,iv:s7SiAWVrEvJeNxWQbkFrkort0suUja7Lzbm1Jr0IMV0=,tag:+BS6Y8oZF9aS2CwJSNf44w==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ZjdldFBRN29hek9aQWpV
        L0xvOVFQVVd5YmNvQ2VDTlFRL2NXL3NmdzNJCndjQmY1Z3JtbEtENW42MjZVdUgv
        YkFFMndCOTJKeVNldHVNTlpKZC9xcjAKLS0tIGJ1aWd4VEZFdGNVK1JMbWN3d25R
        UDh0SkJ4TDlkdjJEdE1ibzEyYlR3dkEKl2ciehVviXW5f1nU/aHRVw3GX7EzJeS2
        Om+juKjRuathn7sOhiLKF3v66hXYSBzLWNXfXt40y0/0wfmX1oXQxw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-17T15:45:57Z"
  mac: ENC[AES256_GCM,data:O41pnunAqutpTYnraH5eCVdAkBCpcGX7eET4GYnm22S4HIdVNfF+q6fwOcqeeZVurSsDUIOnIT6HW04fiugcrSHACWRX4g3MfGK8lALFIQHc1/RmYlEkGZDLUgogC0hMa0xMtK0Nd6HmlDK25xscY+jHv/bCuqDG6PdqCbvojyk=,iv:4AnHaf/VvmxHor+66v5nxI0P5k+tbWSFMl6DBnoEKeY=,tag:mPqDVimctIlz4bwUCG13Mw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
