---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-config
  namespace: security
data:
  configuration.yml: |
    theme: dark

    server:
      address: 'tcp://0.0.0.0:9091'
      headers:
        x_forwarded_for: true
        x_forwarded_proto: true
        x_forwarded_host: true
        x_forwarded_uri: true

    log:
      level: info
      format: text

    telemetry:
      metrics:
        enabled: true
        address: 'tcp://0.0.0.0:8080'

    authentication_backend:
      password_reset:
        disable: false
      file:
        path: /config/users_database.yml
        watch: true

    session:
      name: authelia_session
      expiration: 12h
      inactivity: 2h
      remember_me: 1M
      cookies:
        - domain: jgrecu.dev
          authelia_url: https://auth.jgrecu.dev

    storage:
      local:
        path: /config/db.sqlite3
      encryption_key: ${AUTHELIA_STORAGE_ENCRYPTION_KEY}

    access_control:
      default_policy: deny
      rules:
        - domain:
            - immich.jgrecu.dev
            - nextcloud.jgrecu.dev
            - kavita.jgrecu.dev
            - jellyfin.jgrecu.dev
          policy: two_factor

    notifier:
      disable_startup_check: false
      filesystem:
        filename: /config/notification.txt

    totp:
      disable: false
      issuer: authelia.com
      algorithm: sha1
      digits: 6
      period: 30
      skew: 1

    identity_validation:
      reset_password:
        jwt_secret: ${AUTHELIA_JWT_SECRET}
