---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: authelia
  namespace: security
spec:
  interval: 12h
  url: oci://ghcr.io/authelia/charts
  ref:
    semver: ">=0.9.0 <1.0.0"
