apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:CD5lF6F865XuIj4AQvcX9m7i/pSgsYzHG/rr685yKs0=,iv:EzQFIWgJXHS4ch02ZIKMkmbWUX+CQdEwtXsRJv8O/bc=,tag:5Y2JBdWDAS0MlZXwc1YdsQ==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvNG9YMEZUTDVsQ0NJL2pG
        Q3NiQjd5RDJISU43MEFFQXlmbU44NXViOVhBCmhWSkJxZXowcTNJbU1rMnBVS0ds
        Yk1FK2NoYzF3TmcxaFIvSXZWTkc3OHMKLS0tIHhHRXZpMURYVDVLeFo4ZkxSVXkx
        cllJS1prYXhrUEZQcWRTcTNhM0gwSzAKN95MbzqHsyqDid8DuVexN94Bwk454ubq
        z3CLv7BltJpKBAHQQ+miuvvK+xAQx8mUWdRu20y1C5enBcRQESb8PQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-21T09:02:45Z"
  mac: ENC[AES256_GCM,data:Aahq8S4gSFmox10akyGNI+VxGNFBEWWHyG3li7wuPzLSoBocTOWFGtdid98V76oK6bWjRiYZVSIsI0aiqbP43fTHvBgIEoJiC3hE+AsvGLwb8RNo3eiT9IHRHi3e51voq24k5gK1dOYCuzSQ/0b6WQyrHGSydDa7g/oc7ojhdDI=,iv:dP8877QR+oNkYkb7DmPBCYYQji+YQtQccMAzTJxhvk8=,tag:PZn2KowVYSuoNU2j67sxaA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
