apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:H4coYb3X6LNkENdyAiPnvx8IZOdevo0KPopDnhzlItkXVA/V2KnFpw==,iv:+4K6klXDrcH2d846YGcVtmFj9fuXcW1jaQZzOrl3qmY=,tag:2fGXsSIEg3GUKwM/fBWArw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMVHZoc0JtKzFqSDR6MUtJ
        NEJVN1FKSXI2WkdmNFpzZXlPNWordzNKZkJVCkxHWGJPaEM2SHduYVhXemJHZWhU
        Y2hXTXB5RTZYTkFCWGI1clorWXlLaVEKLS0tIHNOZGI0Y1I4azBMN2FPbzJPRjhC
        ckZURFoyMFFqOGpvdC9zakllV2FDRmsKa0iI0Qa+0yin1kBVuTNOjG4tIiiYsK1t
        xjAyAX2e5bIjbyahQ0VpJ9gvA+b3BfrRUxjH/mKcXZ8MbRgnE39dig==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-24T15:38:30Z"
  mac: ENC[AES256_GCM,data:mH3LTYv+Gp0WRAjGw+vC6zLzzwqvdS2pGcWczqnGC/8kCetVluNkOn903MXMpOajqladgGRUE4QOii0/EijQrUgwQLtNBa6Nl5IqfFZ6IMhtJpXe5ckv5dWEduio0wO3Gcw87OLggJTceTh78+Vf0FDLxlR+tF1CjHHqTEOBfTU=,iv:E7zBkBC3BLg87YeM8U5P1tfmjzvzRkAxaCtkrqsCnho=,tag:vSOZkA3SE0PrEdqrYrokgg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
