apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:CudsKVqFOS830dNnj50tHAiN9TOJpmdwLx+81N1bOSg=,iv:CalOM5dfZqhiPNfdWx24+rQze0V1rFoZoEvJtmlKqjQ=,tag:2I46otJZVUSXmnn1RZLxPg==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrSTRWSFZMVTZzMExucXpz
        QlY1aGhTeWJEQ2xmR0owNzl5c2RjT05VMWlZCitlN29jWmdrbmlqN2pvR2NBTFQw
        UHpqblM2RkV6YUNVRUNZZW9PQ1Z2bWMKLS0tIEJlNEtNemlUZ2Y0THByNFZlRUdp
        WXFjN1RaOE04cVN6SWlFaUFkV0k0RWcKKztfHIxWiwFOFYue1juqsxrY4VJj6a0X
        lKeUVd7RUsqynt2DG0QW9xnaEshei2MN9+NPsCHCJ/OhF22/iOCuyQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T16:38:04Z"
  mac: ENC[AES256_GCM,data:411Fki7qI5ae2ZCxWXZT1EeFCS/WgGvI+jJtWawsrI1uKE4wqNESNdwJ7xOABEaPpWWvExaZLPYdpXnqWA00HEhtn1sZ4Q02uPyJdxYohRaX+6BGwofLBIVY6JBB5uZPCZ0PbbkfNFG2dyOyKor1re/m1mEsKzrtxcvUNMay3G0=,iv:+vMR4JFCzb8ETysD0obxSZSdYaNV4E8JMUCBtl1jVOM=,tag:wAMwSH4+aFc4ip1cV0+AqA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
