# S3 credentials for CNPG (barman-cloud) to write WAL and base backups to SeaweedFS.
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-backup-secret
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:BiTQvX/iEu49ze+8NF7u2I78U8iIQHxS,iv:Rxgyvb0jR6jhERgisCjskpFntkbhZ9zlqhVvXt3qJvs=,tag:OyhhVSHCKP5uVvJF5t53Tw==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:9Ezcb3umShlk4TOHZx703dWpZI8J8ganB4zEIyScjadShmIr7HDhAdRnS09axaAZ9HVEcWcr4Y821VuPHHylDA==,iv:byyPbjbzGPScjd31X+/dawuI2L+Bv67YV6VV4w5jJ3o=,tag:DKBTUlIrSQ0JdhfrHor49Q==,type:str]
  AWS_REGION: ENC[AES256_GCM,data:aJJsLbv4s15i,iv:ctE4kWL2REGTgxyxzlldFnwX9SDuVIpJXzcBqw3h6T8=,tag:KRxktncUl482QKkhSAEo2A==,type:str]
  AWS_ENDPOINT: ENC[AES256_GCM,data:Oogd/YUPJmueXaUPscgBJoBTu0atrGkVfkTGhaMVXOK2rDJ6RwPqSmD0/vObXL0TsWFXRLY=,iv:Zq4kohRO9OmohP37ON7//kMWao35yV0Uy4JQMNE/Uz8=,tag:FV9ysOlXwR0WLbcQA1QRCQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMm5oZjJhMDVIRFZvMGRJ
        dHFmTzhNOXVSemUvWUh6TTFPSjhzM2hMdFZRCmdjS2krZGdkV0hGdXlnL3BwVGxa
        OGhnNW1yVldBb3YySlBFc2hmS0xram8KLS0tIDFnd0ZNOEFuSng3SnZzYlA1N2FE
        UzlBVGp0M2lTL2RCNFFCZHM4V1p3OVkKorY52zSKuzv2bHOvr4R3VQIZTUfrO/Ce
        jYJssaKU6wEiN07ynzDsBUMNCDh1gcOz76VkVu9cjUMaCLSx8gQePg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-17T12:37:07Z"
  mac: ENC[AES256_GCM,data:IuwuAwZxydxbY6Jczns1n4HhKceATt7gn5roCoIpdSG4bY6OxUx7dI6YMRjqcYME6iIV3DfW0tVn9z1aboxaOM8DBzldheQh7nV+CZfzwWqQyDLOPrk4cf5dmEr9sOaN8wvqZntOqhpbf9LXG+5iTY0Tm3T9fpOJuEbZj/ezRkI=,iv:XyK+hVdRLRTzL+5InE/nCZV90M/euYDgUiQiYoKaXLQ=,tag:Eta1OHiLphzFoGCnR0qlkQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
