# S3 credentials for CNPG (barman-cloud) to write WAL and base backups to SeaweedFS.
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-backup-secret
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:LMMNJOdu9/kucYrTvBm8JxT9ZvekrbA1,iv:uGpj5hiAKeDV1+bI+i7zHVUeYN9xMOOQoQ4ihhRNI/A=,tag:XucnE4BZu/B8vfzemKTKog==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:OLJA0enxw+cP2rTGjKgwSc7oUrkvgJyExL+JcW3qfcI1aG+bPFjkRrBkGWiEOuJfVA5DaJcI9CBffZCgBcOZ6w==,iv:UuVj7ATqbZBnl0ccDHUms9EcIatgnxqdDl1PCkJ2DeE=,tag:Cu5TZoYVPQrAqex080Hdcg==,type:str]
  AWS_REGION: ENC[AES256_GCM,data:ZJUvOeF8Yjr9,iv:GtNBRrzmmkkh/tWVJLarDYsgF9tMp2+zyizPtbv2w5g=,tag:UKVB8EkW27j1hHGMWZZ4Pg==,type:str]
  AWS_ENDPOINT: ENC[AES256_GCM,data:89jQ9FYzvXSgF3dTbdkdzNyG4W/lP15S5w7FzqtOlbvTtDHqC+oZ+F0R1gY/MX/AoaGKrP0=,iv:q+VbivgNH/ko+SAMFwjXetCV3zfC7ctEWXsKKvZff/I=,tag:U+6esjKSLWldHXdpwkcTQQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOYjBpdjk4QjUzOUVnTkNX
        LzAxT001YU9xWTVlZ2ozZVR6dC9IYkxBd2pZCm94M3FsK0dkVlAyek9LcjQrNzhh
        QTRZMldSRFIvbS9RRlVzY0xndWtMbTQKLS0tIFVuT2dXM2ZRZVhaQlhTMldreENL
        RzA4TEU4dmIxOVRRellxenZFbnY0N00KJhwCFRbF2/xIEHt7v8TypQh4rvAGg0Qx
        +JhdcocskgOLRsfSVxQoytsIYo5m1+r/VL/g7oqDuKVZ50ZAPItXSg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-30T07:05:45Z"
  mac: ENC[AES256_GCM,data:WhgHecSSlHRxKPHEX00sGdnwI9CIFHtj9Na21/DtziouukrHqW0KrFeCRNlyR/abYcveKBf4/zMReLAq2vyz/BMkJIYHnPXz2/RCb5aoAUlhPt8aDTJLlfu9SEbNrkFu6hE6+ieq2iidR2x5uaumfJgZa7qhNSzE5kK9RKS9PCY=,iv:GHQQBXI0PhOwvkAFv8ePP6431Rd4fgipgdWtDPNPwkE=,tag:0o5dfYZ0PTkkMbXucawqlQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
