# S3 credentials for CNPG (barman-cloud) to write WAL and base backups to SeaweedFS.
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-backup-secret
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:BNhyxOuuLvqvEU1VcdlXq/SlKGsUmGve,iv:F4UQIm2bFMWA7k6ekZIhev/hB/TDdMNwjw7o7qYJ7AE=,tag:s8TYQmcz0F23G4oWbJm1dA==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:zGIkH1bkxy7P5diI2z7saDsbSZYOIXJ0Et3XKYrQGEDNBKYg6V4o8Tcqn8QK7wk5nSE/Ynp7Smp6uVtdjOPf8Q==,iv:sOsblMuGxynu+T7mgUMYDH/l4IqlnNO2oaOuMt2Kfz8=,tag:9LS7rsKjtdMC92HndQqmxg==,type:str]
  AWS_REGION: ENC[AES256_GCM,data:KOvMDx9BssOG,iv:UjZnvIaHllXNGxthgLj8lXoD2Kyouy47Kz76pr+8mFo=,tag:T7C4oaHv285NpkRNSQ96hA==,type:str]
  AWS_ENDPOINT: ENC[AES256_GCM,data:XzhYzg6SzAYGlMpf4Q0xw7F/aqvtM6GGmIMeJcKMS3+3evpZwFUTfd5RH5U/HQ+eedd7Wj8=,iv:OHaE1eiCBW5n9qpVYg9fCkszctAbAbNn9Kyp6aK/tbc=,tag:2Ps5NpYit34ldXtwW5DiSQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhNWVweWYxM3grVjk2Y2t1
        QUxiQzJCVjVFWm5ERnFUY0NTc3FHcWhtWDNvCmV3RmxMZE1jSkQ4aHZGNHZRdnFY
        OFJmVDhTTDVsRENHYTVYaEZaWVcrck0KLS0tIDgwMmJ1SXBFSmhuaG9VS1drT2U1
        TUk3RUg0ckNwZmdDZ0R6aGZOQW9mQTgKWtUzcG9zZq21j8EstgDuWfq708xs3zM6
        bBYz9IAK1+a06ATVl/3FFF5pwdhEiFVOa+xItS3azCSEYEMcUKbqxg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-06T15:52:38Z"
  mac: ENC[AES256_GCM,data:spwSOmn8WR2IY5mQtmjyeQpx7A1NftnNbV0MfvV4xyZWqpKhCPcvL6vHTQtP6HMWNN1GeymqVPHYt1Syk375YTl1vzTAWm5Eg0KIIDK8HLSKMjyaPMESB9qcynPOEzRu0Z/ZPR+rRVtDlXtczS7vQXwa3fcQMjrzj6rplUr2juE=,iv:l7rP/srlS1YoSJFMPCh/rUUOuN9JrQE6PIswDf7A2to=,tag:ngfqYjYnjpAZcwwkCDeMwg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
