apiVersion: v1
kind: Secret
metadata:
  name: woodpecker-server-secret
stringData:
  #ENC[AES256_GCM,data:977Msklt5izaVcUqn/1y6EY8nu8fzvpokrQL71L+1Q==,iv:yT/jIhvj3+JcJvYeVePx3ygZKLa8F/o9IHoMBXB8VP8=,tag:NIS5r7xIMyotRma2wcirdw==,type:comment]
  gitea-client-id: ENC[AES256_GCM,data:JaFJE5pA7WhLGJtR8DTAqAbnAQvWTTVewAZqJL3UNjoCdGW6,iv:mce2n0rxzj8jtCXHP5GajLTgV56i0RBLGYxXnG8JWqM=,tag:GhLKUpMuoOYba2geHPVvsw==,type:str]
  gitea-client-secret: ENC[AES256_GCM,data:jioWx6WkTbW97R0JgLLGv4o6u1nP/H2SNCO1M4j8COn9EAypQvoiLE32Sp4zUKiZY3eoaYhAS44=,iv:cLxy2IWYg+iPvGcY5KrVmAVtCOghDB6i5VRLAGjKSOY=,tag:mKb33Apvt83Di9cd0KdmpQ==,type:str]
  #ENC[AES256_GCM,data:M3PPcSM15igFtvFv+ECovUMzRBb7vBOnBnJZzg==,iv:jNIzS7HnXnwdjfW7yQVCd//EsC8MVaxK1h8W7a3Tjos=,tag:YoCK9CxwVbZHi2q7hOVmYg==,type:comment]
  agent-secret: ENC[AES256_GCM,data:qaorK2HydiM3qThV2eB2enPeyH1s/4ndTX8xybgUE0aJntzfrpObaR+aoTNpzCSIFRMeIqS3Qe62VhK3ZfRDOQ==,iv:gA2MCtJX85nuueioT3zBGxcjG/f6TqEqS0i5JwlqgMo=,tag:aOf0aSfe4GQddH+SJLGdaw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0cWdlQURIUXdWOUFSQ2VV
        WFI3elpMalZQTGdrSm9nTnpvNktwZXNpbVc4CnlzbS9BOXVSY2NSaGp2WUZZY2Ro
        b3AzeXVUWWpBb3dVY3pjWEdZS2Q4T00KLS0tIEE1M2M3bVF1SkdlRi95TmRpbldh
        WXRBV1JPTHJlbTd5Q3R3WG12QVZmLzQKIQPVqYslGIbRJdz3zO9oTdpGimoXeOUm
        qiVgVerNMprP28ZrjfZ40aWyJGDfPwH/tfLO5OeVk9achnnxtRPNxw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-06T09:15:41Z"
  mac: ENC[AES256_GCM,data:zhDEtVm62CQOK9kvBTiyOutUgZlpolkwjKWqPMtbTT6XJVjlD/JKVO0hhS0jx9s9t1mAhvMB/4V68fdRKY+yrqxmVaFOndDM1VqPMltShkEd3kRoEjTcf5Pq/vJSzMvwyOg5kzJ3hWw4kQpxuQCjm81BrS2SU/J1SvVeEcDwlkA=,iv:HRpiu8EIeCVAab5wV20eGoTOpkf7i2mos5M63zTYCjQ=,tag:jAkvnyJ4po+bwJJRM6tOsw==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
