apiVersion: v1
kind: Secret
metadata:
  name: woodpecker-server-secret
stringData:
  #ENC[AES256_GCM,data:8+uvtVLQylO5SYSt4MmOG29tLzzNMITMMKJcesybMw==,iv:poh4mQl4aTj6gD2+Q1lloHL3eyJHG9/7zM60vDQaEN8=,tag:Ee8VBarL6TkBkvjvtvdFdA==,type:comment]
  gitea-client-id: ENC[AES256_GCM,data:lJFosa3hapoEyxyS2G8DwRMerOmo9nQKe0ZGFT/AXc4sI5/V,iv:8KduufGY+WixiL0idEfXyFY6hphMqxkOFBxLg2YKuDU=,tag:KIF5Ts1BfrlviSBG8SUzlA==,type:str]
  gitea-client-secret: ENC[AES256_GCM,data:9ICGyVx1B03oZG7SPyTlXJ4kRMCpPYqa0qV/uvetKypg2jsCNVVHzQ7Anvsu2fPn5TXo36If02c=,iv:HKQ8qbmcvxzspp0XXSJkOAIwkGjrjd+SLMbnKgffVto=,tag:ilwVpGFTMoT05J8Y8gT3PQ==,type:str]
  #ENC[AES256_GCM,data:WA/6KmxCdFL8a/G/Mk3odz5pUZDcOPT8zBemgA==,iv:xEyNRWBf49I9xK+DrRbZN/K010JBGu9Q85PQhU1Jqe4=,tag:WXpEDkWy3X7WBNczsZHnTA==,type:comment]
  agent-secret: ENC[AES256_GCM,data:MFMSevR3ShjqNT84C5LD8Otnh6F8jfMuOem00mExPzB9whqPtumikJOlB5qZ5oG/3wAyZFfHPbjkWlreKVfw7A==,iv:tss4RuRqahUNjVBCbsTRIwAhuTu/gaNc6PhFZ2DP+Qw=,tag:he0OrTRhilg8erC2tmDGNw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyK1dGQVAwWDFrazZESEox
        RjdHbGU5Sm5meE45RWZIUjZ6SlBZWW1QVGd3CkNkRXZmRUZlZzFESjk1TTIxMHpk
        VS9qSVZYOXl5WS9Jd3BiZlVveHpSMTgKLS0tIGFxbDE3eHFjVzBHTmI3MlRtaC92
        Q0Z1aElKYTRkTFpWMnBaWUkwZnQrRU0KdggKjRN8gJ6ScvreIMNxkuKwuMjyphq6
        OE1Mun5orV5lV6UNJkiZ5hgc45Qnku8oru4nNt8gJ2TRjMg38Wzm0w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-10T18:02:42Z"
  mac: ENC[AES256_GCM,data:yRvU+19KzRvZl3U8pdcIjvyPv4TlmgL9WXRrLbaE2ADvR0lghJpyjOStTg/ynrjQA23D9KWLuo7FtZcNfSC1vwjYYav2FutVLkFkF57vo9gIz+qaCXGWZPx5azkZTveiMH6MdiQ+V/oJsICliuRFadR5uo/5He5v76lO9TPq3uY=,iv:c/cldfKmdZ1epfjUa+dFfc4hre7J6JAgs3nykN/jVU0=,tag:7BU2nHOFlOBVQSMzjsTMKw==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
