apiVersion: v1
kind: Secret
metadata:
  name: woodpecker-server-secret
stringData:
  #ENC[AES256_GCM,data:hfCS6OULbPZh6AHhlGamhKZCAb3k8OgjoKILklBOXg==,iv:ArxksFwPCHMrnOZayLmMX8pK6c3JVth+Ny+Yo+eeSF4=,tag:K3ZXRkzBz82O3edFEcUunw==,type:comment]
  gitea-client-id: ENC[AES256_GCM,data:+iItZnBytF9Z0xh975KJLhmmFVgexrxAB3Q4aVLDo9kwJz0m,iv:ZRiKODLar9liUuBRZFYVczgxikn+vvgOFPK5ngLPAEc=,tag:LI6lD2YnhyQnl5qp570eFQ==,type:str]
  gitea-client-secret: ENC[AES256_GCM,data:YdujFc0iM2GMEG3/W705IfKXHIzfqrJTvaFONz/R3cHHJlH53dPk3lM8qKD3a0GpbTUUgJnuekA=,iv:0Z26ekYNxr1NariY1HVcMrrjUJms6MlNMXxxaA2EKLs=,tag:j9aSaKbyQr25df87OWoJEg==,type:str]
  #ENC[AES256_GCM,data:tJNYBH0wttUxO/LfeE4AyHy+6da5nkBll8EBEg==,iv:S+Ah2NdMiRX2mDfxPhp5zj8p3wkI0erG9s+NCBkc91Q=,tag:5TLQSS6kVFmeEEO4RE/cig==,type:comment]
  agent-secret: ENC[AES256_GCM,data:xj5AxsWpZ0OwNN87+25qcnX1A3ZowMGImy8yzlgANF9j5dxTtKqG8CruZy9AvWMJbYByvO7IcG+3B7jjQob3QQ==,iv:N6daSawoiHlWMOmy+NyxSpAk90svz6IvUWwJ/vaoBxk=,tag:eKFsXa+stMBRqwKJ9msh4A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqOVVuVVJEQXg1SklYM25y
        TjZlVEF2SU1uNUhPNVJYL1Q2a1UyZ2o1R0hBCmdwYUxzR0IzSTZCcklQd0JrNHFT
        RFBVWkFGNVJoRm5NeGVHWUowbDI1cm8KLS0tIDNkUW5kVDJqS21WUHJDTzFjNVda
        dFg3Nk9kWUFwRDUwOWl2MDU1QVlzSU0KPi9BhYhNALBVkESXehm3tWJRnrEl/W2R
        uQGuTVZygKkN/WrwNoI892HKC+CFVMQAL/0y5P02nljxMLR4lvgF5w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-04T13:21:48Z"
  mac: ENC[AES256_GCM,data:G6wsgBsFpp1w93WpwubN86bDTwVFrO1+g9+P1BSE9E0VuQYRT8w9v3xekIAAH5oazJ+lUdhAG7xPcqZxP0QOlUERIwzfVqLAIFiffyT+zg/dVv8V8Pu6DATfy/5OV1QStxgBMjOFqQR6zOBqS5FzJ4K/gszJ/4be1FiEhbqpeIo=,iv:fIp0SXQ7+hKJjK28iFdSYRwSQLYBKuKMivE2EEtnIEI=,tag:bJCih1BXIuzBVSL74/XgNA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
