apiVersion: v1
kind: Secret
metadata:
  name: health-auto-export-secret
  namespace: health
type: Opaque
stringData:
  mongo-username: ENC[AES256_GCM,data:tp1TkcE=,iv:UE3gnO0gJBlgEgPk9Acbw0mUdPJPSdSE5pNWSjEr9ac=,tag:ef+AuF1mTCf4X4BhS3uGiQ==,type:str]
  mongo-password: ENC[AES256_GCM,data:zsW1CRreI324+B4kpIpaKhY=,iv:j5WCEbF/4AOTt4OoAKJFjkr4D33FxF/xWqYxzXUWfWI=,tag:lJy41kglpEnTHrdME6uU2A==,type:str]
  read-token: ENC[AES256_GCM,data:8UZqIlG23+8qbHVKKzUBixyCWjdVPWWCjq/1s2MFaNjUzVY=,iv:qzWnvSixWazBmIFkK3RChVnJZ7avyKND1HpbQwKFv0k=,tag:Jv4ZYmEocEZ6xR0qvytlyg==,type:str]
  write-token: ENC[AES256_GCM,data:/nE1ARqHGLi6T9l0fZYByF3fGmc4fa/HwXyN5jp8ZZD07Dk=,iv:9QLH6XtY2OKbrdpLoCVG6h9OxieTUq9k5UeovnaQXso=,tag:XaSRuCk+ZNWju4qzewRPhA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGci9WSkIyQ3NhTU1MSHpL
        YmR4N2I1UEljWnllWkZnQ3NkNERXcFE2bTMwCmV6bVRSTHBkL1RPRkp4KzlHcVFr
        a2N3empBMjlzYlJIVE0rUkt1M1NUK28KLS0tIGRld0FxT29HVld6T2dXNGZVdlJI
        UHdzV0xYYWpBTXRHUXBMNXVwRGNvWjAKQJPKGhiUb+mp5lTcD/+/urebepgDXgoZ
        hft+jK3TrMCd5HffLFaT9t7gdNS1T4odFcVPTJmPLbVxseXh46M9wA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-30T16:01:33Z"
  mac: ENC[AES256_GCM,data:MoYYmaKk09gjuc3dgvrYgqZu3FJqWlch54AVd2hgVAojBnTJaRljhl7/sGSa4Uy1cN9KVHSZvABo+0T3PjPlJiFdKOEG61/0SwMBUxipWFvUTCjvQr10PBndpco2++SWT7tRCNbdR1Ea93SBayyZHaz5paE5qc4UwIficcet1pQ=,iv:+TGAZCPzoaVm2vcJFNCZERUXWYmu9fmX67cZTT63cbw=,tag:gbeZyAERrhFLebxqvhIP2g==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
