apiVersion: v1
kind: Secret
metadata:
  name: health-auto-export-secret
  namespace: health
type: Opaque
stringData:
  mongo-username: ENC[AES256_GCM,data:/X6syA0=,iv:rowYXsW+AfFEqOdc8kH444y3hzlhGcTrt77x8XJICtk=,tag:CiROSuVm9dv3UAKOJsxnOA==,type:str]
  mongo-password: ENC[AES256_GCM,data:iydlczxTZIwzlUVeyfg5n2w=,iv:I0gFyr9Be5qqSDOjF+9hReDbvu7xH/QrNsBJ9mQzsz4=,tag:g2+ZHMlRjBf3sN7rPE2NoA==,type:str]
  read-token: ENC[AES256_GCM,data:jN8eh/n2x7aOiEj7OwMHC+t604BIHzGN7eRrIp3Gif7HtQE=,iv:+ndzTtHxsn/hA2qnSyQZ8Ym1eqfGDJS6U4tr+pvfq1g=,tag:8nhRrBnpJl4aPsagD4WVfQ==,type:str]
  write-token: ENC[AES256_GCM,data:wsyQAz7AZWfpXaELwEcS9RS5fVbK1GM8WgBuSumLZ96HmsY=,iv:LpL2BeqnSpJ6kBjJBYiZnxwtQ0Z/1pEVWsesxNr5QdY=,tag:QUAkQU1weqx3nEqV5CEM1Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTXNUdDk3UUFMU0RUajhp
        RkNwamZGWkFqYmNvd09YMUF3UWk5NmtoekVJCkhaOHFtNnpucUlyOVdvVE5vYzJL
        eTJrZXZSMS9IdFpoSmhKd0V2NGpoRGsKLS0tIE52ekdyQ0NvcDdJVmQveDl1T0I5
        QmxlNGZiUWFRL0djdWdValZqK0Q4OUkK1obQCi5hyIpN/Rux3kPUeGcr0gqCKIJz
        w6+6E6wPqx00cJWI0h2bh2I9r33LBBpoBez5pca+VuHYNCxk9h0Lrw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-31T13:06:52Z"
  mac: ENC[AES256_GCM,data:Lvsvq+5WCcGzwE0ze1ZPXQPq02FN72FMi0xUa01B6IQSLm5mYpjKyA5V1/4VtYz82xakNxmqNgfvbaOHh8dfeJ0kBrOdEe43br1L1I6ydE4wRYFXGKYV+v60UdSj/svh0Triw3w6A7/yllTK7Rb3ARrN+czjGkp7G3RIE8bBnHY=,iv:olbHpOmDk3aQur1xq8seBye2uU0fTBwzJaW0o/zHmRo=,tag:vcFUnyBtLT0RiRPHrgt33A==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
