apiVersion: v1
kind: Secret
metadata:
  name: health-auto-export-secret
  namespace: health
type: Opaque
stringData:
  mongo-username: ENC[AES256_GCM,data:9OhK7zY=,iv:aqyBMoOWx72766fBmhXGUf34DDFYaBLuG3eCANONsx8=,tag:42ZlmstYE35IJpdywwrXYg==,type:str]
  mongo-password: ENC[AES256_GCM,data:emGHjuGN5xQo0OLdIcpkhKI=,iv:NGyBeVNatNrMupm5G8BhHDzX3JCsVdtWhTnkfB7o/xA=,tag:jy1IO7qAAq4iIMcRnEF5KQ==,type:str]
  read-token: ENC[AES256_GCM,data:VoepZrhGI2Z3lPY71HpB/xZrivHRuK7U6zI8GhtQaDXc34M=,iv:l8NIwRcCgHblv/nYVRDY86jkDGahAO6vmvuci/rd8Qw=,tag:zr+q160MlR5ZeluQuxceTA==,type:str]
  write-token: ENC[AES256_GCM,data:S/ttmypfTnsDmMg0AcZsiCEVpmxqYM7xpPFGVm3oVlKhTKc=,iv:NCalaJvgM0kqKP96OvNmBqr2RbB2BqsfCKze5b8b58s=,tag:EVwqvTgzn5AUcgOA+O1Meg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VFJVc0lqdERKOEE2YWll
        UEc2TWUwTHg2ckFwNXZtSC9vaUVHbWRWMHdvCjNuc2lxMkFxMjJ0ZDBDWTRrWEVj
        RC9OOU0ydWdiakdKcEZKcDRWUG5aTEEKLS0tIC9GRU5yZ3o3WkJ6WitrR0xlSVV4
        cHZZdkhtRW1XcWx2cGdORTl4VEJxd0kKL6Qemee6INcqOTX3KXa4gJQ9B5jc84cI
        EWSgKithCfR/1oTOXrdutoyJ0HmJBlr5CPqU1n5x8Ku9umkKMYf1TA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-24T17:01:21Z"
  mac: ENC[AES256_GCM,data:OP08e5o9lXlOjt4AuM9bm4AqP3V6hxaSdJPFtvdqP3isa0xFerOUk/IGIknodlMI/kS2QUXJDw9kJQ/GsjfUYmBdGWvVBRWVyIYCvD95zjO4V7cumPb8Yl+eQfwTtx5/C0jpc32D6HhPn3We7idtGfz97ZZORe5izEhf3Vsj/C8=,iv:ZkSA0iLWSzsGmzS/0IvBiB2+whElOsjzuD2n8eqJsLI=,tag:EupOszwN/Jm+CyMvwYiX1Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
