apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
stringData:
  admin-user: ENC[AES256_GCM,data:WEd8DTE=,iv:DQ8vdIPYwjR9NE83Oo/PfdEaoc8YY5YebSMsU4AcON8=,tag:E0IX8wiM610JK0mUeJ9+2A==,type:str]
  admin-password: ENC[AES256_GCM,data:jOXlSFf+v8yu+oGAO5bMln7XLoCHi1cd,iv:MzHY0sEU65p9LiIeQVc3hdGVSbCXQe1RxD7gAemCPLM=,tag:3zKZzVIGXesXDNUDatlDhQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNmM0aHFBcHpaLytFeHFH
        U1g0ZGZickF4dmQxanVhQ0NpOElLUEpDQ1VFCncyQWNHMGJnRFA0UlJta25HUTNi
        RnJQc1BKWm0wS2pvRGRiYjN6VndqNjgKLS0tIHJIVTEzQkZScGphdGk1dzRmQ0xP
        b1IxV0pBT08rcjhwaHVBVHdZME1VcjQKALUumcMlzdhiwef+RmKZSUQ3BosijTES
        YAZ5F9E7zY+KdXrjRWXbJfcA6obBqiFd8jo746GqpugDLinsi3nGAw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-24T16:34:58Z"
  mac: ENC[AES256_GCM,data:YFJEyQeA+s98cKlMWd9yi78WEfeXh/HCXFCmOj+7bVVp2puo/EZAxYLmtIpjEi/ZTf+jNMRMee0WxoAUTfSYFWhe3QLaoCnNI+fHgBQpLPD8hv1DrbdnATJGqq9hnFKBcZG/jldX69YTGKgqB6GwW60/dAMkkeB60Qu2imJJc9I=,iv:ou+HS7vWEJrf4TOfiSUsIyWRodaIc6L3r/XWEy+Lm0I=,tag:O3g1yKJRB9oefMnKkeqYnQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
