apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
stringData:
  admin-user: ENC[AES256_GCM,data:Ykm9FZE=,iv:HtCCZkNiPm7q0xzO5QB524WJBhDhLPdvlMvqvj+s/Bc=,tag:1tVzVcqaKYgz5D8BlnImDg==,type:str]
  admin-password: ENC[AES256_GCM,data:G6TVIaiSQ700D2CSsM7HLYRI+EmM5aud,iv:K8ESH+q9+XNdJD7QRaO5jyBXYj7Zx/SkX0l9kcyFIoE=,tag:p4U54Rdx4VkIofLc7C2Idg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUGNLanNWTUVOL2J5WGRm
        L1lVWnVBMmgwU1plenpSaXlMSjZjbTZ1b1c0ClNJSnVQS3NUdTNUUFlVbEwyR2dr
        VTY1L0ZxWjNqNURHUlh6REk1dHZwWmMKLS0tIFg3YWF1clRXKzVpdlY2NUVZWTBs
        YThadHpFeEtSNnd4WGxyOEVTRXVTSUEKDX5O/qwcp7VRD84AGk969JASNELYcBGh
        jFfgTSxOf6JsygiP7h6pm0Xn0G96sUcZ187BVIEpkGcOSdHTq0Ea0Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-14T14:38:06Z"
  mac: ENC[AES256_GCM,data:HwDEofGZsJgact9yaLfS11dt92qlC8h6/PArvsvaejfQieTHrumYEn/68Gr0dTnjnJEHxNh2A1QV8lJv301APjtkJZMsEgGBIqrk28bc8KGHr3xyoQPkd4kG/2LLd0W/9YGHoH5LE14/W6mVFPqvLjU2VaWzTPkwHs3cQJPKOnQ=,iv:a9/j+Gub3hoDeCu030P+MmTnC8+vRakEjfiooEVfQ/w=,tag:na/ewXKg5KhE9tv46alIqw==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
