apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
stringData:
  admin-user: ENC[AES256_GCM,data:3N2nFgA=,iv:pLCoWNZ10f2iY37yTQkTnom3exFp57JpGScFsudY6vU=,tag:mrHzdbP8+4ml5gJzG67Qlg==,type:str]
  admin-password: ""
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqcU1OS2p3SUZ6MGZsTkl2
        MDV6bG9JQWowd1VhWGl4bWlTWmlWbE5ldlR3Ck1uZEg1M29sUnFCUkNsMW9XNkxR
        ZmdzS01JUDB2SEhNdlJBWHhxQ2Zia2sKLS0tIEMwQUZqQkg2RkJGWXN5eXZPa28v
        eXFUcG1RQnVhaXpsMmU1c0NmKzBMMXMK0ML42RsiT2LPyv35V53Jia7VSA3k1MH+
        5IhE2VpguyT7XluxHJlP5O2v7J6veQJ+hrQIAPNXjicf5D2fvMCkWw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-17T16:23:42Z"
  mac: ENC[AES256_GCM,data:eq10XqpeALRdKXzpOUe+ng8jFsUfBszpPoNx1bp3+Pa1NbYnBuLkrfk/+j8oW7Sht6lI2Mm+woFCbjl8EC+/tyo2p1fRhbUtt79Ypfn2oihPj50gTwPC6MkM+2k+3l/BfpXA0iIbXt3mrAnps5df7XVORzyWgPS9M+CzlSqyu4Q=,iv:vPHmWeT8f8h7QXpZTAWSzWqq0qoB02DLC+HTKqnmTSU=,tag:7p06TkZ3tua6a9yY8RPoLw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
