apiVersion: v1
kind: Secret
metadata:
  name: s3manager-secret
stringData:
  access-key-id: ENC[AES256_GCM,data:+h+uBaIXlMcyCAOtRyBB7aRfK+cuNXU9,iv:uFanlbxfZEnOKMCXHj68Yv+hX0Hreoit9vvkUVXmy0I=,tag:Ok6rVcgGV9dg0TtRP2jWVg==,type:str]
  secret-access-key: ENC[AES256_GCM,data:W5HjY23oX8+FU3CylBW6L4vF9yFYdIxLx8nQwrWQ30natNSrtXIXeCoc2q6BEWCe8Fs4hCsD8Lre9swClmwyaA==,iv:RQ3Y8B3d2prfavwEyEOUUgqjBxG4+9BTY4loCFzlV+8=,tag:Zv9et8rZyOFUa1z/7slKzw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMU1mNmQ3R1ZPSEhBQjBO
        VFVrbVl3Sy9MaDd4c0R2N0JXYTJmR1VDUnpZCmZubTRja0U4RWZIZWJPNElYbWk0
        NjdGODNrZFYwSXpWOHcweW1UZzh3ZkEKLS0tIHEzdlFjRWVXTGtjZVJmQkZRaFRV
        VXJhbVVOMndkbVFZN0VEeXNxejlqWVUKiK2BNBJHGnLayGAKp9lgR34sDG0yYi3S
        2yD2dXsHS6ZGLCJnUSgmzr9rQATXl2gLlDrWTHTeoOZEj/wGgYrNmA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-24T14:44:04Z"
  mac: ENC[AES256_GCM,data:08BmjHMecreXAzQiEsSMi+2jG34LdHq6hPIbXekbwiP0/dDxLAtnsVm3xRWSWzprkgOfvguHsXUU/VG7wf5C9ZU26k3/iHMP7GsFk1eVFtFXEYtq8nff4gW0ti7OAB8Aqs9h8KzLTDc/lBPmXbpDCSlosRVGUO7xLFCMAFGcb/w=,iv:Gy65qRs4lz0qDGN4klqVb68mUeL7RuOCfoySERLHoxU=,tag:cFn1+shIBoO/FZeNORTdpg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
