apiVersion: v1
kind: Secret
metadata:
  name: s3manager-secret
stringData:
  access-key-id: ENC[AES256_GCM,data:MJ8K7O3JOetyqOVTQSTfWqY+PEN4ua5cM24=,iv:RMV1Luk/TsmTcgWcyZoBFc6Mk9ue8o6W29BkavwJq6Q=,tag:DMJO00WPWLOLbUOYQcKpTA==,type:str]
  secret-access-key: ENC[AES256_GCM,data:sUupAT9G2ugSmJmvo4gmNXhnUESK9pgPDAzTYF2WF9FdpVfyAc4HH6H61bqkxuVAVGuwNO4EWVqc5PCKa9vTJw==,iv:a1+vgygVUFdSfrqQwLVQxOle3cJsbaUF2vunECC+y9A=,tag:vjYWDi+cZ9KtQOkc4MbmKQ==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4R1JwZEFnRW1uK0V1T21K
        dzd5RUhlOGMrSFluT1VZV1I5YlZkWXZOSWtvCmFNSzYyUVhwQUVFYmdPYTByWVkw
        TXpvTnZrSGxKRjhndzk3RjV0TnpkTUEKLS0tIHY4Zlo3UHltTXBUQnN1aU90ZFZr
        SVlYbUpSbEk1Z2tMWVYvdkpMSHI5dk0KEPHIOGGdmas4PDto+dfOPK/jQK9yxYoh
        rJsJ34+hanVeerWbv6uXGtzjV58p+lKoDMnhQuTvYR6q+d/ve4OQeg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-19T10:30:26Z"
  mac: ENC[AES256_GCM,data:leK5wYDId0IchBQrQH0HE13Nh3GuZc1zylNiE9OLtOHnTZDVFVcja6SZ8lwkZ50MwEm7yzDBgiiDRMDEkS2OOHtbhBpJigrIAM+NTdiRa/0wJ0YxJk7wNNa15Pd+VTrnqjRuqJgd1qvf6m+S7qIyTY/zmQ6qpk2tR+a/TynPvhY=,iv:kor3SbzJOQq9jwH9rMrViqjkaR63tVGgEwb2Nhtc+9Q=,tag:uoDIYsvFT3Y8v89u1gc2ew==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
