apiVersion: v1
kind: Secret
metadata:
  name: s3manager-secret
stringData:
  access-key-id: ENC[AES256_GCM,data:aUNXW/pAaXPxG7cgifc4UXR6iRNvjrNw,iv:mzeIAeLv8x9dUQGHWgGC09I15zunh//HZsa7i8ujN4Y=,tag:JypWjj+CGFA6CNbrhICzGw==,type:str]
  secret-access-key: ENC[AES256_GCM,data:iAE9pn2ajoHqoxu0JkivoSmvZACneevcgzk7B16ZuuhnlYXOlqIWZ0RnIWhSK2NAOhIynzPJD992KhIUeUGUpQ==,iv:+dJC+f5nG4SRiGkBuJNAMY32xVtVUvxYKcmXQU3KjVM=,tag:t5ekfKaSjmOjaShut6duxg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtbEkwT1kwUHhrR1RaeHQ4
        QkJtSGlBSUxaaUFXSnRsWHhwUXhSNkEyV2lJCmFtWjZVWWd2bmtSbVpuc0grT2R3
        T1dwL05UWjQ5VlFNYUxYdVdwYUZRa0EKLS0tIG1TNU5OaTdLeTIycmdUckR0NDFo
        Nm95SmRIbmxSZk1TblNMT2s0UlovaWcKCPnIEWJFzaogZJmQL/S4k74crmTabHz0
        w17kADkAVUGIUIA58lrdrpAP7H5YzvmM4zw1mnm8OvGLaGqWZND88Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-15T07:11:52Z"
  mac: ENC[AES256_GCM,data:xac+EwMT7EDx5TdNYvnYsg45wLrwjWK2AejxA2IxhkZ3lXAnCBSD9BMVUn22XRC1AaEzwo3rt9eQy1+FnD2f8t2Yfx+8mrDHvKd39AmPHEi/K550XMtISzGlJMs5nNCVFl5dl1MDriVjz1k+9qNzjvyHbBU+MFlgcGamQB2UiSM=,iv:f0/H/DTxW3j0q89QxfzwMrBc7UsfaOVl/2gsRm/fFas=,tag:PEtIMHYLizx9YrkDtz87kg==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
