---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: authelia-bypass-s3manager
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: s3manager-app
