apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-html-restic-secret
  namespace: cloud
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:koKIASqtcqmik/sAa5ztZozB+ifjOLN/VMMQQ3C+mwQEaPDLFuWaEoboTefNHBAjrNU+3QPKfxP24gTKuKPrTapzl6/icbVR+XRnIHB20NfN,iv:8B6W/v5V9wS40PjVnOJBEjq6LIFApz+DuLz7AcBTQIE=,tag:N/0G/UU8pEC7znlD/f83sw==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:hmVEG4QlbXYurSztgKOFrGkh+TeX6JTAbHKFAkJIznTuoQFe4UBi60D+iv4=,iv:YbxToosdyi8/nWeAVQnr5gkpIXhtUTWy+2VKE1FYr7I=,tag:NGPDWWo5oXOJXHFdJAkdCg==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:sk81uSpaKrUNT656QlmlmyYo8tSZqtlH93Q=,iv:BBJE8u00yIyWKjF4eI/adb67LNNUXqMGyWmpMqVjiFQ=,tag:JFcuBXw6TvceBAiZvlqr4Q==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:U2gcHJZjfaZjaB2tPhJ+e8PWrqNOyu1OCMrH40U8JQWKELGlgnJRdVihKeMWoQUdkSJQluKLWxYQ/KmkQo6PCg==,iv:W+ETKjRQCMwifctMpN0J4msmsO/fXKOXglyATDzuM2o=,tag:Nx5ByKoSwqQUq1vREpQvJA==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dVFteW1SMWYwRFpaNi82
        T3huc0NOcWNBQS9KVlJuR1BOSm1JSkRBNG1nCjgvRjFRT3ZsNzUwWVdjeXBkN0k2
        K2J5bkVrUm9tOUtZY3ZyWDg5SHE0TVkKLS0tIHhmNGVKVXIyMzM1YklJUGdDRWFD
        ZXpNNmNwNVI0akJjbjlXNjRwRjhjS00KVibczvNQxJ4094Y3Hn9xr3WuCprQ885T
        JpOhH3sv9yYZolnX0raNoCl+vZbLLLKCPHobw8Wqixjim6960a/8rQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-22T08:39:57Z"
  mac: ENC[AES256_GCM,data:8bHISExKAB9JYD2J6AXRQ2T5IfNvRaoMpb/CyERyRqCy/L283VCnjFNmoYtcFuqy1KrgRG47X020E4aWxe0sjat9TmHm0hIuJ2e+84iQuKfEW5TyETpji3VKJrDWQcsw7kmH5qd7mJGj5xyR2DTdxltl2HmmPw/9g8FTMpJWCVw=,iv:D9vAlB1Pr1IdyVTyUzPKTCt5zz2OUGUw/Kp3CFc5sgk=,tag:tU1BGMF4ukWbrd/hnAPAEw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
