apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-html-r2-restic-secret
  namespace: cloud
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:t4lhqRKhemFWNKNnV1h1FrT6rgX8daQTlTVlS6b9ZACRt978V7bAJ9qoV8TXnWlhNXXZPXLqYS77al85vGPAXRoN8rJwRfjEUUH7payAmd3SsohFlMT1NZ9z+qfgahI4YJSKJ4Zc,iv:L6o0jgsMF1b9mr/HJk+vxJJh4Cg+6gH7O3ETuDCN4hs=,tag:m046x3LDyZq4gKnb3/eHMw==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:Q0zBunUImkxmSh6cOH8+JIxRUBK89HXJwado26T3XdBt8KxkeR13AZs/EhA=,iv:9u405h990Svgw5qCqx/J7a5X+MKnrEAgVlf5zDcprUE=,tag:Z7xiC4A/BUDoTpsE7aeY/A==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:OYFaKc888Gm2uRI1pmVpdIvhyXAYzc4Y267hRv2gaWI=,iv:B510RqvOFNsgMD84yLfHlEilEgGmn2zBO74UZsY64h0=,tag:GLth4frfrtAuMdcxtLsd1Q==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Jh+yrH3pyZXsyKJMIyacAa2laUNNbjsVknDecK1ImVa/AgbXg1M798bleRl1oviOZJJhPTlfKSh6tZ15y0Tf/Q==,iv:FzMVgGlEHKBkuAJQ6kQMoRAGuPOHTSRQ7bVRvxtlwjU=,tag:UJr1Dilm/frUxesFGCOqpA==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:uiaraw==,iv:FuhX2V1xvPwSh5GWX6Ley/5LztIT4EjkI5iZsqucDkU=,tag:UbpZUiMQD5iIScRSIYmJKw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1THVpVVpQZU5qRjlVVTBH
        S2lVRHhWVytlYjg4RWRoWklpL2tkU280UXlJCjN0TEUxbXQwbHBpZGxjeVVCbG5Z
        SnNRYlAxQk5HaVlhcEkrbGVHY2U4bXcKLS0tIExRWGlrZ1NpTGU2UE5zY09OeFRn
        TGJvcXpOTm5XSkN0VkxhN1BxZmxsd1kKAyZ6y9dDWZQSqEi8z42t9Ct9XdpciHDs
        cUIvFHeDtkf+craD0mljlHZgLysxoq+BiF7zQGj6B0oBlSVTuw0neA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-04T10:21:24Z"
  mac: ENC[AES256_GCM,data:RYRxgncXqEPANtaMvvMGCQ8sm8SWF5gbr4rIMXAfjkACS49nHZ34UeVTUxszNpGeOfglx9Cblf8fMoKeNFpWdRJqRCGGLT3zd2GlYPP7ScTo+0XrMiFf4GazO50em1YMgyokoyxnCg13nKHw0KKJaLRCjECb3FesSwmel65OiHk=,iv:hSWfkiYrmiwwGCOSMB0mYj8kOZCEeZ3zeUXcR6CXKdk=,tag:sOwmxz9iYr3jevOo9721fA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
