apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-html-r2-restic-secret
  namespace: cloud
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:2byV5kO8q9/wa/XdGfTUSr1kcpPjepdX48qyrJpVOfA7bS/9UpNIPdywKTPKPniG+Y7TDzKq3n7kK47zoReCZE5YvDNnoytPruB0+OWl7XWBd9QGV4oP3kSrehzubm4SwjyqG4qD,iv:RF43zONvdatZOSK1DsOxPTY/0nizS7ARnWkZMQjQl2A=,tag:F0fyZ5LJgY8pYI1EKAWJPQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:KJXvcgHdqBnXeYs67MjutqOvdcvD3j17AZ6da+iATJ1bA/GXl4kMQVU2gIs=,iv:aLbqM+uW39nen+JT8lwmgss/XTNA3ElN9tQ1fORSh0Q=,tag:dOteicQcSez8nl0ksUCXqw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:tfDuiM97ypR0uqMug26qcqYZCR62ASBFpllJLd9fxog=,iv:vmcpW5qDRVRHNFQaKjcNWkRAoa4SzA8cke+QNIaHkXM=,tag:BYRtNTm9qXLXf/mzdRqJ+Q==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ZVUn0BxIlUvxsxHxhKLL32b/1p8EiC6qZaWY54RLUsNbeI1DZffeRbWFPDmGs9VEciNBh5x7geBh33Z1yEHC/w==,iv:Tl3FRMwuVmmIdrYmRcAk2rxUZ3SBOsewhVxxs/yxbKI=,tag:u4s29DOxlvcEp+4G/xvtjg==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:vSiO2w==,iv:YXP5X53Po1JNPMO9sC/8Ezvo9KpPLaAZlFOPDx6vDYE=,tag:Nulrqih/+NGF+P80XE6UXQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSkRYbWtOODlCMnBadmRi
        Ulp0OEtUaEk0N0VJcGJiOUFId3o1QW85RkdrCnZyMFZ2K3hrMHBuQ0l4aWhqVzdP
        aitsR3N3V3h4YVNKZjllQm13V0QwUjgKLS0tIEh2eUdyTGNWRzVXb2J5eFdYaFJu
        YnAwK2x6eEd2aEdOblFuRVFhOEVLbWsKSUnnJAxxnegjQjIMVmkbjSC7MVywLy3L
        fEmPmQgkV3ConySymxWyUpzxP0UOegeZ8MM9m60b07IbGwe0NogFeA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-04T11:06:03Z"
  mac: ENC[AES256_GCM,data:BVjI0hRpkcR11xt8EObIJsg2D2Iyl5lUX4DtEYl89vs7ctN3b4DTvvnpF2VP90ezdmaOspY8bu/NJAGNMmY3lOTQROskFNRfEmWFdI55K3y4WNBGBz/Mjib+vG255qoLNYu4MJ5EwSHXPXzQidt2Jk/RZW/Js+iuZ45I16DeScw=,iv:+hfSjGfoql59uABhlht4FDXMREYlEr5S6qZP3/zyz6k=,tag:phkvaPqqMPF/6UhYz9n79w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
