apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-html-restic-secret
  namespace: cloud
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:T0FX1Fd0EZeZPclnAFl73bQ44IxaDUtNXGVgEuaZHocadevwByToX0hL+kGbjTpN+xH1Nr711pIQW2Pb0xZ4KTwBQW4xhxru9ChR+AhimiIt,iv:w537mXCK1sfy5Na5Cnf1sM9MWsLGymfS1S7jeJeOKSM=,tag:HhXj3hE5tYrzdOHZ5R0NhQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:Jr70zoLYpH7mL3TqQigyPhi0hTIhlMom6H9G1BpKOwtpdiIJVCObam1vIA8=,iv:q4WQLn7BdHkiki/Zd01DA/2byaUMw3odzGTUI/BHXXw=,tag:YouU9/m87GLLC7Cunf9ccA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:u3AL+MCnc4wV95YjRoRf1BpR5NHqed/6NxE=,iv:KomKZ1bjwF4COoAk/kXpSN4pvNq5AZ0A2OX08ZNk29E=,tag:E72LvEJ8FXok93Y+UWcfuw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:KbFenFeA4JKRXvKUONSfTXs5k936y7n0lxLOcfOCi0kFDSP3ifweN2FaX5U7EHgBXzQCdDMsKEWIhDyON0kgTg==,iv:gYx0ppgYQyqS7r2Zf7uDYW3E5/JJSirQBsPfoiKzpQg=,tag:SV6ll8fgB7KdhvRc/hCfGA==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Um4rTWhjMVhuWHZ3WEdQ
        d1BLbStGL2RRZTJPb1FwbkF1MkdGOUZuNGlnCnpOc21NL1VheFIvbFdic2M2Qmcv
        L2JvRVJFWFQ2a3k5MHE4OEd2RWhFNDgKLS0tIEhBOWtieVY2WllLeUZ1YzlMSytT
        RW41ekNScXBaMXc5WmwzNmJ4ZkIvdWcK1JflMrbEE6AzCCgO8nqTQwzSX6mllw9t
        U0ZMGhfYp417PkQQlNIdmMqU7niXLXglPKOP3HhS+kn4eY4nPHdxWA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-23T08:05:17Z"
  mac: ENC[AES256_GCM,data:KG+KWVntIjL/y3f2tqEuIluMR0tXrzVxu1HDPS7w1J7aSke/UjXSiiPw2jM3bE+pZA2TZcWP2+kh4eFATVeudwC0GgEYR6eGdrTqPXh5f4HDOdwFDkJnbdtdr62jmeAPb7b6PaoLrlZdQy5XxYjHZH/N8iLLMePjebrNhDURFpc=,iv:G5wvcnBX55L9g2eEFUHAjdXhMMs7SPUTq+py5Qv8w9Q=,tag:NVLrRTRa/gnjqBklJYXSEg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
