apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-html-r2-restic-secret
  namespace: cloud
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:8HethLTDYg0Q1r+VGP6Z3Zvv33ZN1JO9ny2leGMoVMi8ftH4/BBLKOdTVkjZ3DFr6Wbx7NIoeFvTQoPnQTGd7mZ3rOzj3ZP56oBvTNreQyLcptxCKguBDanryjeU9fufQvP9CQVh,iv:FAZDCvYoTQAGsqfxxqTFcN3xXHX4Bh53fd9zjeTmrKc=,tag:h812aNFPAKfwITkHRn6KJg==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:TrDa2RVIiRU9VSJw6mPdPYVWgy3IWLRG6RG/GJBB69IyYxE7vXgJWQKwces=,iv:TDMz6QWQ1CQjvUu2Ourk+sMvzRWTxvPEGY5oOz13CNY=,tag:4UFfpVG4ppG1o2YyOATUIw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:woWd/HGFor+huNn6fiumSKZahHhkW307CkX0KPC7sWc=,iv:k7MTqrZIJEpezbLzQ5fu72AqcOx+h6zmT5QNiR/0poM=,tag:lVd50plvbLRminTPZDyvEw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:LEDb7gFS3GEnFlfpPD2afgOCYdUuo05+Us3Iiifl3iusKFwC1a8ej+h6c27sAd/M63htvaCQB/QFQHvb24H3Hg==,iv:/IeZI/3qBjh+8iISq9W8y9bfuItzqBUuHY9eUWHuH3o=,tag:f8QMYVlAHFuWR+npdY9xyA==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:9gYoXg==,iv:XkydwJxQdIKM77H3b0W2489ciKW9BuKr7uTbWFH31L8=,tag:0shnO66XZISICxM6rgBbSg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRlJzbHV0NjRuUEljdFly
        VTg1ZTlLdXJoVjBhNWpJSzRtN1MzTU1RZEI4CnhnMjNCZGYwbkwzNXBYWllGTW03
        ak1UZGJSaG5KSnVnK2lGdXBhQURXa1EKLS0tIDBlOExJOHI5aTN2UElIY1JJUHlY
        YVNSd09UOFl2M1hVWXkyY3Uyd2k2cXMKkVH0qwrFrdSw4cD2xTTcNxlVlobfOkHe
        qpQZpgTpLuiS/eaDHZsU8CODTdrW8fMWtwI0iVYrt2XLJ1Q/qVoxSw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-18T09:43:17Z"
  mac: ENC[AES256_GCM,data:aoqK3C/NO8VHnmdkvg8EerCPtC4OH3y85+jej7aWIdPTO4TRfB4GKV1uO5OQKD5dLTRQuNd6ZOdujZTSW2J1hriHP8aqraLwi/NxaFqBuz2z+0lmg71u9vCmhKLMOtPqpW9MEHqgKVdP1LTwc6cBJkEU+UC3fQCbnIAMaqt5P6k=,iv:cH5XLcYR+vma+SWcte/icro9hOgMV6Ffq7WTsRY7jwI=,tag:b2WzaE8Wxymazv/r8/RJxw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
