apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-html-restic-secret
  namespace: cloud
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:MGtwXmPnIjdiVHFm67a8OYLOvHZQsrrxVvnvyEjha1vh5MethbPAdgUUpGVwFu++TUmGMaHNczsf9pzFVIV7oI3k6cbrPWd92oZK9QYfAOdh7fzVo6Ox,iv:6Eh7DFMnZIwl/VvLdK+NCY7VkfX9vPMDcfVVnZNkBx8=,tag:b/fEiavit6oAC43+m+2efA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:HR9WxcCj7NHHbcPXWl6Kh1g5/QhriRxoU+WenC84FChwa0HyLHqtUkkvrn4=,iv:PvlTxDZmZwKtt9q9OhKGCXGQ4JeAy6sRMWQTDpAV7CI=,tag:yxTeF16P05gQ5JcK9NpxDg==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:C/eFOSx5kz7NEVJATdfHE4sQNdM0HG4x,iv:fa5+WOr7Ekd2X18UhDduTm8lnN/hCaXVH5b6EsX38IE=,tag:a1oW2SfTLlB2pwxXeEIbPQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:sVGJUgEdr+aqUWOHMp8k/ppSpFG6w7lrPqMJVSHWL6UoR3ne4xi05NwhoWqsqwW+mGNqpYbBcfnYD2bLTw8aBQ==,iv:9jkIeboxbv2VQ6xLrkevDPYHvMO67Ev3a4lTA/eKttQ=,tag:2c4ZFXIiP2239u7uEj7DAQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDVE0wNVNmV3FlSitMeElQ
        aG1RVzc5UGtaK08ydGx6bHhmZ0lCWGJZeWljCnc1bDFUamxiUzM3Y1A3RXJDb3VB
        RGlaZnFmU2lJT2MvUkMvMlVWbXRHWWcKLS0tIFN5V2Fpa2pBUU5udGMxMmhjMys0
        R3VWb3lZMjc5b1Fqa3kveXVkOFlsRlEKB5kIkuj40qefe4/sxoIi3yQu8peaGdBF
        s2ZcgbwtHGBJIVbkYx+f3qA2Q/RH/wCqo358nXqXMwJTic/03OMjfw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-11T13:48:06Z"
  mac: ENC[AES256_GCM,data:80FSU8BFbbxKU2u2DHv33ai4bX4sSkeUcwev3nydJGES4DUkpBa9pwV6PMblD75n/ywGM2OXChOgIqt1287FC040BkXpwotRUhmf1q97AuoJreHSoMx68dFdg7bdye17WDKrx8HkQZzhQKIP/wyZknp7OpxzWxZ6Ax1+ApeAt4g=,iv:30bAitrOY9n9TIydwQENeduKYJgq4TPVuTkoaZwiJFw=,tag:HG3iSMMzUClFjAZZ22DU4Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
