apiVersion: v1
kind: Secret
metadata:
  name: bazarr-secret
stringData:
  api-key: ENC[AES256_GCM,data:ud0jUOmo6QLm6eLSDG8VadNeV9xCfhr4/VZcE6u35Z8=,iv:OrAD/x9UMSZQPeXTiV0ieIS+k7SJsnlvlX4pM6LaLso=,tag:zjGZJb5Gc5sqoXLStPe/Lg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYWFjV1VSMXFqNlNtMS9n
        a0xWSTBvUm1jMzJCdHFpNEFodm9wdkZ4OGswCk1pMG1OMG85U2N5WUFhNWxnMzlK
        d0dvVk5TVW43UE9QU0R3TDR4YnE3V1UKLS0tIFNJVHFpbW1XQ0M1dm0vVHdDampR
        Vkl0enZmVjRJczdpZDl6V1Y5bFovcG8KQTUJwHEzDEh83cId6Tt1bftq4p60WGRg
        zSzgBfsasbZmSSipAVk+Ptd23uQEBk9e/DdIIpdS3ay2/4BhLPApfQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-29T12:53:36Z"
  mac: ENC[AES256_GCM,data:z78ZPncve0k7BjTvSrwO9lMJZID8detqk0QNvxI0c+ir/sw28+fXnQMi4MqOa0D0Ih/ELY7VGZ7dwaoLjf2W/doM/kqdQAFxDcZs805IebkJG6bnFW6F1IQ6B6uXASu6mBRMaFSzj4OS4cP3/aW2+QNOOsr+3RaSjsL8tBatBS4=,iv:en4sQQsSXMGpK3Jd0c+x3GfMeUau4LEi83wawIOtnsA=,tag:c7zjaCtEft8LGD9J+yTgiQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
