apiVersion: v1
kind: Secret
metadata:
  name: bazarr-secret
stringData:
  api-key: ENC[AES256_GCM,data:UADCB3AZby+s8pp/F4DeoU3bkA9vlMsWQ13GLYU0790=,iv:7eGs0HDZqgzKWCmoZ0ksZEIKQ/RFqhNzUVs2OSGL2OQ=,tag:YBWTH0NsiambSJo1bZbdkw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvYTI3VkQyb1pwVUFqNTd6
        ZXNOVTMwamNLVXI4Z2w2UW92NlJNZFd0RWdNCjV2ZU5NVTB4UHNhbGFzTi9CWmo2
        U2l3L0F6L1BjZDF4RDdpL1BXeFpqRncKLS0tIHNJZ0N5OGFVVHBwam1uT1QraHlV
        ck1JS0p2Uk8xbXFlUkhkS2VBak9GSVUKVXoFac7/Cto0zyoD6x2MJKs0WxxxFaTH
        ORkccArJ13hDRLAZyzFVElWQEo/0jSQzkWYuZnfxtUwpS4bqMXiplA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-24T17:01:23Z"
  mac: ENC[AES256_GCM,data:Ikdhf1oBX1+JZUOZ9Ew1lQUzFw+g0jWpDzKUAnPipdmrnYW6rP+dcljMM6ERm9P/6KosNndpz60DQRNwmObji7ZcSEGb6PsZGcYbImQVSGrWkTLiP/VnK+kbhwFmLXQGUAO3Rdf6iyZHOzd8NqsbIly0z0e/xVwhzpRLP7MkOoY=,iv:tDy7y9R9LLT6U4jRaSB1+IePyH9UdGejftpDz4SuMnE=,tag:E+e0/NDLd4WuZGhnH+8vmA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
