apiVersion: v1
kind: Secret
metadata:
  name: bazarr-secret
stringData:
  api-key: ENC[AES256_GCM,data:tN8ea/sFIqBp5tJyOdclFQV4iV0uW4ZTEfsZqQW25Ow=,iv:lPWpMC23wP7WtF/rfU4WjupY4pHY1AjHUQrk7NA97og=,tag:GupsWvnMU+gUsAS0BvaZfw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMXp0SW9MZkpJd1diYnpv
        ZlR3aUpvRmZpU1puS1dHa3lUQUxHczFwS0RvCkZmdUF1RkNnalRpZWNVUXlmUkdK
        bFg2VlJ6NDIrM3N0OHhnSTJ6NDhoc0UKLS0tIE9RSDdFbFpDZjZXMEE1TStmcEh5
        QnFzMFRUODVNZS8rQjdPVFg2SGFNbm8KzUgRmZR8Zd7+8BRfu8k0tD9EFh4x/RU5
        vAp3D8xZeY9XuIOYJSHlHRhOX1cAggq7OnGmyBWdokhhHNKMq2lVfA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-30T13:34:16Z"
  mac: ENC[AES256_GCM,data:d78FNgzX8pupWNAIa+nqnhhaVlAxnV58qr8ZVnDVmqlDCiMOt7bAr6eMsrEtiYuHl/TxuyznVYbu4+7pCXS9aDFuS0zAJH2iZ5CKtUZZ/Dzhl/SQgzdS0cwK+m8tZTl1+wLdrL6d8nhMFl4Mz34aQNzMLEc7szGVVpFyFScCjC8=,iv:JdplzNZx1y0f4E7xf1ql6JsBg12gNz7TBbYhKWTdgC8=,tag:gfu516AVVZernGqSoo/mzw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
