apiVersion: v1
kind: Secret
metadata:
  name: prowlarr-secret
stringData:
  api-key: ENC[AES256_GCM,data:sCGm3TVC9pe/RYi1d+9ti+UEP9h/RJiljbN8JuBHHp0=,iv:4lNttVGltXJ9t+2kFguNkbecQYPIK+E2ySSyKOZTAIM=,tag:gjIrr5pVkuELAatsPsSJHg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVU9yTW1wYlduN1NwNXA0
        MDhaMHozeVdGbGlaNmhsK2JJVFBMeGYvdG1ZCmdyMGF4OER5ZW9CZkczc0s4a2Nz
        ZVRIK2VSMUdrcVdPRURDY3ZDcHMvTjAKLS0tICtJTnl2YTI4YVVtUHNLMWpKTk44
        TGpCY2tKUHJkV3FtQ3lHMXpNTWdlYTQKywd9VyzRTSILhYw8BnWVCGCuF+vUJD2h
        xzEUrIQ9mDf0+l7jLDQgGWldxFCeZDtBfUIn8secno/SQ3uppmH9Xg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-24T15:38:32Z"
  mac: ENC[AES256_GCM,data:KkLl9BRCnlvUGfnEBKKITeMKueQJ/gNPdvxEgVg5huJpXA8gF5ztUyn/0RXurGmVi5AN50yQXeO5SsrnATuUKexKAMzJZy1Ue5+SHb4pJOJU/FYdAiR4yHuDJXZsZjfLG7Nv/ZfTYNFtcSLC4wm90SFhyUOSKYKWRt5KxpT9gtE=,iv:JMkbj3lnFilwC6mf6Cr4yYmqRYzliIAvG4foOefyMuw=,tag:DoYpe1sqYPU59ID6r89/eA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
