apiVersion: v1
kind: Secret
metadata:
  name: prowlarr-secret
stringData:
  api-key: ENC[AES256_GCM,data:+0AS5iWlSll3qTG92OCQlglnnzhlgz3su6l+Krbu4j4=,iv:23fOXhstiMKLKNhg+2bb+uWPjzBXJuupuZLQTiY/Cic=,tag:CPdvnKZWUz5Ch0kUtzZQ/w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaa2ZhaHo5RU5NejlZd2NJ
        OFVBNTUvT2dTUlJsTHppcHRDOXcrSFV3NnpVCnBMMS96ai9QdG02eStGOWhEckFv
        SU9JTUFEbVYzVytPRmZ2NDRKTDFOS2MKLS0tIFlUeVRaSUdCSGkxMWxlT2RBUFFq
        L0djMDkvV1pwQXY4LzRFbmFSRUVVRVkK8YrdZGsqD37d6z75BH5SM67RS8dGG9Bt
        ntIUbeIVJfE7Rpo5koyHu5M+qd0TBptSxtuq7PtjKP0jYOKQNzvNNw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-04T13:01:06Z"
  mac: ENC[AES256_GCM,data:Ego9XC4UKdc3g6eX7NMrbvws2rAU264VYOVGyZNdpjA7LmcXablGqsF35EiukEKSyVzSCIyKEgS0usMeaAm8vvr3/LSF8j/Fdj1FDc1iHigF7btV0b3ChU8b349JUrC7OdQaxJAHjgMszNO8ACla+iDp7XBpfEstwhzh8ouUksw=,iv:Whx1BiBm1Q0SmgEK/mwZTYWARxccov/b9pUVoH3cMbw=,tag:KhP6/T72QS9FFDtQhdBF+g==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
