apiVersion: v1
kind: Secret
metadata:
  name: prowlarr-secret
stringData:
  api-key: ENC[AES256_GCM,data:2HGGsHXCzDBa42yOVzgg+klT1ZdMX472lzxIDriSg/g=,iv:30MJeJPMz4V06PZlO7twIMEKg7N9H14x/Midnn9Wi5w=,tag:AmZ6GI+1k4vLCYW6sKr+lg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRzJPZGNnWXV4Z3d1V2lT
        ZWlZa3FJTXJFVDIvT2RjR2NxWEN2SzB0WkQ4CmZNS0RnNS9DWFJNbkxPTW9Jempr
        SVROS0FZZlpUclcwcDRCcm8rM1AwQVkKLS0tIGk4cWNSZXFJWnJ6TVkralk2czVu
        K2hzU3pFcVA4aEIvTUMrdEVYY2dJSUEKCwkVlOYiPoVZchVYKy4XFkzoSCuJs1ft
        PvHI4Lyi7unZLLcpAcQT766Y2bzimztWnecrk3O9X3RuSCKamN8vGg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-18T09:15:12Z"
  mac: ENC[AES256_GCM,data:ZGOXogxQqyxcvRA0dDkk52utcweCIqI8Nz8/qkRTTzQtfNaiKhawOiTiBze08ZzGg3b4uLh/dpE/OY7bunjNgrC9oqqyMaQrFBbjokVWbJ+QZUD93NQKxyBQycpeteMLQPjHp1HP8R5zmN9C5+2LzMkXBVBDgkQ8pnKA+XsLTK8=,iv:5soLyf+QmqC1RlU5KGrpGX4OjZUpqCf7aBcKnbCzIig=,tag:CLJSPIiN8WPNMZPKLSI08w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
