apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:0/yXMNhDl9xC3/h6KyeMfRcDeQ+DoFwoUsconrU8TqHlKqv7BcfV8yDxI3lB8qmRCKyTLh7gOYth5UKHPBHFOoOfFMcekcoRmvnAM9LUf72ifgPsbrRV/GRp0ZWBOtiFwIybTt+g1mMjFhsa6GxnvwUVqg+iAQQjx3W4icjCLSMsUbBuiL6Ui0Dq2/XciQz0+Yrb9VV++lSIx5rbCO+HP2AuhelCaCPdxRwxU6d1/d79ha2X,iv:u6azWgmrgoju4/qkyOmNA/0lo8qYKKqLi8aNOOTNqlo=,tag:woTdbcJ7fMU3vynw8pZZZQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORGZRUEtxL1hlcm1oYVpo
        a0VOUTMzVkE4VlFjald2ZnIzWHhyQlFPQjBRClcxd3VOZHVYWGk4ZjVkc2FYeXZj
        S0p3THNBMjFzQXlsS3o5TENhRHo0SW8KLS0tIDBiZzR4eW5YcnBmWWllMHl0OTZq
        dTlLVFdoMnBsRHdzYjI1Yk83VGJSRTAKHVnSW/xT6YcVajHDbY1tLv30OO1gCR7/
        lVIyWdIfFH2BpnMTAK9N/QQKn/wKfjY5/PcCajcIKByrPyQOjvlpAw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-23T12:13:04Z"
  mac: ENC[AES256_GCM,data:Z3yHJ+FAFIlmYPf2kPa1goezbYdjroGGJC+QUzAgZ9EUhdSLNZ6ZTbQbzcgvtKrcEsuYpAkfi37dUYYkEnFvLNflLqOYGoFeIkArWG+GgiuCrwrO6lEL1I8qNJjxIiEDTnzEybzDQnVZjOPhHnYx3yUip5skdw/BAGJDaauEwNI=,iv:mGtDZNsa9dvEkDkVY9adIsGHLEnk68fXkCbzltjZPyE=,tag:c5Igm3PZOOKqyE22CzOBKw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
