apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:BfBTQAdxCGO2NqI8W46pDDyhQ1Y2ZFwjLxSTMrLDn+U5Ul9Ovc4z1Gm0ygmfNXzYZCdiV6+yCQA454U2MnVyx25UrSoqRlB0EjvO+FJXtwSREqP28+I3wEcxp0+NrMpB7DlxZ7RoCg/AKJdSrTquttoyKBAgpHo03D6XiyDyQ0ne+iIi6vzqkvK/ZFm0PvU5lz6BeMTah8Cb4sMwlIwS32QTlbyHZBIkY28Rb5tEIIcH4MK9,iv:CJu5S7esWwLIOCAPubxIVV6JeLPD9bgWcNGKW+Ge2jQ=,tag:D4F4WctHvKx5yWmCN+M2xg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXaUdMNnFWQ1hGTjBBcmx6
        di9ONnlvN09UZXJYN1VGck1OelhJaVRwOURZCmVFUlg1U0J1dXNNVUdGWGdvY1c2
        NlpKNGNJdnNPd0dacGNoK0p3MnJqc1EKLS0tIEJteHFQbkEzeDI5aHVVeFBhd0Jq
        TVlybTBmU3NjSmZpazFSeXQxWWR0Z3MKzuEIzmkrhJGEWwxyZAdjREs+5rc08jv9
        T/88kW2qWUrraa20tw2Kc4+gQskFb2hP8CKPNu7T6/BpT5O3vke1vQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-18T09:15:10Z"
  mac: ENC[AES256_GCM,data:rz74flbLLOZmagk/P1az0qg92EFkGMxaen24r5c1R1Z3WERiDMWYL1Ozo8GEijimLwJlJeppbn+L/i9l8RQuM53d549G7LVI7tSA4DOLgA2rYs+lHrN1Kap4ddCAUfsdz49mQ1KxU1q+uZQzycIfOLNsOiGOuGm1jXTS5uq4e3g=,iv:toF9UUAaEn3W8BPvMTiHPAX4kxStTwIyHRNKlwgArkk=,tag:A4PdkRy6ogmdVQx1jKnqdw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
