apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:ilBdI+T7Epewh2UwGj5huejsTFxEobCaxW6ADS4iok74KqwnZz7f13XElIaq/8qGnYPCCXicRA1xqiD9gKnbKyqH69eF5BLysYCzUp63W8i0cJ5VircTZPFFCLhtGdRjWoJFNKNVFJd00duZSYLgEk0E2+nS7RcYya5ho67HrHgvvitImIb0VlcqE9iT/zJNc7j+U02B+A0Xrk4xaxTeru9Rr1ShrEiPhbNhAkws/iCduG6y,iv:b0I/i50JDzli03tjnOcxkY1hPZ2ykxBpH9WRauprjsQ=,tag:jm4DTppXf9Edk5RnNdTQLQ==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZE81NXBKVURjaTRqN3E5
        enhkV3RoSWtOeGtoN1F6UnBUL3hBVWdYdkJFCjJ2Zmo3eUdjdW1oVkRYMXU5Yk9k
        dHA5L2tPUEM3dDdpaWU2blFmSTNiQUEKLS0tIDlnQ0ZsaEV5UGlBQzhkR2U1dUxM
        TnVzZDFUQ2hia29JRDYyUFJ0eXQ2OHMK3E/SNf9mFmSPUr/RxgmSpz9AbPUPZo5W
        PdXDSM4V0xgCj/k5mCQ8uPm7GURUnDCtgYv4eD1IAX9B9IDDNjTC8A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-17T17:08:51Z"
  mac: ENC[AES256_GCM,data:SRtvrKbM2zAsDr5Nsv5R4ONCxV9B9ULWX/vmGdCng3PwuwvaltF/oE3tGKByjkW4hYO523FAAsy4CEeZ/exLrVs5GoB7/4uE6Gab8t/tV9mfeahcb4XudSthVG8MerrXW6kiyECqjeyOzdzU81TW9zGSWZ9r6fxmDATvbOpkERA=,iv:/lIt3zC6gMCkZyO8JP0D6l1iayqp/64WCeFj8PvvlfM=,tag:Jg48P8wkzEJ808BshVZ0hQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
