---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd
spec:
  chartRef:
    kind: OCIRepository
    name: sabnzbd
  interval: 1h
  values:
    controllers:
      sabnzbd:
        pod:
          nodeSelector:
            media-node: "true"
        containers:
          app:
            image:
              repository: lscr.io/linuxserver/sabnzbd
              # renovate: datasource=docker depName=lscr.io/linuxserver/sabnzbd
              tag: 4.5.5
            env:
              TZ: "Europe/Madrid"
              PUID: "1000"
              PGID: "1000"
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 8080
                  initialDelaySeconds: 30
                  periodSeconds: 30
              readiness:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
            resources:
              requests:
                cpu: 15m
                memory: 256Mi
              limits:
                memory: 1Gi

    persistence:
      config:
        type: persistentVolumeClaim
        storageClass: longhorn
        size: 1Gi
        accessMode: ReadWriteOnce
        globalMounts:
          - path: /config
      downloads:
        type: persistentVolumeClaim
        existingClaim: media-downloads
        globalMounts:
          - path: /downloads

    service:
      app:
        ports:
          http:
            port: *port

    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Downloads
          gethomepage.dev/name: SABnzbd
          gethomepage.dev/icon: sabnzbd.png
          gethomepage.dev/description: Usenet download client
          gethomepage.dev/href: https://sabnzbd.${SECRET_DOMAIN}
        hostnames: ["sabnzbd.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: 8080
