apiVersion: v1
kind: Secret
metadata:
  name: forgejo-runner-native-secret
stringData:
  registration-token: ENC[AES256_GCM,data:haDOY57E2fN2h3jyMAv8dCImsPsrxVWQJ7U7mJ+z/w1lCZjZJbaQXg==,iv:k7aFWqKD7zTUwRKzCKjk4BBFUDMQs4SaC4nGRZ0IthU=,tag:ogoZLdIre8tRDkKL3PUyLg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTSG9CTkdndHlSOHdpdEZx
        eWh0MW9NUHErVGJxV0FYdDRsQzNxRlRlK2dVCmdPcGtxU012eXREQkQvM2hCQVln
        UEVURlVnUTRvMzJMMGRGQUpJc2tYNVkKLS0tIFMxa3YzSUFaU1dCeDhuMHRvWG1u
        Vm4ya0J6MEhXemY3N0E1bUZtcWJodFkKybDwivC2sFoqp2Dv7pkQZIfc3UnpFiwF
        M2aSuuS9KiZ8aVv+1GZU4CvXLGFWqU97Q0++BJIe7yupkzZkIO7ghg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-24T13:48:20Z"
  mac: ENC[AES256_GCM,data:od/SNxZhcYvimUEXbIlGAk9PWn7U5oyDbQ531qOgXG0gGdcNDC2olYAO6oozpAqtvMMmMTFZ5QVpTOZDoEh247zOqHxSPtYEu7CTt+C2yDPEf7JRykzDB7b6XyahkAQml4aCq/QEr5K1uEVpQAqrEhVZBwYbS88yd5Tm7jr+7qI=,iv:NfU+uH8pC7koPWfrZrWTnLl54a82ZgBz90C7X/wUkuw=,tag:3yoVhBoDR18aZc89cYwcwg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
