apiVersion: v1
kind: Secret
metadata:
  name: forgejo-runner-native-secret
stringData:
  registration-token: ENC[AES256_GCM,data:U8hOVfToXqoo1oyw/WJwT5SbvZuz1RkHJKaJrEO+wEGcGmsR3vWvKhtWhg==,iv:/qVgzj+FU9aumBaD/X4L2FXPbhiwCe6jwnrd9hMxLAs=,tag:6pj5Z/si00YiEroXYqTBKw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYzJWdnl4OWc2RlhMUHBC
        elM5ekpSUzlHRENIOUpVS29HZ1p4Q1ZPVFFjCnRuRkJqRVlvMXlKYTdCS0JEdXBt
        QzVzTkttaTFrajNsR0tKaEtuUUtvTE0KLS0tIE5TNEZHYk5wNGZoS21IUjR2Z2hV
        Tks1Wm1jUmExL1ZyeVU3b0tRQlN6TjgKP+4gH+YS6unHWbXfjiXFZJP94n4pEUmk
        XXfZ1LzhsHC/VlyEBoiU78Ex7V7JkL8NHF6GAa7P7dqnmSdiY5v6+w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-28T11:31:41Z"
  mac: ENC[AES256_GCM,data:OjQcmM74OSli1qxQAfZucZmfv4TvOZcmLhD7EmWyHh450n0chrxcXILBdCWBWr3skKuSukn9mOLHW2dbegAppwcY1LLEhXvbh4fsMKUa7eUefjqJU8peXRTXmLC/FVWBWFQCk6sGwxcKYAniYHvBVMBknwGvvbMPa8BG8Zzc338=,iv:2gd9SrzRG9AtgF+3B3QsT1UtHvPLyYHCpMrloq8TXL0=,tag:5IoIHP39mbJepWO6gwItNw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
