apiVersion: v1
kind: Secret
metadata:
  name: forgejo-runner-native-secret
stringData:
  registration-token: ENC[AES256_GCM,data:wqgFxdq0zsl4ewA6oxZfv5DNhqcMPor28/20nBd1CbqjHyhTcXMqgYlxQQ==,iv:yV6yiacE4OHsnGEVL9LL3lHwEzFsk6frVMwvVtTYV0k=,tag:cVthX2Q54H/jSQ3kJ7rlTQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiaUd1YVFnTWkxeVZSNVpW
        eW1EamRBYXJQa0tFVW96ZmowbXJFUm52WkY0CkdrRUZhU2ZHN1NVMlBlc3VPUGlj
        VWJVTE5zT0pVODhETHhSdFFmWndCSjAKLS0tIFhNWTVXUXZFZ29pS3FFOE9WdFNR
        OS9lYUZibGJFbmtrNFp5MTgrYlJPdUUKImZiRHzM8tGzeRKcNgCxcBrtsN6qdfGQ
        dFC5OgKoMbZJYQHNriDNecL+tZnAxUMB4bu2KDMDlKRlM/hnsFgCuQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-04T10:28:13Z"
  mac: ENC[AES256_GCM,data:WMQVqfvEm8jlfmtsyO6QsjofohixYd5iKmTo6Zun6UTi7vi976wTd2BS35pFOhajgLL0ZbU5lqQ4fdmLlwuT4KPvNRGfB0kpdlQELXFVasQZDryxDRI6jVIr+mW8gNtmL2sytmM95p0tFw/uLXiYEYqQZdt8YZGiFjUL0NEmNQA=,iv:LEGy0KQpdeNbSstqYVBqkQRZiNP/Sroz2CgqhP+yyVE=,tag:cfdRe7iif8/atKtok/ARow==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
