apiVersion: v1
kind: Secret
metadata:
  name: wg-easy-secret
  namespace: network
stringData:
  admin-password: ENC[AES256_GCM,data:uCmqKNkBs0+MuiRs9A==,iv:YKpzcmHtaTPcVaECJGRC4sTwGieMM1++zPboKSlv6JY=,tag:xE27uVoN30G2Tfpzg53I7Q==,type:str]
  server-private-key: ENC[AES256_GCM,data:GEY4rOQ4xphBo44tJY809UG0qHI5TqMlu1GMu+ATje2xagEwkOtsKghgjms=,iv:TKqMmagMiA0m1aUqNE1Rf7b/C9vuTzq/mOfZWPPZ8K8=,tag:fpbjs0UqHbeTFvGWCRCWRg==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlS0tLWW1xRUp1OVRaRTR5
        NG9vU0FSR09Sci9DV1p3UDJOWWVNMW9meVN3Cmd3RjhIbzZIWkU4aEZHSTB4dkpZ
        SGMvV3hPMDVoNUg2RzhTenFicDA3RFkKLS0tIFJObXJqZFNZR3Q3NUFxdGN6ZGRj
        RXJNMWlncGw5U1l3NTJvdUxFUDlBREUK8g30L3kRMzQNAGl8p6FXLbwYj79iYeLk
        GBH4EcF2NAw+kTjGkDep+XEDC2QwK2/Js9hWQiKm3l5JB4krVBfpuA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-24T08:06:14Z"
  mac: ENC[AES256_GCM,data:Qz4GCzc9G4JQeGNB713zaMQtAyzDC0gFBQ59eNdySkW2tdFaNHF0CuqNklysXQqk+lSjUv2UNDq1C/HU6BRi/lpalxVJihN9TxV9BSUCgngNy6CE2gFECFfTzvhlhzgnJ84V4di2zI8859eS9QkQ5KIPYvZklQSollnWr+p0YwE=,iv:FD/pMUIE8/xpq8hpO+SwJ+rMhRMfQ8UZixcJ/gBzCoo=,tag:JjOXWa5pbvBSbEGiwSeG0g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
