apiVersion: v1
kind: Secret
metadata:
  name: wg-easy-secret
  namespace: network
stringData:
  admin-password: ENC[AES256_GCM,data:SUjejRkrVhdiO9qhjQ==,iv:iV/8+E0blG6YjVvjLMWKm4mDaWvmvC8pyyKDCus3ZHQ=,tag:3KVWZmjDKjfjG3dN18aP3g==,type:str]
  server-private-key: ENC[AES256_GCM,data:n/fgordhjuIU14alVDD/7u3BKMgpRF7INQvy7WTWzAPjJdQ4IXD4vpvkPTM=,iv:k+2kvWhhBk60hVfdSF5EubW4ZL8VI3vWfwXDvZ3TPBU=,tag:6V2Kwxp2qj24fjmkooOlIw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpb3IwQzhtVXl6U21EY1FU
        d1p3MTM3MTBvWjdKaysxelBhTmdqaUxIYzBzCktlaU5qYTlwR1F3cGpYWjFzK0VU
        cTNJZjZzeUxjN0pUeGxjS3NZaEtDV0kKLS0tIEQ1S25TbiszSnBYR2RrTXBMMFFU
        MFNIT3JmTkFhUUl5Z0JabjR0dWpMdUkKbKqlQq/kbNENSXkzVAneea9iblvS8JUw
        acW9l3360sIAu+CxMIYqJ4sk06vZEPRiNg20JQfxkg5b8rq77yl4GQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-11T12:53:43Z"
  mac: ENC[AES256_GCM,data:Z49z+srjZvjdNfUWifpO1WdxTJ7J92z6+ndS3vMfu8RJskgCu55lxpGATrpHtz+XwqSAAjd6/Mk8I9nsT/nIKbSg0QVCtVT6iFYiP5VI87b5S/X0DQ9HOYv8o7nHUPPwEVr6qouBd1uEO7KBO5qgsBv8DC/KtO/2BVhWKdG0zAQ=,iv:FhgUphQXW1ObUEjNqedj6HaJup6s+HUzdqNgcEqdzKI=,tag:8nvg0uCQjM3uRWZqwdruYw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
