apiVersion: v1
kind: Secret
metadata:
  name: wg-easy-secret
  namespace: network
stringData:
  admin-password: ENC[AES256_GCM,data:kBDiPODz6BGH7SGSMw==,iv:T2DPw/PBZ6qi/3ZJFYaP7QiBLG9iw20x6o+l97yJZBI=,tag:4r6IFZYp1W/5mMvkek67sA==,type:str]
  server-private-key: ENC[AES256_GCM,data:3fD/mbSNk4A8lfkXvX2cTBzq1k9iXpS9VWQqQh8YaMvl2y3avQRt7ckyKWA=,iv:enHt/qQsXNvN+xzU4/+mlRhsCmWPbpEBViVR12kMZko=,tag:Jc4Mkxyddut1Wf/14bfj8Q==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Q2FUMm9uZFcwN1k0M3N3
        QTUxNHJ5V0VoanFoT1VHVTZyY0RzQ1hpblZzCkU1NExKLytVMzBhT3RQYUphbWJv
        UzN0YnpGTy9mNUk2MktkYVJmN2hFR1EKLS0tIG4xb1pjYkN5OXVEOThGanlFckth
        ZGZWOXhMREI5TUx4Q1dnUng5Y2I3UmcK54s8k4F0R44fveIVbKbUNcjB9ZcPbNNS
        iXgcKF3lPUUUPWWIOxiZDb9RjLdB53yC4NGEvPC8exEEYB1QlC6e0g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-21T12:36:28Z"
  mac: ENC[AES256_GCM,data:fYV72Flb5bwMQ+CqfgyBTovn1r4DC1LMhBc/c8qF8pyGnIv0HHfoEOF8EnTrmD5nE0lnMQgB5oKp/pqQe2rSRghFOQ8QcCdG2ap1CKJxnkt6X1pDtQmbzsphG8+k6cgwXnHAn6Ky66n81Pc4AstpluigIdHiWaHMtE4fqzBZq4k=,iv:w03R5VF8eA19+TkodF+tO1hjqjXtGCBpZ/Ylb7+/RzA=,tag:FrWzo0tpLm1gVh9aGrWVnw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
