# S3 credentials for CloudNativePG to backup PostgreSQL clusters to SeaweedFS.
# CNPG uses these credentials to connect to the SeaweedFS S3 API.
#
# Requires seaweedfs_s3_access_key_id and seaweedfs_s3_secret_access_key to be set
# in cluster.yaml after SeaweedFS bootstrap (see seaweedfs/ks.yaml.j2 for steps).
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-backup-secret
  namespace: database-system
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:XiW6ZfczNGKdFj6/XAzr5TP40n2+EMr8,iv:pMNRAO03uehLKNmA1r9c2dsaMnr3HuGhhIe98v/K+WE=,tag:9ZGP/KX7RMDSWHjce62X8Q==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:WxZmwvokqnlASqt/Bah0HGLIdleQRSxThikMdRlgO7R5SSxdFky9lJ2vdVP92FHRmUyQqktz3aI77EY8403yZA==,iv:a/Tx+q+dPrVje+NRzyHVmfUcbSCyDmjTkpSJrW76lRw=,tag:uyjS2ilxabq1b+icZ2IuFg==,type:str]
  AWS_REGION: ENC[AES256_GCM,data:1Pk4n+Ot/7JJ,iv:udwwMRKLe0tda/3W7AM7EAMFcV60Pcv9hS8gg3663KI=,tag:lmscCOgwOuyiz8qeYF5PgQ==,type:str]
  AWS_ENDPOINT: ENC[AES256_GCM,data:p+t9k4gQrW7nxjSn/N0D/6/JMuZEp7gkucODxXbTdnLdbpw0LU1N6lC0kowK3rLsY16j7UQ=,iv:bKANW8hDd8VycXj/rTJzINwEfoAw4ARNjNsjhJe4UsE=,tag:zskHamQVpY0Wcnf4426ygA==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBbUtFcEZaWm1JRGRJMnNa
        c0djWnFYYUJPRy9DYkhCTGtUZ3cxTEVkalc4CmdmeWZDOHJ0OGRKSVZIODZGT2dl
        OENnWjBVMVZhb1Z0by8wcEVGSDBmR3MKLS0tIHRVaTlRZWlRZVpNcXpLQ1VKVGlG
        M2FrSUdadTA0cVZHcmUxZGQ3czljU1EKfqqefDr9xwe+iJ8B4XZVx3718YOvReIS
        TlwTVvNbQkMH0k6mXI74zeoD3U7D0YtzrhB6l1d/kSuStN2iTv51nw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-08T15:47:05Z"
  mac: ENC[AES256_GCM,data:htqznsekPdne7pb7cuUvnCNViPntHm8NVUqAKnxIQMTpQX9ImBtfsvEVb6n4lZGlSVHsj3lWoMQeuMKWVJsjCQleZdLNv5V1TGxhXOChByABFvE1v7hEErMoD04StEMZD+uAQHb79P/gm2MF0fuawCFyoOzI5FHfgIFpxnvrZQM=,iv:Ik8VT2/qXunKChevKJ6aAB3nsLt7K/lLeM+yUD+B2Fo=,tag:xTTr4d/Ye7bFydYWKAjZLg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
