# S3 credentials for CloudNativePG to backup PostgreSQL clusters to SeaweedFS.
# CNPG uses these credentials to connect to the SeaweedFS S3 API.
#
# Requires seaweedfs_s3_access_key_id and seaweedfs_s3_secret_access_key to be set
# in cluster.yaml after SeaweedFS bootstrap (see seaweedfs/ks.yaml.j2 for steps).
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-backup-secret
  namespace: database-system
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:5tofLbeYAgdoijfqqyQdZTxiGvLAcfVc,iv:gm1W520GRBWSk7pGXb9+DRvVO2T9q1TS12eiwEUznlQ=,tag:e2pcBzrtL/UW9daIIf9SvA==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:/1SytjVYh9xnxz/qlcrGIRT6GhWg6C4u+xiKACYtSydJg+LnItguTiDJxwg5WHi5FJzxI3J7fd4mwtFflx9saA==,iv:gACxIASsMjq44OhEohaGT1Kwi/UmWrzsS+Not1rqXas=,tag:cQ6g3TM3pIgIZQ2eCwYVGw==,type:str]
  AWS_REGION: ENC[AES256_GCM,data:AgycXOuOls8j,iv:nD1D857QK7NbRNbkN+ex6J+2MFFTcwGsVPlE/R+aC0o=,tag:l9YUYH57XK6XOIIsXpBPow==,type:str]
  AWS_ENDPOINT: ENC[AES256_GCM,data:XFemX6L79mUGfQ4e629qRPfk+foPNxBJDOI5oNNA8dBCtTpYap5YU6KeIzQPuZ7iP2TUQd0=,iv:dPeD8DbX6D6ukYD2NE4MUid4Tdd9SzFiYUX/qww4OYw=,tag:XvWnJS0F2Rb6mN2/S7lLIA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Nkd6aVA2VUtYQ1Zsd0Rl
        V0ZhZkdyNDZER0VDemR3dW5CejhOTlNncHdFCjhnSHhhU1FidnB0dmY1cXRXZkVO
        Yy95b3R2SS9IR2R0Q0phdmU2bVNXY0kKLS0tIDBJNHZQcXh0ZzhoNzZJOVVuaFRI
        TVY2UWFNdEd0bkVBTURuNkI5SkhBTzQKylYtLATmaXF17hMXlUKenolxeZS7AMXy
        fSWoXjRLSdNm2LM7ZuT+wEj/x2ZaqNZeLW92fjDW+wiYHv1bX8c8zw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-06T15:52:38Z"
  mac: ENC[AES256_GCM,data:SEBxLLm32qAKC7Di/ueIMlyO53l57rJCyLXgugZtqDNoOqbOBbewwAmjS0wLA7DmI0zRFz/iG+RqDhqVjYTcEvxFcWXB49wyZ+3KzoUNqY5/Ix/Kh7GeXVtiqIsWGtYTJag5mIXn2szJGDedfrLfPH7Osicp6hyrCHBu1rmfC+A=,iv:pI2sFxtBRk942Fbn7n5Djmsx/EQK4speoeukPJJ3hjA=,tag:FeyUPVbcn4S8KWnQBgYgmg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
