# S3 credentials for Longhorn to write volume backups to SeaweedFS.
# Leave empty until the SeaweedFS bootstrap is complete (see ks.yaml comments).
# Longhorn reads this secret by name from the backup target settings.
apiVersion: v1
kind: Secret
metadata:
  name: longhorn-backup-secret
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:DerKeHIl6z9g1sNZtpKwKURVx2HmbVVc,iv:GP7bha4t3GvUg1mGmUAZ3ml9dwEIaBfF0iUW+i07JAY=,tag:rrw4SXa7YQ5IJ/66vxtFdg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:d/TwjMscA5461sU8yAVanlKvp5qhcrNqZZ3VL+wMybzf2uU4Z+st4T44dFCVrp/TwsGFATyvtEI+fjylPRS7pQ==,iv:KVYX20MZzJcplqRHoyTmccRI+IvaHh6R+078C5Ba8xE=,tag:B3Ze0US5k8tiqxz/jG1fcg==,type:str]
  AWS_ENDPOINTS: ENC[AES256_GCM,data:k2boBfUsO+8cx6vKMl4JKlIFbh6q/DWTu59k91T84/GnUC39WDBs7Jm1x/C4fyD5oJZ4y+M=,iv:gsnjD0NsohpUd4MPpIdF/aDWIhUyVVVpt6gxuL4R0RI=,tag:phsWpaz0aC6PKB+FIYc6hg==,type:str]
  AWS_REGION: ENC[AES256_GCM,data:7MvVDT46ET1m,iv:suwz3MQk8YU+jDO2wpmOczK65wEs0zOJ8gC/lHDYShY=,tag:RYQJN8XBRRvjYCOkt3sPNA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXeHdvOUdYUkMzM0pRbUxh
        MWl4Qmx6eFVRVzdKZFBSQXJRTXBaOW1QeHlnCnhBanFQWllSUzNiQkZ3OEdBVzdT
        QUpVZ0lmT1g4SklMdnFqN2JpMmVieFEKLS0tIEVURjRXTlRYcHM1SitOQU9ncDFT
        TDAzNnJRTFlsa2FhOW1EdmhjYTVMeVUKbwv6rDLSAZnd5Udn/l0nLVRHu3MlJ1X5
        rQxY+0FvCowi36pxsXBIhpqbIgeAoWLCsdj55og7i/JQY0xWs+3Pcw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-19T08:28:05Z"
  mac: ENC[AES256_GCM,data:26dO9OclgRmWejWvAPF1hIHLZxC3zh6OnWrT3xL388bWdo01a5axo83Y+g1sJ8kmK1PXz6i2g+jjpsg7awLtDQ+3YecJIjK6iYZysAZFfJrM+rHE/bgYK9jS+9Q+TxILUS1jj4fgJzrjH/XzWdZjt9xdvaX1uY0uFkdp1ZW0SRk=,iv:WkEZiXxvvoA4NyOgiADJ921Gvtmh434POnqouuLqvyg=,tag:kbVLt6Os9xIPuSTJOKS9AA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
