# S3 credentials for Longhorn to write volume backups to SeaweedFS.
# Leave empty until the SeaweedFS bootstrap is complete (see ks.yaml comments).
# Longhorn reads this secret by name from the backup target settings.
apiVersion: v1
kind: Secret
metadata:
  name: longhorn-backup-secret
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:wlB4ZwtlmEEq//W6duTEg87TUbIxVPfC,iv:exBmu7WvH6epOjxtqYqTthSyURtbrJ9olCQBYu3NSl4=,tag:uscI1z/dPsXw4yes01u1iA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:XvE46LikzwlrXnELJZ8bhSOt9WG8bqHb2QkpfUj+ng9n7iDddc6OAXbKzTl1YC7nHdXZtL+g2X0OKLbi+NlzpQ==,iv:f39KT5yAlVGETAVGWatOL0v+E0t9FVgXdI14m6+TjXo=,tag:v/Sf8gE0KnoOSkwavgZiHQ==,type:str]
  AWS_ENDPOINTS: ENC[AES256_GCM,data:XN48bp+1lT4KloZQvN5nnAdVLkYgcoDbvZ4dq7OHqIVEKQucpAqAmePxjiVRD4z1okqkh/A=,iv:0ZK0+VLHj7QTPlRClCk4BiP7ZZpd6jd+5/m5iQaltgg=,tag:U3xF4EvEYUgd1soGVq/+0Q==,type:str]
  AWS_REGION: ENC[AES256_GCM,data:s9WK7gbNM9Rz,iv:VvPbl+kDvGFItXjP35RIolQBBGwx21V9a2dBB6TpOh0=,tag:1GF1iCCqQCNvq/tUk1ZClQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUmlnck5DTnpHT3gvWFhz
        TjB0MUhvdUVIZ29JdTRwaGliNkdveXJjRXdzCmFlOG1sT2NkVnZKdGZqS29Ma3Jn
        OVdaaXZCRldnT3llZU13S2RtS2lvQjQKLS0tIFV5Yi9HZnF0Ti9Db2M0Y05QZFlj
        T2dLUVlwRVVDZzBYSkNJbXFVZjRnSVkKJ2jY2+tolaLFgvp7+79o06Yq6XRtz3/v
        tcgP9/TDhP+NtQlNHAnrOM5t02Ga5/csrH381m4jcWcXPQymvY9teQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-13T10:34:49Z"
  mac: ENC[AES256_GCM,data:k9ONdD+lcqjV/U12bTj89PyFlJo+/jFHMT6l5+we715bQ6VPp2xXkiLP+9lQaK6MIWH+o6jeBSdQruBP7wYB1qJbKgsvlT5etFqzrZ6Cp6z6uz30WeiACJad/194MrXE80LWt2fYwY+0tIUXilnFvV1sEtCZQEO2NYU7j0JWg/s=,iv:WiR2/dZxQRBeonfroq2oSZVJQ6O1uetuor6c+wSfLzI=,tag:dhokx945wsHK6lUKxzvvqQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
