# S3 credentials for Longhorn to write volume backups to SeaweedFS.
# Leave empty until the SeaweedFS bootstrap is complete (see ks.yaml comments).
# Longhorn reads this secret by name from the backup target settings.
apiVersion: v1
kind: Secret
metadata:
  name: longhorn-backup-secret
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:/ALcmTOm/24ow0jXJ0rSf/CYSQBednPm,iv:w30gAHNA/6jvgVFDCPNIQuDj+PSbjbXPqbmnJbxYVq4=,tag:YfvWKVEBN+jlbR2uEvC10g==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:jgLMWnZa6kJ7bqB7dfIfRDumxM+2wHnGL73zhOzfQZ83ursZDS+XYh3LlZ+hdNXWRCpi/tjsnOA2uQ7h3Jm0kg==,iv:Gi15v7KYhRo4WzND3t06TmEl4EGPlaUuh7knCNK9LvI=,tag:fKiTCa6Q59I0dUuuBqbjqw==,type:str]
  AWS_ENDPOINTS: ENC[AES256_GCM,data:vK/WjgGcvNTmUZ8F5hSrelkjcjOSnV6HmjKwcDhKNeSGSAMt44Hv+5O3P9L+oSrvvCqSHzg=,iv:NXhPMmqa3vgdrIoR91ZPaRvymz+BeBFLmcvVWzPaeSM=,tag:G0YdvaT8s08ojKpqDp9tXw==,type:str]
  AWS_REGION: ENC[AES256_GCM,data:JENNE8B/hl8F,iv:iKef3UNJVUkgDJRUXlxjVbK48WlAp9aWgnIRTCIlDFw=,tag:nR73k7mU+iJpUchs/OM6vQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTHp0NnFJemZ4NjBGeTRo
        bDUwNXh5TGhLRmEvK3BRbGp4MDVtQnROMENnCi8vTTRPdkdDOHN6TUV3aG5OV29N
        U25wTHZwbno3Szk4WDR3WUJEZFVRaUUKLS0tIEpLLzYzMjkxU2RCWHhudjN2QnJl
        UDYyQkV5TXFiZnMvUjRtNkp1Y3BRd1EKzl2yHYZ6dS38g9t8ipjqkz/kPRAILUxD
        GGomVaHc/a4akx6Jgj69/P7Bp7AtPZHwNZKHEZtXA102/1C68hAPVw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-30T16:27:05Z"
  mac: ENC[AES256_GCM,data:N0duY4zBrLaX0NtTWaYiwR3CMyMt0hvqPdIpUqgl2qUmz4S54A6wrIUKTqNh92d0CEtu/Vf1MdZvdlGXfZNoX/iXafgIyA4xwxc9Fn/l2khb07z1u0BvRwF9TPmPs5SIDa2T2lsoqI4pTkCdf/kplx3RX7Z4f5Oz6vN7R6lzWsA=,iv:y2CArX0fSMRMgdj+hHH/0GD9+MoXqRR3hC34aUs5rjA=,tag:/CqhE7PTBJqe/78Mkr5LKw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
