apiVersion: v1
kind: Secret
metadata:
  name: seaweedfs-s3-secret
stringData:
  seaweedfs_s3_config: ENC[AES256_GCM,data:ENLymKQL2lKgXqdM7QWhHsZU5GeIdZUPYV8WsSPV2LTyID2KCiQbNRJA25jYWD8wjmrbmB4VoqrVqoOOXL4ZJPg8ldtbEZ+m22pBt6TpwJJZutH86kmy+FHNrq5ZnT3o6dUPx7K+VlHCZFdtU5+TsvjhpvOKZjmPDd5FCyjviqYizAJPWXc7eGPIK2R7sG0mxdHyL/FQkwfZaHJ1n6jSnPx43ybeL7wD3ZVoEblFWidofYh9ArZml2qnm4hUnHxe/TQb6dTvlAKiGm8QwpR5OKa3fEY00IuSYa1HWx+j3LcfWqnkht3BnaobK3eCr9cn+mhQ19W6XfgR3nYWKiMzUL2FyZo9HZ2JQtFODkPBcbHOJvPTmFpq9bSCHDah0jzymkhwoysWjH2u4+vitEddrpuLJXy4+p/4jnrFZjEE3EfCQ0wBCjbIxDSnSmc5gjzDYqGYif0880rIomYstnIaoIBnXNmcVCRVzt3q8qI=,iv:v6yPOtRpy9ph3lD5N0ESIIyNFfs9tvKysYA+A9Pwff0=,tag:IkJbqdVUGRjSjIq3A1KZzg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1SXc0MTA3SEtUenh6VGx6
        ZzdoQlpTU3RoQjZTOGUwaG81SjZONThiZFhnCkRGOUo0bTMyNHJqNWw1Y2N1TGhZ
        K0VaYUg1N0cvVWYreXhwQTI5b050a3MKLS0tIHRQNnUwVGhBcGJDdURXS0lsY1BZ
        bUdTdFBwcWFzdGRTQ0tpY0E2Zk1DYWcKb7SZnCSZKl7ThETdyEoBfu73IVg4qPar
        NUKOBnCITaL/7qyDbcDZS91wQXURYzqQTIoiYQiGLEZ1iW7oCyfxRQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-24T15:58:54Z"
  mac: ENC[AES256_GCM,data:GH8mkmHTsk7n9j2e3keDGueeLKr+nPH0iJRFNb2V4paT4UgVQXqLhBBm5E3vQ5kyNQuIBmGehsplmlCMdE5Vm1K1WugYnpU5a+8UktudlVsh6UKt78tr08CNvClxIPBux9/mgzx1gWkirWPztf2WCtyvz+ZAhL4xFTn4AX92AbE=,iv:dbLSQqZtX5kknrwJXNuoAQ1yhZ9n2Uxzsk5yroGdOKE=,tag:gRh4AdbITcvrYj1Qpry9Lw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
