apiVersion: v1
kind: Secret
metadata:
  name: seaweedfs-s3-secret
stringData:
  seaweedfs_s3_config: ENC[AES256_GCM,data:H3244RJa1/AE8SxaUR4hxfo4ty/snR03IRaJhYwmMASGV0sSSdAUfw4ixkioaINzqh/+XP4wG+VHjUn+X+VPU2lkNKRIUx23YYDDVS8X3/c0HAoTkfR0DGG3gqKORmhB6DQ7zFp9ibMcAVzwn2iaSpX2SAwqni8TI1h4npVB2gtnWnrzzl4gF6EEr9KRmoHktUfaJorCTyfwgUWC94JKNTsrPnL72WazLuVMPlA5IcoHJcdjIp16R9ccLcnwzmR7ZiCVSdAJoTHTFCSP0dIDQxdAzT7aR910ByVwUEjsQYQGRkQ22HErmTuwncz9Xcnwbw4hS5uMujOKlkksP4T67BbqU3R0wzI/pR6wXAB4mJYOr63m6dBFHUFG4lZSXbK9SuW9Us6cxfcIeWfB395dAoxktmVqeioTKKDRTl+Xkqa9LzhfAMznldICNqk4FT3OvL71nIlKkVKpjMqg/6sqmUNP2atyiZcSmc/ghDM=,iv:rUO2hVrpBB+kyILzyur0GGRaugCldfgmtgUdMbJCVFs=,tag:YJY8aX3blxfgQaSYp68bVQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiM1NhazF4UEE1bnBWTWZ1
        Q04rUW04dUJTVWh6R3lHMHlLUEV1ZlJtUWp3CmNnWkxrYUwwRTBzMjFqSWZNYzd1
        ZUJNOGxZNURNdDNrU25vbDZmVDVtK2cKLS0tIDlQdlBZMHVnQWF5eUxKc3REOSt4
        ZWx2dTVFRUtHeUNqdytWalBxQWVQdGMKosg4DCDrQY4Zl2r6ciiRSwPHSzN35GE1
        Jj9tBzue+Lw/nwmU95O05UtAXro9NfOCJ74roxth6eJMgMjLX0ud7Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-29T09:48:07Z"
  mac: ENC[AES256_GCM,data:SDKrq8eR+2IU3n4GAlXfYD71haQ/D5YRj/lPH4P5lm6gOQohLPUgo1MxFyVO7L/37sjxOP/ULPM8uu1dowC8QAxg3gC8UBWZ2wyOSb1doYGyo88TcLXx7fM4ffhr5XDuMzcCR6J1LuYZRbqxfahqesBCXY2u0lgtXwB0ytIqmlw=,iv:N+j3B+aPcEwgiA6q/npIAhLFmR521K4HyPZa0vzoRLE=,tag:b8FYYguBb+FeFAmGeId9JA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
