apiVersion: v1
kind: Secret
metadata:
  name: seaweedfs-s3-secret
stringData:
  seaweedfs_s3_config: ENC[AES256_GCM,data:TzxJjdbBpYQHv0w6iSPfSv9fQlFi7bYuvyiN1mYSKjYY/9X3dgMQ7k/mFQUfbSlydGun3lCYDZtHxaZO0cLAKCAbZjscKkZQBSVfYkTLSMzz0Owbdi7q7UirBTolsxuTkXqtx4pOMeB8IuLt2TXZt4awxBiYiS2PAX54MuLKI2OVC1X+sFWMf52+h1Nl8qyBsegjOyWJM9wgML9M8ulm4WAbVPIBlafaUClhxh6RZX5YCo25DV83J4wMKqY2lbFzNbgnp9218S6j8s4WDfCzyWXkUwhWi1FSibm62zPrCgYrIFIBnETlt8zOTsOLMTHbVAyLnoe3Exh5ssHW3n0Lq8zBWP12nFGwO0TpJkGJznJk0dkpzFMikQ28/UhzXTRLJEuJOkzOh4qMgmhwJur4zhT95uxCUOTsXJ/V7MsHfowpj1zyPC8Vm7Bmtqr5SWxuwhduwPjvn1EhzQbXvlA43+m2VE77k72lQrBNx6Q=,iv:Fmz4e8QjEQkNBi/CyfwEPcPde4MwqYOGtbYr0T5oSUg=,tag:nfFL5kzkiPb0Lwl4kQlDUw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5SFZqRXM0bm5WODJ2V0lU
        aXduK3RYZUFFc3dQOGpBVWpsYzR0M2hOM0FFCmh5bWhhZkdGTlNCOERnWERYZmFK
        Z0ViQ1RXbngzY2hpVXYvczN0R1pldjQKLS0tIDZyMldVYjVubXdzY1NTUGdyYzhT
        K2Z5TEhpK3hBaTE3cW54TWI4MG9RWXcK3ulhPzVmBzWYydj8VVZKR5k86CdGl1P0
        DYQ3Hn985Rm2MWQu7S+MM0g2u9JM0mFum+RufKsMtz3gHesx7HlYRw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-01T10:12:03Z"
  mac: ENC[AES256_GCM,data:mZVMJWw9AdFi+U9jklo8rpLNmF2l8m2m5m4otVqV8bPjEkxn0uBD7cNCZYciB/e6kt1skUi1M7SAgkzi8MPhM5+77AkgzAGwBdPV8bKVkNZpl+kmoabUGRxdr/j9xVkDtNa2R7rC+4zvmM6f8Pgfr2peUdScl83d7tTjEGc3tgc=,iv:Qs4b5p5wufameSK7Lb6qLoSBKNYVTP4MFHmKgYg/qtw=,tag:Eq4yMPRAYKo2Qm6HUAkNGw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
