apiVersion: v1
kind: Secret
metadata:
  name: sonarr-secret
stringData:
  api-key: ENC[AES256_GCM,data:tmY6bKEPuYNV7YHu5BcUUK37aBnHL34YIwv3wmwehxE=,iv:UHXCLlsL/rOyUyNeicM9uvKH0vOTfqSzvEwyHwZ5LEk=,tag:xdyQpPWesaAkGng3Bn+Qew==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcUpDclo5TGkrcjJXZnR5
        ZGM5dGl4UXJBSVZZSVE1b2ZWQ1BTcmxmdUFnCmR6SHJjeUlWUDlWQ2RTMlNGYVc3
        dHQzaStFdkRqM2VXSjVqOEVQS0xBNDgKLS0tIGJOWWtFQU9XYzhKODVsejFUZnNI
        UVFJaS9lbVdHcFJyY3E4KzR1blFPWTAKaSJCTcLo8Z6HIt/CV1CgZ+qq51fEeGLN
        7yvAme4uwwfem7OS6ZU6KM/LzW7DCx2H4PD5v+rPcpxzeO1sBVrCKw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-27T10:36:53Z"
  mac: ENC[AES256_GCM,data:CjT+r6kwa9TuLSwq1YnVj+P5Zd3lS2UI4bIzlf72p2/5Ukzj3I3AOMUFd6p26O62lhIl8iFQKrxxyTS2ZreLJINDpY8a3LbvRmosw1IXQ8x/eBWLnglQBNAkUybytAu9IdY/qSlUFZ3psrebcVhhq6SFm4wMvIW7YifntiW5Ssw=,iv:0ZeY6OP+vgrVzvaOllM/s5JQFTeR+ixptXDjzTTzNWQ=,tag:+/N2+rK+KDMfRGcedF6FAw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
