apiVersion: v1
kind: Secret
metadata:
  name: sonarr-secret
stringData:
  api-key: ENC[AES256_GCM,data:psdPQK2NaOamp1c7vy6JxaqDDekXQAEohmB3PE5yLtc=,iv:A3sQyLnnAyA4HZv4ZPKdQ+/kUGYHhO3P6DQjL6frdFk=,tag:4CdyRZ6byVruJDxvWldC4g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvS3hlSEhRdUVCSnQxYm5Y
        U0dLQTBsVEFsdy9HbEpZcUUyVTJSc2c0SEJVCi9aYzlsOUs1czQ4OWNIb2plK1pa
        eEV1bytMeGRvZUZwaTNuVnVHcDBQMGcKLS0tIE9HRy9PYU1UOUZ0VEROR1JhL09r
        WWMwOFArbklZRnNZZnIyUnFiQ0twYmcKbVUb+AAW+8CrH51EGBi5M7JefKnY8IRz
        1OM1yjmPePULYo5oKLh8Iv7bpXum3g1FXzi9Bmy8iNkaq74wxQyHJQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-04T10:25:46Z"
  mac: ENC[AES256_GCM,data:LrGTQtcsr8/5VyX9WeASqW0yNrWMznO32VrPS4w4ZKNWE7Q0pLs9Zw2qViy1fZkPy0ZUnrl+emwU9+NWdz1JI9JM41J8uP/noTpvn1G4eKUHg0EXBfTPTf/jtBuOHBv/mA+POXLGPLxNBHlm7igla5t7NoN7na+nlw6jddBBrfA=,iv:thkuChzBB5ySlIdDBWE/TCmZOlW4ktaxB4oJKzgDBJo=,tag:nkCGRzPw2cuNF/4tOyTjtg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
