apiVersion: v1
kind: Secret
metadata:
  name: sonarr-secret
stringData:
  api-key: ENC[AES256_GCM,data:kJLiHTUQ0FLAcYZa4+JsdADvZObWGEug5L6ME2EpB8k=,iv:wn1X64kuofigF/PEKHBazAEfoO6MDICwDeNstC7a++o=,tag:HOM0d9xMdbd2OgA56e76WQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMnVPOTFaSTgwcnpLQXVw
        N0VpV3BHWURnbFVvSTI4WllLTVI0dlhVUm00Cks5a1RVaDNrMDZtVlowb01zZWRE
        U2xSYS91cVlQekpkYXdCdFFZbzlQOWsKLS0tIGlEcG5rWmNGbUVVSjlxQyt6eWRW
        eERhSVhZMmxPa1FjMEMrOU14NVRmQzgKVSODdB6/SHi4M1WmuCn6FB+Sc7822fxe
        o5QMFI98eGghIaA4mMiUp5bt+1M+iFMLFjgqQsXiWT33IlvJLXnfBQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-23T13:24:55Z"
  mac: ENC[AES256_GCM,data:/Bnnd22pMmozwQot+Uy6+2oZP9bX7UsT0WzI/Ldsyv2z7fww9IvfkOJAs9ffqMchwUOgjtHhB0OOL5PzAtmE5t+riLuRl+0OkCkbboCUNFxvUAZZt49HoGkAaWmHR3Dbw5AqlGJ0SfAGvMf88VVwqhTF9sLYoiAVu/kfXPyJUII=,iv:PtEAUkTXh0KfvK5GtgQPiig69rgF/K82yeWK/YAUJL0=,tag:4qVt7hQ0h01o5HVIA6fyYw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
