apiVersion: v1
kind: Secret
metadata:
  name: jackett-config-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:kxkk07l1Q87PNo/gKmzIIw43ehQ2pmkSf28+HMxHVSTlCQ/rNr1A0kJ4uVCZ54AsMD1M2SYk25aLtBs=,iv:QO/KSE1sLT5cjcXp+QFxaaN2Hz4ckM74I3ck0jmHMvs=,tag:OHAbrUTtNR1ALgT6rn9CsA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:l5sl4PRvdr0zWv04MDROIgA7qh4/9EZ6FKKuEZfvH0vkEIcJPpqWa052stc=,iv:hstS9BH6FJNHIeReFmH1rmKRAQny+FUNGwig7gVwjbw=,tag:81Lirv793aefrBL/yr8jtA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:GE2Z2LqU1hLedm0tG5wT1WjExuMJqtoz5zo=,iv:Y5HTapx38uzP2dQbzJ7Pu9IPQ5WSMd5JhxUya0Jo4Rs=,tag:BM3m7usdLevPPkQATutbMg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:8nwVP3sMk4CoUzm64SNFzEELf7m3Yc1CgRbj3aPCxnvRiN1Tk0jUOspljByT+EjJ0g4+zrc2Lb4Mxd+oDJKP4A==,iv:PNGFrtBBw6hpnbChbpME8soq4QabcaVYPGEYaCWrVe8=,tag:f3OsPMuStbcYER77e38P/g==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabWJLK0xsNldEclZ6TzJH
        ZjJhSzFKRktESjA1dnoxbVBsYjVuM0xaUFdNCm9OaGtOSkUyZ2FVMmJzOGdLOE9k
        b2pRTS9yRWFiVVc5czgrandLMFVDUjgKLS0tIEdLUVhocDRpY25Nb2FocDlGcWNn
        TVNqcU1tV2dyR1RjVzFCU2twQlJSbVUKj/Vyca68isSmWdhqXbQH8cnR00261vNV
        Y4yRlY/aD22M39rn0ei9craBmtLARC9P8DV5jGTFsx0iT1RKv3LMOA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-20T08:44:28Z"
  mac: ENC[AES256_GCM,data:tsZjpAOZUy5oq4FKp5vg6AUlE0yKObX8gh+6fJ8QfNU1UJaJ+unQh+Hlsbq+XDZjKpkfvaBUK7yMdJgi/kXv8hlXHVGvwrgZ5HHobOj0N8qEwJFuuT6OG2jTcxJZg/KG/caeyuCOcjW0h8z/9JDG1aPDgD1pyVVJF/PvqCyc//U=,iv:U5jedwPHnAlnz/r0bOUd2xg6dM4rbXWt4A2YvIy5wNs=,tag:nlY70L8euNafZhFgDRoQAg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
