apiVersion: v1
kind: Secret
metadata:
  name: jackett-config-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:Obn1OYFohuwSEVbwyccqfrsriwQeyghQFr2yPn349WgrhkePcnRzUR/JvLdjXiX53MiGjgoe8y/JYVI=,iv:4ZTZql5xEsJ2mYHwlkGAqrfHa4Uv+cGUFQWm549hkDs=,tag:1r7gJMqr1iNTu0ZsG4JugQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:rXSv7dcsFPlFM1rJmsRzf08j6sObVnXxzLSiUc5VwCQ34VZOFcyPNE25Fs8=,iv:G1i6Z7j+w01KFRBM+y5A4BiS1cdgFlftrgTPkWTBroY=,tag:IowPZKWOrSQXd9UWyva0sg==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:SmdMCQHGtlUXpaa8flyzli5hVlCh6Gweqds=,iv:12WUbl0qW7NFR8lzE4zA5IedQotNVmP8TOzupBU/eKk=,tag:gp3E9eJgH5VkWcyAQLm/zg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:1YpSlmJB/tD5UOZaT9Nl+JXTVdUrObkZjAKAt+5lMWe+qx6Uh5YwuBL3GTGVVhD090+7iwvzR5dwnrJDetCbQg==,iv:QwpD38QnHZ3dzf8IjoeXamSy8JsxC90PihXazo752Fg=,tag:cT1+JFVRojg0zvACoz2OiA==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxRnJxOXBac0N1WkpkSUVk
        cTZJVXBONU43WnBDR0ZyQnR3bk56YThkZkM4CnJBelFpcDNRbU5Ld1FEaEZkSnVl
        c0tLZnVMNDJVQnl3V0hIV1JpU2FFZXMKLS0tIE9TWWJiMjYxdFZmOGJVazd4YmRi
        SjFTTjRJRXA4VVZQRjNlK0pmZEsrZ1EKC5wXGn44HPNuxB19Ji2hmA8kX5DGSV1f
        E1tLKI2UXM0JAbWvoIa5n4Jl1rXyQ8QiU/yc8Pz9Y0Q42xXikci0rg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T10:31:48Z"
  mac: ENC[AES256_GCM,data:m/2OckshnEUNOmtIYn94G1S0No2psO4uIT2Y/XAe+8m7WY0XqLR96kn8qkOlNtnY3gxmNhVrMp97P/fFKku6Zptfd2W01wgXhmFmQabdQq+nZLXSw/P6Yyif/796MpAEMeepDaKV19V9hPiHPtEd/hBamx5IcvNPnOdX6kDqrmU=,iv:aJIC0cInsoTEtzBqk8S3sty+O0vJHekFc/WpElR1ouM=,tag:gkJzmu0D1KFUlvx/VrsWqw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
