apiVersion: v1
kind: Secret
metadata:
  name: jackett-config-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:+GM0fSB2VJ8q6s1Vt6lrJbA1792sIluGNyXHrlLiOLDK+Bo8J61+GKiz6lx4pXVu3ImymoVGN/x6l/kAIOgq+ayvmPTmnUsgvNmxLRhQ7Zrg,iv:9UXQRxbppf5Y0eog1iejnkOlTjwrpazzFi7Gb/qJOZg=,tag:0fzbcjKblI1MeYEuhqunFg==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:BPHpgvnpm82bNjGf7rNO8HwINhUhqjSE18BNEgzZMBJ1HJTIwdRvx4aDGro=,iv:RgZq+FEX63E3Q6faY0fJO/P/Yl1TfS9G5BK41j/Nr6U=,tag:V0aV+LcTuHaNXIwchVphmw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:DWdXCGdGZuM6TPcanlXNYM1Sl6LF2In+TKY=,iv:Gxcel4mVWVjM17Uv7gH+iqdB5zmuq6qdg0DZpNboRhs=,tag:6oWNFrxo0ThfNGRCQP3fjw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:aZQomM54izmzDF/RSyKcoTsKTMc7is4igzia+O1TZK74Gpm6cObrOLkk7XrSk11ZqFsxtM96ALLXWeWwJkmLKw==,iv:GyuIO6LKyMPFD3axW2qMWXSgTZUTHFsiKYoWNHFjWzA=,tag:RGjx6sVp480SWkgtFv9GKA==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WndkdGdmTUVaRzJNeFhV
        OEQyTVpEWmNhUmRWS2wzRVVFNlBaK3o0SGo0CnQ4cWg3bUcya2Z3NXpQOWRFbG9w
        WE9CVWJXTnBtVno0NiszWGlQc3FUcWcKLS0tIFQ2a3crNmQvTWs3Q1FYdUVnQ3hv
        OFpoQ2xVemJFZWpSZHAvSDE3NnRJTVUKPzPMlaovZe9CVaSBtY5i+SQ3K6L02+GQ
        1ohyf2R+4PPD7btn6kMNCxCJrNe0xbj7mGDGUtgUsaNSATu4Xp29OQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-21T07:14:19Z"
  mac: ENC[AES256_GCM,data:gQxsj2efo7/EUevO/dStVX90EE48WKU/bhTUECRVQK62uyiQazkSl2+8fBKMYIwMLZ8xd5NZLi/FluGJbjdV1DlH5YMvaoVtY5uUTE6O9C7Vf57sNJoJMUizJXK7JRLZSLEJ11pfgFaWJ7YVaBkSXiXJMd9lp+qmgcXiVmK5zVA=,iv:h6SI1VE+Sq3ZlkZeAhEqqBxi9ZRkLf7Vev9ggnwzQ1I=,tag:iiEJpAkJkQyR2NJQdWvCgw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
