apiVersion: v1
kind: Secret
metadata:
  name: influxdb-data-restic-secret
  namespace: fitness
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:cdqSuJGybS7d9XsH9QgKbE6TNTEAUs7I+Dauzm5kdlnWKyFuS7EmDtkbxi/BEPRpomxjHM19nvMq6pfT6h1u1vSzLTcuZTRqBcBlrzgXgDfQTNALw34=,iv:iKTKTrHI13lWwjKYHDBGuCLFeEg+3MykwbhJcSyL2rs=,tag:dSDrH30+aH45FU1ffLvsvA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:w9DymR+UJ8spZLGohFKy7jgjCRXhjyMsAa9zwViqcI3ELFlX/ApeHOQYWRM=,iv:PxL4tRsOqO08BfLwJw8lQutwja47RcLCM/yQemj4VsI=,tag:ihbPGYk3SXCD8zax0eUqcg==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:b81RwdrBamF+qRCcDl71dZSYxTEgnuLF,iv:uQAnrdmMNovkp6j8uXbjizS2Fmw7Kk8AqBXMTSiczJo=,tag:DL3mPQL/O/1JcZUb8YiVwg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:MvmW8ceX/j4knBBCkKVAZW+eEtjhO83lXFyFMKjsjmPqQILhKJShWioSaB2tcy/G8LHKX4tHyZ1wxisCtQyTqg==,iv:ZmqdzMCJGWVpZLv1WKhSzkAviXhNFDl4r/TPBy7t09k=,tag:BgGxnLIfBtMZk4vK4yKimQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NmdENmFVUjk5OGRyZ0hj
        dlFXbzBWSGRWOFpoa2xEMW1VcjV6eGZNSm00CmUrSXRDMXQrdVdVaXlQcmxsMzMx
        UFBJSStKcHVGYUxTdWNyOGFqKzgrbE0KLS0tIFlCUk95aURSR0VtRE9VNXlGUTZM
        TGhFbWUxditQNWFBdlBtNUFCeVR6d0kKaDZ6lVWl9mBv04Wl24S0G1asgBfMLeCg
        iiwLhpmyFjw4KeBRlWYsRYddShqzNGoTzqvr/+hKkQlG78pO21irJg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-29T16:02:00Z"
  mac: ENC[AES256_GCM,data:J7aZQ6HNBzKfKbncfwGy00bdBH2YS+C7fwp31uOysjHjbpez2QBt33SuvFQZE6jL9HCaI9VMO12GQ7ExWsVp0S0Khgs4FK0qDy5d3uT/OXKwvGoVGnNGitsjazGFVOKBiYl93HCZNjAos3tQSc8xtRFceLk3p41xATgE0VJOFw4=,iv:OPate+sBk4r7ZM25h9Zvji5fdOO44u/g3Scgf4D4IuQ=,tag:oy2txtaiGS3VybHA1Z4Hbg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
