apiVersion: v1
kind: Secret
metadata:
  name: influxdb-data-restic-secret
  namespace: fitness
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:fh3fvpKUg+9JPagOUdKRl87DXv0/eUZlIyBcZqiT9SNLfzDkkgoIF6kHMP+x20JQeb8hufV+2j041/obVAOgNCuXEVV1KQdnSVUu49P42FOSZL8+sVI=,iv:rcXNA4juSl9CFB3niXUpKRUqYUG8AdtQ4QHFUjJdYoA=,tag:VlYFhuwuDl1/m15olYqsQw==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:DclWKFA0h9NTbJEh4R3qkBO2oidIWTBKUtxJ2BGs4RhKGBEZjmHgq4Vcl6A=,iv:p/LIrE2Yd2+oGNWIComgDvSSZuhIQ6Xi0gRP1NtuajI=,tag:/oxH56nOwpjE1CC3iBDdnw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:pMBD4JwsfBnr2GHCYIfGr3ERcnLvqzLI,iv:ZXXWKMBhL7Ty0dMH2XYvr9moEZ6SQgy5ZsByXFcUaGQ=,tag:b1ksY1ngA9XUtundhi55bg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:WeX4RL0BVh3xpdaZ4xmRg0T1qSaikra4EPigEYgFEqZwTLEo8+8dnKjZcIF5xHaXE49e6KCmLE8iP6myJyDCpA==,iv:8KgGGMxLDvgSAz4hPWIEwVElFwbV6GCcHKYnTgb2ChI=,tag:c7fopFBOc/sNzCyS5knYnw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjdnA4OWVQNHlLdXIwb1Nq
        Rlo0T3psS0JYbTZhK0hvcnlrbExEUFpSNkd3CmtuUnk5Q3F5NnNVaDNLTW5TanBI
        dmNkaFlwVytVaXZtTUVKeEtzbWpwZ3cKLS0tIG1WcEprQ01OdTVTdHpaR0ZsSmgx
        eFU4TlFzSHh2cjBnUzFKaU5wL2JDeEkKgI/2hng3xQ/ixs2FN6h8EoperDNxjNXR
        2NQI8gRl6qGpi8hmJpPaFulZf2dPStAgHbj24lAuuD3lqsT99rLy7w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-29T12:23:05Z"
  mac: ENC[AES256_GCM,data:KyvsEQowAaku1qtrg0of45O3SKDX1Tnd1eTKEWdrOM69MOED2AopusT5kgFvtSdurr5a291RZKQgYPc0L5hA73i/JbWCzS9eGYHGd0zNOvzeewpUxixikF1tXs/BNotSnSbtSIc5BkNdOCKoOLdO4V5tyNajibjHK/LmeL6Rx14=,iv:stxc7RjRr3Rbn46GtTg2zqxbFR1kzkzmpVInV8sFZm0=,tag:Amh1Jghmc8PUxvgQewoZeA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
