apiVersion: v1
kind: Secret
metadata:
  name: influxdb-data-restic-secret
  namespace: fitness
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:wNJ4C1q1aCDlxZGTZh9ONSY/DUvhF1oHPjuGz0Q7nB7398bo2RrMRbWVo2WeH2OEsZrFnh9DEey24ccMOtxC5CrD32LAl2tdYg2U2vb/H5Mjfek68yg=,iv:+TR4FhB9XstMiajxdHbB2tn+gDfZM8AvMJjWJUU/f9Q=,tag:weHsdZvJ83Nr0Utk3zx1dQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:FjVzUql51BTvKBAS1+M4HWk/I+OTaXtH0GPWiklY9fydgiKnlK+85mxpbw4=,iv:Y6SuXVDwv9W7xJ2eg68CR0xYxUj+Obh/tfkPpmqH6sE=,tag:YW/fEcPpUTH+D2NT7RTM9Q==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:k9IszFDNLAEn8xXAGCEjLTs3Td0jCaE1,iv:aJRlgFe9HgvTBORPLabKAOigTm8cY5FbKlLmTq2k1dc=,tag:YfxphXWOEeJNto5HclUVuA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ARNsShaQ044bwmo70drSYvSr5XRBZow4+vCESzMUILPyOio+ykqAfxDSMU3KntvgeyWBTICcGlPII5xzA7nodw==,iv:VKnhyZ46tBov5DYwGmajGh3ALPTfYObAbQTSbk1UR28=,tag:pjMCYfPe++d/v3AQmS8PzQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMcWJIYVNZM1dkZHlOREFN
        OGFxVVdTdHRaNjBkbzBycjBWd2JiWnhONjFjCi9zZ3dUWXBXTmxlV2FLMUNHYjRw
        VkdvQ2JybHpDMEI1a0FFRXc1VDA4NHMKLS0tIFJuUEdibldpU3paNHJhVHUyT0hi
        cUtZQlV3RDRtR1QxbSs4UWFwN0JGVU0Kw+Db14a7EPPHmRhfkZT1MJbsM81R+YVT
        PEr0dS2qmP/bSxrpuQZfUp/64kuHl46S5FwpF+v5DiURuprWuCQI8w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-29T12:02:06Z"
  mac: ENC[AES256_GCM,data:X5UnDJ3s6HTv0i+fxT6Z7eaFx5Yk2Dswcm+/D+xarswvmVq07CgsyUcCVTI38bgm7CN69A/uWUAY5kAjbLae88ZUQKUimO4SYu55GBzVRG85vPKnONf4msKvECYoLPRrXZvWrXnRLKtn382OFr0TtmvQs5hKSKSkRJK9w5YFoF0=,iv:Gn8mrdVhd3REUBk6SMrdhxTyF/7O7LNoAnTVn+nLvG4=,tag:2niq60XSZvbAsixDGQUV4Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
