apiVersion: v1
kind: Secret
metadata:
  name: radarr-secret
stringData:
  api-key: ENC[AES256_GCM,data:7tc5/b0JHG4i/Fm1rMb1ralZ1ZDwhWeG4cRdPgzDHoY=,iv:EQCbv32O5gAHHR+f1zRY1O87kPpQL4eDLhWIecpXraE=,tag:lvOJI4YC4lZnWJBtOktfuQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPa09sdjIrMkpRVUNwZkdS
        YmczQVA4UGlTS1ZjdGJJRG4zQklFTzJZR0RJCllhMDRNYzltRjlJb0RXeGwwUzc5
        U3JLZjFhWW9kMGNkclArNmQrNzBWWWMKLS0tIEI3ZXZ1ajJiOE9DVlJIekd5QmEv
        eHFjOEwvaW4yTlR0a1Z5c21ScTIrTU0KG43EykmijCOsq18mppOmEx+/eKod+rGM
        FST5EEPfRHSaxZBINlqBfJl8tg90J/B/P8CuIYkqhqGrdTxUzvZYNQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-29T16:02:00Z"
  mac: ENC[AES256_GCM,data:HhApgxkz8sTGfjGUG/BSsvkTkIZaa5HJeGtb6BB3X/MkSgy2VWUyPNnkkuE1oSev/ODQKb7fHzPhTjzc9/xAcfcfgW3AuKdn9EX1dutfkygSv4ULXBgUriOOy5dknKLBq3g2wueUgLUYa2LbBFuDllc2+wx/dxqiKYfMo6JOMtQ=,iv:DxsTbyhUCQ0dbvajsfTHvbeYmF3/AFRtvRh+8SO/hMM=,tag:2qxlPDaqE2RzT/z+0q/B8w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
