apiVersion: v1
kind: Secret
metadata:
  name: radarr-secret
stringData:
  api-key: ENC[AES256_GCM,data:PEeGy/eylhAKo4mcJdD45w0rbcOf51TJ9VIXIrgU4oo=,iv:xl/O6G5JnSFn+IbJCD7n7aHNNVmrcBHBc/L97QMLjPY=,tag:h3lW0OeroZAfAUEhXfQUeA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrT2YxWlVpZFNMc3pXUmFO
        VGgxZGpCOEwvTTdLQ2lndjM5a3J2K0cyWDB3Ckp2Q050VGUrMGMzWEtZcTJOYXR4
        ZXVyc1lxMUR0a0tCekh6enlFc2R5UFUKLS0tIEhkNk1RYVVvTmdmSENKUjBYbVFa
        Ulg4U2p3dldaejVGdkhlN0FlMTRsajAKvKZqOn0DAkLDxPRiqxqg3EMGJZ+Uhhqv
        WkwL2rgUcx4LRL4A7GVYRQWLkJ6rL9WZKJQveFBbHKbb6mVMuG/Z2g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-30T07:05:46Z"
  mac: ENC[AES256_GCM,data:mOZUXBfvcSE79Ny6Wqz4cYs3SCJGu5mTtbSkfZha5tIkhgfrBA1myW10/zMX0WiPAMd0j3Dv9RVGuaBg7N1G6E/YaRihrykvjoY0WsUpAZx7hei4cCtxY4GZhUxP8m4afc8zq77GIzMCyK3iyL6jg2pJbW+t3ZlbT9HRXXHMw1w=,iv:2P7RPk7MhMGugZOA1L+Rf2xv3j+WMo0JpLLIlreZwAM=,tag:aEOx70qmNMDKU9TPUPQeUg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
