apiVersion: v1
kind: Secret
metadata:
  name: radarr-secret
stringData:
  api-key: ENC[AES256_GCM,data:eS0gl1+KFIay0uizbolGC7ERJY0xVedb+tAhpYfzV6w=,iv:eddZCakSXFHJ/YiSmcmltix4oDvNZ5hd+xO7zKgpiVo=,tag:zgtPUpJFSgTPr44spd8BsA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbldXTi96cEZnQ3Y4RGwy
        eWNORlhKbE1QdnNXaWxndTczRVMvNXlBcDBnCjhsdVR1b0sva1NENDZpVTVSSW1t
        dzZ1Rys2ODJmZi9WckMxbWdXcndxK2sKLS0tIEJBclpiaGFSRHl3UCtGb2FtM2Jw
        UENWYUkyZDNxUnVhQUxBR2s2bm8xUUkKbuu6rHn7T9UqpigTIjVGJ6cv5jASjZPi
        BFF1zmRbzDoQDFn6URemU1G/BiRzcj0Wm8mFIwsS9SgTgwZZY/KxyA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-24T15:06:27Z"
  mac: ENC[AES256_GCM,data:7YA0ACMYVgNXJHaSbkQVzWaJ61t6cTDsMItR4RdOV25GArnBmaJUtoBnrqh/mr/ogMSaiGcDLHdzt7c8/aulPIqPJyhOmRyZXPS2I7ffpnoIkHBkrEwFKMQKwBFYba5xUZExRgZKRC7RwbI9Ez3Mv8R9VWvm0t90CGUzM5/e9Gc=,iv:fDqE824c3ZAQBk0ej5BpzMipYEe6NSehX10yLXnepbg=,tag:baVs6qfg8H5mpSUg77bPtg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
