apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:+SqrfFKMtWMWH0IsrguJ+6LboD7X6Ehd88pnex90DxgPcJjZYjIRWEq8E+4a7NyOZTHuyBY=,iv:Ot/DMCyi1d/WVqDQJGCNL9tKtOT1LVYyJ2PLU6vpGME=,tag:voan08dtXOm5Dz351/kNJA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJbzViakpNUURvanhJSGtR
        dHlheW5tbFhiNWNjVWhaTGVZdG9pM1dGeUFZClBnWE0zZFdxYnRIL09lWW4raTFn
        RngvR0ZJYUtkS0dHNUVzTzZsaTI5WncKLS0tIExHZnJsVFZDUUF2di9XN2R0RmlF
        dnpUbkh5RzlxT2RiRGU4Q09Qa3ZxQ3cKi+SdWtIKns7unJ/HHH6Vcwb0F2vTLnp9
        GU4r1+37FASp/U/rVJwXWFUOM94SBnyo9+bN3FjUd2UeQv/nNuT2yg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-01T14:29:45Z"
  mac: ENC[AES256_GCM,data:uTm9axAcizfudy1EFG0gE5PNekBNsgkXUh3NMeEIs/yrfsBM+l6G1y2tQ1phTdC1HQA6rdZKGVae/uCuq1onw5OgX/d1Ov8WpRedov2ZXqZJn/xeoe78aE+ftijSGr8uuRO53NMwgFom81hEbv9uyN1tAaq88u0qz5WEhB1wwxY=,iv:Mbor4cHMK9RasGgMhIm2perkARFs/8+CS5/n+VyevZk=,tag:rsY4CMG/HiNf13FefmrvuQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
