apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:DAem+8ApEpqQ5zAYzI1ozIVhaZ04CbgMgNqvoYENqvx8c/PIwXEVxrc0AdpRhSCXAY3uf7g=,iv:8CSD7EAbIbXnXk0a9IkKXMWz97VEcXjG6p/WDtFl8CE=,tag:2M4pD+cbHR9D/Pbm/urotA==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNTBJWndpYUFrcnJLUFF3
        dDZpTm5JOWJ3TUx6U1FZYkZxS0l6aE9GNGp3ClIzcDFISUtuSGVua0tCZm1xTFVn
        TitlTk9QNDZBTkJCZ01GVUV1L3M5VFkKLS0tIHdZYm9VbWZhbWZ5cDFxK1BvMmdG
        a2ZaNG4vK2hMc2V0eHVLRjdNZE9iZUUKwDLxjVOfPAu5QJcHEFftQkUDoe4+L0Ux
        HIfrJqWLXn9BwK+AFz9u+vXn1eW6IKo8f7YpIZyn4DRl7iSA65QYGQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-06T16:23:44Z"
  mac: ENC[AES256_GCM,data:kg3MyqMYhJh4ixc1EQQSAY1GQWJGMUxZuVml2CQ1hFnAKMem4FHXyhv1s4FLYyYI1efMFOuAxzZ5iRqzG2H92h6rsDHAPQehNvFVqLWEUnGex8mtN4jcsB5wjihhTkW7P3JBKImpu7fAHjQOFJX3xYOkwVYJ6RwnucbvpKdyNqs=,iv:gwP5Krl0FsPkQ6PGIGq1opxpjJxJRyi6h60GLfzYYIw=,tag:Y7aVyLxdE7orfqopS4ilgA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
