apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:PS3tAZ2eUpda5RG2KyJKPg84WhGI9wrl5x1C4ZVGv4zWVZvGF/oE6BsvA+hx/mMy83tb6fk=,iv:eHeaX+R+Jw7GDq+lZ3fVB+KlbP8/eWZfcGLOEuRVCVM=,tag:bFvxhpJnaJFtVziez+uSyA==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MlZjVUQxUjhTZUlzREdN
        bXNYM1lTcU5DanpEMmFRNzBQTm1uYkZ1MFI4CmpzL2laMmZ5TEQ3bFJEZWN0MTZv
        WUY2b2JqRUozbDhHbGt1SjdkQXErbjAKLS0tIFZKU01zeThLZ3dpcjRLVG9YTGY1
        OU42VW1wdzZQS3BWZ2dZSlNReWwyR3cKfQ67TW1ggFuUeGQyJn76a+UZI7pGnh2C
        2hXIAW1FpsMwhLwS8w/40LAgeP/MD+mhKYU/zeZ5fGre+QlrY7HeYQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-19T10:30:26Z"
  mac: ENC[AES256_GCM,data:16WM+CEvtszRR6ShZVcklLqeGKSed2Dz1fjtEejM5JjvTpBnrNAH6Z4b8b472AFpQz+EV5NTa9lAX3dUB7gEqaTUxZzaR6mvJn5w5PDG6AHJKTqBZM0XarYy2arg2QJx3Rl0vkPHbuy7CaD9cHG6A5KQT9K0A/ecH+GmB5G2Re8=,iv:u5CyC5gTmpK3Nj/6VXrOMASVvHIs20fKSjGQSjXHPpA=,tag:1rAD7287jn1/aNcZYOtIgg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
