apiVersion: v1
kind: Secret
metadata:
  name: bazarr-config-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:InsPuXLcjcZI+aRy75mRkihulTVM9wgLpws4sFa84RUo4i4WtC+/k0hoQUVc7E0kbVJpfYy3wafJW3K5+F7XwMn5wCCNDiZCoQ07wM+D8uh/6y79cUU=,iv:KrRp0dIaGq421yF6q5k0fttM2TgvShmEVhwRPa5ceig=,tag:r5WtrO3eqLUr1DvcEfFTtQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:DGCjmvumA9+yKB2ZcAAlqXXzr24qrofp0skS8n2yGG3WB4cJsGAx4eDCpcs=,iv:mFrgScnXkG1ZG4bBSEh+jNtJM2p1STx16qwjzIldjxg=,tag:nV7zu2BuqnO5fJMObcaYuQ==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:RwUATF+csc8zHsAebx5NMMTrQ4ObDKAz,iv:GfU/i/iync6RfuEzbO54fQ4wjsUqnVfu7jknxfx74h8=,tag:GjADxeW5COmSK/LQRFD//A==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:QbGGjI5XHGCB5jTZnFW1ySlPU7fpGh4Zy118L9lJ0UE8tvDiaaTw/HbYVoHoTL+ElB98GZrTTkEBTjQrQlQTlg==,iv:MU1DwtSFnzQastsHJHTV8ZGM1qRrhxW2Khfs2re/l8c=,tag:jG0ddJvBbaMSvFbCEnLAMg==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbk1nV2lHRjVhZEFoZmE4
        M3VGY3I5RzRROXNMa1Vyc3pMYzBXSUY2c1I0CnFBdXVXVUoyRWpEamNLSysyOE9x
        MTZncDgwczJZYVF3YTZoNWhrc2hEaEkKLS0tIHQreGZOdElXS2JtQm81Wk5pZXEz
        SXN6bzZGZkk4OGFyQmhaZEpxR2NCMDgKCJkMt5vtuYp/J82BCLXCBmSmgzqJMZve
        3UHDn/O4dd3P10kaLBnbkOPQf1KxqPK2BEz3+lBqo802CJQ1S+c6dw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-05T10:01:18Z"
  mac: ENC[AES256_GCM,data:f/6TG1tVAuOgyZUZJXwH8+xNQNQRXMQmAg1kSJpoBcTSamuJg5s77nOJnjVOUC1LfBkwsknDjKcgh2tm6c4uET2Y/0oncjEuPOolMsWDhuXzoRzQuzI3uehxfnKZOpuzlqKKIvvrt3G8inRrCxJ7b1wFaO+MrTAl0whi1GAfsPo=,iv:uqj0EQbwHutpMFpBh7WydreYs296tznDKdYhcvqNp+4=,tag:nqSlqnr4JZtg5AgxD6Z4sw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
