apiVersion: v1
kind: Secret
metadata:
  name: bazarr-config-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:YUBdscDcDcgIPoJTY8fqCKobFzrG4NQVYXWvox2PDW9AalDKhcvFUpYSn0QE0g8UyU86px1QmtY0dE8LJxKEkCfLs2ZmMuTYGZLYVzMMJFvYFIyYVXw=,iv:x31syQgc+MQ9D0N9eqzTcVEA0yctJKvT7Wut9nUKJJ8=,tag:j5yicX8dJeIpF7TvnJCx7w==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:jZ7IB3ZXDu+3XgfkegOw7SoevGuED5Yj3/emN8VXZXm6iTCEuI4t7fQTdbA=,iv:i5DTzeWqlL6SoAClVIzjWYdLe/yIStaxV26a0bNNRJo=,tag:c6P4Ynxw4o3QJBQ9IrBs4w==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:7NbbGPCLIIC03u7Zolu/YUC4qsSYzA7x,iv:oSFs7508txoixl+9HkF+kZ4ROxJUnmwIyfQELLeiLCY=,tag:9m6jbWpaIF/j3rD1winw6g==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:dNP/VFBKQeKODP1sdY8Ix4hDA55Xd2kte8PbHUDM67OiD4//kAH3hVWh/LVjTuS+uAX6c+Yqn4EasKXWv0J8nQ==,iv:9xM4GIchZp0yx0ph7aLoCXEIevyf7bf6ufBAgvD/mlg=,tag:MXD5SbJrm3KMVT2u/DsqXQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4aEl4Mk50RDUvZDlkOGdh
        eHB0MDc4TVFwY0lDaVNMMWU4VWk2U3g1eG5ZCmt6NG14dFF6d0kyZ3RVdFczSzJX
        bThEM3NYdnNQT0NQNlAxSlNKc2dRQ0UKLS0tIEVEU3h2M2JtZjFXcW5GTkZNVFYy
        VW1mMzY3RVhCaDlJWGZMMVM4OGx1NEEKXGnoxLHKGWxhe3i7isMIjSYx3n0d8YR3
        jwAdTYGxT1v1NYIvEnvT9iflHl32lhXOJbDjBWF1UB6uaFb0lv1qbQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-27T09:59:42Z"
  mac: ENC[AES256_GCM,data:2rYnmDvkfQZ51VEWvcLQ+TxM+7W/vTWv++I04ZOuU5owgpRMqTJ6eF2Xn7cRIe7wEHm6z7tIKSsH+Nsy290cGT/Mp+8CQScaw5xZJyTMsMDTnkKcFjsdmxg2r0PRFEALKhROfN7+bQ239b05AnIZ6v5Vb9kuJyW7BLNjDt99x4c=,iv:6YHK9YEFR7H/gV2l94HqGyJIqe9/0xovLBrJ2n08rBg=,tag:rWWUvTMiHxjCmepOP2sePQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
