apiVersion: v1
kind: Secret
metadata:
  name: bazarr-config-r2-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:JuzyblVluOXyvNI/ihvAQ1b348wBXz7g4YgiI3MtnAJEajojKQMUJODYV4X86tBQueBSXMOyO4Y7m9/11FxEIDVPDL2yoEw2n3pjeDxI214nhtiYG3xDp60qfEeT8fku+oGAw00=,iv:Xmeg1R6wthJH0NaeXNxVZKTQy8m05WlQzSJY/3z5wHc=,tag:8Z8R105TJKTUVXT3ejkqWw==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:N/dQk5qbPeTz13Merql4/mQNDX+Cgrb1Ohkm4tz+iRlvMJUjebejENYasBE=,iv:cUkyhE0HqnslzxeFsnaHsSeXUXXu8/rxLdw7+EIyeJM=,tag:Xefq39/hl1/Oczod+v1Qaw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:bXhotMeNpwmMsNavbzDMJdrDasu4cmvnwI+8auZifyk=,iv:eUBjX7Q0ekWrvaW9lZtZzsN7l4io3r1nrjUaDPYqPVI=,tag:4D+TtuSXR+EA/baWyElLYw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Uounb7uQZQQEhx+tDUIpCZUmg06sfgH6BacIvmJdEPOTkB8HzeFGTw9cwAyrzizDsU/DK6UhMCg7ofgyKL7jRg==,iv:fd7ITtDmitxQe673X0A0QG4k2EdbAQFzR8tHT769UdU=,tag:ZcZ1ozgVL9o7fpFmICnceg==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:gVGzhA==,iv:08D8VFesAUW4TEi/EMVhSf2kvhFY9Uzaz36eyG1wRUM=,tag:749vKkmrQV56Aahbl5cn/Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZWN5NjdnL1F2eTMrVHZl
        ZzZzU1BmdjY2WmJ6MW9BRnJpbmN3Zkh6ZFVRCmNOZ3pnTHIwSjZTNnk0R1FtaEdZ
        WEladjBEdXV3ZFNqbStwUEhjVHFHTEUKLS0tIHB4cjRCbEFyR0xmREhmeW1xZm1T
        V3ZMODRCdGwxMktwWkJTVTRpLzdTQ1UKw6yZab5vgdIl67xVuVRtQP8GATH1pAj7
        ZniEHFrYsSrA+t7DH7DjPryV9O9y+3WjD7S3EtOCeGCJZG9JuCz/SQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-27T10:19:19Z"
  mac: ENC[AES256_GCM,data:vvzmvhXzqiwliYvJ0A0noAq83uSyb5ZSJKfbvRBqfNiePPV9EG5HTxaWRVlNBLKcm7JJg+wTh2OU+IBGxGpSyvQx5D+4CXm3Mpzv87Af54Ujmf5zfEJy7jnruusJs1Rp3ysQ/CCWAsjT4D3//a/NqKDPRTGXomMKwwV5+LC9SqU=,iv:N0GjttMO3N7+IfH5aPYcIcNx2X9THAP9ZhDVOElhuyg=,tag:A92GL3NBsBahU5FwVj05dw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
