apiVersion: v1
kind: Secret
metadata:
  name: bazarr-config-r2-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:MrQFErLSojJURi3a8FRVtWbrDRgYNvjdVRd/uxwuowWvqGVw41FDawWfIbmL2U++faoojuD6ksaZRzuswfqv8ng5GZE6csntY1kED2dfVnUed70zvWq36galSV4jdU+t7kIBO00=,iv:q3Uaqncscx55Wo9wCNbW//IXYGfdJxbh7XVsLNPuVBA=,tag:p8Jm55RtaNqfcfWIcErzdw==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:IzGfYCwI5GiBm3TJKnr7f088IeS1y4OEjWw2MrPK3ycpQrgKmSZx8s3yMUY=,iv:Qow/YR1IhyLfRjv+fM4fPjZiW81PANssihXPkGipQ2A=,tag:K83lEZ6NLUxZnJ4qZhsQKg==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:LeHRnAMGO9ikebfBQ5EybE/KfcwwD5Knc0BXUymAMOc=,iv:SK+qiGRXtpcmWdAzuTPgeRIyMGDyKNkl4ug4z+EooW0=,tag:pnPtJBgXAsqT7ZAfM4Dt2A==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:CNplnz8GyKZka2uDpWpMaAdK37wkv/bdxM/jZ5u/YUqRpAmAsjc6smPjC5qi685j8E4uNXHcduDAmkVRbCGZDg==,iv:VzQsNYFp+nb7ySDsxmZuxZ/hJG40kSwEucZ4jzYz0W8=,tag:U/lw/1BzcZqOEQhnE0Axzg==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:jG1ciQ==,iv:rJb0NCvEJm1VlnSu+cqR0czRtcGVQmyNM8hP7VoiifA=,tag:p9hH081MlYDi9dYlvZsdxg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUi9ocEN5Tkc4eHh1UXZw
        dXZuMVdLaFJsMkZKN1Z4VkJuaS8xZ2tJaEFrCm13cEYyWDJKQ244UEJXR0hsK3lP
        R21ZQ0NhVWFUS0o1cURIVktWZjlBcWMKLS0tIGdtR0ZsS2pnQVMzT2RDdkMvZWY1
        WXd2bVhKMVhWT0dOYkhlSkgrcDJVemsKdB+UzhFF5Zef+rm9z65jYw9TnYfKiPHN
        N50nQTrOV4NIey7uN4z2sPPcct6n4r0Ip/CC9NkUvqALPk0dRoosuA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-25T09:27:33Z"
  mac: ENC[AES256_GCM,data:uSjENq8cqZkPvuFQrFZu0kn6e/BvoBu0imeqFfMU7/JT/OqvGASS1k+adn0UezYd0tkA9QAmU7K8AiaclulNMrAaU8Qo14o6qr5heZpG3hQjrpFJ1FIeBbX16j7ZCYiGQLnSeQYF/ndFB5DZRKx6PGF7/EsHhTkWF189Xu/p3pM=,iv:elQv8cGO5lnwIbN+I3brINUsZjQg7THDgYbFCBxAo+Q=,tag:MgA3veUxkMac7rOcdPhU8A==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
