apiVersion: v1
kind: Secret
metadata:
  name: bazarr-config-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:FF5m+GO+qy4zh1bjU1HEo++QiMZsm5dxnlQQ+Sd8kxAo+FHY5rj1mh/WKufaoPpz3dHvCrGqeIcs1zOtEWPWOJz9ZoGgbq8QWbPqz7+uLozGLEZinaU=,iv:i4CCr2FtGhgvvGO6xQJpV20CkAjGt2JzSz01CZHmWHs=,tag:PzNseOWdZgVnunLEFKH40A==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:U08flqYAl6tLSkcT0btfdfcNIm341ft3sJl26F7QwcNoiC24lIwU9A7Bv30=,iv:57+Sye0PyD2sPfBZse0DuF5McHXQFg8T1Z1k+wB6DkU=,tag:34Eg52zD2y94JoY1+VyEXw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Cd0Eu0OXNv2QC6yu+OLUpZHnCXGNHa2C,iv:5baZaDoeW58JS5d6Znjpaeeycfj91qZ37xe6d3VHaEI=,tag:nCV3G92UOwmrngm726XKxQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Pjxm6vtWkM7Dba+gyYxLWe4xlkOqCALB1WqOHTE9sPrPiAV/w3fTYBjPLwVWEG8qx+e5mc01IISgEzpq/1aEzg==,iv:t1rVjQ2UvE0TsM651rL7jw7O6N4ge+v72WX5li6BQIw=,tag:LHq6FtU/RSLM4VXNW99Jgg==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYWVEcW1mRWZZMExnOWdy
        ekFzc2EyazROTU1HTVBkK044Z2NCcUhzUkRZCk5QV1hCTXZCU1k5eXpLV3NqYi9q
        c0E4RlNaQmlNMjRBZDRQamwrcXVjNVUKLS0tIE1VMU8xa1VhUE1HV3FDZXVEbDIx
        NkZBMytGdE52SDUzelI5cDJxc0NQZjAKwm+N3I6wCYgw1o6wNA0YiGMa89YxFP8X
        7moEO5d+OhBxUmszcu9CiYoymRYMSP4AGW5d2/SHn909Sn5SAx7ajQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-07T15:45:17Z"
  mac: ENC[AES256_GCM,data:3PSWT0pj9V2xLlk0Cwe8zN0QpqK7MX6/kPm2OtKBN029s578b9gaUrpPvXjRNq8FyY6gnevcmRMoDmT7djPIqIVfVzIDsvJ0hFXnfgsZV7LYdq7964IcS1MpRB6dKk8ATanBcH21aFieJ0Lhm6kxYuEzbVACcH/oSV9Bw48UhsQ=,iv:rhLrQZA/t/oSKouSKNREKz3zeloEG6SNahNdT2kNxRk=,tag:eGFaubgdkw4dWGTozzQmxQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
