apiVersion: v1
kind: Secret
metadata:
  name: bazarr-config-r2-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:3zT6LmmtIzR42GGa8QpTUvY0hCVpV/0vHLJfpeMfUZz0IX+fbB/ASKY3lv62gLs1JewzLLTnd+PqKdVLSi6iqERipxGmHfSHLNi1kYEPsUlh3+r14+c/+NPe+f57CNMbvWxFWEE=,iv:gINdsKPI63SEpsycgQ4sXRyIFwO7cQj/sI+pFsil9Mg=,tag:ASUeXJ/X9UUanZkMHKwGkQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:ZWa/7cHERbBYUPap11l7r4ykGkIPehwRbRxsijkVUR77OZ8F6zQZ8yXUaRM=,iv:5qgLnhiS2fY2elY0RtUI6nbaDEjQBYYGP0ORpxFz6xg=,tag:ye1Ac1n9Y4oBeZW2NBHnPw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:iUieRx13W+d0T+0AICqYRhuk7idTtJipfqdHJOYh+Lc=,iv:KB9Ekflz9EG0aAK3/wbvbw6NWtHKii3X1L9FODavXOY=,tag:WAJGDcMH7TjCvSr5pPS+wQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:NDO+f2k4enJwXTIJ2toFfPa058Jg0wa6lk9egxtIljkgAlivquwVJ2RsNpAomnRxkJOABFNBjT0viAfwn0cOUg==,iv:GLrxvAt7MTMqHPtD9v6SGA0JsjRt+2cnq5/BrJjGejc=,tag:GIt+KPzgy8gThc65W0azdQ==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:tcecrA==,iv:f+299AQ5K0KAoexfDfm+rtemqDAXpFPiQ9q2R64Pcw0=,tag:YRiWmm9P8lmZlGCE2dhbPQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUVd0b3ZuK0puRkM3NFBS
        L2twTWZiaXU0VStVRkF2VEdsMnFPVEN2MlFVClJPY0FzVW43SHJFYkNEcHFkeFQy
        bkVBOFRBK1JmWmliQ3huL1ArQ1RGY3MKLS0tIGtuU2RjUzgzanZnYTBCK3QxK1py
        bUNuMklaUTBydGtkNzJDQldaemkwSHcKuipJie/HTpHi3WPlhtdLzFGhkJVggRiF
        HgTRHQsIekajbkMqyR5PjwHtwQExiee2KOPDcb996nMoXWadFjU4mw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-25T11:25:51Z"
  mac: ENC[AES256_GCM,data:XFf/d8sHs9yv/RRPU9WySfyV1fRW5Oy3wV4i4aglU++eIXYDIUSBAhjfWNzxnH16ACtWiBtpCLqQ4vj3cPf5+UZjI7NJX6btcCf3FCmi05hAX6Mce0Oy5oiTgKHieYI0pZKi1lom8m/+7+cQniEwIQYeuhIGWosPhu+yQt+MQb8=,iv:fS4B1DhFbMaDfl06Xj86HYrgNwsc4ZpTFOVMC9Rw6aE=,tag:+GIOxyW8AWh2Xhx4M/wfzQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
