---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.1.55:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.1.55"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "m900-ctrl"
    ipAddress: "192.168.1.160"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/9ffda6da42b0e45bb9f486a3579c3c672c6971c1acaba0cc8ed8e9a0a5bb9e09
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:23:24:df:a2:64"
        dhcp: false
        addresses:
          - "192.168.1.160/24"
        routes:
          - gateway: "192.168.1.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "192.168.1.55"
  - hostname: "m900-wrk1"
    ipAddress: "192.168.1.161"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/9ffda6da42b0e45bb9f486a3579c3c672c6971c1acaba0cc8ed8e9a0a5bb9e09
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:23:24:df:a4:57"
        dhcp: false
        addresses:
          - "192.168.1.161/24"
        routes:
          - gateway: "192.168.1.1"
            network: 0.0.0.0/0
        mtu: 1500
    patches:
      - # Label node for media workloads
        |-
        machine:
          nodeLabels:
            media-node: "true"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-longhorn.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"
    - "@./patches/controller/machine-tuppr.yaml"

