---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fitness

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./influxdb/ks.yaml
  - ./influxdb/backup-ks.yaml
  - ./ingestion/ks.yaml
