apiVersion: v1
kind: Secret
metadata:
  name: woodpecker-agent-secret
stringData:
  #ENC[AES256_GCM,data:oBnyDK1e4aV/E+VgCC7Yd1SPwaZaPELeRcclym/CWmoxyt1ZCodeQM8qKhnEwJ9Cn2xRlj2LNPbG37G/ug==,iv:UePHgbT/kOxhTVi7/qo/yOLhZ8fINX3lM0jSt71Jfgk=,tag:UE0awca8yEuSC2yRBQC4rw==,type:comment]
  agent-secret: ENC[AES256_GCM,data:1AyGXDeZ/c2UjEbZpXfLuwO0zf/CQPO+6WQf6GLYKQEUF/Dw1IKSkPYmjuZtUeokSmXXjAh5wDNwOsJFHZnoWg==,iv:u/IWnEcXMZem118WUvnRrpvQViQOASH+DuSIFxyPw2A=,tag:wbVWzqAC9gE2u2YjjaWV6g==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbm9halZHRC95a2tDbWRT
        TGlqZXBacUVCbUpRb3gyaGwvbS9sYkpZMW00CnZqeDdTbHMxZThORWNBdTdtbzBm
        QXRJMVJ0bHp5NWUxWWRwa0dCUnYrenMKLS0tIHYweG14eTVObW5Mc3U0UGhzdmYw
        KzBDZm0zYVVMNzdNSGwycUNDenMxcmsKOe4RUFN8hHBrvSZe1LcK/bVNNtQ/oeeb
        6gdXmIPlUE06YH4V3OzE4k4IAhx0BicMkl3L7HGkrBwcwVbuSBAJOQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-08T17:01:39Z"
  mac: ENC[AES256_GCM,data:Ju7Vpi98kKHUa9E/skqst+94Ou3W8QJWvhdTwV0LvgdMCOwUQCeMZyjAJ32IwhhUTqepZ8k08UJS3ob6mDMkqAKNtwLEFEjLEl+IaA2270y69xPZ5JPzEMeHDAbcqXpFrhA70VvWv4Sgu783eBbH6f85R3K2nn1gbG7CAzmXhqc=,iv:H9278TUtonUUakzKcEglwWXXVrK4plk6Jsb2prxk1Zw=,tag:7ACeqxykLoYQqLEeRWlQJg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
