apiVersion: v1
kind: Secret
metadata:
  name: woodpecker-agent-secret
stringData:
  #ENC[AES256_GCM,data:3W3dMMJoS/5JlLKxUNVurxjiObdkf795TorXMYfI9cxetDgOSh5fkozqWu8AqWulLu2YBe477zhjWmBWbg==,iv:MxkF0Dv2BKRekmUFcz2DZ48qqnDxHFODjkdfmwo232o=,tag:ZJgnxTR04FRoT8qQ42wlrA==,type:comment]
  agent-secret: ENC[AES256_GCM,data:4nC8dajmjBHTSS9r8c8mpPzLdQPnBV+LZUtb/BN+1fn7jDvqHqNYYo3kBzbuN1SBwBgWpad8X6ewxf93Z58GxQ==,iv:r4Tu+7sWkROn3G86Z/pxzEz+ol7/RHfG1mAUvR14BtU=,tag:Vr4/y0dqpzuGNBcFFpP1aQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4enNDNlJicTNLaG9aZWRR
        NGo2MmZCeHo3TmdkN3NFRmgzdHNGQkZBS21ZCjdoQzRIOGZuN0g4RWxUakdMMEI4
        eHJscVZvNGlwaGhjRW5adjRMWURHNXMKLS0tIDhKZ3h4YUN5eUJ6STVMWlYwSnp0
        eDd4eXR1cFR6aUZZU1phM2xLU3lFS1kKPVfmRz64J1QLmFE0QL6TXPw3QvBYNLgb
        h4eVRVHF5osyP7iRtFEuqU5A5C8wjolNlJtioGvVo37tKJ5UgYkrRg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-30T15:40:06Z"
  mac: ENC[AES256_GCM,data:vpYZlhglV5m4rETRed7moVnUuybzRCj9UpV3qUouV2KtXDeiht/9mnTFV9rhM2YROiKidFmbOOG748rr8tKXIjgSQrSrpjBPOjCsC/SL8FFu5pnq3JZMZcnhVzcDH/qWqgns5yN/Zrh9vSeFuz8T09G4HaKQdw6Vtb65+3uiEBQ=,iv:CaTI//xwnzOHhz3ES7XSDvyvsvV0Jv0RjmSOnGYwo14=,tag:1c2KJaeoYi5K0i2YFco0wg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
