apiVersion: v1
kind: Secret
metadata:
  name: woodpecker-agent-secret
stringData:
  #ENC[AES256_GCM,data:PCXbNvtTRe/Mox0HG8jhUkfn3CapjFqIi47dXJx9YN2A2sSf5y0DQV8APJPNYNma/v297pZp6kngRY6T4A==,iv:O7r0HTwdwSF36p1fvUqnrCFLgSkWPtkCW0+npc+XEx0=,tag:4fteYC381A2aC2tRCf9/dw==,type:comment]
  agent-secret: ENC[AES256_GCM,data:l8E6h2TAP//ahFgQGHweyITGnjY2ncBtktejlEEi6X69t+fq7fMUJhVr5VyFrp0k/ThvOjFVJ/uSYm0pasN06w==,iv:V/lV7rsSR5dqOwvdWMJezzaqtnoJrQHJy/CILyPXbew=,tag:juuhOqXITsDxbOzlqoGsAQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiN3dSWEZMaE9YYlNzVVMy
        dEY2VzlNeW5nUitlL2V0cmFnckNMYk9uUEFrCklzT2R2QTRFUHpzdFNwODlkRkZ0
        dnQ4RTlHT3FqMGFOczU0SlpIZkMwWTQKLS0tIC9GK05TWExpd0NxZEN1UE5GbEhT
        TnFEanRZMFE2NWlic0w0K2JvaUJxSnMKd+PPAlsWzd6nqOPPDtEWR+zpvRaD7Xg2
        w2UaSk2Nxy4SyQUu0FYrn2fzHJPPL2Gd+MIQ554doZQASLeb1sLcbQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-25T09:27:32Z"
  mac: ENC[AES256_GCM,data:Pv8wDCIElVvJCq3W0uPvNRaI8HftDFHQfdyTNQ9Dkeq7rlxTWOQ5ulnLfiDHidm5C7UoAQdTBHZr8PMw0/avVgHPTGxNZbeK9Ld4via/Y3bkTVxTtv5qvqgLLEhpmDKWFbrAUG2BDnczUn0zhlNshNXVDNUDezylvjrduWOGz9Q=,iv:9WnzgoR7J8QDlh1MIa9jCIbbl2SFEWf9lQO9y0vY9K8=,tag:0sYO/aP71Gn0zZuOisleRA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
