apiVersion: v1
kind: Secret
metadata:
  name: linkding-restic-secret
  namespace: cloud
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:eQ8lD0k/Lw30GMlFK/lZXW0y/VcSr9A15xH/HUfO2iQA0FafEuJmBL2Pl6ePliJ8rgfq2pNmSwed0DLSt0iM1RNwxcwuPuWgavbPUq7U++XaaffV7pg=,iv:UJcnCT/ZhmVNTmXHv1SxbfvrfD5aPG9S12d9nELqcIY=,tag:D1IubqIX0vOmhCeJAzSnZg==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:ol3CcJyC05jBEMC3atnstGUHl37yDkdugz3SzJAF+bzIbsLRRIipVaSJvak=,iv:8z2+AUDG4TdiGZLQNI1Cb4Dq9ZV73oqfkVOEtppYqns=,tag:a/3YpAJentvS33GWw3ESAQ==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:4nMon/eviang3mgbqr+1vw0j7rkSUDtu,iv:nFYsRbU6+oX7lQHglNyUXxVCNqc6TT8wBbsYL9pyyhY=,tag:7lLNQpQ2fRH0UXYoKwHB1w==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:8J/wyb1qyj/oqEi3qNyjz7rQRbwMfDVz153UFXu/ULoDHjSqK/qDGQPY2KD4CKaQWQOj6o1bd+NHKe0EEhpjAg==,iv:C6qCLCIxl971F32Og2AE3v0cx50zhM72WcDV03LQgos=,tag:uPgRtpvSE0bFpFkTLDbrnQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSmcxM2k1MHdWN2RqU1N6
        eVJVWjlzRklrRFA0ZWVBSGhuSmRLWCswNzI0CmF4bG5PNkhQcGZJemZBaWVuR1Zz
        dVl6K3ROdEFHRjJiaVVFYWcrRDF0UG8KLS0tIFNvN2VxZURYSDExUmM5WUlEMVlO
        V3pFeVJNSWFEZURRaDVDcVRFd1Z2T1EKIV+vwEtE2g+27xVK02IFqwXvXJylMRlF
        6KYa9wGY8qoHsywzd8fCuVU//v+kCzWzMYqZ5MvDXHQFSLDZXEKQHw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-24T15:06:27Z"
  mac: ENC[AES256_GCM,data:jqEyRCkSq21E+JNc0BtadIbQaMBzZiZWDaiLjokUmL3qXYJ3JY6Iest8g8DPGBlENZvSSF+TXJQ/c3MPZFZGh87jU0woLTZ7k8r/odWOgZuRFUDtPgaqT1sRKYQM7xXSFOUZPPQGGgsVydqYh8eX+FLGs8K6KQGqSI0aG8Ndhc0=,iv:5EqAwAyzN8LI8yO6FKwN8MznpHFk1aA7sp5gZK4jqKY=,tag:xJGXGRItLW1dljGJSAl90g==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
