apiVersion: v1
kind: Secret
metadata:
  name: linkding-restic-secret
  namespace: cloud
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:/ZMQIUZ69hMuR4vavSeDQNmhv7O8Q7EPzSXo+McSwy8+kFta88lgdkw4RskUffljy9471FP7XkDHe9OBf6bpyu6Iyr5Qwr4dfSNAOGMabXksEJ32sDo=,iv:n4hmUJ0w9AtOFitE9ynIUwlcsXKWpz7Z+Cme6x6M9DM=,tag:0bTOG/eWMFd93B1ttyVDvw==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:wgf9kQvFMiIL6KsNAH5lZq5DPn1UTC0r55nVDq8L8A+RvNEuAQCvRDlzkV0=,iv:pG/XSxsmYCmaewaLHmJiYVPPwKwYgxDY7RnWGlWNNDQ=,tag:C7fh8O5BTUexf0RunI0n9w==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:EXz7Tl0lLHpTkNWDNjIXnehuUKYWLGyb,iv:H29e9BpO25I1fN3LY2XLNtf2u5dw/robnkTCfZHd+dY=,tag:GvwjfkXgEh+R+hjfnSpsIA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:GwRcZKy48D/MGBhPKBCLGyhBVwT9otPQicMazDCbLEN5Si5J04O/zjBZ1pXqYDhCsxo7sv1moesPY/A70KCGsw==,iv:fOwaTvwgpI8PF/EcgxtByJC69oMT7hlsmMZfKI90H4g=,tag:LXcGJVmNpW7I/HSssR2/hg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvOUlTS0hjaHlCQVpyUVZM
        c1YxU2c0TG1kTXdla0pqUWcyRExBaE1JM1E4ClpxemRaS3J3MlZDUzBYa0ZyZWNs
        bXZONHh4UnRLQ2lUVnRuUTJQQ2duV0UKLS0tIExkVUt5WTE3NllTWGZXTkRVRGp4
        dUhpKythNENyV2o1ZkEyU2lmM3Qrc0EK8VTWJ9n/LTdZL0u11LcIi/JwoN6+RhdJ
        q9npOhntfS5WrY1SrPluLaCOS1gLve8IrqF3wjc5hI3LL7BDUpDIdg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-10T11:14:25Z"
  mac: ENC[AES256_GCM,data:DLREB2ec1a+QgPHOi49zbqKRoJpt1U34UOt6lz8RZLWu76LdLnax4g/UoXgoRzQNpbAIMWii67tP31XqNoH/uuz0rnuaVCpHUv3KKWESGMlTpZUeHn/oX6sFoMHJkXipSUjb2PyHySdsuZZif52sqJ2sQwzHBvkyFkAQPLV8Lbg=,iv:LKcq5RQiqr9khk9mehYXpIDoIQlFWiRmBxfsstUUDGU=,tag:QbfyGCwqbs8wYgSUrm2cxg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
