apiVersion: v1
kind: Secret
metadata:
  name: linkding-r2-restic-secret
  namespace: cloud
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:ZDhfitDgNwZPbjgSdGDNDtUWXVMU50YbYmPEZiMvzJixa27HQG743x45+oL0PJxdEb2/LpxtqioNWBfDL+3P5WlEhiVMzMwqieeMJkJ5JiZfeBuqTBimoNXRnfEw5vutVeg3jcI=,iv:d851ka5QjArxw0FdjYF76urqXnCBmfcpRIq/1taMeE0=,tag:EgeQtT6Ep51MK7aUqTgj9A==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:SEwHh1b8c/LBIBT1tLzxqPwTPA4BdOhNBHYdhZfArRQ9psbt2hyZe9yVc9A=,iv:XP+gFvN5zX5dV29Aykw7SgJsHLtKDcYhWEdvl07yPLU=,tag:WMNeTOUm54gZuZdvGInxSA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Y85Nuw1xuoXpF0REN05inOw3oueWMxFcqvxBscddEy8=,iv:/AHOUeSvSb0yqv9+w8tI47UEFWd4O8KaP8We0DIgvUE=,tag:EsDwG57SlxJWtdN5BZ/MKw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:dOi/H9K+gkymq+CT3tz705UYWHpIc4VJ5R4yppaszEcRErkOl0LKt+Ga2xgLE3i0q5aYdxwtX3sgj11PUxEf6Q==,iv:8iq7RbkO1Polc2vF4HghhGvQo4799VEkU6VQCrvJ+ww=,tag:+8s8o/L1EL3yJGhckFADmA==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:wTAhRg==,iv:Y8WwDjmPp/0XyDQfLvI20prNGudFNCA60iKPGKJeFpQ=,tag:81CSFrMkDU02TtC219/rqw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSjRYdEkrVDNsZm9MZmsr
        NjN0bWNRZWtDcW5MSWhlbnlrb0ZydlRTMWxJClNuNXQwWHNNcmhTekFvbjhsWDlG
        OGZ0ODBHSHU5OVBvVnZQVUtRSVpzTEkKLS0tIENLeDh5aDgwam9KQVBQc2d1S2pG
        ZmtWMVlpMDdDWVREbW1ld3l3dVFmWWMKXBrHs3pNchf6iUnEV6bdPXyEmmgLXwSv
        /CR0jZUJo0ntyDSSWhyxctvvVRI2omN8o1PLFQvQszII5H31DMBaDw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-20T09:47:27Z"
  mac: ENC[AES256_GCM,data:xdhE/ZK0OyOxblmIqk/Y4AImNvjdat1LahURYvkVdC/FON36VNAnrelHtjceqvnC7bmZNA/2Qf/oFhJSTJRUPMO8DZUpKKCm3/qtVDVl52s+m/hTnV/91eC3iE/TgVlgsA1og0e0NipU1uEqy0rH1ZB6+OemrukdJQg4EwHSdH8=,iv:t5qfNR6E4vONbWcvtNnbXfEYj7ld+di1eFhp0Rp6JOw=,tag:Zr+zEbKueQPT2V6iYJz2Ow==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
