apiVersion: v1
kind: Secret
metadata:
  name: linkding-restic-secret
  namespace: cloud
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:Dy24ekO5K7qde8mEy5jzPh0XX6pP+SfsmG/uQ5nrHvCAXRD/2uBXWNpVYRzt6AeWlUoAhOwMHQJfrKtWA8xZlsCKfhARqDSLgimCR3C0ZP1i7CTM6yg=,iv:IM8CIhl1/PE97IHSdfojYfwBKKCiyPmLvyxdXu6x7nM=,tag:Vp+xlsQC60gRVtMOwNt7cQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:X2tSpPEiqshRcORQEFEBKglJF7dwv91B3GqOh3jitzaWdGJFE8HmiiV4jSU=,iv:ffGkFK62svLvS8oK661MVkmV79qiWfSKujIt4DTFg1s=,tag:Ce8cA5+nszFsFJIKGaqVLA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:XFR2HQOqScg1y1OV2ufC3V/7xcXyUy1k,iv:YphP4qe2F8ZJz7s99IFrR5yoLbEboNReoi3aCKDFzIw=,tag:HFvW7GjR34r3TUYThYRTFQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:XUTFkOeXhEtyCQKt1Qim9EqjlEFKe5pVmlKYeEEW4ZTZeGUWqof9wH7YcMj5IAaGafnmiMw2vCFLqqDc0RvY/A==,iv:myrYAVT3L8vwMJXqTW4hzheRnVFt25Avr+YH8/A9YuA=,tag:Elgk60SOc3U57iH0dlvgKA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WkV2eTFHdXVyMFhaUFgz
        WEdOdmtXTzc3S1dzVWhNTEhOdlB3aDV6M2xNCmMxSTJZcEpOcEdIdjE3LzFMbHZi
        KzNpaStrVzRuR3Z1VzRCem9TVWF5QmcKLS0tIG9LK1dDWTdtWG05MlpJVXJndS9J
        NUlEa3AxUEZEekxseXNaNEtTL2M1Z0EK5dty7RcfAhK4veRkMgJtAuWchUuD3xxe
        MB3t39Pbzs5JSsaL00T9qeWXgHXCKOUZypvpfM+Vz9mXjwanLFXEFQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-24T13:48:20Z"
  mac: ENC[AES256_GCM,data:R8VeQWGQ27K1JDXpCMfM3/JP4E/Wz+KkQq+GsRlyguBm2fA0FDSj1vW6Jqu/ixr9vz9aXXF888W0/4INHtEdpaYAKd+wKjnDCIlZz9QLaxUqmo7QPu1VWP4J4D8WmVA/aNEXUkls6BeWSWa9/s/kHVN2ypmO5hDhlWgZOzX7D+Q=,iv:E6rSehAvfHJJflV9FIaRLhsb6g6b7zpveuq14kEAKN4=,tag:WHo1sAmnS5puoouuKtQeXw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
