apiVersion: v1
kind: Secret
metadata:
  name: linkding-r2-restic-secret
  namespace: cloud
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:uDZAv0x0dT7bN1BbfANUdLpTKZeh1tA6Tsg1y+nFbwy5t1mIgCCryRECFo50h1ZX63hcXL0CzxspXeDzw8QcHRNHiCKo3ukXG28RxhBH9apFrw0rPXKz/zpJLylHHg87TWIQsXE=,iv:+XwLWgffrVSeZc/6QjteAJ3d5DUVgkxbtFVcfQyoDvI=,tag:XgIS0J8+KnFgW4QYLH+rmg==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:naRkgu/+OCyesWNU5oRisHyIyvAfWiIN/aseJijOeUhUG7GejwPDnhmvNAg=,iv:E7JO2q6dCSVEFRhjh62ywUJrbgjEUieHxEWlgTJPCDY=,tag:rtQzhnY4tLwwAr4KL/5Dfg==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:eVxmi4bmnlBOTqYSJ/cb0OH7/e0B+iqtDUi/9mUnj9E=,iv:8nQxlpakgDNeOkmjoDWnKQ54EAVzaiItkKF5HFcsI/g=,tag:ubi+GyGYtxrM5LI/KISTUA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:8stB3dVYUtSLLDtNLoUj1HWAYWr/EHS/CQNHMkyXQkeIMb1Q4cIaYcNUspeajrUSEdpF3USrUhNBPkcZiWBLCA==,iv:ZIj+vX1lOssEPPRWxjxdxmFHg0jJ5su1cadPc1UwcYo=,tag:vx48EGaXZd2w15rHg86lmw==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:zdmVfA==,iv:h/C3qwKrwbGpVfd6PCpzAm76di1Tzm6V4Vz8FT9u1jg=,tag:jDTDljKT3KZ+hpTz0YqbTw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSGRnenVKMnI0T0FKYXFQ
        bTY0bWJ1T0lId3pCSXk4UytYYldYUXhPUG1jCml4SEFUNktIODVYcnBHLzV2NUN4
        dzVPRVFFSzNpc1ljNDIwaUQ3dEJBZzAKLS0tIGV0N1JOQUw3cUZDK1pBd0RFbUdl
        dVIrbmhwQXlMRk5KZmc3SjJURElldTgKF3PncgKIbxlpsO8AYj0sxD4+FzB7hMTt
        GDdS+vhkG22toR7H4HnC0794mb+QykRga0INn1KS6d7q6Xzsx8ZZPQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-27T09:59:41Z"
  mac: ENC[AES256_GCM,data:hAl3p7PyJocO7pwua5DYRUD6ZUo+WgEG8+dpjv0v+3HGr3yrEftvS/nObw+F6K5R2H5t7zO/RsUjbzMmS2Z7RcJKx1Bl91V/hhTv2DWSjhF63AiZT0tDJj7fmqJZncbYYfnP8UrH/dC43LeeWX9RFs5tIaBkoOntx7ckpCQMIW0=,iv:4d4dgs2NB5CggFEfxJeu/bMwUQ2GAW8HClHm4ziYwrM=,tag:+LpSl0JdMShY67ECQFFGIA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
