apiVersion: v1
kind: Secret
metadata:
  name: linkding-r2-restic-secret
  namespace: cloud
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:vNRKWH8b7IuN5+CEibsSniTmoIRixkLxQSNEetSu5AsyISJLU5pcAn7ciZNJ/VvKUMFZOVVeWcp9OkmTbFoWNWrmGBSpHRTfe2XTicdtMVq6oMIrcd/2dT4MfViS95wIyZM9/Z8=,iv:lJcfx1aaARUB88VG/iO2o3FA+/Z08xeOtodS9QvmLZ4=,tag:DZ2gzXgKMnxh1eUnQmjA4g==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:W+7zST1Buc4amk9bRtweF00F5V1OaaYBRoM06TjHI5+UQqZgOvzbeGnKyD8=,iv:rp8lm7eIZPKV5PpcDd59BdzxNRcn8h9Lwuz+TQvwm90=,tag:s/FWbQl+d7xHtSNJmFJx7g==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:sUDnvn/H5QINnZJXxROXWy8T3YNTPt+wQhG2uex51Tc=,iv:zBFj+1KY2WKk0ITnALel/L6bEXLOsdMNp6SLB64Cgsk=,tag:OQrJbZ5/VWnRWtGMR1YFhA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:VOCGt4Rf1RePncdUb+loRcnfP0k/uUFtKy3Hn/a+ak72XnrACsZoJqXRZM4Z5rD9MJsnn3KtaRadWgL262I9Ag==,iv:1DdQwNSbFt+wdBcmayP7jweRksvu6ocyBxY/RJI44rk=,tag:Fjd+TorsyjZHbEdFrAkIvw==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:ZPbdOA==,iv:U/KhI0G9ioI63w59j0E6I/DrV3BsLBWfx9ScNPVYiuw=,tag:DOTy5sdRqMYbqdlH1v9M6w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMcEtWNGtmdHFyaFhHaTVC
        TUs1UVJWa3AwZzdsUXVwa1dhMTc5ajB5SVJNCkpZRkltdVlEU24xVVZwbVNaWElz
        UVFnbEFXZWMrcGVSVGVNMmVZZGlWVE0KLS0tIHozSUtRajFPRTRwVUR3SDRpeFV0
        dk9GcGw4U3BGSEJpc3paZ0owYVgvbWMKlm3L+Uz5VXHRegJnwwAd86wsSbOeDnM8
        GTDvjsN4n8LkUXrAqqvJqi1cwBruvPAXHbr493Ey0OLeHOhCXXub3A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-27T11:54:14Z"
  mac: ENC[AES256_GCM,data:TcBGQlmm+lPogU6XBBe6WyhbiObqKxQ0Qsa48dljl5XKwpZ3xUKoR0lSfATb3hKwYMnYfFxAdgw16giPKBcNZRPuaXkKzUPDxtS+EufL4wpl5rvUCTTZpG0P5UNZssOFa/azq5ebK2feltk5RBQTbIkFGqGAp2lGFxm7AMC3r9Q=,iv:op7rCnDSUxbJEwWiqUnyhDue7sbJ1wt81tN09I3+Mps=,tag:Xke2qgq2hsfT7ulxTVp17g==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
