apiVersion: v1
kind: Secret
metadata:
  name: fitness-ingestion-secret
  namespace: fitness
type: Opaque
stringData:
  #ENC[AES256_GCM,data:uycQBAaCjupemiaRk+9PBmEi6ZrBfVTGmyFx,iv:Twn4ztHriAeAExC5YonYyLR5n1vyHSwdc93dm9vPVIY=,tag:YgB+CBGvqIQ4JyCndA/Vhg==,type:comment]
  GARMIN_EMAIL: ENC[AES256_GCM,data:fhk6mT9enkq7lBWnLiNwjQ==,iv:zcG4sT5yDFwmm5PUd2vJ4hYsLYdZ6gP3kyNBSewcjV8=,tag:TGb6BlwYi/jt7yWLXYrfFA==,type:str]
  GARMIN_PASSWORD: ENC[AES256_GCM,data:0mwOg/a7HdD+Nm9AACBn,iv:rIx+r4BkToxrIQt+hVV1VN5UQRPhSdLUeiFyoSse7tM=,tag:0okXEHOSXAV8k1eueMvjTg==,type:str]
  #ENC[AES256_GCM,data:x6/l2RoEm/OKLxBq3GW8kSWq8rVcEa4nbF/R4A==,iv:OSWm+ASebRpq4n6g8ujIkh9aa1yRMErJRheI1opAfW8=,tag:mbPQX9l9mlhnoASb+7tBig==,type:comment]
  WITHINGS_CLIENT_ID: ENC[AES256_GCM,data:Dx0sjLvRgDxNGVS99KhKOUuvFgqnqu2adsW6M+LDHFoy53jwzd0dg3WglbagzBOGwLfMFXH6fwQuFvXE/YbSYg==,iv:MqxK6rTN56VI1QBQ8H8PMFYN56SY7zRb5QYZSYKYcWI=,tag:KgSWP6BBD3jHjUXq97PdBA==,type:str]
  WITHINGS_CLIENT_SECRET: ENC[AES256_GCM,data:HZ+E+hk8f8r0DCGiLmwJTIjyWOdDKn28wtMMzGfzxEZ/r/TXceC9Gp4u7bhrDbzW+xjMUJsSVBvjwkV6TkvPeA==,iv:djLjvaDd9Er89zBKNphPauBvW7B/3EwQv3PEjswcYPE=,tag:aXbCdK40ndpzfOZmuzLjkg==,type:str]
  #ENC[AES256_GCM,data:wkKqgEnmfrZJ1I3UiNHYKmjaK+w3z7SVd0yXvZg=,iv:VI7syyh0QZl4iPzgrjVjrNxTWXp9yZoEGusvn5PTvyE=,tag:XzqyL4v6ui5oW7bEfdxiTA==,type:comment]
  APPLE_WEBHOOK_KEY: ENC[AES256_GCM,data:+U7iHuI5r7QXse2wZLF0AGXexAJ70R0DoyRryxWg2OyFXYLoDWzCG9d1suXMmNlrNPjUGb8Du0D6Rpe/bKCnZA==,iv:2YedTyYcxCFLrEit08n1gNT4b0U/2iWfKZIuQv3PTDI=,tag:ODL4m7V4RXElmf3UyehVXw==,type:str]
  #ENC[AES256_GCM,data:Bd86GsuWVjaaVj0P3RkSJyz6i9M=,iv:9ttuVCqXdM4vDQO55okoD185zzArKtg8NgoDZ8CZzgs=,tag:mW1Z4Z/QkAlS6KY8IKnLaA==,type:comment]
  INFLUXDB_URL: ENC[AES256_GCM,data:9zeBsdBNCJwDwFEGoys3yTCrj2IdbsRI9JtXU4geHHzwYJ2HgVRxwCy5Ta7xzw==,iv:kPuLay7xHTjEpgL7u3cLrxxfx8dzTNA895yZWHhN5js=,tag:JtM5uxemAeTjxe1hynggjg==,type:str]
  INFLUXDB_TOKEN: ENC[AES256_GCM,data:VvFISdjqdvJv1AH/kZ+5eskissLfuGsVJAi+BiRiLmurPMCEO2errsFv+X6ZAp/xifyN924bYwID3cxAshhVYA==,iv:Jqmedp3UJk2kgIqWh9T6CZAV13VxHmcwCYAT5BY8QmU=,tag:4tflYvd1nsuxcX2tlBldnQ==,type:str]
  INFLUXDB_ORG: ENC[AES256_GCM,data:7jpmPGINBw==,iv:9JQsj1pSm5zlpHd94VMDbJG3W6aZ0sfE3GEbmZdJuh0=,tag:93wF6gt0KoTBMStNXEcFiQ==,type:str]
  INFLUXDB_BUCKET: ENC[AES256_GCM,data:R8SdkRKGagUJjmW2rbg=,iv:D9ZM5v7lhfaMzZAwWZmbADGr6uT4OyxFXvVD8IDQ0Rw=,tag:AoMXdt5JZA/m88PgZHPfAw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3YWQ3b3VHOEpLc2VRYi9F
        di9WY2tOWXpBeTRqZGduWWJ2ZnhLSHZSeTJjCkFoK0dMVndla0Z2NTY5QVoxZlJK
        bXlNVldPV05CRWo3cXRrcFhGWitIYjAKLS0tIEpaY3dheWZGSDhCWkpGckkyNzVa
        RjcyVjdHK1JKQkFtbkpvTlNzeUNjZjAKUXfBvnwj33YcwqHIdTlWD3PCQ1d6kKEw
        anV2VllBvPv2KlSxXtm8RsR+29VO3Iw9hLRC2g2Z7vmhZn+f1ZSTXw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-29T12:23:05Z"
  mac: ENC[AES256_GCM,data:T403Ug44++5JPzvxtAmnv8EQMiTAVb7bbhQpFYGiv3hZhqD2LwuzkYIlBKLYd2RkIgLLs1SRELQ4/198P+bva9wvzyDywnuzN8FLqp7QPFKstT0MvMRPM6C2bzloIaABSRUD4jJjj+YdSXdgi7OZJPc407c4zbQnQzbCP5dwU2Q=,iv:bLvG4ZZVYkINHAzlh1yZ5plIVqAWCsJh9vgGEhWT7Fc=,tag:jDjPFeGwOr5tREavk53DVg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
