apiVersion: v1
kind: Secret
metadata:
  name: fitness-ingestion-secret
  namespace: fitness
type: Opaque
stringData:
  #ENC[AES256_GCM,data:6qbjwh1mR/N1eXbHOMNGvhOgWYZESIOXkQrW,iv:GNtYFOfuGi8QrzbuljBjbxULav+kjnYlGAzSTUa6b5U=,tag:74qE1nm1SS9ivpR6bOkSSA==,type:comment]
  GARMIN_EMAIL: ENC[AES256_GCM,data:AcMV+qKZdXi/GH9Hkwghug==,iv:4AQKOe40sLLR+S2Rwz1dgQEnUF2flWq+lSZ9+iWDkfg=,tag:IXPt4rGc4Js+LUwSCPzswQ==,type:str]
  GARMIN_PASSWORD: ENC[AES256_GCM,data:fFhvjqm46+oHnybl8Jjz,iv:dqLgdxm746nF/OyULyBVHsRY5GwaGb5u1hPSBTOHhSc=,tag:PdBKsux/BjRZZeXfI9TPgg==,type:str]
  #ENC[AES256_GCM,data:PiZ6RRsZ2YshKS3ivSn4vBnC+sWAYdmwkw8kKQ==,iv:/SlCGfnI57z4GScVLrb6TWbABDardyEo+D5eyy5R8KQ=,tag:/enyi9x+h08rhziUujRAJA==,type:comment]
  WITHINGS_CLIENT_ID: ENC[AES256_GCM,data:RxEVyoOdSYhiab4KizQULo+63UpwSe11gQD3aVBdnLy/I0DZ7EGI3Ph1wn2awCI5mE1YruWPoE8fT8KBsVoMdQ==,iv:L2ItzgiRARfn0T0dMYm5EsLqhxfYBe74LS6SALWGKes=,tag:jxKaobdMMJF7LpmaUTTW1A==,type:str]
  WITHINGS_CLIENT_SECRET: ENC[AES256_GCM,data:mKdvp9DYalvWY0uGozkDUAfrB4iS1FzE2Ta7nXSg6DfUNBmERHdH64im8Ez3O//qWYTGoPWhCGFJC1RwBDrCvw==,iv:EyXEhJ+ZXTmTtrMfLxgq1P9lHOmKYIf0AirYzGyYDy0=,tag:EJV+Mon47XhKh+Sb3UndZQ==,type:str]
  #ENC[AES256_GCM,data:1yVQcwaHQU1qB80Gy6sr6VQElcLAqvyKlP5TfJI=,iv:5hvU577k39TPc/4qMsUaeWhkmUXKJ8bVR9WfdZ9wUpg=,tag:+qcPn/GGChMbm9x7MOeiwA==,type:comment]
  APPLE_WEBHOOK_KEY: ENC[AES256_GCM,data:Nq4rK5nRuma1+qGG58cjnYa05nuA85Z35zOstFQuCBc2NtC3duqEPFHGMy1IrePTw9uXxjkj7q60jIq+889TpA==,iv:M43xgYhB7zklwAd8AU1dSxKhxnVi0O/mov8xtpFWxTQ=,tag:TGBnwp+uSiRHpE4n2MzWgA==,type:str]
  #ENC[AES256_GCM,data:LXlcVIpts7y+fZHSHsRSMZ6tWTA=,iv:N+V9JkzQl9YKHJJUifI1rz8Q8Q/ptUHAMS5u9+eA8gg=,tag:ecBHHhsu2upKnfYz1d6fzw==,type:comment]
  INFLUXDB_URL: ENC[AES256_GCM,data:SjomjoVzPcgV2uin5qRmQYXV6zFi2DXBRL+dvIASMjux31Oluek5fTLtY6UFCQ==,iv:rPtyJ+F5rgWNpNLdkwEi5VjIqa3M8ZsIyU3kVFKM4mI=,tag:5N6H1/kf1zaD1ISjqBZtIg==,type:str]
  INFLUXDB_TOKEN: ENC[AES256_GCM,data:c1qt5+3XNKjyn7V8Wt12IGoHj3kK5pn7K0wlQUtpyZgmmXqU/8UiLkPZ79IH/c4viR9gZacYIP0pAGUFvt7T2g==,iv:98/B90XCLg2zW/jrBGvP/Qf0RfEn++QB/VTIAa3Hsvc=,tag:bZNHCICuQN5f0B9BEXDl0A==,type:str]
  INFLUXDB_ORG: ENC[AES256_GCM,data:oX+arB5bAA==,iv:oVPOVwUPxfc4zFSATnA7WBEqDAO/o8vqe02L4be0nzM=,tag:5pd1AKId+PLjpddWEcp19g==,type:str]
  INFLUXDB_BUCKET: ENC[AES256_GCM,data:ldLse8S7PDugq2v5SV0=,iv:i3zueoue6ECao0YsGhjw8IrMAkICm2BNlWpDoGU+CGs=,tag:al1D0ZoUOHHEn/FxktTyZg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqMU9HZjBSSHpwNmtCSDhs
        Q1Y0aFdmcFlLNnNmVEt6NUQ1ZmRZSksvbGpnCnN2T1Vva3E4cktvY2paSWpSbmJr
        OXhVSStJU2M1Zy81MFpBdXpZT1lEVEUKLS0tIHB4c2duNEorWFNjUllTd2VUNmxK
        d0tvTVNHRHVrd0twcnRoLy8rcVJ2Z00K9mD+8xZchhOC711hTTsM4c4jQu5kbfJi
        xmj/ztM2IcHG06tQ/uVeq2469tAkaX2EddkuFpyH36jjLH1V9cCeDA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-29T12:53:36Z"
  mac: ENC[AES256_GCM,data:uc6A6dn0LAqaXnwvPOuOyTky29C9oJekWBiZlOpuo5Usalp7RH1jSJqIhN6w7tz5EvyBQRRC1WkIScQxkNz3TiBEtKyOxazsCb7r3gFCnTbNdh1VQNHKsBeS8p9EKmlq8dBTTOhCfNV0bwJcBuPD8AeM8WhG3xme1nHw8NZ+LPw=,iv:YXcFZkbmcDF0qnkqmCJJbGiAbscibgAMIRGOEIx4prk=,tag:5acArxT61Na9ULg24T7BzA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
