apiVersion: v1
kind: Secret
metadata:
  name: fitness-ingestion-secret
  namespace: fitness
type: Opaque
stringData:
  #ENC[AES256_GCM,data:EAVlZU0k1D7mHd807N0QRvoKni4NLcPThjYq,iv:tn02T00rP4NBYY4xcVgfjoAvKDT+QSReatG0U2xObD4=,tag:oWzJ2cM412K7eH2xr19iLg==,type:comment]
  GARMIN_EMAIL: ENC[AES256_GCM,data:wMi0BJfqcz/LzEvYa5XK/g==,iv:uFCH4V2BfSZ1on3/R9j5tkCE4AFNZqabOLGFC2fjv7M=,tag:/L/7SIV53JgTCHLqOB/N/g==,type:str]
  GARMIN_PASSWORD: ENC[AES256_GCM,data:QXQuodzekVFEkL3sRkOq,iv:kBfzHg6LNsdU8txupTIU5IvxzbIz1BdMLDj2d1vEGxM=,tag:6e4QSaRkT+y7DlvFCpLiTw==,type:str]
  #ENC[AES256_GCM,data:HBrqmcaywu83pDOAPQ0ja0yccldmt7Bx7Jml4A==,iv:YVKISeSSneJWvQZVmqlLu/D25NQtproRA5IAaWl0rrc=,tag:izT3JG5ZVaE0VECNdp8Lpg==,type:comment]
  WITHINGS_CLIENT_ID: ENC[AES256_GCM,data:kLyvBMDwfb5b0nR9KRmLUb10JaNNR6F0QLPI5rI5VLFUnk/WRuTetPzza2ZkpOQBQJzh6Dn+PkebyJ6qcwmlJw==,iv:lr6E2xYgVVLv4Bsg6PbC48C2AdFBd7+5SEZQIh6HYCk=,tag:HBlhCY93JdhiH6ZYhsr70A==,type:str]
  WITHINGS_CLIENT_SECRET: ENC[AES256_GCM,data:etlOs8GQxpxmXU7p6q1/O9nqB3EkFZMK/rs0BRlkdh3/TeTJBSJmPVitbIqGkqUkJSBuLMeXEQdhyEE4/LlEow==,iv:VNXQ73u8cO4kawlmYpDruvjVOJGAHUjmW4lxASXKrew=,tag:HZCyWrD/w5aXN5t485oDwA==,type:str]
  #ENC[AES256_GCM,data:hods7XyQ5NRJEkMJJsY5FMRUJx0KDxBrL7UPRk8=,iv:D7zcaeuGs3mbP88Wi0RbubtGJ3V6BW1Xk5AlnK5d8j0=,tag:ph5V0tRlOgaZbl13VTw9+g==,type:comment]
  APPLE_WEBHOOK_KEY: ENC[AES256_GCM,data:d6k58y53OLlcL/0Dy/SlScPDnPv9zSf7PlBp3EG6KtPcqQ7zEaM4cWaZkSu3fhj1/8E4GYrVE2G3ebiq60sQ3w==,iv:1wR+4IEbryl5+X7eZNam+4lY2bhz7U2G2huGOpRxKp0=,tag:wg+GtYnBu/TVCx14uPqxJg==,type:str]
  #ENC[AES256_GCM,data:NDNxry5oxYAvGObpzxWc1ziwzG8=,iv:QLJ8OzjuyNo5SRBBcsJPgxMpvWsgm+BzlvMFnP/keEQ=,tag:jGgOuWlx6JM03y1fNqnxIw==,type:comment]
  INFLUXDB_URL: ENC[AES256_GCM,data:H4qvl6nujNrVOVH8mtuwzx3qJVff+fNB9bxW0ZYAGuBVHNCcnsGzgekrmZJ4Pw==,iv:SojZZFK+XRZYrZiiOFFEb6tKEztSdv/xKD1IhNEwS0A=,tag:1XIcNQPe5UtMzqzK87Lq1g==,type:str]
  INFLUXDB_TOKEN: ENC[AES256_GCM,data:h0X/I161Y+rJs4f+M2cL1chKg+TXKgGjb7jxXmOHLOkiuE/xLUmd4brcXx+3MVEwu6KlCtBxLqc4Y5JXbnPjlQ==,iv:2G+5p8n3C4gnEyU+VPMXw81u78EFCJzh/hTgov0f3Xc=,tag:1KGbK51w2SDIEmyEWAki3Q==,type:str]
  INFLUXDB_ORG: ENC[AES256_GCM,data:sd5URXXZwA==,iv:vOSbq3cuOQxMDfbJNFKDjHtAdpclQRaSq6Gnvp781dM=,tag:ZUCyiyOhDC4SteKy6DYacg==,type:str]
  INFLUXDB_BUCKET: ENC[AES256_GCM,data:zCwcGK6Stz/SJs3hlUI=,iv:pzfYuuaSe4F533KjgNvFcnjbsu0Wrb0BeXB01NXfNR4=,tag:mRm1+2wQ6XTeoFs9hmZ0Mg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVeFphMXpaS2llUkRwYzMy
        NGpVVzdkTUZIaXNqM1d0bHBmaHhNSzg2V3hNCjdRRjVuTkN5U2VzZlVjRjNVSm9v
        bXZTT0pSeCtqc2tYR2ZOZUhCcVhmQWsKLS0tIHJyZ1d1ZVRCeDllU3VLU283ZVFi
        eGVVNS9xeFBVd0hURGtxUXJOZzZUMmsKgHpc+I6RWNsW9m2WElsj4I51+J6+J+2n
        7PQBIexqHspUIhwQ5L9AQFf0L5TZXq+Eaps2sQy0ToHZJxxBxl8sfg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-29T16:02:00Z"
  mac: ENC[AES256_GCM,data:VxuDFsvfBlbC23vdGmqLqAb+CdCuscEDdFs1Z6/273UeC/QKiiWY0QVD2NirfJXYFo1ZUELKz6HAupFqVarLPSt/17qdVAkFZBw6DNaQ/uctUU38b1McCEERj+BMKE9MUkY5tUHO5J28Z+OFoqanYhYBrqUrrZrNESaQ0+j9HvY=,iv:kxj9HJMABQlvlr5rj3LVDVvG5MbCG8uDny7ih4GoXUs=,tag:UWX4MfeXU2Deaw5hlb34QA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
