---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: authelia-config-backup
  namespace: security
spec:
  sourcePVC: authelia
  trigger:
    schedule: "15 3 * * *"  # 3:15 AM daily
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: authelia-restic-secret
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    retain:
      daily: 7
      weekly: 8
      monthly: 6
---
apiVersion: v1
kind: Secret
metadata:
  name: authelia-restic-secret
  namespace: security
type: Opaque
stringData:
  RESTIC_REPOSITORY: "s3:http://garage-s3.storage.svc.cluster.local:3900/volsync-backups/authelia-config"
  RESTIC_PASSWORD: "abfc6eab4e116586346e88065ba2ba551fcdf823386b65953942bd3f8c4a3df0"
  AWS_ACCESS_KEY_ID: "GKff99d45ec91f29804bc2f2fc"
  AWS_SECRET_ACCESS_KEY: "abfc6eab4e116586346e88065ba2ba551fcdf823386b65953942bd3f8c4a3df0"
