apiVersion: v1
kind: Secret
metadata:
  name: kavita-config-restic-secret
  namespace: entertainment
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:QrGjuCcmNYKEVITp9f0nPb+F7HFcxSwVI0SQpKsAazr0anGoK8K7ucmyP7AeZLXZG2jK0U+17Ofhcw/LD0wWNWqiIxz7kjRfA/tRiGRRFkb2v0nQ1jE=,iv:KSow17H13sYGNSkxUDcPG68g/+meldB3HTo3KJgXyOA=,tag:Ij6FxMlHgq6IBLgOhDYmNg==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:6NORuVMiptuWSN3Mv0qMTiQaAwHOeOpgDPL3Qg8c+DHc3h5M7bZd5Zw2g3s=,iv:9g/pD88yb0J2VkBB3cr6HhKRe6CT/5IOl7HGL5GIeYg=,tag:0CHT+AHZqd0Co7hTnidQYg==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:fQ00cWLvnvK/6UiACFa9+fTSYBGm0t3U,iv:kWWqiZdnpZEPFHQKSPjRx81L3Ycnne54f9Dcz6Ykwmc=,tag:gfUMl29vDaDyss3cayVEew==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:minuDKgCTW4ut0gtKW2FqyPvTG9NO/YKCZiRMTzEUzzt+8UZPQvwBdha7u/h1n18pAFNTiZPxiUw6pA+lUJIOA==,iv:3Ts0ki1NyaBTcq3qpgc1IHifl/yeMVmk29LIjEnIVxk=,tag:6Gyb8eVYAQ82IUhR/R+Wpg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWcTRJSmZNQXNEeHZJdTda
        cDFON29NUlpMV0E4WGo5TUtnc2hsSndnNkEwCm9mUk11NnBOR3hnWVdOZEc5ekFD
        a3dEKzNCTGdlSXptckVPYXZCdlhuMXMKLS0tIDJCTUlEWnB0WHhRTXBRckg3VnlZ
        U2RQclNBcmhIT0xxM015cCtMczFVek0K3bGQqeVdw4bhcsb/wf+uZDwTK7OK9aXw
        IgxnHXGGWWAHY9/KeuJmZ9ceT6DCcuOFHZfh/hVXK6m8Orsb3BrrbA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-10T12:07:28Z"
  mac: ENC[AES256_GCM,data:TirDm5bQ/zw+/KfqtFvFEwT7R5JiHAsTmWEXKhvRWzVeHloQ/px6f/RQHtHbm0OEdA9X1BYbT0eTZAQsnYlsphbdrGcXmvqmTPQV8lM4R7Tlm65/na9l4l58G65GVuZ9S90Nqup5vKFvIvzTiMudkP+EqcLF7ALACrXrzj+EH4c=,iv:5cJC7h0H2MICb8tXUYqxCB6XBYbiWYDvKUqvLFXZvf8=,tag:/xhZd0O7S8Xm5/ofthPjzw==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
