apiVersion: v1
kind: Secret
metadata:
  name: kavita-config-restic-secret
  namespace: entertainment
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:pIpR8W5zh1xOkauUwqpiXQSQfXswNpoI3vL2f0MjM1D3HaLcckioOjUutyNVhzBHtj5mZ9IDW5FytKOlr0AD2G12mlSUkwYBs7tldcwY09iphDz+UjE=,iv:bvaiI21w+/OHGKyTvZqM1q95Uac/GIbgj15wwV1JHXE=,tag:stljlNqqyfVxz9fppCn4fQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:NVZrHYkVCbQLN3W2OJD1GlrPqKCvVB2YfbzHZepI1AasErbuh42/8BlOLkg=,iv:806Ox2Ga/BQa9F/0F7Tfv5mpf8XS0N2QPREHcR2pq8s=,tag:e8gZ2vJYI+FQLDjiQM141Q==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:TmPWEyEtkl63nBm15UZlcDM+eV2xa0Fz,iv:m2OWa4t3mNnouQHWoU7GfCwwfsY8K9vOCNd68gOPWPY=,tag:7G9tV22yoarSzqyFkRZo0A==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:/VYThIczJ/39nxQVNXx4NNirzqJsfNxjGWvZcNQo5uHkNyiCNmy9FYrBDML4oSAh5PSQz1dA/o+s8RYjN2Lb0g==,iv:Mc0p+RShM3jXrMU7EkXue+DLpzsNrwLN7wADZULpi40=,tag:qEbAQa2xIvZ4O/qITkO34w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUV1A0aTl6d2JKdEpOVWox
        MitReXZwbzlrRjIvSGhlMWhpZGRFa0FPK1hjClcwaDQxUmF1TldkN1c3MVBocEpZ
        enpZZHZaYVQ3UzBJVHdQR3JLMCtkc1EKLS0tIDJlK0owbEU4aWx0QVFtMkltN2d3
        cHRvMjlrdEVFVml6T1RxOFFqT2cxVUkKwoERPcDPXZu5CZYrnTDxOAk0AUArDmlj
        17XqXfbi/Pm8au6ajXN6SuaVRQ5AvtENhp+t4mKqnbTxU2g9kYRyQQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-10T18:16:18Z"
  mac: ENC[AES256_GCM,data:EDo+zw6VyDzWNBNjvpIZbNw3pKAFogbuQHDJOSqgUc+gcKDUW3IO0k6kpFH9IJ8BB+mogSdN8nt2EZfgQCsqO7KlzGSlOFnRoT5eFZvS9tZ8RGkJw2DlR0Hn8bLBLNPLRbP/qL3oJ63H8U6axg7eXMMn5GdO/fb6oa0MRRgfPH0=,iv:MtAsYMtD5aE3KumSEU9PU6TBI9MFqSRNujV/pNk0l+E=,tag:qp6o7Fb2PEviYgAQJscrKg==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
