apiVersion: v1
kind: Secret
metadata:
  name: kavita-config-r2-restic-secret
  namespace: entertainment
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:0VO4gu3ZvcxoH8Hss5ssp0ZcGJcCiFXwghiAefwRNylhDcQ9viSyTEY5QLNaN/khrIZ7FOaRzz0t4wnL7dFope6OAxEkXt5W19LRQceib2jTjIo71O4vymvk2EugdPxs3GbZXBo=,iv:X6BrYURLMBcYzo4ADhEfUmdIcK9fZnRKmBPekR5vhyg=,tag:7ZYMe/KirHEVsjO8D0iHtA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:bMMh3kj4ZQJ595ptwkJoW8rgY5qS3XBSfC9Q+UA/gKsjTcr98GY3bC/Iab8=,iv:4BMlcH1WDK/lWNmyzHLk62lXe6JBtYyioyKfqG12MPw=,tag:IMcF//vwVF+d4tOBfj5jAw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Q5rjfaYrcrRx6oATxUy2ysm56YND3EwJ9zav85sfHdQ=,iv:fti0kWKMt7lj8NU6w1AAjHZiAlrWJ39TuagVnL6zhBs=,tag:xD5tUf7K60ULOIPIu47KLA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:yADjo24zAoz8rXRZ9gM11yUmEGQ9aqDyeiD7PcNL/0awfqExGSMwtKXGm9Pld2wdLW1AZ7a1J7EjCFERDvpJ8g==,iv:4cigVmeozU5ucSLmj5YzXSbs+q9j1UIPnlDkr3lM0FI=,tag:wAHviLysoZ5d66TcVLPFYQ==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:zZt7nQ==,iv:Wo4gDVMKwaqs0bRVjeD/OIJbx/yON3p5G4uNJT/7Eos=,tag:ZOYB0HyUpD3xd1Y8yhFPYQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMkY3T1hRTE5mTmFXNXRL
        NFNsbUdWdnZZRlVNVEdEY09QZEh4OW5OVVFBCjNyRk4vRFBRcEozTnVtUllnSFZP
        ZFhwNUl5MGYzWXgwZ2twMEo1MzNOYUkKLS0tIFRpUW9lbjA0WWlyZzRaOG9md25s
        eEFmcnl6dU0zdlh5UHpJSnpVcUp6L3MKARFsOBPAN26S8jHuQwVBUb8O5kfVG5DI
        vNMsoU+3Eh9qdQZ6TR6X+EuSVHqgL/DB4gfplMFGlW2NIcd+97cs2w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-27T09:59:40Z"
  mac: ENC[AES256_GCM,data:8wMVCN5QQP3Cg5b13f+RvqsqmNGjvJhgGTko/8wk7lgjPkbyyFPd7+kfD2JLhkMrDZJ+3NfKlKwutwBycG94AuCdFVQclybJvXXeP5jLyylrn6bAwk10F03KaJLfF0eCgjw59SoHm2pHVlpAZMqGkS0zCHdWSb8lzHyI4fZ4lYg=,iv:vTEEz8i/ZqXomdyz7FMmdmwkZcKfrYN4hN+nLITwUaQ=,tag:pmwBEJFvtwaM0H3051CSWQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
