apiVersion: v1
kind: Secret
metadata:
  name: kavita-config-restic-secret
  namespace: entertainment
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:MiIjj183aT2xarL5RSVD1Ck4bUJvxBpjzAW9xXHqTxNde42syi4KyhznfMttf1CEoDljXGK48yGuTA==,iv:1vBh/FuYcezSrRb6tyUkHQ9h82eYjeHwB4WW4DJ980Y=,tag:xsUjs4zJeBQgoYq/BpXMTw==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:6qJEDqv9xFjOIA0k83sNOyaiIYqklbMXUIxduXhDehPXydkkhKyrtOdpbRA=,iv:egfjTn6ecFDt1ojMN5K9AB91okX4Q0FWxhFSsWHn/o0=,tag:UFiC22CUYcshLB23MDfnJQ==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:IKlum+3IO9thLMmM4bi6ZenCQAP4vXW6wls=,iv:gB1E3bwIVFWJ76K0y0vaSb5+cD6SCaQ4SqZiLbFhuHc=,tag:mapOBdRLiZb2YfdNafwGQA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:AzLsIEwSx367gqqOq536b5l7h/qjtzWnV0nTz/AL+CFkSD8Sd8n3yfa+nLx+BPlGyVWWC+PHF4UoulWCdRwsDA==,iv:XqFjOsJ7EgEHUT7+dWJDXVuJHbJzcH16pHxNuPWWkwg=,tag:Sw6CEA8WMcFnofAHRuwjfg==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLREdTVnMxMDhpVHZzYVky
        RUFudFNNTzNIQ0t4UzZoUnRsbmtheVJ3U1RzCmNSM2dxS05yV003ZHQ3MnlleDcr
        UzBGWElmZGJsWTlOaEVNVGJpR1dDZ3cKLS0tIEU2ZVVMQnRkdkQ2ZzBhZzJWUVhq
        N1pRNUFySWMwTXp1ZnNSM0U5ZkxjK2cK4oYMole+TMNxFT9TeAC95LX7j6Qp4dMO
        Ab1zLCsjRnrz+ibZD2g5vcZGMHVYAAD1XAtfcQjEVyIguHmqtlVmgg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-19T10:30:26Z"
  mac: ENC[AES256_GCM,data:jLmets933HG2NmqQxLvVS5RcxTP2P0SsueRKdFxMw14rSjSUb9nkw/eUaVsEXAIs36WLBltV3m0SL7mKjiVagXqJLsxIzXikpJIeCJETMVO2sAoLdD8zdO4+SeOHWOdk/3qCbfJpXU4yrvzJa2sgGRKLtB3bIXdwGtq5I1lOFzQ=,iv:Fy7iWeC+osFXDJ3RmjRC8WKZHfp5JmFw1U0R49Tr78g=,tag:b8yrwRje2SW/inG5y0g5zQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
