apiVersion: v1
kind: Secret
metadata:
  name: kavita-config-r2-restic-secret
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:aY3dM6b0wEYg9NF1FF4g4bwzoAiR6idV11GIwCt45e0s/6NAqGq4Y2RXlNhz5mwOlkndYcqYN91vaqJLeUcKDcArWeCSS8gcdO+27HakQhyKkoZUFNSi/eeQfmYPHT/GgDYUCBI=,iv:tkGLVcl/bKXkobjSivIE9V7YIuvobv8DNLkehctBpz0=,tag:YA4iOqQatm/9SEFG8tZaqQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:cmJJ+FwR3/xMA1iIEEb03oJD5ssaEYX4xO49nGnKgr5TXWZ6k1JCC2YoMMk=,iv:XQWSYpW424FE8KRyOcDVnntSHa3wIzzt5Ry+oK56gNA=,tag:zVki4pS6o56dpCTY8BPS/w==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ciJFvSzO9VE12p2pAQOhqTeTKdpetZ5eZ2+5OW5vb2k=,iv:nTWFHG5jRZl4ozAkc97XW+BIXC6dWozerL7Wjf9j0mY=,tag:Y28o8+JV8bfE6YKeJryj9Q==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:AP3IBfCkTuNWR97dkROwVZgQZQeTioXIwvawrXW6Fj/QclJ8JWfq/4dsQa6HAkhC8q2r0Tj8sf2RhYbbAHMZ/A==,iv:ZrgcyGAxUKBxzU6DepjqQEqR9jF5S70YOCpSrjkTwXw=,tag:kINrgSQvX2lLNdmiRVKm4Q==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:SKL+Qw==,iv:QyQeMKghr69D4Ech9j0/hD8Ow/i+V2qtSC072rGjf0w=,tag:EQJfHkwWp+Qn958JYtfTXw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3V3RVTE1BNkRxTlNyYzEx
        d3ZnYjRoaXNUajYrK2gwTm9PMy9KSk9idUNVClUyaVNtZ3cyTjY5ekV3RzdoS3VL
        QmxyRFFCQjROdWloeGxPY1JzMEJ1NFUKLS0tIEgrR1pEMEx6UGVrbTE4K2Q5L2xt
        dmFhbWtuK051eFREeWR1ZGtZcTNDSWsKPSQR7aaGJIu+TqbTT/N30nhWYROJaTYh
        7Q7dNaTXqnwBso3SHhkSGQJ3/VBRQRH0LCWoywVAitacRQyymYLNvw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-24T16:34:58Z"
  mac: ENC[AES256_GCM,data:s8IZu76EYIyhfVlWb1/ryvEG7WHb+hTSCnqxRgIMOERv7abCIU2ss391VoYcMlS+8eaE2G10Sr32AtvNW3XuSo60wwL4Gmem97oA/9Ef42PGdH9e4lPxggkAuRXL2OuDf9xgM7VQdr1pZq7R6/DMihxUqnm+k1MpSKH4+zeKJJk=,iv:I9+Qjgf9tD+n/pCaGbqVlGVmyL3Vuj/E6NOWLkAHu5c=,tag:gGX7DfprIBpblo/wgmOqUg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
