apiVersion: v1
kind: Secret
metadata:
  name: kavita-config-r2-restic-secret
  namespace: entertainment
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:jZKTfk+7yaam6MLLObckxDsOT1+j9Amo8Jga51Qz10Sicl/9oPOMrGgvo/nPB/W/0g2/VaoHJgrpQJO/nXIISxk3JEGikS+spzS4g+4AVxevdVAvjnbXvmDXTIplzLJhZJlDrlg=,iv:5zNpVNU5h0UxMJxQWsE7hwza66VZhoAv1mQpsMvVMQ0=,tag:dnbXaRoIbwe/TFM0Z2XUHw==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:jFS+jgtPyCD3CcK+v1OfVjCB3OwcD5HhqJ5wLLTY2Fjo9y6eeZHuFEgtLjc=,iv:N6cPCP8jXJgKp4hhibGW4cdijhIntFhyqEg1G3fsK1o=,tag:NTxfyJbBNFdrsbxLzscJJQ==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:U34hu46eQMOhwTCn/XYR4OGtq10MURNpSnZ2ZntIifs=,iv:GMhS0foKU74Qhy/sBAx/n0GccWfg0qeZrx/CNNYkGXM=,tag:HArFDvMBsKSyNkSLqETlgg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:xuuXolOwp4IwjgyJHapLwddSdusiduEcJlieuVgh12IbXATL9hx9k2+WNG50hs+a0cxh4jscvi4sU0fZneV1bA==,iv:kPCZgGdyQklrPNb4+ES4nDecfUEB9VUj/6mXj8pie9I=,tag:m4I9yTntvdrxXihnOp8ptg==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:IzRudw==,iv:59jeyW1D6uMFBsJuKJWT/VOLrXXjRzBm+MT8HnKCOok=,tag:XCv11dBkuX/A0wQXG6UUOA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxbjh6aklaQUJIUUhJZ2ov
        S2R1ZU5kOW5SSTZ0SnE3V1lQTE5kejJidWlJCnNMZVlIWnRoaXhKVHgzS2RLcjV6
        TzFuT2kycnV4SVk2QU5kMVhrUXJHVVEKLS0tIGlPdTZTZ3NXTDU0ckoxdU5Scll2
        a0NEZVNHVUdnMTF2eFZyWXI4UTZtS2sK53ByjOJpwBSfO8DFjqz13lLILUw1N8sj
        KfZO6VOpXrxFLUATj+D4d35VpG/CuAEfp/rT7kqQZUa7cTjAmVnSSA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-20T09:05:45Z"
  mac: ENC[AES256_GCM,data:lSPCOVVgIXmlxIjuBs2hepSKay+wpED89nmwbncV2esWwiqL/gK5xHZVfy7aLsj3E+7T27HDrGUTPIBrKLBWxzCpBQ2tDxRAu7WPX7iviChrEjFUycoEfYm2/R5pf8mIOvn8jl5fZ+z9cC7S8qks+Z6NUxoVq1wlaEWmPWkf1vw=,iv:80CFdzcbKlRIyBccXO0bkogtWb2ye/Rx3EV5Y1K2b74=,tag:HcQLWh6gIrzG2gy5NHd6Ag==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
