# Restic repository secret for Immich database backups
# This secret contains S3 credentials and Restic password
apiVersion: v1
kind: Secret
metadata:
  name: immich-db-restic-secret
  namespace: entertainment
type: Opaque
stringData:
  #ENC[AES256_GCM,data:EP0PRzZ1seQ1DmvCGxtSWM7u1EHC9T86M9Rd2usvVwJaMmELtg==,iv:XrEjb063CGqZxg5vbD/tx9AXtc54Mi2vya52fP1qVAY=,tag:xnsdf9JKcbqizu07Y160ew==,type:comment]
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:NPa0kHe8mj8/6pQJ9Wo/kZhCf3x3zcUZSVKEJYasAb+4yu1+LWloe1hAy6IKeYnWD+pb2X2X,iv:Vcm30ckDVSoP7ncH7uIBqNWFJxMyNGVVODBqtj1WFW8=,tag:s38x7X1S2B365IX3awATNA==,type:str]
  #ENC[AES256_GCM,data:bMjPN3fn/F3YH+hctGZV4ljGjwxZYGERiQv8,iv:7JlrjI10sJsThhqfanG/C8jvepV4aicvthHceCmG3XU=,tag:mX8xBfrImSH6OxlP2S9wJg==,type:comment]
  #ENC[AES256_GCM,data:5f2TSiImqHRcZetGLy+15KA252bXmsb/+lY1PC2bcVrhD4JDCHMH,iv:XM8hU7SpAlkesEqgBAd//oHRBbUwb9/ibRzj7sW8ZRw=,tag:igrqyyteE30egEuDy7Cj5Q==,type:comment]
  RESTIC_PASSWORD: ""
  #ENC[AES256_GCM,data:G2f1WgeDjbF3cE+p99GgYMZ3xXt+/A==,iv:CmwGjBw75k1NUCbDP832bCuoQozH8LiBPzB9BMj6yJ0=,tag:ifh87aUV873nYjt5eEhzGA==,type:comment]
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYK09kZDB0NEhsUUV0OHll
        MFhpUDJuUW1rUFJTMjBMdkc1T3ZPTlFEMnpzCmVqRlY2OXh1MW4zam5aYzJ5NGhs
        WGxLR290bC9hcDkwQWl4ME94NWcycUUKLS0tIGFsUkJZNUtuNVhvS0ZaeCtibkZn
        Rk1BS2dOeDVSMitwVjdRMWtRaDB3QUkKjT9tV3XIdBlNr66EDYC+pmvOXjBbNsmx
        xnSZR5KJEOZzcG7HKv0bBWmfAUygLYLqdEPvzNUgNtGul+hCIJUoyw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-17T15:43:12Z"
  mac: ENC[AES256_GCM,data:W1MXmjKl6G4eWBqo1Q/9Lt0lngJ9uOtMKkkb1l5mqP7uzy2HbAbU+3GzzLv6lirJIyb5pKwqXuhjK7jMBMV3DHQDjt4zbkqWDqqsGMxPiOVPvtMEtrUrey5Kzc8hA5QlEpjFhnyqKSsNTZXjhyZnCs13oLOuQibBEbPqTCRpmWo=,iv:U+SPjdTbkpv22gVRncPChHAGIqM4L4+4SVF+/m75Gh8=,tag:4isW1zZuuo7flVRLIUYSNw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
