# Restic repository secret for Immich database backups
# This secret contains S3 credentials and Restic password
apiVersion: v1
kind: Secret
metadata:
  name: immich-db-restic-secret
  namespace: entertainment
type: Opaque
stringData:
  #ENC[AES256_GCM,data:BtaWQ0huWxpQJS5vn/hEtQmaNCEklaoAxh17Dq3SjfO2E9iKaQ==,iv:0cwrxJTEGPArsLBG8SjKCLyJ5khX72TsNfHLU9Quing=,tag:DOpQssUWIW0Rmj0Oa6gCkQ==,type:comment]
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:fu47a3EKiwhp9G26uw/sQX09VCPQ22Y2WfYDxrJQEskJqyygSm+mLiNkb4hfxwXrQ9XZeelY,iv:MBEbX752JQkX2oMNUl+MpwzvUlmxA1O2A5Ph3+k1eFE=,tag:DkT611kokBdXTOdAQ3PG3w==,type:str]
  #ENC[AES256_GCM,data:F0XGH6OOV3xWYtDbkdserLaMuwzIrC38NX1x,iv:hbn776ifpree6CRHI8pNCEfkk/FEv0e5otjHg3pZOS0=,tag:bkZ4m80UL18eiHqXcP3qZg==,type:comment]
  #ENC[AES256_GCM,data:A5K94tGuV/GgbGKjOxUhizcBC7B59PtWe8+7jEmbEJOqonHkCKu5,iv:lwdzsZp5HD3h2X/IUDVbPF33k0MMWdDG75CclpsUarY=,tag:Yh7xPG2AHmkGpgeJ81V/fA==,type:comment]
  RESTIC_PASSWORD: ""
  #ENC[AES256_GCM,data:/GqOf1m0LRv7WatagcoLtH2r1YFb1Q==,iv:ZP1c7gZlIDltf9IQOQ8kE1VI20nDmWfWh6trCaOjpdo=,tag:GrB/RtgaPLmSxNfocxtt0Q==,type:comment]
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBObGFvc1pDUGFnUUV2Rkhw
        MEFpNi85cTcvRXV1VnlWWVFKMHlPZ01jVlR3ClRpV3VxVDZ5VzZ6S2ZzQzVBcnJr
        RDlTRVkvUSs2VVpGZU5SVjVNN29HZVkKLS0tIFB2S1FISStQZDk5Wmx2RjZXczVK
        SFlDNS9DRHl3OFk5c01YZGRUTG8zTUUKWP5+rXLpZ5eUKl0gQkDvULH5t3HUsr2c
        aj8xSOdjUPyrZeHpIY6DU4KlIglN1qCJqqYL3Jq/pUGJjEGxpy+hZg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-16T17:09:26Z"
  mac: ENC[AES256_GCM,data:gNsOlh47i0CigOT2MULXm3F9xmNMabpzlv5zs+u+rl72/q6Sh/Ndjzovp0gePw0iWHx+G+vbxcsfdBqSMRh4MGlgypayZRNsUnaldk7xA7sll6yOMzeg9yl0wySSPprm5EK45hIlNnMe6GkoFeIIfc6Ie77fN5bNnQXypLOuWK0=,iv:EUjXpJXj3aUvOVu5TzydaJQBTiH0ViJ8UQNXU2mKcqY=,tag:OKJm4kP34pyfd8iX5tuuLQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
