# Restic repository secret for Immich database backups
# This secret contains S3 credentials and Restic password
apiVersion: v1
kind: Secret
metadata:
  name: immich-db-restic-secret
  namespace: entertainment
type: Opaque
stringData:
  #ENC[AES256_GCM,data:POdmMtShJTkdB6rQ/iGkn50fSTP4qr5LaWJOKuq7Me0cjibnbg==,iv:KrW4SzM8LhPM930HZ10zu+hNj3tSHyMWcfBrd2PH7ac=,tag:HciE7dG8rTXU7iDn7a8fmw==,type:comment]
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:cOX6mH+Gu5nOeR9MsAhP5Cq2ecbexeG2EkYw8rAVPrW5M7aIbQDdCYU9i8npo8B9bxMKS3Mxek2Ep45lPaNHvCYMtpmJv5Qhr44LEq2Ue3OKsg==,iv:mr7VZwqgzGVluoEQ5t3Hw59B+BAlPMFssnI3z4YFgH8=,tag:kncjauZ+dIj93ksixz1o3A==,type:str]
  #ENC[AES256_GCM,data:X9H7aRJ1SSAT6N6AQLMI+aOFDG6Fbf1K6etH,iv:MwQz1qq92L800PmyDfeKq0//ZYOKnRKcmikbzeYtuvM=,tag:iy75wvOv9+78RnVlZzjbeQ==,type:comment]
  #ENC[AES256_GCM,data:JSJkoGmyXn86xZWuW6AJsnk0h03prEQM9r0WEM/OvBV1/hub1E3N,iv:QoTG/egUpuVMh9Z8QciF9/pKLT3mStaWKylugG9hw10=,tag:cadaBIHgfFDskUe7Fyza4Q==,type:comment]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:eEFQUFmGQCOaYy7ppqlu6qxxijSJ6mVr8ZFwUJJ3pkZhKYxarhKvcOEcFHk=,iv:FTCiOywXtkpqzk6RcykbKV4EPUuIXP5IsiM/9UOHKP0=,tag:qO/4aihg2yh7yo0Ii5BRUA==,type:str]
  #ENC[AES256_GCM,data:SwsByMk0wCkNtvdtK6z0JFSyfVS4rw==,iv:SOsMtYUJH3EE0JLFVNpQvteIEYGM+hWRSYrv+zK/afU=,tag:Iy1h2CevLWKyru198uAFHw==,type:comment]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:X93C2J86Si5EwS8UnQxD146dO0uaFyva,iv:N2Yaw3C0dr6GAbQET9EKTEMS5TTsEAyD0thjLNJOCgU=,tag:K04h/NV/zOgd6REiXhO2PQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:QDByZutJiWQJATungjFndkFEESsMUGTTEc0/KvlRhtqr2wMayjVL3czWdkCbku7ZkbeBPYEyH5Mx+bZF3Jj52Q==,iv:iL04/b0rKAbQhVluHiuRXoOe11Qn1blPNofuiTrYP9o=,tag:XjVHHWybNeVU2EgXx+nI1A==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0V0VtdkY4clZNQUtqRE1Z
        dTl6ai9URTNsOFd0aHh1V0l5SGY4YjByQ1VzCk1oRnQ1YXZwYzh4ZXNDKzRLUUpn
        RTAydUcyVTdJZ1JNV0t0V3dITENaencKLS0tIFEwRlorQWdLMHpBTzBsQm5lYyty
        VEZpa3ZOaE4zM3BFeUJJNXFSMTZZMUkKZ9Tnf+H69qQFOCEBiDbS3AXmn5Wt6PXV
        GXoenOu46SygsdthqcLumlaelbA8zbKzDwqwJN+wi1zSxjWKErkL1g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-05T07:55:06Z"
  mac: ENC[AES256_GCM,data:ToPdMc6TmJK9zdlkR7sl0GeZ9GfCx+Yw81X9DgVQwUmmj05v4AXlUNkom32bm4uR6yKg9HYKNrne7UsQNbec0B23LhqiltrXo30MXpB81ToWyWS3+Tmt6NO0bRQZqZmcves4X3v6kb6puCRw9AlIbCoIZMvrErVdDkMME+dFKN8=,iv:57rtXF30BcSRY+JczfP+iNBMCNBMf0cTD2Klgf2961Y=,tag:KJ+A+jJFyJQdqXVI+0fXHg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
