---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../../components/volsync
resources:
  - ./secret.sops.yaml
  - ./secret-r2.sops.yaml
patches:
  - target:
      kind: ReplicationSource
      name: volsync-local
    patch: |
      - op: replace
        path: /metadata/name
        value: seerr-config-backup
      - op: replace
        path: /metadata/namespace
        value: entertainment
      - op: replace
        path: /spec/sourcePVC
        value: seerr
      - op: replace
        path: /spec/trigger/schedule
        value: "0 6 * * *"
      - op: replace
        path: /spec/restic/repository
        value: seerr-config-restic-secret
  - target:
      kind: ReplicationSource
      name: volsync-r2
    patch: |
      - op: replace
        path: /metadata/name
        value: seerr-config-backup-r2
      - op: replace
        path: /metadata/namespace
        value: entertainment
      - op: replace
        path: /spec/sourcePVC
        value: seerr
      - op: replace
        path: /spec/restic/repository
        value: seerr-config-r2-restic-secret
