apiVersion: v1
kind: Secret
metadata:
  name: seerr-config-restic-secret
  namespace: entertainment
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:75AbxdDAs2gMuS1jcwb8TIEL3Vgx2kw1Y22WoyeBcZaR4694tx5CaWUTqbnIrtUrUmio0BS3lAu8jW1UJwCrXk2vczST5QyxGlPqzI2mcGP2v7Fbfg==,iv:5K1zJyfAdFnZj3bg4C2u60y+HiRcoto9gjrDL9lolyk=,tag:h5+op7TODHIga9xB7JUyvQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:MKT3A0OgPtT/ZHUszD8RHyLEuIgLkYndWW5PAdaCJu6+UMHiWs2hcC3Ju/g=,iv:unY5BYknwX57bsxyACjI3xLhAVNLIwMirf7mySfkP0Y=,tag:8VFkOh+9foYF/AckW/SgAw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:DCBm0G9+9ybPhkHWuV4dxUZXF78uNlr/,iv:sF3WQ6gcfFz67V1FspjG2IWhzUsqIbIkUuDOim77Rxc=,tag:nm7Z3vB5CeOvqLMLzKQ8jw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:DyBZ9AVFcvaRR/BDPqHOtaM51FbSJaPuJMw/QNWen+5IgDhJE+2pl2SGbxyeAVobGt4wvafeKBStp4kDJRpDbQ==,iv:jVN/EO6JDORJgrES1aobOUpW1YSu0UKH2oh0ZMQRfkc=,tag:b21dOEWyp01uwZWC4IhPnQ==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAycC9NWGpZbmJhUjFwM2d0
        dnZtNld0L2ltZEswRmJ5akNtd2czOVhBSVc4CjBFdWsvOWtiNHR1QnVUejlEKzY4
        Z1BCblJteWd1UHRONDVRbnRBTi9nYlEKLS0tIGRTLzg0UU9aOE1wUkRtZk1xY2Z1
        bHlPTldKcGM0S0lzcjRUR2liQzZWejgKtzrtfnHdR/SguN3JKCOBR1vqR5EZ3iWG
        L2dbmLAzB8cjWW0L67vOP1+wNYGNa7FbXacNVech6N/C8uvMGJFdxw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-08T19:08:23Z"
  mac: ENC[AES256_GCM,data:+CVJILY2K3hshL8cQqw1dJpAHgAuC1xcM9R8U+Q2gAc+rCRhaPAHUImCcmLUPgOgA2lMUoYmN4ZMn7N/Hoq09yS6tRlXSJSa7bm10YBXECHZmPuxkc8XrW5P9yti8xZRc2LX+YCM5XvIDC5iF9b+0la9bBSR+O02r+xXs7+84eg=,iv:AiMzzxqKL+a3WyAt/0QkppxJNDEH/PR933qJQUYMsG8=,tag:fa1cwgdpzM/qTvDzvxlqsw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
