apiVersion: v1
kind: Secret
metadata:
  name: seerr-config-r2-restic-secret
  namespace: entertainment
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:WONYjD6QfqfpSJT84aMvkuAvYT3FFEejO+bo7QoRb6jPIl5zva5kORODWFrNGS9mbqXoOczdcP8oq7nmyzXvVt7MNk7sG3rkmHTAKJvCvuvtXuYb3cb/f7GEjPPlJjOWKAaJ7A==,iv:00Qig2kl5Nbj9lHkKtuLYCleHwBsAqszEqdwFYeQDIg=,tag:IRN8rif0Yu0GGXvHKVGT5A==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:sGFXms+SeETo+cX2N5AjDpzN2/Cp2dhNxNfTQZIItG3lQsx+aG3xY5RBUJo=,iv:wMMQQqDfC6mt5xc1SzopdR9SfmJhNo4N5FK1LJMSU5o=,tag:OEbHSHNd7PsXuMqvLeUvZA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:YL1t4RfKhlBaGzjwdiNWfrs6XJyN/j50+Dsfjd4q4QM=,iv:DkurAS4kzfioV2Na/q2q367EvA2BxVyPxgbDwbDtKlM=,tag:LwWG/v9lZHGEEIGMlBbGvA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:DxjJiCqSLw0hs8tVgg2UpRk/VFWv/1jChn4fw4XytSdKJ+Jr6rlP7+/8dr4jBw9qZe6mHWC1RBvNK+RqUQCBFw==,iv:bFn925zOzDu1P8Rf5nUCClM/5BPBuXb02Pc2BlzcIiU=,tag:c/2qCyVlKIQjqgC5TV5rPQ==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:rdgG8w==,iv:lTJwEBq02QDLAFCDiVezPHRCBXuGL4yiKWTGPPqvMsk=,tag:byTuKSrkrspKvsQfGm7vGA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWOGN1aTEzNCtKeC9FUjUw
        Zy9FMVBOam9CUnVRTWN4REEyV3dnUU5JcDJrCmNtckRHZW4zaUxsL3VYTmk0bVIv
        dUp2SGFpUTBQbkhvQnVINThwWjU5QkkKLS0tIFhFSFV3NG84dHFLbTRJOXVjMkV1
        b0twZlhBdnZBV2xmRkhrRERodURybGMKN1/AxCleZabjBKug7RnSUBOM6+eSxeaD
        ScA80IMVyGC3aRHP/aNwOxmTqQCQnH4U8KbThYi0nXLKBbojCFMrzg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-04T10:50:08Z"
  mac: ENC[AES256_GCM,data:/SnyruE7x87ZUs8PVwRdw9VFKQ/KBsUWy8tYTgytiVjZGEZveYJeQaaXQIffaOW/JbOvBpswzsvm9hN1lVCsRTVb5yTdRVGNtMvpB03xX5YgOyKKTv628KEVKGOIUfwp/SDU1UTkxxS9JDlOt9Zb9MPHzUvyNUT7HeNAfQ4QE6k=,iv:bNsys6OBiVhEKmJ2ykW18Epwt2tfNqGrmd3Le873+8k=,tag:LjCgryBT0T4gSEnILtEqig==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
