apiVersion: v1
kind: Secret
metadata:
  name: seerr-config-r2-restic-secret
  namespace: entertainment
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:wbryNJYOnjhV6lJdWxPjAb0ZK3O82bm9eFq1Urab+V4YzdBcWc5lTQ7VULROWoEA4QcDxuFM5Jk9VbPYkAS3VU7zvOVIEoyjf/cP+RPkk6ID4scy9FhMQk9UTYW42swDFyA8rg==,iv:QyF0XPMz9fWfoh2OVVE7tPzRCXtOZfA3sToxa92nvw4=,tag:7TNn7KUMfLkxwlOg+y2MYA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:cofLW/exm8sWfM+ASfblVTpyw4tT8KhXNRjc3AZ6VgjS1zbpi8MmdYr11sw=,iv:RuTV0AU5yG7jM91Lt5tDs6kq6xpQEBTalsJ+RS7Wk/g=,tag:lsqr/rbcNH/V0t1gxGYpHw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Wa5I3htvtLvQgfKMAWVdQRtwMwyap4z2qLdFV0iIp4o=,iv:Vgd0+5KoEiBR9x8gNESbyt/QtevELarIyshUulJP9nE=,tag:Ix2gCAtOGPg1SYTP+zvMfA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:/T7MTyUulIJbjcR0SZlduqlTtLd+qYGad2Lao1Znmp2MNG8moHaixfYqizTRuOzJX/tIyvfcxlVSbLRcGi1J/g==,iv:Z+NbR71FejqAEjwXJNzXMZ3e6/nnzmO8RO+Uyljj1N4=,tag:wM+ERQ5oyWYcKOnneYrixw==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:QCxivA==,iv:1DF5IJlHOLPOwQ7q1oN/CTQXkDwJg81rzUaQ0jA9iJ0=,tag:9FxgvGn9Utbl4TxGmKhnUg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMlNMbmszY3RWU2dSdHhw
        TWR3djgrKzVIS1A0K3NDYzZoTzg4cGUxYTFFCk44NDYwL3hzVG16ek8wMm93RlBM
        WE1RVCtqeWt4VXlKSkJEMFVVdVVJTG8KLS0tIHdKaFZzYUZ4TExKUjBzUFg2Q0Zj
        VHRGNVQ3MGo2ZnZiczNGWVBwU3lUUGMKt4KH8adIwDPRSFfmhnZeTzfp+VzAWFNI
        qbYMrzFFnObCZgahIpQDCRiBmnc4cAoodM6DNzzUZWNw6ZNsaKUohw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-29T07:29:37Z"
  mac: ENC[AES256_GCM,data:NV3JDuP4ox9UwAjfcEBSrojD9UJ5SebDFl6CzODZvRKQG1oITS5HdWrtmlOckdFQPtpc4Y6Zr8eVJjSwtl34Tjrl8n5uRov3Pn2Zr2p1ia7nP+RrhPe3KIGdXf469JtOl/V9GVFuA8ZnmBXx06lq8oDFQFmXo0uEJus2EKM5xTI=,iv:RDse5kARqjdsNG7nurdyd2Oc6y3cfUbo13+mSJAZkxE=,tag:Oqzi98imXEjkiFbq4/SZNA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
