apiVersion: v1
kind: Secret
metadata:
  name: seerr-config-restic-secret
  namespace: entertainment
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:S1D5KUQLCcOV51AWJbRMe+A4N8b8TXKOxEMQf8BP//osay3cKaedu47v7ZUaowofWprHExotko3WSkfDrWSWG07h+G9azGsJEZJDtBcK20XucIptHg==,iv:x2lC1c8MAC3wIGSw+9szTQsb2O/Yn7Atum53Hk8PZw0=,tag:6HMUcsj0P6B0IQFARg0uDA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:bG+I8K6RVdlOaGZLmQi924CGtLlWKnkpFIoYZGJEXNttNFqjPNAJgDgEZc0=,iv:ZQZdyDrwf5HIRcP1XzPmbkIYPZYttko5KSvxet9HNwQ=,tag:JJBd6L9bYAeiJVmpo0TOOg==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:pHWGj1l7cOutgAU+gEha/4YUhm58ZJQr,iv:n/R4OcYiWN3JZ/xblE6KRNeFQgxaZhgwfXfMQhlqrv4=,tag:lX/YWkDFkmN2Uh8Qu7xpzw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:3LyDYxShR15WQAS+S55A6PwfezSuQZ0trxeqHSvmEn1r7j0faYYRCrsYLP0XME6kI6BY7qAwNZ8Oae81sDVttA==,iv:bWLAj7WajDPKhoe4V9Qlg/5jy7J3Yge7/ZFEhBOcvY0=,tag:rasawocaGGXHx7iCIazQeQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1S2lWNUh1SnplTlJFMHlJ
        cG44OXRoTGt1UG1KVGc0ZTNoOVhyRyt2c1FZCllTQXg4a2RJOVdOVFdLaFVubTYx
        Z2crdGNjV2EzbHpMTzZrdE1ITlFGUncKLS0tIEd3U1BXV0FFRlFRcmh0d3hSeDhV
        blJNNlhhL2tYdmc1Ynp1Sk9pM0N5N2sKyNZZaKc+OqliTqrzMjZwHI3xpulJ1DbA
        QNs5Mw/RVqqmWEo7QvESCDTECNEQRdI/JGzi8AQzfUo/2OsaAXqGww==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-01T10:12:02Z"
  mac: ENC[AES256_GCM,data:h1DOWXjrINtLp1Y3uTkJJfyQD7RVd4r0Km/t4tebj6T2x3VlUwLNMrVc8br2VNAUMklPPwY7JeCiqgcUGZm3QftY8t4E5U5KMiZIvTwdjkRYACgOljgUjR4KmxHPuY0A75G7qY96br8Ck0bjm+f8EBDSme7goK5gMYlpX/RSvoM=,iv:KdZjXxV2j/+BNRtLUnuOSBornmXrxt7FLh20zU2oV3g=,tag:xNUDA1TJH/Dr99TbKJ1XuQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
