apiVersion: v1
kind: Secret
metadata:
  name: seerr-config-r2-restic-secret
  namespace: entertainment
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:znRHWwjpT6FrQC21Ksx45IHhXylMPKquulOZtI4dMnMpjTcMKmb6Yj9ApUxfFLz6r/LVuNamQ3xP1C6pn/n7MFyL5H20SKuJypU0H2DaxJocJaIgTDS2CkdejuyxfhoD5HMUkQ==,iv:T9BQF1uMnr/1Uk7t2GLL4k0nlUsn2TOme4n6tSUoaaY=,tag:VYpFqguetRW4vGpECcCLQw==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:GFP11U10hcuiViOzgV9EBe1vF4qzHD+fOg8y/gdP1KHxyi3WeEB2xXvHcyE=,iv:gAV9eXlkb+MI4o0z9UYtoo8rTb4/lB8l1RcgbNUGQdA=,tag:wfuYj9q0MzbT2/Jxqk/viw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:UKIbMmx5dh8C80ip7ShM89DzjeGfptRw+E0s4dkFLB8=,iv:i6Zv5znc57g9PP0twy+ROr+uZ55qzoCNj6K+m+rPO4Y=,tag:j8FivByMIxq7YoeOyCoGrw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Nav5TNJiqqavoj1YFEqIZQIP0LpofEaf7tZSspx2fJt3kDMusE0OY0mRGwIoyqZ+l1foEQksJsDPiP4rnfolig==,iv:6AqOE4ONsXxMiDVXm/hX/nlRiMOYkHZkld3KKOnXzS0=,tag:3/poCI98lgsubW8KC7ifPA==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:Ve+N6w==,iv:5+Ky8Id0VwkwAt9jGNMH6LgI+ZztlV7iPsO6b+t0HQA=,tag:VUv41Slh8PsYksLeswt3LA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYRHFzYzQvWVpESHoyUHE5
        cUNGbWp6THlRdFExMGFjNXNBM1RzUm9tYVR3CnlvdW5vWkkvNkZiUHpoWmxkN25W
        bG9sQmluSjc0N2ZJbU9Ic0ZPQ3ZPWXcKLS0tIFZOeWlRbTFiSUluaytLNCtiUkZH
        ZmxkZE5NenRROWNPdFNOck1hUU1wdVkK9x8SlbmXUlyjYp6R31L/dQ0OhHfhpnJT
        rDvd9yROgkWTO9wP4oQDuqihhJDbwD3jQ6uX2ZuSpEFMDNhgkU64gg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-04T10:39:57Z"
  mac: ENC[AES256_GCM,data:IKexD89CvFFyt9qIs8uYiRuUlK39f0C96/1I8gg9nztKBwUuPXGJw+zEoE8OLhjZd3Xtil6PjYawgTrJa0/UUY3bBtds2JwlPLUD1vuh6wiLNJ40hsxvCsvUyBTh9aHjWuuvJeOzZJWpfRsvlMi+9WN2lxfLO3oWAmTCgnmybOE=,iv:OIKesGLmEBrg2ZIaVWKHWnSp7/zl7iueNVe64e0p4RA=,tag:CIZ7zYlnzxo0dl1cYpqReg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
