apiVersion: v1
kind: Secret
metadata:
  name: seerr-config-restic-secret
  namespace: entertainment
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:rwKsNCGoJ5WhZe8lSQmnofUCrhYp43DCv52Wr8zvvKoj4JXRyC5jh175RVlyuDvlmJw4gkK8NTxnWEoY+6nB95xEe2X1rk3wiFhg0CYWmx46yE8Z5Q==,iv:Q3hMnl5r+DZlIkPwFSz4TRUO/Io2PDHc6vG9tEBtzMQ=,tag:YTEA/m+kzPOlFgw8NGRBrA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:h7jUNt5kHmsHtd0/sUoTq+koBrabbORNrzDIhUpk7n74go+JmfMVxyqnNAY=,iv:wWkR4AUr+oqZbX9EZcl/jKqaClu8kYCA5ghlmTTpRVw=,tag:5toJS4wc79MTcmkGF6eu4g==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:y40FE6XPt7QiJSR1UR3X6rKADNxe8juX,iv:/0UnySsLa/Y8U3P8ne4lrOhlyLfwwZyncMvdiduvbpU=,tag:SjNxacCq4TtosmZHK+jAXg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:7UsPxAqUoZ8v7SgAYOQg8jhd1U7fJibvZe1pbH5/DhF8QXeRLMcj0VhF77vJ+5MCMdBI9fcPcxxt55USeEw9TA==,iv:f3h3Y2rI3zj/f4IGg4aDoExYcZ0UQ8AsC7VTgAfrSWc=,tag:8Od8Vz0nXJ1xq2XjeOY3XA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMloyS1hQSEdtcnQvcTlK
        UFRsRkNRME14aTJrRTZmSE4zUVp2MERwUTM4CmdFZW05VG9pb0YrKytiWVAvTzBH
        bDlDSEhYSS9TNms3WVBxYUZaRzltTmsKLS0tIG1sSG1vdEVpNDB1c1lKeUNxb0U0
        eGhueUJMTGFSR3V2S3paNmFjSnpwR0UKvz5DvuXBfENnfHyvq1JJmdpt4AjeZ8wJ
        8Wh/2LqHKZx3yq7Eu6l7oLuQhb6td+v9jY5pZqSrk8oyqkYIa0DBTg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-14T14:52:07Z"
  mac: ENC[AES256_GCM,data:ZZzLmgWNFvdFm7YokTAfUAlhHfameCIHbyOZn4WlrUj1jj8ePyZNPr9PcppRGxNXpzVdRtiWkRJU0cHnPm1ZBi8I3mP5kzi7GcQL7TRtLvVQ0LXD2X3UdAfcYWvnhjkKZ3T+JdmgkrzGLziDfzhDNmcHmewFoCk/8iQ2lXGOLBE=,iv:EJ0OgNLSoHte+l3tibO+nMhIghx4itHWov2TsOdz0/k=,tag:a+g4qwCdFPGxMG8Pn7UhAA==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
