apiVersion: v1
kind: Secret
metadata:
  name: homepage-config-restic-secret
  namespace: default
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:a8EAk3JDgHlvlunTJfGL13EPF8NcyY32dw5kiR85TIIqabRJkPS1WIwTlOBzPt3MNOWYv1l8bZUa/Gi6,iv:lAhqg0PiMFbYIKWn8M5Z/zIXNN0pSyqMYFpiGr12Cyc=,tag:egT18anNifDjtnq3WFoqxA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:jSrPK5WHSRQDuUjH8YcxFstCH/gnhyatW7vQIBaJLD7JKs2AM2eEMTRP0j8=,iv:KgOBWym5nUyYlDco47Q55zta4E8/C7wXlZENKWIvey0=,tag:k9ykN8zW+nPTl/EDlm7tfA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:mNAHMQNhhQKnNCt2LHhXVdB32IIVkn+mi0M=,iv:3MlFfeZr8NrDUxTXm5FCzOwvuFBvaZArG77vuBnKTEE=,tag:e6BAhi6ufRBil0KJIgjy/Q==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:I0NkoxyPb25fpI/V8UuLbv2MwMEMMYZWZObmyjfBNqhUTnA94xBRFuAaRKSckQ93yvGzhKLH4FfT5/eL1pp7+w==,iv:MykOsuNTA2MW0K9bMOkbTmPT7/mlfNljU7wEyljEHS8=,tag:fMiEnAbDG38ZQKVB9SWXPQ==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhT25xbERrQUJBQkxaNG1i
        N2J1aXQvZGd6NWg3RVdaUWpQS0J3RjZoYTE0Ci9EWlJsMTdRckJJempUbG0vVkZ1
        ZE53OWx6Ly8yUitxMWtnc0VNK2dMMVUKLS0tIGhjNEgzaHJvMHAxVXlTajFSREVX
        blVjWjIrZ0haUDI3SGFyVHN3YzNEREkKAv4vVuUYfxETtGeg7E18IcEjIe9Dnzsg
        su1rhSziI3qAN+R+9BVBbj9vvAqaj84cDFZqHj6ENXT1MrFWnpoWOw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-19T07:37:52Z"
  mac: ENC[AES256_GCM,data:CmqticHsPh6XsnXQBkkQaP1kTKhWtw2Vm2O4RGDCSsDk3Zla1jmOfQ0+CrEBgUix5yGSGx3/sRHb+V+LCTdG3DYlPnh6TJLiyTma+bn1z82b9xidaRtTbC3ItNdpxBTfHdypSgrJSFSC6QwrNGM9/RmBKl9+WfKpaNK8/m6lfjc=,iv:lLOSUQl8/esUIp8oou3LBmSIIV9Ml/YshaC+nze2QlA=,tag:JOUBKgIKFJwD0o393GXOpg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
