apiVersion: v1
kind: Secret
metadata:
  name: homepage-config-restic-secret
  namespace: default
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:rg+XBY1FHYc/yLVx+a8UlGRWcIyt4naa/cn2zUQvYIXpVHyP8kCMmBdOz+odn76rlaHUgZdj6vNOjv7J,iv:gXaERbURwE6nmCYljLkVjCJ6YK4oK+HRFNiCAUAnDjw=,tag:VsVraWtGJzRc3Iv/GAg8wg==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:nQgHyhATTL2/07MkZANAJtTaJrUlCURvVY+ZAFfUUEULdHmCbJq/Zc/ocHk=,iv:rQI7r1zr7bL3ltWYBItNbKm7ktLZkZK0vUxXayhi8u8=,tag:AJCpsEIxYJG6OuoOkqFHBA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:sBLAVyg7xwK/R4TSHppoDZxWKZMIPld2wV0=,iv:n1fqFbBa+XAKikBzSwg+wt19KcsCc9coVmc/mYzSQyE=,tag:1Fi47HyZTlwxP4OXQKtCPA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:DFKx8DCLINEH4Br2m/wlVOTO+X9o2gbFKEzfe9Yy0K3rZvZhVx6ml11qBdCw1KXKXc+T94IXQKHlk/UbPk6nkQ==,iv:24fqhL3SpfzJSsDItH/PdHsu9lm/cMEUco+SZxt4QWg=,tag:ItKtb5FjfmY3HVVK67GS7w==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdE1IUm9uZm5SYTFxWHdp
        a3dMNExHeUtJdVB6VFVhekRQQVFPbmFZY3djCmlrWjAyZHQyRnl5ek5hbmhxNWth
        R0FOYVFsTm1CNjNnUzNzamZyWjZrcHcKLS0tIHFYSklsNVBRcVdUaFY0ZnNiRWVr
        WXc5bVE0U1RRNnV0b0dZdkI4YjhCeFEKCwlN7DoPJVVE8L2less8ddh6I+0nQYQi
        silHIqEG/wq2bKf4xUc0865YuBZKXo9XU9wDWnhsB5XM5qpkFRhiIQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-17T16:17:52Z"
  mac: ENC[AES256_GCM,data:fTTesTrkU637GUjFyCAlKO/B9feXdRabbhd0C9UQTK8r2DIn/dimBra53lNmeaA9Vvu9SIpug2sbOqi4IwIuT+2KaIJ/y91dvMHzZk50MtDV1G8LYxfqWLrgkxDzXi1Hoit8gFCl8mO9LtA+gpqT9uIq3eR2De4kF38pevk2cEI=,iv:QHztLDgmvhaY5eu5+sUqyDTt35AhqNQlSPL3taA+i20=,tag:BFRWw5p+uVQkDgL/9/1SgQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
