apiVersion: v1
kind: Secret
metadata:
  name: homepage-config-restic-secret
  namespace: default
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:CbEQuscZMAoZGqnYS6kTD+32hl3CMFv+BFQbqnKXpdwZ6tkye7yfs2pylZghtri2jzGfCQdzqDaT+abZ,iv:sbyl2pgFWNI3P/8jb5h0RUMaW/3CsfGMqcUxY3D9/ls=,tag:DNNPZNDCkiaFM+lbSIPs3A==,type:str]
  RESTIC_PASSWORD: ""
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWSVc0bWl5SCsvYnRnMGQv
        dWROVUYvcjZzRWFLcmk1aUVMWHVQQUFiaDJrCmVPRlg5M1JpR3dCOTRnWDRZOC9p
        VjRYT2c1aHhQY3FaRjNIcnFIbE8rK2cKLS0tIGJkZTRlNkc5eUJwSjgxYjAyUXh2
        SzZiK2hYdnA3dUFPSnFxM1BjSXVHVEEK8uZW3WmbF9cj9tXnAR0lz4CyW48+WKAr
        EcfQHAdNTtFGjfdS6wFkqd5CUPDLwDYqbUfr9ps9FDmbwc5H5nwmDw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-16T17:09:26Z"
  mac: ENC[AES256_GCM,data:3f3yvxXcRyJ2/USpTVqDscrs6IcOi0PC3iPfEgPPzYCHjud7EaX6GyIZ3TdoHT+7EQDa9myJFisDjEvNX1egfST9jGmCY/j3YiFlMNQXnTPBMNZXJdz3Dj1ZJo3APy4tGiUr7TNWHIhIzXWz/ksv5FuRc6gnHHKJ7j1fGRtUG20=,iv:dYonys/lhGe7y/6QBWnP2Zi6/0/jbaLxz/aX6ygtffE=,tag:ZJIaUzvR0IHKtUEg4JjBrQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
