apiVersion: v1
kind: Secret
metadata:
  name: grimmory-data-r2-restic-secret
  namespace: entertainment
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:1ouiBXJzdoFy5l0ESFf8sKMlpuC35t81BBW1Ycc4m3UEAnJ9czquPKvuG87HOR0HeyRsEwRBss+AKRBHL2tIEtICAYv0+RJzlC3169PBmAVG42lne+c5zj2TqSO4d8ziEXVkPU0=,iv:YCABvqC9r1ghJQ9jkXJ4s7Y/W0RfPwa3G31rVuOKbXM=,tag:UNLzRhyivByFeM98f7QIzA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:H5x0h3+EXoVDjzlvkOn6PR6eUkFBSD3++Srggwbxs8hEMZCVOrGrFurYhpw=,iv:vkiths99uGXPDJpI+AqLSzSNGAcXPd/J47d9cwHmBrk=,tag:FWDl80+xr3gNHuG2Xx9OdA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:D9dF7ej5HknfRELYIElOQ2w1vUubuWAj7AFPVClN4uk=,iv:mucmOoczf/6Ub56kICEnAiety8y81BjSz7NWL1emKts=,tag:cWolJclXdXZPl4SBJVTufA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:jiK/LoegKcHpEaxgH4ugA6UzSpuG6DBacAs08vCuHsnsBcEwF9qRBns0WKOvZltFLlndS/nNyA9WZghKlTZMEg==,iv:Fcu08KjP/EvtIUNOfPIWNnYkxR5d0VpuhoDczeCuZZw=,tag:6HdhDddYCT+pIsF+Y51uQQ==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:K9kFJw==,iv:lkXjHKi6z2qHJwlLYV4wgt+g8zqp9ASgf1xtcHuzokk=,tag:prAVIxYQhyfTZXlu1yHp/g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSzZtUWlHUk5Gb3duci9I
        Z2lFTDJrRGJZVG5xU2pneUJWaFp6cUJqSFM4CjRuUzNETHJXeG0wc2FYVTM1OFJ0
        ZURsS2J6V0dpalRWcUgrVThPdDJPUVkKLS0tIGZrWXpPY0EwWWJiSDV1eDlpYkJ0
        NG9UVHI5VitOM3paZy9wTkQ0OUpGdUkK6H/sXlJEXfDAMj8tjmezeHr6hjjWyaYC
        Tw4AIye3SvXJyhpLVJ/6ikPQVBfw6qpFpx3u0RUN9zwd3jnqELNecQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-15T11:32:21Z"
  mac: ENC[AES256_GCM,data:aaeFlrj62YX1mdc00THOjoAQ5tIHFYet2XnLvhRxbmsB8OLph1PJc8uFlv9kkek4xWyhUpOZlZCly/J6CxlYU70kRUHGN/328g3A3sLR0Sx3QLnSYGB7hvM98B2K4Gw5mtAWfQPAYph3EThmtBPtb+bH/OA6QKiasVxXOe+NvOg=,iv:g7aG28AoDYT4QE0SScDLSMXM6hlmrOpbEqKWWXmwBvo=,tag:u46ZkpV4HBEpUmUFgEm4Og==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
