apiVersion: v1
kind: Secret
metadata:
  name: grimmory-data-restic-secret
  namespace: entertainment
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:KSMQJG4SQAIWb2GjU/n6SqjoNC2suACnQ9h2OBHQTgDSoz0wLtnl0t560E5+BmP/NonBzb+szP9bDQc5aW+nqv0g0LIjsgsrXkymLB4X+Kb8wVAXwWo=,iv:xqyXYXR9+zMbUXQo1GcJmAdTjhzcg9DtYuYjMaw3RGU=,tag:PLpr7AuEaObf5gN1NySE+g==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:xbP0IUjKIL0iDbyZpQLQtvD++UWG61SbOHEmQPAocg7gjpHGQiye7x/NODs=,iv:5upQDQug6jhm4prXtWYi3plgFn3KvLuCneRFKfzoRK4=,tag:pf/Rmt/AYAJ36ByGNYMKPA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:fj9XhJj0tuH6WfNR8b0Ptyx++QphNMwY,iv:qUpFoPNd4KHQ2ItI1CqYmWdnxnzM8D7OH2ko4U8ly9E=,tag:QjEcyi8HMsF8rSAmMGk89g==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ZmZQr6Btagvm2H/zFIDChLkfv00THLVIiygG12QRwRWZIawfDm9nR8IyB6BaU6l1Yd7PiY29qLKaemfwbuO+Gg==,iv:OcCe/KiF/nVGI4Gfd0bKNuHbxtDOuP3bkjIGqyVTMfk=,tag:k/M2sI54c1Ciq1LZIWgsfA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTjhGSWRDcGlpbTcwWWNa
        b0xzM1VzWkhTeWhPRFg2SXZDVlZSZTM0Tm40CiswaUw1NUFBQVZGdTZPVzFkcndi
        NG0rY0Q4KzZZMFVadStKS0xjbnROajQKLS0tIHI0UFNkRzdzbDNETXJrcmorT1Bi
        TnRvYXpISWxDYjliRFpNNlpaTHhVb1UK0qirsHyfRxJGVH0ok0KS9KZqTx4ENOKn
        7LB27klcrtBYrY84n62Uppmr0kGkuBggStJUMqSNkb6QzdX2j89CoQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-03T13:43:21Z"
  mac: ENC[AES256_GCM,data:EDEAZ3cTt1+P6W/hzaSXZ0GyxM29gfdclMusRxVEP+7QsO8XQi+iWCxNC05dlMmPeczNJJ67RGgH5x/zevLcUjLnwWyFUyW6Lzld/KlIk6bmmFsaWsObU45c/+n/YqCpuooP0Rml+awAqHV+yOHpKF+YmcivcdtboiQq9foqS+s=,iv:32vVXcapnzWDnQ3oRG3GBeKqV4/6twY/tjbhP5YyYVM=,tag:+TImr/V3i7LdPx9Os1lEFQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
