apiVersion: v1
kind: Secret
metadata:
  name: grimmory-data-r2-restic-secret
  namespace: entertainment
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:P3m4KMiXKh1rY3UdfgNRW4zfypibg5WCYZhca4NepzyRMBpMbSjTGXRF4Ps7vJudBosXS9zsKkglJ/nL5D0ZnFn/BY5KTRFMQOOiJR3LP49K/heZdAN3VzHFSxoGL6L9Gek2R8k=,iv:kLtiDWIDiz0sawwt07VheXIX58ssaVAVz+lMfU8lHxA=,tag:dLBQ8YRmIFNj8bz5ArAY+g==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:ABMTFXDZXHwTEqOTbXjtSTFKPHZjopWK2kVaKM0c+F+NlcHKd6aHRrgWuPc=,iv:7RCPsjHuWKfzH27r8+UkTn5CXjFc57n2leODgaY4zkc=,tag:nLBqjeM8Dv90Td/d2GAeyg==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:cVkv4hSxU/aHauCJUNJxh02JE7gb+tx86alTkcEx1Y4=,iv:apr3zIV9apKZ+O4XSPXqaWP7KE3YYh/qcjK9xrzrvFo=,tag:CIe5yX2g/Ro+tMa+MCawpA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ppGXzI6FluMziWa+R+b6gwFHuuqbh4nOte2ePMXIgmA9ALftTbu3BQn1huu1gEmSj8SlyeH/LsyNwCUFASnwgg==,iv:FiDuDXLteOqcFvdZ8RoD7u++tNroaHmxCJcP6pAtvVg=,tag:cZPyHzojynt5XaLWT9maBw==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:1BfDkg==,iv:h/AX8JnKda77IY7FauXIVPKmYeyH2g9zrZ+JyMbjQN8=,tag:nU7frcZXm3Aq8G8y9P3aFw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjN1hqdTdWODRHVUNBL285
        ZmZYcHNqR0tXRkhDVU1QMmV0Vk9JT214V1RrCllhRll0OXcyellQL0dHekd0cUVE
        b09mOUhWV1pNRVFyU2N3eHR3VlU0REkKLS0tIFY5TFE1ZktNYVFtNDl2QlFVY0ZF
        ZTJjekdUWUlud05URVRkazhKSERieHcKkR1LeqcBpNcEjFxtfXBm0OMeSY9GAJ8k
        uUROc9WBwRaWQZj9vQI+kntoFxVNLLdYUJl/Hx7WaiNOUVFTkpGW2Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-24T17:07:21Z"
  mac: ENC[AES256_GCM,data:8YrKDUN23NCUYNKhazL9JgL1YF+DH+ryVbsdnpgdQM4gn6HqrBaAQMo4bfQ9Dpgk0NGxoVETwI+wxW5eioddu5ptLRppAC1PYIa1JDbbGVY4Hq/HyBCiMN88aX2PkikjN+fdu/TQBQkDnMMfNH86iom+DjjXSRPC9mj7YvFAr70=,iv:Arfx7mRYiXDr51WYR7/kUtxUaYnDwiNVm4RNff7w3nk=,tag:W9Sn/dDzlEQOh/rcOQcQQA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
