apiVersion: v1
kind: Secret
metadata:
  name: grimmory-data-restic-secret
  namespace: entertainment
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:Ok9XDbmmaY+ji4znALvcq+l3CiEoJtGAAsoWeiop9EdxHTjUmYKA36iMeENvAA2Jrj9K2RmuKCTGEpgzJ83bm88A9efnYJCXwgzrPTv0eNqHAAsi4zw=,iv:TZ/02F/vN8cxFq2DFvKmKJOyK2Iif7+N2Cf34SnTFV4=,tag:jI3Pi+MJMTAZ7qJgi6H5Dw==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:tdpkWWYR4cOGf8Y92KSc0LKXZgFuYEpRS9zeb87IGnFRGAd0hh+caxf8S0M=,iv:acMSS88j1rlhzBd5+Mk8T5kMPZigbdkqZirUT6on2aE=,tag:9EY5O3j/17U8/wj6AaZAuA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:4F22Ceb6lcunh++iDXIIv82cl/7mI2FP,iv:Ypsiy9ctW1KfN+Tttdhx7sG+QIO6CjCAWknW5aKz3Ic=,tag:FP3GZ+7lazpw4g5w2B4qUw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:rQ7+O6k02aiXcyA9fAyCHqfEXr059hdIEQhDc+J6g42jVxunwGzgsYbK12WE7H2AemBN462MGq/wK1pJ8+auiA==,iv:ZzaLlQ8h6LMAWLvJroXSGL39nGO8Xu8BeGnVlQCVw0E=,tag:4SH8uVE1VMjnwey4IaQUCA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQ0ZJclByaHI3aENVeTFj
        ajg4cUZVN2svYU84ekJFSTFvUzJsTDNVUGc0CnMwTnhCcG1HaFRneWdWdHpyL003
        S2xnbmJUSk1uc0lYeGt4VjMxUCsxbzQKLS0tIHVSelNsSkRBSmtiWXNoSkg2ME5z
        NU5NOVJiQXpWd3NQNWV2NTVncDIxQWcKbdi40z4uz/+2qHNTRquDX07IVkyqaruR
        9QnM4q9+j4/M2Fbwrhla87LnUyzQCXawOpIl0jEJnpTk345YRheqpQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-06T07:10:03Z"
  mac: ENC[AES256_GCM,data:SQN+1/sMuRGB4IXKLjzohqLipgjjmjCUt5/azzHJ3urcmHy4QCijddBTqOhBe1c8qVpu6XYqhChXgvGrGv1os1XWUObWlfrTeqOan/f+4SIuRbu5Ce+RWE5l+ni0qMUIhto2qzLrIijK+q3J683KhEl5NED5NkPEyipc1p2t4vc=,iv:9uireCdNo31aEUItx+MyBwWa0ouigIWe2XCfmcgxviE=,tag:AZarREO/aLePYonVGSuD+w==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
