apiVersion: v1
kind: Secret
metadata:
  name: grimmory-data-r2-restic-secret
  namespace: entertainment
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:SzMfILffvn2F5N/F7AlI6IMeR4535+9S9OPqpranUfsge2rFYVR1HTEzA/bk0eMrjfUV7uRjedF34Jilyy8mnwyWtYGwnSASaHZhghiNex17qXvqTFj+WSn8Q65zQOC6j1V002k=,iv:zEJdOY5A5Kan7MUTZOoMjywepNS8g16dKG2cSjIzw30=,tag:h+//hhSCbDUsrNX1nI81JA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:6N0HJuL/P7qRnFf7PeTrVGXKgTFI8BL3dJ1CskYWyPSZkRqLGa+YPuOcRAY=,iv:tbTlwlBSni2cAFmxSaIzrK28TGg6GMJSxO4zoOYQjWQ=,tag:if6SODN1lZ1x5OZBMG9FIg==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:xbam3FFlgo+LBnbF6SBL9ZCtXCbLPNInJY/LVBaiiYs=,iv:UOJLJKn0yjcQN5ORb2Hv74QPg+a9knhae77x8+0sI2M=,tag:bVhT/hzd4AYhVMyk65fy+A==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Vqow3kkw1fs944Ho9Wk+FIGmWfYnGRSTOhhYtr7JysO7SqFk03FdZj3oGQR0FDMZpaAmW91J4vboLKgGryBHUA==,iv:vHrP+sQRJHC2VInpNSuCiW9+Ug1rTtjMA+UyaaIb4Fg=,tag:ir4iWy4RrQDu4ROnand2bw==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:svIDXg==,iv:PW1nFCjU2J0mmMd1bNf0YJH5e09Ap/iB+rCuWl1/j2c=,tag:pMGQWV2vae/vK/ye0CqcwA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6bjByM29nRnhnMG1kZENS
        ZGdROEZuN05UM2VnUkNiQ3hHV0dDOFc3REVFCm5TZmNJOWJ2S1llUWcxaVNyUXBF
        OEhvWlhRamR4N240SGJBYm1qdXdpN3MKLS0tIHE5UVBqQ0p5Y0FHZVpobmJONWFF
        Ync3bXRCNGdRSmY3enBoMjNzWUFVY00KVL7H32G3YcftzWYp/VgE1zsOrqdwXpel
        T+pjNgvSXpSQxVi5ItsnvydBEJhmpueI1GdkRkPR9+bP+7Z+WmGvWA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-28T11:31:40Z"
  mac: ENC[AES256_GCM,data:Hhv4ygNx069EursdyVStMsDas5sv+NHEXKg5AdrWC0oFe3RNPvFWfve4/YZ7F6WDV/vNwP1gag2uF4pzvXYl0egP7MzZXmp/JS/A8bYGSiHoke/VPsXIicgvNfcQXRZHQg5AdGd2QVWTc/v7FaDP4r6QrUrAan1RIiNSjQF979w=,iv:SQIIV5jUs3lfu+RCZ/+RpTdiqS0TdAmwhz+yJKeY0Uo=,tag:/9+NVyPtT5MoPQ7tdnWoZg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
