apiVersion: v1
kind: Secret
metadata:
  name: grimmory-data-restic-secret
  namespace: entertainment
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:1ESF4+oLNXdBjkucCsGJYTxof3ux0jt+ubai1qRHoHeJAWlgo3Nt9Rz5r3Fu8vG64c0Nuv3kSzfOFtDrHKdWdPs+YRuMd0Hn3Vho5Ge0YbmVb3C8RTc=,iv:oYydFIsIqKx14pghwsmbSyhgBikNK82DsFYBrRW1ln0=,tag:UJjDGjOMovtxzYy8iF51bA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:/eTyvhodvLRkVo4mrNSJib+SSIc6eRHq7kl9TBVhlpXtVKTYHXzr27DN1pY=,iv:IzKwBwzuezzuyEU/D948yNTul1egmGkSm5hlARlVeAM=,tag:MIjhRSnn7UX5sb1/FobDUg==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:5iYqt4XtMWN+acA+Yzo5g+DMbmtfNuKS,iv:j1XtodHz4hIQsDxSA7Sk1Oma57nzFpdz/sBOOO1Y+/w=,tag:CUTEocMk0tU4WQyhbnKDBg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:VEkHOi5Y2L4vJ0F9hSUhylua3uwcbFDFuwLcVuUiWu8S1TPyKNDCDOzK/s7U4DvR2tWaF8IkHA1lbUX3XgEq6A==,iv:ote26OgEXuZ97iGn2/Q/PW+SOk7qxM5qlcyjvE1CDYE=,tag:WGUNyhQsEPYlPy1oo+3xEQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1blNZZ2Q0ZFg2M2VvRVRR
        Z1BvcEgxOUVhbmhKaGNYbXl0ZmZTbEF2dEJRCmpQRklMTTRMWlJtWTlPZXFueWdx
        U2tHWXdzUVh0TlZYcDUzYWxweHE1ODAKLS0tIHJDbkZrOEphTW8vN3lpdDdnZzFB
        dEY1SVFLRzZLUDJoVzNkR1dBVDBSZWsKCovEFPtDQ6SUm1pHm6gCmBJ4vaQXyJmN
        YJO1Gk39X7z7nwHV0R3qr96LCcWqtipiBSn09Birj+S2una/bZdNJw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-29T12:02:06Z"
  mac: ENC[AES256_GCM,data:3HzYe0t9VTjwOue54ospMBl9VWUg+Kuqdw0azTquDj57IGLqFRgEharTHNI532T9viZhCUULExpqjtzwlAyUE2K1hrKmSJWjOc+/dQ0rGC65MHpqGpnYlnZ9VzQLBqj0rwOzYIIVxaDkGZ6U0G5vm0ZTCnSrTSWaz9Kahf8Lf6Y=,iv:tkFNxerESOs0EhWAo7MCAiHzTSvKw1q5oybpVqe4lTg=,tag:VX5q0E0y+D95Vo9fABcpNg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
