---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: health

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./health-auto-export-mongodb/ks.yaml
  - ./health-auto-export/ks.yaml
  - ./health-auto-export/backup-ks.yaml
