apiVersion: v1
kind: Secret
metadata:
  name: jellyfin-config-restic-secret
  namespace: entertainment
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:b/4c2KcNVZgvJgkf661AIf5ZYdt7QBltIB7Ff3WufcDu45oDsDWwUp93nSFqscV813lElTLiBIOS1BL1MKzMdB/ZAF6QmfCPqp6O2zmEdZ321ScfZARYnQ==,iv:j+pqAaXgWjlaV469toNgbswoky2hvlFiH7Pcb6Tg2iQ=,tag:YcDTkBIg2XC+jqSoqYVpGA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:FKIuV7Z9tbIQkI5PK6wm1N+Krrs4dDngEpQm4Je5orvv6ScwZ59Xs0mAFyI=,iv:m32HVkFFXypHBNXxawXMmongGjdOZz+jvPE7N8t4Kp0=,tag:Bkw4RckJmoq+wWBPk92sRQ==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:kLuvSTtskqW4HxF7YpmT3UdQHFYMXIbt,iv:SIAE8m/KF6Z3hBOkm0RR++jpv/vT53sL7M/Qx4pLUBE=,tag:cICfFrpCpUvvLu6HeEytQQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:oq5EhteS5o5CJuw7QuKI4eBJvbDVOGiJpccH5X8vlYg02imSLUmUndSZ/UQliiqU0shj+UOjApYlDriM9Ra7pg==,iv:E4zSpGquVZJexIbeNvgbu+cAx7ysKK36tBPcCW9GkX0=,tag:INZrAkIZANfqlGCHVbbszA==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZUpVVlBQQk0zRk45QmVo
        NHRZbnRIL0tHK2toS1g1Ym5FZ1d4NnduTnhFCnMwNnJLbGlCV0ZRL3VzRXIyVDVi
        aGszMGpYc1diMkQ2cG1LNGs1Y2tRdEUKLS0tIHVlQm9sdEthQkg5bTVTZWg1ZExs
        L1ZYbUlPR0NUWG5YOW1DYmpKajNxb28KTGBo7oGdjYUC9HjATw+MVHdiGoQTdq/W
        mIikqiA+myDwme8feVOoK9mY7uTbTAgR1A73HvxSPhXiL4NJ+SGL9A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-07T15:51:39Z"
  mac: ENC[AES256_GCM,data:6lmxQTdCr9WnGfXWEaFcV6u9aWtJEN19u5/ck7v+AcuJwtfcUaAxqkIFHz/Qe1M59lnnznTXNOMo+ESRDXErepAKf+C5AAK/o1VY/n6NHpVKrA1WxPabcY2HPyskWw/mwI08KMQ6eZnaWh0Y0RW1CHyNY0gLPuE24vuL5x6TQBc=,iv:Xv+78NGFbYw21MkSJaYlBx3wmw/wDg8UYLSILrY5tm0=,tag:aQAK6FJQ6p1Dm2kFia6u4A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
