apiVersion: v1
kind: Secret
metadata:
  name: jellyfin-config-restic-secret
  namespace: entertainment
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:6JXbIYfA8O9+twclPzYwzcdanbNSsw3yVWYlrRhjMClKKjbEGPwAtqxmtAkOsM/G9gMhKpIR73vuwICjGYC02cwUqj3Wipc2If8c7doqPEIEA+soWYHSDA==,iv:YhQh2CHEji797FPCA1dUQx/M3ZvzEJN/18ZLaeutJDA=,tag:akO9QKT61EG3GmywEuP5IA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:GNZgQ5ShvHsagOCeetxH5v2Bd0310v4nfUgoXY4cfz405GOPqPno+CT1pUA=,iv:S000ObL+UTEZSEvMQpnOz+vUPYAQH/Fdb3lO3vfaL4Y=,tag:TvmBRmbjDG1piSvKa/5JUA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:YRokHvi1Sy0Dg+F7SC7KHl9EmJRvxzY+,iv:aPSP7lZY3o6qKX9rdqYfcNx7MGuSNzoOd7IIhq3ePiQ=,tag:wTk4nPtPMWERgzdipWGpvw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:x037kWIHO8RIeKf5pIs3N7pgtuiaNs84g9UTH0aAvq7vQsyOTPEia0NVq0SfdfWVDNdMXHn1Mz3AloksAKApPQ==,iv:pVNHovMLxnwP1VmQS/+ZgU1WsLIkXvJbZsWPfSfXrlI=,tag:alq+qUPdcj1C77E08WADnw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdDZYVzZvdTJqNzdoZGZ4
        Vkc4LzRsTURKZzVmUFVqZ2tUT2lhS0VKYUZBCjJPR09jUHEreUR2TWtENE9aUWg5
        QWRJUGM5SHhwL2VNTDdodUtsM3pvdUEKLS0tIEt3SVZQNlFONXQ5U3BURTl6bE5r
        UUJGQUd3UDJtVWRVNWNxZXA0ZmVodFUKR1wtIHoXG8DV5sPuioU9taaNsubq+5kq
        +S04lG1HCDDMrGxHeEgV2mHtyY30zIUo/QxM+4c/rwjZ0+yIJI5fhQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-11T14:02:52Z"
  mac: ENC[AES256_GCM,data:dKRaaHW5RS7FUxXVLRGqTheb8X1LmsYDgAEiOu6IdIgp66ZNhDq12Y6n24fEMl2BweIIp8rAeBeIhR1RK6SgqKOpYvpO079aFMjmGxIeq3383OShCELWNIYfyQtSYBK/38CwnX9hjYRzp58LDYA5pj02v0rCxDrfNRH6t/GCPe4=,iv:6deaorOW8sWqcwZOnxpBURt2Ml6RFOxPcPZ4gGQl+NQ=,tag:jcgU1AB2pTDIw61onJbKtA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
