apiVersion: v1
kind: Secret
metadata:
  name: jellyfin-config-restic-secret
  namespace: entertainment
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:qd/hK89EVTLpCgJ+hWFVEUfpflcPqj0lTRCgJC3pKw0enZQwc15hEjFI7AsQLS5I2fERLFoUqtPg8da+RKIOD3Mmdlg/DKebrud3tPK+MTS83U2oOwoiSQ==,iv:fNhzw4flr0XoggV/5I5JR5I2CeqtB8XyLrCHzMEmM80=,tag:ul8MbuJQttRTkTS5QXKccg==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:VT+2NavWiBfKL2tJs6Kjaq8m8YEF/jM+vFER/1IDuNdlTLYqAx4nPABDuV0=,iv:MSDdbJaWTqPFMVaHwwYmRfEeOkBZtX+q+Bj3TKOQ4CM=,tag:svKYs+dRBqP4in3T4vedaw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:CJ0fKkFE0HToxzl+CbO2Cn5qwqAJ6tVT,iv:XG0O4HWyTkwSa+/6WAIeDnYyeKJZDzxZudB2maCXBco=,tag:8dC2mSa+Otlc5vuS428Pow==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:fouhMarthyvDeBt9CtCPPzbQeAEENd3ePhxvryccx2n5niyg5VEBvRTsI23mq+z/tWjJpMvpFgeZkXHV7c7DYg==,iv:OY4W9xs0ZEBna787LvtxlsM+lJx4w7sFycSWYvScc9A=,tag:Dab85hg7CkaDUPi6GavCDA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhakt5aUN1cmxOQklsQzFQ
        RjhpWTR0RHNwOVNhVTZ3RjhTUkd5d1dUeEN3Cmp5UWVzUHY4UVZGZ2pNRWlVNmxD
        VS8rdUtWK3VNM2gzaWxwRnl6SFRLT0kKLS0tIEx6UUprWldhd21senRlMFluZVBr
        by9IMGR4bDdKQlZueGdOYzdOTkdzRUEKWUiecR0zSxXXPTkPHUD2ONHcHPygSQfP
        t8a2GEQ7x5RdQ/QYD/3MOecYV/rv5oBg7ML5RDytIOV8GIrzvdnQrQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-27T10:36:51Z"
  mac: ENC[AES256_GCM,data:nrwvssAbinIY27MwvKx6iujjHY6kXBkiK57QJhDcvpCl6gVyBZIwcNt7be1ODP99iWba4PM3I93hCN8/AJmPpRr5JBOuUV2g5+FZK/BOv+KLmZRY4I6bZI9f4sxP/Z/KkGG9n7DV9n9n3f0Gyrb8cGIlr4jARqPNd9Dv6v01nwE=,iv:KBGC/j4bXhFebCHdr0w1fXN3tMismarZO2TXqs1d/fQ=,tag:W/bdw7tuiew9KZ6+QaXLjQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
