apiVersion: v1
kind: Secret
metadata:
  name: jellyfin-config-r2-restic-secret
  namespace: entertainment
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:Lj2PBC/iM5NuqkDV2klJBBTghWaEtbp0aPB/96lvBy7TTg5MI0p128EG1UdBLkiwD3qOROoisfGEiOKWM1S3o8eVzOUY5RY/o37K47E5bUI/8iI0Xrs3LWgDvxa4PyyhPxhpI0xAaA==,iv:il7UnuyI9H6V7fYaGYuZMunV2qKKcHcIrCPW/NkFkOU=,tag:D3aIRbSEZy5Zq2R7aBM96Q==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:0blyY5/GoSEBzuXqfWFl+R3TroyPF2B8NAO/5fTPr6SEP1HvCqBKGjFEC5k=,iv:nHIV5BuAvQSJz5PpZtxzvbcZJc/Ds9AOC09KAydVr08=,tag:FRMNNI6etF0jr0LXbNE8zw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:VEjfaMnpSXy+IzsKVk2lFbAI9Lh5EXqSaPRpjnv6w70=,iv:K5Z+3CXq+kTpJnX4mQYgiicFA8/xpYQdh0hPyXuuAq0=,tag:ZCw7LIrZ1ROVL7m0VclZQA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:IsbLvljl59+JyPYiNY7HMxKpBDSoIHHbGqa6/RZtHg9A/3btLo+XHT2H/BfLAYhvT0/1sX8CWcG1ygYXj1ldcQ==,iv:4H0eY2ACk1R1Iz3zeC25rP3YA1IDGs0czSPL6iFoKrY=,tag:D5OlFjrCkNSazGeeqrPO3g==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:rfKfVw==,iv:LTE2RgzdKOZfvdxjm27I15UBEKkwrHBvm02/kGsxLuM=,tag:6B187DGHTXOQv0ABRjZQrQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNUVFa0NvNXEveVlWUUlX
        QjRKZ0FuRm52SlMzQWpsall1bC84elRVbDNvCkRoL2Z1cTdGM1R2cStUK1FhT2Rp
        ZFQrWmd3ZktuVUdld2daWTRMd09Ock0KLS0tIFVOSUdzVkNUZkVYeHZzVmpON2FM
        NStRenV1UE1iZXc4VXlNZXFxR08wUDQKWYKkuW02xvcFcXGWPQpp0/nk/8cQGzds
        tl7RfilxRqAedlRVWKeCU03CrHqlkuDVUN5aeUsELj1I3a111sc3qw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-04T10:21:23Z"
  mac: ENC[AES256_GCM,data:4JDuCdNDuivNtnGpERgMZT7GbQYAEG1yc8xe3j+oPzB9dowGJol2SUzdyDeOd/4PyhtrX3/0X+08pPeIFCFFCVhO/0hSPSD1TlmiyrJiHxvHqu1H26xv+LGRE3g3npQx//EuFTVQW9V4oKAx2BKViE/Z2bnPTaYfQgCHJK+nHas=,iv:bYscDBqpYwxdyEwiSy/TRDsrkezQVrOfzBTsKWAg7Co=,tag:mO0gD9nXS/dgo4O2cJwx6A==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
