apiVersion: v1
kind: Secret
metadata:
  name: jellyfin-config-r2-restic-secret
  namespace: entertainment
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:ZVOv35fN9aoZTD1LU6GkpvHsV4vYYow72h9pY4l7BkZ6rY9QlmV+RRcev5UNid2tpnfBzbRcKHm4tH1F8/lJslZuS6BvJYyfW8Aw5NTgmf1w114PpBsA0HxW0KlMtyUdqdvyy1DpZw==,iv:chc+w8Z9Lw+4H8lcDPx2RdPCL4ttrNZuYbWxCOC5R3o=,tag:2v8R0T/RdqIodeJjCdE2Hw==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:ydDYH+s4Uxkz2QSD+pvPXpygr6KvzrEOHdaQsNQNmEHZ7mK44L+ihtTWC6w=,iv:ZzGq8CunYXqOGjuVgRn5r/pvVayRz0qmuZx4hPzEc6Q=,tag:lPddOiY0gAchwk3MhB2wPA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:/KEP2PcJwwO2yJaDDUB+K/K1eP5sQ4FjxMO31RmDz5A=,iv:KUt9MrBugGC8cpMfQP3pfAhxuwTjoQsbIiOIcdxMCcg=,tag:+xwXC9ERRiMRBZs1hrJcKA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:e8WgUed2zHnF7JfYvYn1LdRD+gV0IDVnmZRJJqi8JvPiKn0VYfRYOZ5BQcKGpkhDj2NFJv/bzU+3XhyrK+lo7w==,iv:YKrB2SRca/fCgGdEdt0KWyNYXeyKOTKkFzS+mqvYFkw=,tag:4cRu+GUpRBq8WOzTf/QOig==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:m4MT4Q==,iv:J5yJ84V9SXUIYm8TqhXkBDFrBa5Zu7HKx7M0nBDw3Ps=,tag:NZvfHqSh3hFXPJC7EjHmNQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobWhkamdkLzh0T2hJWnNK
        T3JYSG9rUXNxZm5pc2NYL0RnN0ZGOVlpMHhRClJtYUYvcHRuMFhRN1o4VGd5RkxT
        d0lkeUlrR2M5L0YrbHhRYmxNcWJSUlkKLS0tIDB0dmVraFR0TEF0MUE5S1dGM0hY
        SW9JSTFIbkFxR2tjOXJ3Q1NPdlFNUkEKhR+N4zLKV2bvB7ruk5YMpbs9ZkVj7AVj
        F8Ud+ox+SjIml7vlx+2/0e8kaVOLImRvB+Z4HDFdivxFFPYPQgDokg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-25T09:27:31Z"
  mac: ENC[AES256_GCM,data:1BbFmDPSEGuuIYQ55fAOCxDkbqMNSAZmc+bg1a72GHGbHC8Jdqeb531zftTcOSEXQkIv2UKTr1od45ONrnfAAdi7fYgH5FBF5eaQhs7KHy/xK3tvCeZcS8FbNyDYxOSP8UxzaMQ9sCBWBkUBzi5nCfN25DP0q1dvpyrVQ5EKUHs=,iv:Pu8EZtdgRTACq6UsgJ+OCrL2pJGC08N7cYX8mYmRH+A=,tag:8kFjbyYMI66gEww8U0J00A==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
