apiVersion: v1
kind: Secret
metadata:
  name: jellyfin-config-r2-restic-secret
  namespace: entertainment
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:s08vdaA/HT/5w2iDnEKAttN1cz0YgBUjq+AvencWB4DsR8+HeDgVjZ5QZiK0SX8XycfzNCBOu3QKyA4ukOcJYzMPYRU3vfq3fqioHtc3W2/B6Nmn53AMMLa/dS6wkZ/D5353Bos/QA==,iv:g65od/qgoBK1O+J2WHJAoeuZRM94Mtj/+rAMP5wNOMY=,tag:udaRawKZCKH6incD6vUV0g==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:/LhFQCx78Ti1GA1Y38OMoHbQdqG+owv992SVhQRwMwbxmMF8arE906vfNMo=,iv:ADCBlMnn1iyVLeT3Lkn/02l4zUjGrlLDc2vFyX+Wfgc=,tag:C08CS0KguA8/tz+S+czgBw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:grGr6HL989VjgXCe9FByKWH9h5t1JgmWv908EDEYBfM=,iv:g4RdpkuQduqauNbLTihYDO9d471lBXd4ie6rvnxsq24=,tag:t1i3f5ueGNKSHo9xfUpUEA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:90Qi7PP8ou54Ftq/SrD7AkmsXCJl+s7HKD87B7nXExzJ2SEOnNlABZALCLEpG4E+Vgpgk2w9v6aKdTy3FEbn9g==,iv:PcUWa+9SL+G7mlFUThR+byVOx0GoAIM5Xh55aUtLqWE=,tag:/Qd+Wp5Za+CwYNhMee4Utg==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:+VZgXw==,iv:/cypJxHHh8XG7LkccpF7v7bN04heqQM6xW79JCcQf1k=,tag:m+TUlvfWXd68AMIUmSo/DQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RjB4S3lQakpwMHhwaHVM
        NVdvY1Z1SGNUNEIxUWNNaThoYTZVR25oVldjCkI0bUFBYzZBRGFLRXNobXk0TWUz
        NDhjQ2dPZ1VOQUxES09LNFcwek8rR00KLS0tIDE2SE03NHdtbFpNYVdaZGErTUs3
        TGxVaDZUNEtZdHdPMjgvZHphZ2J1a1UKmc7/YH8QIhaDkRMvCtMRYU6KdveOayBo
        WPcriCjC/SU9vfVmj0c85pC6fk3lv6sWjG+PjARnvxmALCK6nKsJlw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-24T16:45:41Z"
  mac: ENC[AES256_GCM,data:67AEbwn1GfcovlShHZ18u41cVWNthTuPpJ0x1UO5IegdS5TTPUzH56GKcc7mnui5bmUxjG/WNMrjeoPC8lp+N+dE6Qk3MnfEmNvwFd0IquXm1Q8jPd6JDUat/zXq4mxIgeTX/74pa7eonXREZaPEJSXU5rcdPiEfbVT82j0ING8=,iv:xhDWGHTvgSerlJXrnec655ld7Setkouw9mGY2Big+Dg=,tag:kov1mUmN7JuAt50ps8KV1w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
