apiVersion: v1
kind: Secret
metadata:
  name: sabnzbd-config-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:OIRzqsgQxxYHGEas8XuX1lzgRdui2plDvubuUI4NULHKg/9c/hMxx3UAJi+BxEhBZ+5tDjzjyMf+jIpqpL0QINXX3DyYpj+0a3vEsYGvxoHqtXd1ZrPH,iv:D6EN6jxNU86+jCTrOmtfHUH8wxj0xLRqjwmJOhYF7zE=,tag:CPXUopXkExowrWhyMkdGJA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:47PHrbx3Uj9spuYuWMqOVk5n/YlRBrbBStvWMax0UDXWhBvikKg8mSX9wFo=,iv:OKRn2W9bhnzJSQRRTMHdc8LEEeP9yo7qWbyMfTgoC/I=,tag:r9AaJX13auet4TgmstC2ug==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:BQqirXK/E6B0N+ZByikBGcwN7t3VGufT,iv:HFedm7IR1fN4r/qpvYzmuuu3cCd/gPnNR6T7dpbwAm4=,tag:cb6TkvRPJCoaAs1cVPF23Q==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:uCPzsemENXThD0l7bcW4cI5QoF8d12+rtJ8NOIHX2f4FHcJEFpvQU2tei4BlVUDtTLWAP2UcV2G/+cUxSHgAUw==,iv:/XSeDIkdcB2ziQw9bo+Beu5fqJVeEetYZnudF2r1Ixg=,tag:9glicIsPimjl2Tr2pRwS/g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1eE52eUk5ZU5qaGthak9q
        R25jR2JGS1BLQnBNOU1saDNoYUZPYkhQZUdZCnlmT214dTRCWWViazBnVzFjMTRT
        YXhVTEFrVENsdm1TWkFQbFBuMUhtbW8KLS0tIFZxVFN4YUdLWTdaZWE2Z2czakdj
        QUo3aTErUWhxMitwK0FYU2tudk5jNTQKyaH9XZMGELmZ/C4C8hNmV6Uo27LE4hZ1
        H5TlzksYYf5e2zLCqM3+HSRTU0FrshDYtO0tLRjTHWF4LVhZWYe4mg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-14T10:21:03Z"
  mac: ENC[AES256_GCM,data:c8XfzRqiNwfBiJZZbB5MzgZ1yGPXYgjHSpiBG6p28ea6WXS5IbG/udnGvqXOAyDuw84/7I8D/dQAAm6YORPBXKV1PHkKqzE7CIn6nWWrEHUfiF1IM+t8ddEqI9h3jwxgnOsWxgV+SlhTIyO1pG2qxBlG/CLsyFk2uaAPBhQxx1k=,iv:RRcLTguosYaEbBTQzRyMdrsFKcnehi8QL7LPAgiuxv0=,tag:dmrG3fTSggtuNQNaGB4gkA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
