apiVersion: v1
kind: Secret
metadata:
  name: sabnzbd-config-r2-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:JotbFQohHecI7+e2v7dd3IIRf/XTSjyUja2Tm3tveCvJ3p4zWywdOfJuBioprUQdEqDbp61Xw03HLmzddCGBZZu9H8RmgbrQjJdMlvIlxdrvAaPXvMslx10Wg5mfjib/Q8SOZgy0,iv:s3hz/ip7pa6OvTCZfOJTPPt2+cyMlhD8/Zl53bTlilg=,tag:V+Wy7vnlzbmEiwM/lAdy2Q==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:NPuiJlGH0Th6VV1QtY6k/jXQlkzlr4gv7ZcJwQ7v7JZjbZRQcoaWXYnAP/o=,iv:bMGQb5lG5+Q9z0/l3o7N+Ekk4MqIob+GYnZWmtVdw4o=,tag:kq5OC8QnySYqqIgkui00dw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:2a4jpqHWS87yswk/fqLFfYLkU6iO0qsS4pOFqU946jU=,iv:er4v0XEC2O1cSDuu+iNeg2e32IejfCEEhVQioTxUmC8=,tag:uol0+mLajtIpC/22IU8liw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:O6WZuXBY7EXrYxOHRDMu6avwSVEp0ZzGlJSCt7pnZzBld5TJ6bCSBnbmowTyV32mo7X3Z2ZTFv1CrAEbNwfFXQ==,iv:IcdllMP/A6Pg70KrpEdMcHgD3ONIZ7V7TsNWrJLi8Sc=,tag:p+rvshdHp7M3RT8dksGBpA==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:I5ObKQ==,iv:FFh45mZF2pA0DOXnrh77sFeXyKkR9ZTc+elUmIyVBLc=,tag:A7c2tGyuQxL/7fvQwLrqzA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZE93TkZrMTF6NGJUSmNm
        N3EzL2lWdHRRUDcyU0RsdDZGdUNiVlh6Z21jClNUc3QyUjZ0d3F3YWtPd1NWWU9L
        d0YzdzRrSVg5TGV4RnVHaHNFaXBxdGcKLS0tIDlXbW81YVZGZ0d4VmVFY0ZkTTdv
        L1puYjVocHVpTy9ITlJCbTlzZ211NW8KlTd0vc6+fph7NLrYlpoD5nih2MzC6thd
        sIc5BzdK3CgmtfZ6Sv9d5Oy/nFrIfk+et3R9a1HkAC0Bq3H6DqzYow==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-18T09:43:18Z"
  mac: ENC[AES256_GCM,data:XGH1gFOOYedb5a6F1ugSoNSFColEtcXLkNYVZ7F22d5Ik+UcW1rPuSSV3Db9sKld+0KUZCMoaIk9BU9MQ8s+l4gyz2uC0YVtawowKHxuoy+YbJe9+IAFPd81kHViYEWw32XOFG7JOplyhE1ldinZ1IbgQrxkMOVKZnxigaLD9d8=,iv:m9cqHmAh7s6Cp+BWHKnhgXfJTsesovN65Mq7hqYcTgM=,tag:i+ABCSQ4RIatLFMQB6VlQg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
