apiVersion: v1
kind: Secret
metadata:
  name: sabnzbd-config-r2-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:ecoRuyGVziE+GRYzbdP5arez/Iz9KJUAwtyxdTJajBdeRHy5sgPmY15mOcdp1qrq2PYsvd44b3csXwNNBkgouf44CN05RNvYDN4e8BH5yMwN+r/FVLUzk2rF1tpRydMzZUlsK5Ep,iv:2sDkUb14rv42eipGe2H8O2D+87kfFLloNnuqheDhPEk=,tag:UYG+kosDeAYwMvNLmD1t9A==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:28V8IUkrFu3X7rNPTUCEikZ7n8ThhRnRqWYghfugLG6BlN8Q9ky+WGOlBls=,iv:Madzgpia8e3WOJMEjQc2wA+/CpWYk6dS9LRXzRZ5nK4=,tag:3MLg7aOBUqoT/o7yIorkSA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:+ooT/7nRq5IjTzKgDfj7hJYUf1OBU/htRM6WcJMaq/4=,iv:Qhmqzz47WNnGFiRdXvsVpgAHEFgHI5GH086gruZoKC4=,tag:Rs2NhNmox0vLsVOT3dxSOw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:JMyN/PTeHVdXk/RjZNgB05zWAY4P3MN/LHMREh3uMe4Z66FSSiU2Gn7jJ/qwESLj/N43uQr2uICzmd2rdEiR+A==,iv:6noNg/BSEPJ/jpqkKXPUN0PkXbASnf9dtWPZ+bPPFyM=,tag:T43Kw/eOhu2+kc9GlCsQ5A==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:KZBw2Q==,iv:FRsFz0iuQDRZe5Q7Km6krvwDmLIrUF5MoDqDD675M2c=,tag:FZSQcOSAb/2ZNogLy/DDYA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNY1dGWmMwU1gwU0xxOEpO
        Y1Y1TUVEL2dPTzVpTFdUazZ4VU4rU0dVL0ZNCjM5czI5TmJiL2gwcFN3YXJwcEti
        WUx0akQwT0E5SFNwQWxIbHI0UHdGbk0KLS0tIDBhTFZkNm0zTzhOV1cyM0dRL1Mv
        dUJ3bUxGcEtWaHNpc01nQjdJKzlFUGcKLuVFVAj7XBl3RFYE78/pxcM9ZOOWSPac
        dgclReLYS2eCB39bDTwHrP/mD7G0Ty29Sw3asQ571v+mLMpSe0eh1Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-18T09:15:12Z"
  mac: ENC[AES256_GCM,data:ymy848U3wgfIH6sDbovmmuDORIV5MwkRn7HUqfke68HaMjTInhzTrD8PqZg2DGMkNXBFiI6VTKPGsgVAtzVzIKL0Ic2CJD9vdBim4EodAp5mXi+rz1KtMe0c4Sd/UdbEvsULLpZOqogKif6PNQZlOaQVQt3nUV/kduS0OKU9LvE=,iv:EuiMHDGBtTpOZuGF3IrfpwquVSHjvgpcZLBNSNicMo0=,tag:wNjLIeYdI2Ru/K5cnn+PnA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
