apiVersion: v1
kind: Secret
metadata:
  name: sabnzbd-config-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:c8Olz4EvFwf8Feohqo1Ncwg7B8VBiDxlhLRR0hJGQda5zz1SYfKyuXDzX07N0KYdetMiDZIRSb/Z9f7KNfscdcQrbyi9gtSubLRf6GN4+j3SPx3x2NmN,iv:lnFxQoymYuGtlEBJNTVq1Xqxz6i19otbOND4lWf0XII=,tag:b266yYSSpL8PkxC9MINkvQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:AX8bb+nvWwE6FVe+xs5bXf1T2IfNbDkLGoQJSz0pW33fHIpW1asFNerP7Qo=,iv:z5vUePXcvrmLCxgT2nRyvNKyB9KlEiox2JoxE2H1Y0s=,tag:K5j9GzeF9+jCeoEggNkBeA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:HcOqju17L5N++DoUaGUk/hSUbrIKUKHf,iv:oRM1g9xgqTEHg+EiRflfR85aHvBv4aRuJSKuKO3UGrY=,tag:Fj4JaX/Rco2zhQ/+Ll20vQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:l3Gt+Id4UVQXPoE4JCU724UnpuHQaor9LB3gzidCsZBHWkO2pAhJhDXrwR9SiE/2kMLXJ7e3jizm+SEF4OJaig==,iv:Ywii/JXFH0m1QK82GpvSVLNyT0QBlaCRhGnEKwFQ8K4=,tag:B1w27zbKTU0WcRPmx02NsA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZjZieTZXMjhCbTkrNk1X
        VzhBOE5PUGZwZEx4TjRsRy9zNXdPdENoMWxRCjhZY0pNM3c0elVYN2VlQjBncktw
        NnJ5SmdBNWhtaHZKbC91UWlENnZWNmMKLS0tIFU0ZHY4OE1hVkJpUnhLWTBHaU80
        eC82dVpIUUFZK2RQUzZXcUVmUVN3UFkKPZ8+/KYrNrV11bZUcWiNbQHnU1+wduHi
        QLAPNFd8pxoG3NuR/r/fYddDhP6D/6lziUd4AakNBYcQOhHJR4pSnA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-20T09:43:22Z"
  mac: ENC[AES256_GCM,data:si8DtlQN9WWuM510sPu61lS4iDqXudXPmhh3+cQBv8F9faCXwYLPFEBXXISI696gT02SYC1ynr5ZYL85HBGNFZmfw3cSxyWdgcgOtEmpQMo9cac9UMPrevV71Ykt3MDX42IZSy3ZcoxU9HcqY/wYL8g5Iz0BT4ltKBTge/mfgoM=,iv:FgGxYkovhHw7ptW1rV7l8lrYCPzx7EB004cM2nYthhg=,tag:lBHYOfdmn5/qFWhnDjCB3g==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
