apiVersion: v1
kind: Secret
metadata:
  name: sabnzbd-config-r2-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:1SC0a6amH42HJQ0uuqwxNeFt0h8BHNwXXoERI7LCBQeLE5F7/qTtV6OP303wiZP8/qskBXufey72FHe5hXgsPuNaI57DzWExrlWNMpadlKGXZjVUmkCB0J/e9vRkc2KPQDwP0Qrr,iv:oktyy5j3Wz3cLdzO+mNq5DWLCFRm5TQQ5iWxLRFUptY=,tag:nKqysfXn5BGtGDd4iYMrZQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:ZfLe2Y8Lle87qnjmLkzrYfWrPYiqPCycvLlO1pxxnw8BFm+1fZ+FyPlO8QE=,iv:Fs0ERgaqTOxhjciWGZ4jjRSnv2kJzJ+9fFPOrRXFCqA=,tag:3JSWE1kAtwqVJXdy8LH4ig==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:SvaEt+rmbg5onrqDT2f4IlQnSMaPjfylIIDBhRKZ9I8=,iv:Ij/GT7L0BI3rG8pU65Vx9VOLOjuC+/aS3r+0yVVW0yQ=,tag:Sbc1QOjsGJKovD8CC3pxPw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:5UErsCrstiTATSB81mhHkrFrimVHQkpU3rV2H6S64a3nrxk69pd4WalZCwaiu3JltxLa1itTgNTHKbjHPEurog==,iv:YB5i9dCgfSOUKiNHXx4BswVNEBPn4NeLLGg7/T3UN/c=,tag:N5CXR7A/SxbXbQbVIbO0fQ==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:BE0kew==,iv:Is34eK6laiy0YKLlif25zgxqYpS87Gab/P+uYTzbyks=,tag:i6rlU4iVGfMrDiz194NUQA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTTIwSkN6bnBGbVVNWmYv
        Qy9kOGJDWFdMcjVBenBsU1RhR3lrbllHL1N3CkZyb3NCWFhRWU82aENEcHczNTNn
        WFIvTm1qWnlWMWQ4MWkxMmZ1UTI1QzgKLS0tIHpJcmM0MWRvMzNRcjc4WlVRQUFD
        MUV4d0NxWlN3ejczZjRqUFBjYWt0OWcK2/cAMKx2vFsSHqF1XJr24jIfg1BXO70u
        Rl0qxppWw901PSheP1Kit7Lhfr+HREQ1YmUvoia+mirODZZSNN3ADw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-04T10:21:25Z"
  mac: ENC[AES256_GCM,data:ndU9rR6L/vI8Sbp5+H83HLqPrZFbXLGJqdoFDHm6bMjJ4eQ1E1YdDbJ/uDHzpddOnqaTyFLNJLVtxrdhooCL9UVXeYKL9zWPCp3Hfm1E28KGXQ2IdJpWFo5tO3UiL6fJrz+gklFIqFifvOmPrEzV2zTxYPQ8R2lAQUjUno69Ml4=,iv:EbTBZsWXMVKKckQsG3S0Wo2rSNmbu6NN77ZrQ1h/qME=,tag:+k/Y/VBd8SvGJOMSPMaw5w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
