apiVersion: v1
kind: Secret
metadata:
  name: sabnzbd-config-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:qCjU5HjglbqQLzDjuKFPKhbaMD/u2+8U0Rw1NaE+ufYxTUKyOgKw/l/fpY7Y6cU+t/mi/eBU8yh+tDvnvChYCRM5yJpu1lC6irliuQLg9/w2Uj8cuaTP,iv:QNTrpSUiAicnFnAgDTwofw0bLoGbYp0WU3pHRUIMGU4=,tag:EmPqGBVZ+BwqOsl8K+iVmA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:YWzZL61mquacRACPT5DbbvLycTIs7UlrV5dx4c1jBkGKhVUtyqGnUKMRHuc=,iv:1FS8UNwZWXA9O/SsBzGlsCekpHvH+gq9ovPEM9TJLT4=,tag:Jj0RTU0e20nHSxQxQnjLXw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:3PYyLxgZQf7Hh8x0o+X+vMlr43w+dRdX,iv:qLINEbMMGMva3Tyg5+I4OxEaQHtKZsTRhvHVFbICHfs=,tag:DY5DHEZM+rz3yCBTP98rAA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:GpwBRy21JFljGG1ETqtSVJ8BjPwMnXpVoTG7pLiyJBnuN9Dg0j+q5rMyDcH7th2jXT8a84DiTU9dqkh9YjRY5Q==,iv:Dvus6OudXI39A33/7s1As+Chz8JTKnOsK0GDz9XxQcs=,tag:E9OHoc9kH+noEzVlI22iug==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1T09SWWFqdTVKa1QyWGdP
        cEFHS3BsRGpPcjVQdEZySnUvVEFqR2FPdGxFCkZKbUpKZllwb2xJYmsxNkJRMm04
        NUl0dE9JQXR1VTVGdUVLNjVUaFFMbjAKLS0tIDJ1eHVkTzJxb2NTbjIrTTc0SmFt
        Q1VraVBBMTdxMm5GeUh6bWk0SFpFQWcKiRdV8GJfFPjF4Ic0bSO2RQ/1vzQ63Xtq
        5vHCV4MH9Y50M6R8AVoYdCpZw+yAh9QLQADdSnMAWlly3PVDDsoYzw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-16T15:11:13Z"
  mac: ENC[AES256_GCM,data:wBjFOAmXmgp8Ecl5Yfz2ALNcgowRcWclHGGYdRm/09Zsw3Ze3vNoJEeHW1R1HdmFReVn2bumrllIfVMWan5CSq9H2t9cT26I+vYb/6SvrlsN3Vx4bjCwuftfesyQzybRTjoccSbnUmm/OHfsbjNmsu3XcdYQeOq0AoTUuORgXTk=,iv:nq6ksRcJjQPXI2HVZdd+2Pb2ZjIM3xhmOWJwW27gVeg=,tag:BbKgvajlM7XOQGHj+Pyi+A==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
