apiVersion: v1
kind: Secret
metadata:
  name: home-assistant-config-restic-secret
  namespace: home-automation
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:l8Qauas/9jPurtriQUIxv9wtyc1Fcd+mG0XfhgtAV+bFJrxWKYZLGbZq5ZpGkbKHp1mdXAr9WFRi5VuQFtfWl7GMF1RWusoX3UFK7qGpjU4PRFnEO+wbt3nRAbffrA==,iv:a/vUS+K6fbblMgL7cBqnu8/C7vk7kr7Zp4wywqYqpE8=,tag:La414WuDTaIxdj8Kj3JTtA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:819i/MQvKk6NtK7x14YCNox4SpqknoS6p9nk9Gsp1RsBXQzo/icxfsIiWGA=,iv:bAHQ+p1hRVyhab5f+dVZQ+A/EQa7V2tcuHesOujvXq4=,tag:3PYKQzggmSJ7mDR3BOlTTg==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:AsWzMOV0/C1/7YzAKU1Wi6TkwIwF91MB,iv:+QlXOpm3n1+9mqSwIn8r4sDrQ4MttEC/AeRTe3PpaAU=,tag:K5X3FH1jdOGJafsb+Xt+mw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:na3M/bltSML0cZs1dhZ4Dn45At2idb4Qxgq4j0ts6kFDy4Wi+biRWryzkr8NDIKKzpMJlZMhLaDuwtdcp4EdsQ==,iv:Vl35x9rkiBZzleWB1VkWZywnpgDaHDeqDec+aPlLOHc=,tag:TRQUcyfrQoR2zeKt/WSMDQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEYTQ5TVo2REx5M1c4VEVz
        ajZaT3NKSGNidUtkYW40UHdCaERJaldHQ2p3CnVZcWhJYXFFc2FCNU8wWE84bmdY
        bzB2bzRxZHZVb29MSWtKdGtrVkcxWTQKLS0tIHd0eXIwQ3VCU2F0elJkSVBtS3N6
        aHRhUGdreHZreDJaS21vcDRMaDBEV0kKy+ffEpOxuG71oBdhMSL45Q6LPxgrJTH3
        XigELa15HN+Wa2Upct6DZjTQnbHM4QRSIkRydbLPsmwfUQGaCm3ttg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-13T10:23:28Z"
  mac: ENC[AES256_GCM,data:d/o4mHTwtiEnhSMILbIe/3Lrs1RIE/u/UhUPmfCYU/g3BkCAcOe41+bPGslT7sbxHf1pG70LD2qBUJy/K64m/lB9Xczpq1YQ/jQ9CJjies4ruXRMk7wLasKKOaSuSpldUwOls2ZHF1CGKYg74fyeFlF03DkzF+21nFTGdHqs7II=,iv:Bym7Ues7lh42Z5Lhqq7RcVfMzw2HqfbZkc4uXcmb+tQ=,tag:GEQ7XNLeHcUtRTncdwyRpw==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
