apiVersion: v1
kind: Secret
metadata:
  name: home-assistant-config-r2-restic-secret
  namespace: home-automation
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:j+OoFN8qKSOGuI7pXGWdIu0jGpVA/GBWM672VqzzA5uMTh6t8TLFBdFsf5ua8p7pCsqfPGSm/f41mxE8g508ozIRci0u3JdquoaAFiIj86PZhk1x9RLDHhb0RxOQiux/9aSYq6yWrEaZTsrdiA==,iv:tKcJNO3vVEna/hERGkwTiAQJu/6TokzibpTCvHO6DbM=,tag:Pus0Ktq/eVzCsOLzaWJpLg==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:5QrJqhmUSWZp6cxH4xbs3W1lIwPY7py2kcMYaRBY4AYYnVCN/0WpYsU7pWM=,iv:lHz/T8rVFWAm8z/W2K4rHCWNheXBD3Ac8akU2mdGlqE=,tag:Gk67QfqBuyEOaJOizKvNVA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:o3klLJiQqWMgbhh5WIlHcnknOYUpu86vOia5lD8opb8=,iv:AV5/zCil+WrzAF8ePfa7t0SxNpU5Vmh2Pf+gH36OtJE=,tag:f5edPIxvq9iY1tx2hblhEA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:pXNdvnHV2UhOeMlK6/BWc6vbQWxUjc37fWtHpyUoqg65eUuUfODR2u78EAsWFI18gXZ6HIQlraiE6ePYz33eYg==,iv:UaQiriCHIoD6PzXjmTYGUduybej6Uef/nLnBqnWRr8M=,tag:7nl3yy70oEbysyOdo+ERkQ==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:5LvzxQ==,iv:tfzcmdmnAR7TGM4JcPk3XadbcPv9+pLp+5nphzhEL+A=,tag:477H5vSRY5oocQqKcOo+tg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdTJOQ2NkMDc2MFhKcVRx
        UmROU0lKQ05vMVhvY0F1T201ZkFwc21FZVZZCldiajh4YmxiMnR2bmFsdTZNWTNY
        OUxIZkUwRklWUEliWGNGWnZ5VTlnODgKLS0tIHFHTmxBcHNvUXZPb0s2RkxnaGM1
        Mk1xcS9VeDRCSTNUaGNQWlBaWlB4WU0KsmPOnBpBmA+z8HOvSfe8/RByiVdFs4//
        C0kBOUa1bZcVCx+xFtcopbrDWVBi7fJd6mORlsyxZX8y9BC7le77/A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-24T16:45:40Z"
  mac: ENC[AES256_GCM,data:89HvcB2tPg8AedjGvwnJNXYcXz+UpBde6ycpXfM+SxVv6azJDzqV2wTY38VuYF6l62UB3o/grxEafWZYcJa+BJRO+f2Su0n84m5Oa8JvwDpnjEwPQDHcF/tEnJzumEVfx8FR46WPulK+AGwu7LiHWC9UQN0DCzLH/gAT2Z7en4Q=,iv:XhNJqbxyprCnyKs3voZ/f7LDuH88XJk2vSDz/O1CjL8=,tag:ddr9asG9ILWCw1zNF17Yhw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
