apiVersion: v1
kind: Secret
metadata:
  name: home-assistant-config-r2-restic-secret
  namespace: home-automation
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:5gxyW4hU1hL3fTdk+XSnJZIO2WtQEVenmxMxIGORdwGcJIdGz9CuImcWn98Zxan2aFLwCMTYqGrqZURCG8Lde/AcdFKCQJpbuFYjE5L7GfMkiGwpRsS+/Ydb7Rl1j57aLLp32WuyacT7DBOy7w==,iv:XuHMFnCpt7QwNS5EVSN5yfBLvraOkqTqA/+tHS3oIE0=,tag:4MxVtIhmbmWmBoaPbm2VCg==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:cfsCKV/b32bLPsiFTCnFd5NGQGQUhn/qo7CHE/vsMmXDpGhD6zY6DkmTsTc=,iv:AuuKKEgQzrpkun6edOdptfgVijE5G3rgpN/0f3swTnI=,tag:AT4kfJNYnD1GMlNklyl5zg==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:8YuRRDh1PMZG++KFPAUsyIFRYG8GMK83pS+oihHjzzI=,iv:lMC8mQLctS5eI0yalZiCEgVJN4v18hSFfGla57E7S+I=,tag:4j/xW0u+MC2RdgmEjQmkfg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:mGSFCn36rSf1QCeS2DCSgqsviz0M8twUc9j/Wkflx7/2qD43xOMjWB68cvwww3CSAILDShhxv0wC4MuSXYhdfQ==,iv:Y28/MBBm3xAdtUc/cUA5pnrBA2TFtSvaf67nQyhugPI=,tag:Dmz7unn3KgQaYhxo9P1Ruw==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:HO4dQw==,iv:TAJLDKPZZoh/TUPOQuKZi7Nedj3wI+QVkeLL64QUoik=,tag:VGMBMRQHJXw/cfdVkW2iBw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTzZOU09QT2dSOWlvVTI2
        bE1mdzZRNnNLT2hCdytWOG5LT3JqQjN6WTFzCmdyRmxYdEhGQ0poaE13eTM0Nncy
        d3QwRjhEOFlVU1VITHJrQ1IzYzM5djQKLS0tIE9CbitYb25RN2grbHFnd3hwYi9j
        TTRyd1hJTzNwdzRTb1lyYklQWjI0OEUKsZy8c2yrmWk7IvVAJ30IyAXNpZQPrdCa
        qEKVh2QQRvSouTsarvPDzJjV1oD0a01unOuHDIq+iTG52yL1xaj41w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-20T09:05:44Z"
  mac: ENC[AES256_GCM,data:H61pX6RG/QCUbR7yG1JuZFQVLAMDy6LJqaCv0Lnbed6tmmNvjAMO+zNC52jYMITaXU/mx05x3j7Q9ynUv6Ni5C10IlaSzWzV/qPJo9yiUuG320d+glA54cfnszcSeBsC5lo8E4Ryfr9FEuSU2vDpjq+g4Ryu4gWJmxaLGvjZDzc=,iv:9D3fukQ1MNkATL67q6oyxzyUxj7UoIXUfRK0QFKqyEM=,tag:vVcsSQm2IEMruXp28218MA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
