apiVersion: v1
kind: Secret
metadata:
  name: home-assistant-config-restic-secret
  namespace: home-automation
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:0df66Wk3+7KwW3fTZxZQk+pHqcgi1yzmTu827gvI2I+Ys8RPzstCHYLsoCujGiqNI1ilH4rLCnrRdxEKHsbMlKhuiLXLMGZSeF+FG772BCRFAt81zwLW3gv6QAJz8w==,iv:TN8TBUQksLae9eDScoPiBS+iP2Iw5X6KrMtGCt1SKFc=,tag:Azpj4IROmWrr3s/l20GWPg==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:Y1YYndFr4ZLqYKx7+LI4kA4/jzvqCTkT7UVrMeqPUH0pc6YHonZYLdorN2g=,iv:7P9bXtkxyvEl3xhtEul22mVtSHuSp5FFP71envSZ6KE=,tag:5i4AbQ3XC/J72IU1fIdFaw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:QRkR/zpV+F2Sh7G6pu54U1jSHvsnWcXS,iv:4kC8QqYDh6IOom59u4RnVjFshXt1R6rmHGffSWbJY+4=,tag:o51xykBm0iRn078cu+ARJg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:RiiIdBfa2j0VaOJvgBLijM53cKm5fRo/bjLTNf/nwuBDyi/p0N5S7wnxb5aMqNdHEJQXCTfcluIG/h6s7suwcA==,iv:zYrPr5VMBk6jy8gzo9py6eWUbsCl/ocSQKUfhVQpq+o=,tag:7mHk1zjoxI3hdjW/XkDAqw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbHhMT3FQSHpndEtsK0ZH
        WGRlYS9nUTlxWURpeC9mcjFzalkyR1grWmgwCmhHMFkrUWw5eTI4RnZTUnlrYUZV
        czNmM1VXOGhNOTZEVVpZcHoxeVFwMkkKLS0tIGsvNEtjN0hIOHpkSHMwZ2pVdzha
        QUFBYitVTjE2R2NnSFJzQzJXcWUvSm8KQCsOv6AnuQZmvn1MOhtblVbpjvp7W8Xw
        1V23/di6YFLbMEPIT2cuaiySEmKh22i7UNvY4rA0hZt8O0roEZ7kgw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-03T11:43:16Z"
  mac: ENC[AES256_GCM,data:9p8Sxpz/fKY8JaxAUG2bWN2To+pgVJDNHvIS8DTLTuHI2888y9vm/rhYcgSjQEgGwpIefisDTLGztwakCp9NoPE+Tk4AVP4NnA/bPDillpAPzoMTVVQFkIauK103g8rCpSLhUKsbz7R2H9EDgI79A/U5F0SPhz2no1GPaDpYO5s=,iv:OEjPOmem9zceqK6KgYQieeTUZXXvAIQBTKa/Nwm/jhQ=,tag:aiR+8YcKEuJo88nYfeRDlw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
