apiVersion: v1
kind: Secret
metadata:
  name: home-assistant-config-r2-restic-secret
  namespace: home-automation
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:KnMedfof9sEbbCZpHQV9Qj/Q7IGfO24AtoOR2xokAl3Z6Vxl02zPnHA1BdIh300Q7Ha9JZEaY8NyrDxbiCwy4e3Dw7MZ1vkU57s6EWyCP+OD5vWcu6q+sZzl57LMhxFaMsHe1O42Ra725d0O2Q==,iv:7ZLlij38hJD/FvEB8m4UBXVTeSj3Z6+BR/mCEten8tc=,tag:FBz/dqD/3aMyVPhCjqPURQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:RIg9t7m02HrJ6Sqg4La7UvnQ+JoV3THwQM1vLk2LHJWM1M2081mcFjP0iIY=,iv:mHTCPC/ZfXPY5hEFox9ls55mKkfBw4HF7IsxBmIeOfE=,tag:QDIgj6TGtKdD8RomV4PY0A==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:JhUZnEFxYs6MeeBSLGTn5Jlzk4AbfPLc971Dqt1lni8=,iv:KAuV7v3r1zPlZRu2gubV3s13kyVhh5F0FjwU+ggmylA=,tag:qL4d2YVVqeV8mxpdf3SMqA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:AxnDVe11CLHbVaCEidOdB/zdS58mOeGCYwaPXXnfYbbQj/wZ1kJnW+gB458Re0m3Ars51D9WZ6XXvAIkECcXDQ==,iv:yYpTSua1cIzgSNiPYx2K/yJxIFryehplVKPU6h659ZI=,tag:wezvKyCZIkZjfQdyRs3Ysw==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:6dyPog==,iv:BhEG2/QGmwMB/Gl5Jiw7WWHrH+72jD2E082vNGLI0nM=,tag:Rdr7JhhTtl+WAJeCLwQksQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdjNWYjZkNFNKTHhMSWt2
        M0RmcHgzQThJRW1DN3U3d2oxczZQWGtOUDF3ClVHZjBJeHgzYjg3eVFlUVhWckxo
        Tjk3cjBWWW5tbVN6a05SRnBwcjRHaFUKLS0tIE1lMm1LcVN1V21ETTdEREpVNkh5
        cFpmUG84Nk9uS05lUFY2QU5OZ1JhT2sK/PoO90Xti7BKMz+hKAikce9cCI9fuGJ3
        YDUqdGuWJ1Qi9FGnXijPfgYyNqU8QXngNkGyzrTEbbK58NNOxtSKzA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-16T15:11:11Z"
  mac: ENC[AES256_GCM,data:srUBrJscVnl59EV3rLfiyNZN9RSqOi7NegTz1hZI0dmtZsA2IbSQOT8lwcykVT5FMuhjGybSSCbuHMTFpeya9B1GZF7QREg7XiZZy9EuQnmLBFtPbtfcFiXIHUCLbdD8Ef3c/B9y02M3ZN2RJij9DGmc3Bq80/4ZMCOmc7DyVzw=,iv:Pol5AF0gHUNzs589P7aSURuBN0joKUVqU0Iac5m3W14=,tag:NOuWGgeygbHS3vdsBEcOsw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
