apiVersion: v1
kind: Secret
metadata:
  name: home-assistant-config-restic-secret
  namespace: home-automation
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:yEs22gnOJysYJbgcJXvv8/IupZovR/P0NFKXl8Yi90jvhDYM3eNnZ0CdqNMuBVgdtAZTUWSeVp94a/Yz6JsdsM5hDNYuu09KctBT+7fZ8L480Glu1tuTfus+gP0Cwg==,iv:R5JvLWtnRqkVfzT0nLUlENBpnZblLim06ZAYWN0+3L4=,tag:q4sTvHvms8M3A2uDEE+vAg==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:2AL/fRcZZscsPilHzSJFsa5GhUA02wKO0jpxezBY0i0uslXew6rqPoSkUc4=,iv:Zs+7vOIjEPIDKphNklMia4H76Q0fgiELFjtHXGVNznI=,tag:CxWlzZY0tLIz9gplHuTItg==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:YNIHSM8RimEI6iKf+Jpseeb+yDFYC4wq,iv:IDnSRfJTW4MQObaclIHiGXNcIXZvsS6PgYZfd24uoZA=,tag:b0RijPM0RJBwPv/xNuvFhg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:AsI6ZwUFzXdMymxqaUWp69Oe6mGPJiwQHwxIFvLqWEFnBn240X8qUqaebQNl+wluaf+6k+tbF3vfr0WwbWdoHg==,iv:jZsLNAzZYAQneE6/G6Q0WSC154TkAiaVFsuHkqFxhY0=,tag:OlpD8Th5qxlI4fJHYKBIOg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxU1BreFh3RjVXRk5nemhQ
        SWJsT0svSkZqZEdNMWNTS1NPTmMzNmU0VEVzCm00UzJpb1ZVQ3FpRzR0UFhqclQv
        dlhSd0NmVTR2bjhNYXVJeDdVdmNKOVkKLS0tIGY4WXdsd1RJclNXVEIvZjFvTDR4
        V2E4eHVKMGx1aUk3Sy90TE9FODhLOTQKu5Yz54e7K/X25ECWMELHjw0fO5t93Qjf
        whnVY4rDuQr95flPtLTlqwdb+uE+V6aSYKpQg5Un2ex1pTb6frr8rw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-17T13:02:23Z"
  mac: ENC[AES256_GCM,data:JGRLkdPQ8ks0jN/1dBanqDsS0O00IAt6susJScMJ/favrlsjCGN4W5RxZSR7s83N1CIEvlFrViIAGXmdCI6oifS9+CyRycmD+Z6H3+BYUu9K/wzH4f7Ula2k0tzq81pOdm7BiDJXG4yhRiUUrWz6N5QrLfgNFcIX/Mx5fIxV4TA=,iv:jOuHGeHfrsH1dzETJDNjdhXdOOAjhZ0sf6bWn9XlSOU=,tag:I0zq38cimcjNvA8HEsU8+Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
