apiVersion: v1
kind: Secret
metadata:
  name: forgejo-runner-secret
stringData:
  #ENC[AES256_GCM,data:O2GsRLAYamCEBWwH9irQSv16G+TchPB3oW82QmmTyeHUEQr2ObCKjXR3TdTV7yFfy3QgPfya0TBLNgD5rsmN3ufv7TClJf4E,iv:9U8oI8rLDXgnBHfq4rYiHC01OfataIc2xzIZvTm4mUM=,tag:1xr5u170WxtmRrSoEy2UEQ==,type:comment]
  #ENC[AES256_GCM,data:fYtEVQz1qDb2AK1gcI6GXWrI9WuwAKMYQjStEHCURfEblcutnqc7xiwFmYH1w4aoH7SAJqUSoXh88O1/,iv:X3FzxQfNz/O0QnyPAdSMd56mG44wfqAY6nzfyLKWMlM=,tag:NI0IYXgtk6FTTQjpRNTisQ==,type:comment]
  registration-token: ENC[AES256_GCM,data:m2cdMGW4iTOzclYGwQwG2IEi48b9TW+1Q/2MgqKppaCl3TcMqKqKfA==,iv:K80foY6e+bMB9poleGPhbHS20aBDfXvahFg7asTsKzQ=,tag:gScl518YevtocxrE4LxY5Q==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyS0JSS1VuTTA0UkExRFhi
        VDR3N1lMb29HZDNKRXBSOW5mRWxJc09YdnowClF5KzNQVDNJMEwwOXNHM0RYZ1NO
        MlZvMlFBMWVKRGVYMVk0c1J5c2JMclUKLS0tIERhRGJPd0FqcjVqdGZJMk5QT0dQ
        UnR0TzZhcUpvc3E0Mk96Nk5TR3JuRTQKXx4LsXFKxKoarosR/4YHP15wswGr80Sm
        o3J3A8aE7xDDshzCc619kl/aBTp3oc1eSe36+fXwpbobvNVRang55Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-20T12:50:07Z"
  mac: ENC[AES256_GCM,data:VzkDU29AO9SlCi3OjaYWyxBaqH+RlwhbGDBaompYMUSwPCgjnyHhi70UWeeDMOjFJBDKvgyNJKxXNE6VaaxY3fyinJp2jGM91d5g+LBncjq5yHdjAC9W/+JYhzZ5Y0OSCGcAoafLceIz1WnbsHTAXqzg1U89gOz+R+DMS9giDys=,iv:DwMomVmGZc1gmTqVu2gdbKeMz6nKwxkCEBLG7/48Db0=,tag:gMhNTFNSnPXUopvPXfV8zw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
