apiVersion: v1
kind: Secret
metadata:
  name: forgejo-runner-secret
stringData:
  #ENC[AES256_GCM,data:q7vIgHyZC19v2DBGLNUGl/Gy1x8ZlruA0gPmOdUyIXw9LOGItOje9aXL56SNXswZopUVyH1JR3W8hyA3sIhtC7GH+tthqjkK,iv:1LTlyaU/7N0f3lPttS2v25qh2z+Vgm6ikdUiSEi0Hf4=,tag:X7EPsenopq5vkOUg7LeYfA==,type:comment]
  #ENC[AES256_GCM,data:DGK7ur/NiBqZQmI7/u744Fsl3ySS0qhYaYzSSvMEcFEJEdHGCdNai5/EBZPk1gdSz0OyZYBlRLJdVXYG,iv:G1v0e2QnHGorDq2aYpbcMsSHUOd1qRi0oogz0IBCiMk=,tag:KcEp3We/DhLtOlZHF7rzkw==,type:comment]
  registration-token: ENC[AES256_GCM,data:qXEsMrJ1eg2SZAZ17DojdqpiH7V2K9iLlajVueL4II2F5+BZIDpRGQ==,iv:BzEw494cqgP+N2FCJn16AHmR8GZ784oFQ2NofkYbv2o=,tag:vUbjtN2ar3J4095KdxeB8Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTnZ6eDZqVVUzSmsyWG4z
        VVJreGxmVjF5a01odmxwVHJ2Rld3cHpHUVdVCmdINWRXeHR3ZEwzeGN6MEpXL29p
        cUNMWjExaDhKdjlGM05FYVI5dHRTU0EKLS0tIHR0aGlNMmZBTGcwdlYramlBSUJR
        RHQreU9wVHBXcmpncmZXcEkxalZsalkKDcYAfscqGIpTfdTRW3skK1ja0co01lms
        jAtubmPfY+HY0wdZi1sNdIC8ENXidstQ6Ru6zcsScRCDB0K4r6A2Hw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-10T11:54:13Z"
  mac: ENC[AES256_GCM,data:qQb2SNnMWDq1e27beYMgzfq7v0MjtM5NN9DMAnqZ52Wm9lYRS5s6QWaPJPxL5Cb1j3Q7TtFYmj8U9PCtwP0SIRRvW2IwNOyTqtOhOPtdVvwLqRTcy2RcdpmNQ8W1Rv9uRIb2sWKIfroaKzZQU+eiQdLIhDvmkLNQvwWsEBmslEo=,iv:3nYLh8p3S1T9LaU8+ektKvNhEqDwIR8YJtuYtPCYjBE=,tag:X3vihRI5urmJcAW4xwCx5w==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
