apiVersion: v1
kind: Secret
metadata:
  name: forgejo-runner-secret
stringData:
  #ENC[AES256_GCM,data:8/uyeCqBYOMb7Ps6ZHtmfPZ16/3qSCYw4zHtA0lm0x1/fWmIaQ3ngavtQBtEDoarXyLDLZDYp4KOPyJ6Jz9w6YboX4GLhlR0,iv:eC71K4AIdf4X18Xyz81poWGhMPoOeHTCL11Gaxq1AMg=,tag:f5cHrzmgiTZUbLl7n4Hk+Q==,type:comment]
  #ENC[AES256_GCM,data:DMbZg6tKMC3hs9LdBN4MZXLj8uu/ncc6vFtyFXdi3MCJuzWoVZ8/dDUuAb9vr0QiV/bw6HdQ8HLeWsiA,iv:/Pqjrf4yHrI74w+CAgwZOhlp0IiyBJi85xHjiiwZmpg=,tag:7QZsVUCIj4BwdAMZEK3XOQ==,type:comment]
  registration-token: ENC[AES256_GCM,data:imMzDsF8mk8Iun4bZKRBEqfNlddwSpRHnZugw8FUf9pBuNym7coZAQ==,iv:Y5iUXYscdA9uZ5rYdS4q0K7N6t2nZPbuJy8+bTmV63s=,tag:1X6u8htrsyW6rzmXTWFeyQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiR2NteWphSjRBOXMwN1ZP
        MHZaQ1dnTGduaDJVN0VEWVMrWXBKR2IyNkJrCmtydndlaVp1UGQ4UC9ONUk3Rk8w
        MjZtSVZka2FPSjE1L2dTZ2tVZXY3YVEKLS0tIHhPc28zdjFMeGZMNmRxSGYreXY5
        Z0U3WjdhRmJjT0pweTZRZWpYc09Hbm8KTuzWMKAAM3J+a8EpeH0iLbrrqEVaVCzO
        bPVpPsT6Z/eSgmIasOHMWCNPWZioY9UBPtyfoXCmsaJwPWIGsHtXww==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-11T13:48:06Z"
  mac: ENC[AES256_GCM,data:528LpmCGQ6jmpwMofi8gh599k/jYFK4hZ4ZBur2cNOUjlnOAIHKc7gfy2SH2GRKGKb6oIUIZgNmh98BJrsyGyVG7e6a8RDR9ZFl8Sj8KCetRltAl3ykk+ycURoVjiccejjgF5lq46aYbQju9AxcQGjTSgA/IhKKDYIlU1pkmHT4=,iv:vau5RqojckODE5//BREhNBiENBWrLzBd4QgnRucG52I=,tag:Xz4r4PH5HDYVGx2SwcqnoQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
