# S3 credentials for CNPG (barman-cloud) to write WAL and base backups to SeaweedFS.
# Leave empty until SeaweedFS bootstrap is complete (see storage/seaweedfs/ks.yaml).
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-backup-secret
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:JNY5T7GeuGIAaHRKozfawEM9uGeEYrut,iv:KulSPZtNR1gAy0JFLYeOc5Kw0o5+/LhCN3fd3IRouFM=,tag:l+Gl5KOnjXg1h7YohpDMfg==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:Pka3d0Hukm5T0XFWZuaVAC2ExGQV/i47naivkl25Nsx/L8MRD3Vz6OCqKIsyQnjWw4OqH/DrviPu192sUmXXYg==,iv:phkWDqZiDI8NHMSffoptVXfZLw7bhZEmmifqBc+3S5w=,tag:2r+o6O6/+lzSD574VKAhZA==,type:str]
  AWS_REGION: ENC[AES256_GCM,data:0nuBO5sSWUkz,iv:lmxmmxvqGCAscujWWXgbqQVx5xpHl52PyCGF/KVQzNI=,tag:vYjLFi2cQZDo4m5VCeSwgQ==,type:str]
  AWS_ENDPOINT: ENC[AES256_GCM,data:9NteJD/zivEk2nTbuvv+s3Ef2fltwUdX9MCtP9jMuU6vG+q10iqZlalukse3S2j11fcD4gk=,iv:kz9S59V4IrgovPHeOzrMZGBHyopyz5whwF9KXL9u3XQ=,tag:6eehwIUVEKzyit5Q0DeMNQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBbGdKUUFDR21aZkptTWdp
        VWJ2am5qMkNzUFl4NWRtRFNER2ZySURFOUUwCktYcW5GMFovbjNQRU9SNy9WbFRa
        ZWcxbW9jODFuQ3dTRUNkQ0FUNE56REkKLS0tIDhrV2ZobTJJWGNySGh2YmxNTWUx
        eU51R09GM1dVdjh0OEovMHVvYlZ2M3MKHATj2d7yijqIunU9PDMoty9iTWcvf3Do
        CI92fzvrJoFbDBtaNYa81t50Vm2RopT/ddcKTLpvVQwfROHotflvDA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-11T16:39:57Z"
  mac: ENC[AES256_GCM,data:Nm/ehRRRNyJ8xHluOUot/T4g6AxuHrvm2ATxOmLjKb6SYffrlGU1UVMR5qhW2/ZBl6yoksZFN1gYovSfNkSL5/8X4je6mEtGSzPVITruGVaEr0bJXHtwmX4zkzPyf7lzUH2CLg4jYxTkcaBkr1aj6aeEnUhqs9VS01uU2XBbpQU=,iv:UJyyt7Fdgl4CBw4+eUJfrzdeILqrxctA0xOIdbna7sc=,tag:tP9XjlI/PG2N0DQ2dgnNIg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
