# S3 credentials for CNPG (barman-cloud) to write WAL and base backups to SeaweedFS.
# Leave empty until SeaweedFS bootstrap is complete (see storage/seaweedfs/ks.yaml).
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-backup-secret
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:94jM3PZbjN8c4eAZYyhuYtst7+LSTNC4,iv:rqCV9eXZrl8KsBGwYhlflSYCNQRehT6gwlfYLyxNd6s=,tag:Gg1HLMyOmLuRzoNNT/pHpw==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:hFhtry0DiOKpdpdlRF8y/+IQwWCA9xefULTvO/bEUWFru7w/w4iGlxqx2R7VzCf+w1PFu20jLEI624yP2WKk3g==,iv:uWaLokBx0SXO3vFaFGqolN9KnulTmuh3IDMI6wBNw6g=,tag:pHAo8r2BYJGXjnh+o2cukg==,type:str]
  AWS_REGION: ENC[AES256_GCM,data:y0p8or5Vjus2,iv:fysCm6Hreq7TXt+BgQjwN/MHCQMHmGyQd64R7MT/f3s=,tag:GVrvgXRkMNd6QI9INQ0Bvg==,type:str]
  AWS_ENDPOINT: ENC[AES256_GCM,data:Uv7IrpDj3kvq2Unb3fHNTWt3OBlj5CJFSIG8WYyImuwNlTN4jhTcookLgUaiPrEkL/3R9KA=,iv:5st7XbpkZsgjaMohtBLuCdVbXRgKD2uMkVZL87klbsI=,tag:QC4OZjzQ8KnfcThkAwomdA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVYTFVNlptQWxpaWt2Z3Rs
        QUVMakFCS0RQUmIvR3ltTDZaZENFeDFWclFFCmZTZUVnMDJJSWpyeVRwVkhOeTBh
        RWtlZDFmekdLZVljRjU2VnIvZkk4U1UKLS0tIFNXMVdaLzBJQTM3R0NveGlORFY5
        VEo4anhlQmZOdkRFQU0xc3RrZ01oMFkKW8AvdfA6LEVMP5cHBxJStWjuTtIAOvSM
        M43U1afaspIlOByktFS5+m00OkaBb7P40wEbqL9AiYJKgROQ2AdKvg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-17T13:02:24Z"
  mac: ENC[AES256_GCM,data:FyF4Us+TI8iTr243cizoSB8VW7glB1ICcg7kf57PhXa3/1qnkoji9bu579ljskG5fZkgWDyNReoWfmGErV5HBiIUmH0a/gNrcrwCe1PXQIFVrezxoVI7KONEjMagRg778aVQQbbYcCe946oR8PXv4ljPPGL7KJC8pRBk6GROcwo=,iv:/fwhNEn//56+LAPdDzfcWB2IpvZ0jo+mdgxvBm6wKic=,tag:uZH/V3LdmUn/3p6N57b/jg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
