# S3 credentials for CNPG (barman-cloud) to write WAL and base backups to SeaweedFS.
# Leave empty until SeaweedFS bootstrap is complete (see storage/seaweedfs/ks.yaml).
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-backup-secret
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:LQ9uZVSD+ZPmhZXqaoZQRm3xBT+I3RcR,iv:kDBhIvXOsLv0uZda5jA7gPzG2S0ozo3Kj5C+ekJJhWM=,tag:gZlNVLy+nZYQOaqSdCd1NQ==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:uJ1pzs4xMX2513orsnqugMh+W7Lze2toZVeQg9ytHsL3BHMlEm2darLONKAiIz1vuIulhJ4oqIKeMCOImVjUnA==,iv:kmQFZFD9yj5j0MEXoO42JNMDy76Dp/FKZ5fnyuS+Ps8=,tag:aPMejoWb8k/qg7Kbt3MezQ==,type:str]
  AWS_REGION: ENC[AES256_GCM,data:GGvFt/lGeHfi,iv:C4pa0ZFtHQdj6tcBE6dPqH2NoSPAHfHtiRGJK47e0ss=,tag:MqGT2xsezagYx2BsosDe3g==,type:str]
  AWS_ENDPOINT: ENC[AES256_GCM,data:xH1f8/piUgz/MEcoqaQgnpEYOJbG4yxRkZrQIJh4waM9L+XZjA0MV222hv5iTyihH/qBnfo=,iv:no+Sy/qu4nmp4wNANtrL2bijt4DMyUlCb9u7xmYoG9M=,tag:fhJGZfohllOQQmvjjJx0dQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQy9qQW0zeXJCWGxHT1RL
        T01sR1RiMVJubEtDM0ZtZnJNOEEzYUMyQjFvCjJkU2RQSTZJL2FQTUs4RlZ1YUEy
        SC8xazRiVHBMZ0dnMnlhVGFUMWFtZzAKLS0tIGtYYmdINURGRHdRRW5QVlBzRnlN
        L2l4bnJ0alJLSTV6UEJjSEZ3R21mNHcKlz8NxbwygImP85jogenP9/tnQCPQh5tM
        YfseBMx9db97zwr3yHX4UTG81zOMWCkgktMbAdr4ODVZkXGFiFPFDw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-01T10:12:03Z"
  mac: ENC[AES256_GCM,data:mUp3MRuVJMTMJS82KMSgoNLntx7QGgFJ5Dm8aEf5ya7xKAvPU0lhIUzH593Pz/bRfdyNamTQf37evKVHpFiWLDdJ9ZQg0drrr+nPubFxFrh25NqlLbPNgAJBWcwJnYdwrYw9ElZhKP0o++CBJuxthFzms4FjSpXV7g6HbD+mgto=,iv:b9Ut6fdaS2wbyjmavlvcKzrTU7+ICk2nwyAs+i4XXPA=,tag:ltTWOEeSY0hQPZ7pJJEuqQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
