# S3 credentials for CNPG (barman-cloud) to write WAL and base backups to Garage.
# Leave empty until Step 3 of the Garage bootstrap (see storage/garage/ks.yaml).
apiVersion: v1
kind: Secret
metadata:
  name: garage-cnpg-secret
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:i0UPG3f8Uzt6vHf6pBXTUYXQKDr09Muc6G4=,iv:zQX2qp6HiGNgi3PhJdIF3DZK5W4xiVbNgj9dNrjhkqs=,tag:Nn5VCjzRMgdFgZau8scx7Q==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:fVuiNTUxlnxD1TzZdJW36odsTCRM90+NM+UAzNPk09q1LyWGRHioVZMFwqPm5npEONpeDHymbCT/aTnMUVk03A==,iv:hjFpzcY1ZnYVGRglT/nJQ2DTKO+iJEIMsTqvocxZSlo=,tag:DVaLIEpp4ZKsBxP2GuAhvQ==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTDVHalJDUjlXNThWdmla
        ZDBiUEFiMzBPN0pmY1J4dUFoQ2pDR016Y2tZCjhMdDdWSElxOXF3R2I3cnlRQ25k
        c1NCdHUvTnZMSXRzWUFGWW45QWRJVkEKLS0tIEVJSjRKSHVRWFVWVVd0aTRjeFhj
        STBseThRNUxZZUw1aUdzQzl4bUprdWcKm4wKE3LF4s8xCSbarTKqyVwjuL8PjV+j
        v3rAEX3gcUU0vBHGQkn2z4yr6FyBOWH/ioZtmWe81WU6e+EaL96iAQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-17T17:20:27Z"
  mac: ENC[AES256_GCM,data:OyO3aq4dZcREzmzesHHBt5OI60kcA59IdWhCgJTBTSDLH0A5fmrHnKkOMh5yxDIdpilMIov24HBIdStdL0ITSAhdGfcVjXoqnrIHXWvUkMgweABp2D8jPW6wTNsDStaNAQSqkXIgdqAWP3sp4g2pc9jIqa4KoOhtk4bg8FXpa9s=,iv:5+Tz4Ikrfe/Cr0RJpKSdcEcm6AVXZy81L8dSz+FUlk8=,tag:ckc9HO//Em2thGSLqAnZgQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
