# S3 credentials for CNPG (barman-cloud) to write WAL and base backups to Garage.
# Leave empty until Step 3 of the Garage bootstrap (see storage/garage/ks.yaml).
apiVersion: v1
kind: Secret
metadata:
  name: garage-cnpg-secret
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:UwtfqyUHMO7lrM+k1y4Zfhas+YSKCzjSyX0=,iv:MIPXrLFRXvoA5eH6vH4E5+13MkJHd69yKNJLCthc0dU=,tag:ukvlVI7O2T1GgTpbfTQj/Q==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:QW3e/v3lS1s/0AdprOY21FKlQN8lONgXSYYBp16OlnBX+dRuXxi/fFD1NfhCU00GK9ULHihgPhwqlWuP1rgOzw==,iv:3YJqxsdWHQcUI8GqoAtafwIf0UIh9tA7kcG6B6gsdfE=,tag:yQ2/8EwpFxgRkbLuWfWIpQ==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjdTBmN0RiL0YvdFZvVlNz
        cmpTckloVmVISVEvODJWYlhkSXFLQi9TL0FrCjJFOVJybE1wZnZ5bEJGd2Z6N0NN
        bWNrbGlnMThiblBqeDkzUStVdjNWRVEKLS0tIEZOVE1zTTlEQ0FVckpwZEhkWm5h
        VDNuc0xYbDRlV2FYRkVjYTNTZklHMU0Khd0+OqTUPoOYp//Mp+pBU73D9s1ZciLQ
        E/6LnXJ+RHdJHTJIRe1YGisOu94s10YxjPPN5K5s+fN+1cKI+R15ng==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-16T12:19:09Z"
  mac: ENC[AES256_GCM,data:CyUT1kKhBNbXmpw3ato6niTUg/qRpomVds6Mwa4PoY3fpwfpH4ur8BFIZtu/ZBImiNxhipvHSysd4fkYuSFVNfpG8+FKBQA7/lpB5WQZBR5INC60XX2gR9I0+6rpYQfl7BjG83TaTJR9ByWJw0Rr1GA009Snf1fg4m8yJRzGT9M=,iv:4gBk8a4aHP4CnW+qAbSr5pby17uyXvl3flCuy8LOr2w=,tag:Blg+yrQnDHVJKbf3ch0D7A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
