# S3 credentials for CNPG (barman-cloud) to write WAL and base backups to Garage.
# Leave empty until Step 3 of the Garage bootstrap (see storage/garage/ks.yaml).
apiVersion: v1
kind: Secret
metadata:
  name: garage-cnpg-secret
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:MV3U2bALo3vLCyuWh40xKGljRQ+EtvOKDhA=,iv:pYLzbSMmYvN74PD1bdJuhExt9cLAuAoOrB0D5l1Y8rE=,tag:72I/GomjFtZc3Ir6OrNhpw==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:2Tpw2799cvzSI82J2D0Oxceo/WFNlHW6g5xHLj+gajN6FwU4v0L4lG0UEBM5INWfs+yTs4lpWY9TNh0tdwxPoA==,iv:XqCQl3uNQWwT18iuOCWYtaEX4yDmV6HK+kybJKjUdL4=,tag:4G0Ru2Axs6WOUvbra+hzyQ==,type:str]
  AWS_REGION: ENC[AES256_GCM,data:6JYmT+Po,iv:BB2N+CF2kV0wwVECaHuEpxBs8CxdHZWiiKSoTkoDCMI=,tag:aGGo4xwMoASCuQjro6RZmQ==,type:str]
  AWS_ENDPOINT: ENC[AES256_GCM,data:wUta3KRfJYl9dehvw79+spLPIPDadB+pRMNoXQrMOPZp56uARTZvqyUQpKwb6Qs=,iv:AInH2LwkjHSypzib9Lv6GTA6FLWCAlvIOwzJ8ZNlkPU=,tag:ac6R1sN2Iw4u3LQyOZUSlg==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdzB3NTRnNm1sSnhra1ZJ
        NzVBNTRJSi96SjFYZVRtMU9tNmFQR1MzZUVzCkY2aVJDMDQ1cmVXd0ZjQlJWQjlm
        akIyUkJFR1hEcUN0WCs0ak54eHE4clkKLS0tIEFRck14UUVMc3IyVnNzMTNoS0dx
        QWd0MjVhNVRGd3VBQUZKeTM3REg3SDAK0TOLs3KgeJsgK/J2YA8fyiNvxwZqNqYp
        1UmqD+fNynnGt25QtMhAfKStG9Sy187GpKEpr1xivzKf1h5QcV/S1w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-21T10:14:08Z"
  mac: ENC[AES256_GCM,data:ODeUs+CZ/CzPen8CpNET/ZkEdXJwRX19+yl2rzOE0qgtSO+Wfw1VSAlAEk7ephtQ5ZdS+Puw78bDYWAOa2txuwlIrvDLUHfd/mziUAPhmH+pu2S9oIhieZkXuqtCkrPWWZmYvUMNgGgB2s+kr1xDbn9DZ6XWAin6Arebzcu/Org=,iv:io67IO8nwUmTBiSkNq8yTf2tWfxS2TsjzRg01DLh4UQ=,tag:F0ZV5uB/L5Z1AiqQj70KKw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
