apiVersion: v1
kind: Secret
metadata:
  name: forgejo-secret
stringData:
  admin-password: ""
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYc1dmaVM1azJDcHFySFhj
        QTZBa01mNWZuWTBxanNtR2ZMR1Zkdy9xNHlRCkxnNXhYeUpGc2xjaUlKWkNZNTlQ
        NytBN3E3WWY4NkM5YnFRTWVLQ2pRWGcKLS0tIGFlMUFjUVNKRFJia1dZQ1pSQ3RQ
        SEE3QzlWWFVyQzRXOG1QQ1NqYVhncXMKGbb13EdaJvreDPiUS6pOfuP4lsYAbOT1
        ea96VlH7NUn8C/BdTtgxvYZwfYvv6f3asGzoWq91U48u1GUt7KgXdA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-17T15:58:16Z"
  mac: ENC[AES256_GCM,data:WKucl3Oz+TwZ03KkgZ7JNfRBwcLmFWJHqIYr3nT8BwURlNyVm3eIkFXvG+7ez+M9d0eQ3FCF32FLZY+MJ6jQUpS+kf/siQq6vv36bRoU+K0mD0101sZqfiMWQL/VT/2pk7WEKhsLohRdKOsP4Wydm0qK3LPjVYInyY9G1Lnnc8Q=,iv:WLtDLofPkc5EndMTEKYStXdTys0+OX4oRdp1hZ+Sy4g=,tag:t/earEcLneAQiH10wAWgtQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
