apiVersion: v1
kind: Secret
metadata:
  name: forgejo-secret
stringData:
  username: ENC[AES256_GCM,data:XrAijRJmEq4wZANr6g==,iv:qaM4w9xEMbSFdZTHYcleWzMWWKUFPQpKLTVPcRDT+Fg=,tag:7W/ea0vR9FjofszMKPRRow==,type:str]
  password: ENC[AES256_GCM,data:vnWhA4UGwQsd5Fv4Pt4OMZw786c3LOhM,iv:b+rKMIJAc40LUtOkuTpOtbGiqR/xwOCLWQu1Y7dOu/Q=,tag:m4t3myzjnz4cOlZYQCfz8Q==,type:str]
  admin-password: ENC[AES256_GCM,data:5Wn8O9SI+pwdLRXASJCDA6trCEpSMHkL,iv:/RWAsf5bhvuaRIpXOBhCQslY39DJzXJoV7XxdIilltg=,tag:RVOYGbY5fjE/IrshHQSCbA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSFZ6SktQNGxrVmlOTGxQ
        akNTNUppN0tLSUlIVW1GZ3ZUT1J3M1hac1cwCmY5OUVrSStLa0x0WllSYWhNd3hG
        eDBPQzJUTkt4UTZKdVRmNVloeVcrc1kKLS0tIC9rL3doMnE2cmtkdmdwUlJnQ1p6
        YktkSmtHWWFMejdPWFgxT1k0TWVVNm8KIEVnmx/frIljeTqYK52L/8xy45Hyi/Zg
        9sibCltx9w4BKZCL8oK+ehml/Ye49VSavWTF6DRhgnPGhd+fE54qYg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-08T11:17:43Z"
  mac: ENC[AES256_GCM,data:DHlKpOkGitsP3h2rf83U34TfqTlQxBuxfvLwhNXpcrZz1QCzjF0xJcQMmVkAytShsaQx9qj3G+zPziwhAnD90dW5qfqueWdFTntphNBzF2VzjEcZ6U5L5SAt4igcNzOLS6vRFH6c08fyyVWrfIHk8oQnABZnVOPQnchsR3hQgzo=,iv:79c3vRSw08AiDUS9P0sahSMeQzeG1ROUJtA/wuLedcg=,tag:JovJ59UqxlYkddSPJEBPiA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
