apiVersion: v1
kind: Secret
metadata:
  name: forgejo-secret
stringData:
  username: ENC[AES256_GCM,data:2mnC9ozCZCkjH4eeDQ==,iv:nrdHv0R3Em8MmO5H0W7YFPRUmXA8vIoGf6mdH9VcmDo=,tag:KAgy6Ey4TcQNzvVfrpIbtA==,type:str]
  password: ENC[AES256_GCM,data:2bK6c7Pmg4RdOLr1kYMlCFn8Uo0y7p8v,iv:Zs4tX/QX9Sdp0KjNnoLWB5Qze1Q3GUfjnZUNrpNMMzk=,tag:K03J9KxqqqJ8THNeWJyZiw==,type:str]
  admin-password: ENC[AES256_GCM,data:O5XWXABnxr9m2b/8xuIZmMv0NZIJbz/T,iv:4kpqoB1R12sv19rzSLirtIJlHa/UA02Y8gZclCuX1+8=,tag:0BB61bYXQ8gzhfXiraX12Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENDdGRW9SaFZqODlrMktZ
        YzE2clBDeTF6RFowT1BHUnpHUEdTUFdlQUdZCmZubTlEMGNnZmVVK0QwWEd6Z25x
        R0xoSWVnQ2psMi9GTGk3cUJHRlpBQXMKLS0tIDJqUHVnZGNMN0cyY1dsTjhXY2pE
        eTF0VlAxODFwaTFkS2NVcFI0a0Z6OTgKA/M0wMyH3/+r+iLHjtOqx8g+l1hptJzO
        6iIL8Ge1ak18vemvLymDba8SoOTuMEXlLHIRQTYdWb/SqNt4CP4Ylw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-30T07:05:46Z"
  mac: ENC[AES256_GCM,data:xy4qDqKZx3znbbNjaVXUIPBIDF8HfhBDBAdwUTVQ1wUHnWzZXucDqp+CqIAlbncXXhnojNt7W208e1bs+bJbe5vFCVcNPFau17u+gmbC9mbBXWa1OAhKyIAPTwBMvaEUdBG0IKtvRw7+9QRXdMqeTMN9Yf3zbg0o62pic8UOlRE=,iv:EIfgQBjP/nlmOiC40ES3yWISQCIg/ME1tM0hIfP7mPA=,tag:jVtC4uhcbso7chdUULgUlQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
