---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: authelia-bypass-forgejo
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: forgejo
