apiVersion: v1
kind: Secret
metadata:
  name: woodpecker-server-data-r2-restic-secret
  namespace: woodpecker
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:AZcA5+c05XWbiCk2YQletRVrAiC9vocQy1MpSeVq3kjaEsqvDcdKSSPhUeWBYi11deVDEQ15Lxg18jJ1JU4b+v8I7+iQM1btYi8Fz/E2/RkiP/2XIJMhLoA0KRP5UgY1qGk/0Gzfe9RARwJSu/s=,iv:o+JZFga1MyLorD/E4/IKGCv0VWPGehRCv7ER5XNE4m0=,tag:J0lmsyKRRjd+SWWYx3PvBg==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:Udltl5v34lnirKV9WX5E2mULK0Uuj+5i5lrtyCoGDjMIdkvCDPelaak8hqY=,iv:3myOAJai0ZeqnOaO39fgZGiNlGPbBUGE2swaUwr2RRg=,tag:fmz+4MLL01m/oiaqGqURWA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Za/q16EM8IsmrmBan+gTt2NwM0GbkwX2Hup3Y44/TiA=,iv:Vv0hJFyFQdr2ZnXL6KJ+AdzFdShEZ1Izpia9H1G5+Pg=,tag:hI/MI66guwYXN1697/XSSQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:w/Dk3gKE8BxLhWK7puW1PdzetH7XFObm2lSqZszK0zcuTVV05yvoQdeYV3KpUaPy0lm7+tDJ7T51kKku1MaTcA==,iv:jiIYOSwzNLwbJsh3/sMw340pswhtk77sbhQzSTw46Do=,tag:Oa6lVCPLdNhek+AWyi+oBQ==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:VQ7Tfg==,iv:6DVNeV+jywokDPMce2Ei25PKhXqfeoBf2SZYTWRmfR0=,tag:M1D8WvmDr2yqyfE9qCL8iA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtc0xvMWthSk40R2VDNWVL
        TVU0bi9vRE10b295eWlqTW41RkJKZGdYN21vCnhLUEVDVnhWRVNrM3lMbGtTM0ZV
        VTRFMEExVUV0UUxSZzZlUGhsZnNrdTQKLS0tIEx0a1RreDlsZjhvSUtNL1F5N25W
        dlJjNUY3Mm4rUWdXSE9jeWFOSnQ0L1EKlmo8GtsBdqS0hVEGzFHddd4bov86vhqp
        fRrOlLMFU11fTfD7s4/BCG5ESma1wRrBsyESYgPqffj5t3K7u0f3Rg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-24T16:45:41Z"
  mac: ENC[AES256_GCM,data:y2MtkGkhb7KDRxDj+gqHlCiAr+EurHZeRUi5zXYy+/e20iqEIvTA2O9qvBOJo/NeCiOCGNAhylAb4+Qs1mipE1Y4ruvewXfki1hM+HLZycKtxlWuReWxaIjYzlGXT9mpW6pJyQ6pF0TgG7V3NVYeHVjCeDCbDLXpvFAXIZu3mKc=,iv:qk1X3j6wcFub683BBhqQyQxXKJ7zSEnx9WS9PfA9wTc=,tag:84p/z63JIOV5n5TrYiourA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
