apiVersion: v1
kind: Secret
metadata:
  name: woodpecker-server-data-r2-restic-secret
  namespace: woodpecker
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:1mSNgsk1ZEZU2i1Vpvi+kSgu1yYWiD8gAZNjElhFDlxxV2aXyfiJNl2/4V4KECjwjDsyoSbnaPE2Tm2Z56g/1+t5u9oDBqpnufmAR6igL6cwqbP+F2U/mhOPxCrtPxSSbchaARFoLC1NsLzPU9I=,iv:FrDCy/mSU0/Sl9i/v/L8VamD3yQpvIqD7aOLNCzckHQ=,tag:Yw0H8IYce5GFBgdGOSscPw==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:4LSdLtdqSnandjKLJ2TDRAwJT418tQ8wPiVYRv8shqoitFCsKbz9MC9GXWs=,iv:1hQIaYA5FGd8vch/CDFIZI/t4TcoZea0TDFlpvUXCSA=,tag:TFKZqO7OJEPRnYmTh8hnxA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:fKnUZbsC1vYwUMaSUWsMOBFmXzAok+CTjRkT5kMuKbQ=,iv:H2ZebUrJFSUgsOV5azYsiy9DBFD/Fbyh+1YfszKgYBA=,tag:elFM3Qtk9ko7KrnZWVgGoA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:1ZHFkkmv8ZKIZ3ZwELM9wmfAmy8bL+uQTMUcrz89eCV47P9eLkgdptrR+K5dVefmOSvY2p/AvmUnZ1D7gDtbVw==,iv:c5LeVcsFeZsiSEmTY9bojPZZqCnw5SNd5YXOqVqoYFE=,tag:tHVyQQl6nerc1BXhBIylzA==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:SOT2Kg==,iv:5bYfqHrV4rQJKU2lnJjgYDXx9OXQw+X52XmRwAHv+U8=,tag:3OdsKxeNckG2ywgJv6PS1Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZYUhTSHVUQ2V1MGNZbE9z
        dTJORnpQMGZ0cVlRRjlnWjRWU1ZZVDVzSkRRClkwd1Z0N3Ivelg3YTlKODQ3U1p0
        Y1J3emF5YjRNVHhNY3M1Z2xOM1FnSE0KLS0tIGpLT085OTMzM2VabXEvWHpFbERZ
        UW5VSGtmTnNFQ3lUNVR2dHR3ekdFbUEKkx8gqPtjdePiPo47FyhjjrH2pv9uw5S8
        7oQWdTEishPC2xTVg+yLmZSHCIVv8OozyKhKD4sEHMlfxDeHvVIJjw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-14T10:31:55Z"
  mac: ENC[AES256_GCM,data:kNu5sizlncsb1Ixlq8uH+1J+w06AeyoLsNs2zberlNCSuOgW+aCImkKIHzWIocVBzXOdZHmjOlkTxvGQAEfPY5QjQT739dmieV1cbQM8N8rc47JJX57MdNfH9E1oDKhc+UJRdV5smmU4bRUE4pErCX2FD/G4MJLJ/n4+95Alrxc=,iv:06ncnfUfHCsg/S6hQEWOoiJN1vb7kAY0soLDt11KkIo=,tag:pWlHNq06LOjWXtW/j5ibRA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
