apiVersion: v1
kind: Secret
metadata:
  name: woodpecker-server-data-r2-restic-secret
  namespace: woodpecker
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:AwnLX0iXjQGxaBENG/8aa9Fhs/KxpfrV7alyGxCjSABdT82RObHGCLg0O+rNl1YFeJKIiPUsIy34pDttA2WOU/zVa+bBl5C/ESXtzvoslSAGRg1/p175LIUFfjB5L5KA1AunYtGhFCyry8UfNrE=,iv:5lvpJlHELTPPx067y81gZDlf/BqVcuW/6nFoXQ6Tn/g=,tag:3ZbVVMUSWcONuAG4/05/8w==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:X4pHzJ2/1qgMGRH/zAz6vL4Ehk003w3z4AQRDpkTOLeFP/m1/WrfZCNDk8I=,iv:DDrUCXSL5gmCKOywYycwqAoQ7r6a0ydVlbZINgsqJGc=,tag:d70NxxMZfkrHC5F6Nn8H6Q==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:PyPxvegU6WunabS2GPvtX/zqziCxmxGucLtUCYApyhc=,iv:i/x+NiwzQWE2+DBsMzYH15B86RMNKnjnqpvvm8lunx4=,tag:hhA3PJsiF0eT121yOueCsA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:HPRSLVxF69Ar7lJ3j9vLzCqRsfzq2LUqLLv0mwwPALXzOe3DmygUPia8Hq2wTFJH4zv5AuH083UhbTkgHd9Zkw==,iv:EUYF4kHcxiSLRAYHXJ2dW7NMX7o4l5pyPJxcSnLa7bI=,tag:/Bu9RuG1NOoLmyPkJ+1NlQ==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:nEJVhg==,iv:dXvytYhLO7F3khDNhDeF6qTgxgn+ETBOupEX7WxMGZg=,tag:+9f+qx+T7ek4I4E3I/Xd4g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1S1hpb0Z3WVBHS3JIblhP
        dy94TGE0enJrT3NIcytuRG56NnlyUjIvNTFNCm91TTFoUTdQTDJtSXRTNWRxL3JI
        OGxhREpTeUh2STY3disvckZPcGd0YWcKLS0tIGZiUFYxRXArNS9lem1KNnVjVHFX
        VThMcFRoNmZmRjFoMnFUNzNJV2FSbGcKcGE4q7DC9udYbsVR2ZrIExAjgkQKUnrp
        4SYGxdRqWtGsjktqg/nmZQspAHeN5ouaylVSuZRUmC8yy8zc842Rkg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-04T10:50:08Z"
  mac: ENC[AES256_GCM,data:p1ojN5ItU7MK9dBDkDU+F2p07GXooWZbSoIu4Dgj5orpesY98yexqe3N6fYGzS94N5EytPlUPVbAEoQYiPVL45M4bHPzFXU07IeBNbgqWWyLwenR2WBWmSQa2ONRlvx5W87tnyumdtqbLGVJmjWVWdfzgfVxD6T2hCl9U+j9KZc=,iv:AL5rrLENw6zy6D/KdKEYyGZ2X0WTtqQTzp/NSaALUOM=,tag:to7KB/lCe5y1yv25AX/lJg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
