apiVersion: v1
kind: Secret
metadata:
  name: woodpecker-server-data-restic-secret
  namespace: woodpecker
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:Ou0twYZh+7V96MNPIb0+mAXZuig761eh4Ys0Nh9mXXlrsATwtScU//VZQlI84oJH1wf5uLnQjx5iYmJUwJvRmyKNLvj19OWM44cwZGjbUkWj1L2GaTgnjsu2HQc4wJU=,iv:LWIxz/U951TJRslHaSWICD/nLNu/O1i6oXJ1L/LuzNQ=,tag:ZLXZgSbsK8WpS9f+uaQ4pg==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:vGaw+HPC4HyDVKb75XxBLINT4oSw72k8G4XZ4dwzPPOQa5Fy96/oni4nXKk=,iv:PA7ZWx3+xSMDAQ8OZaubWVXxlzbJo/HSjrxpMA0Y79w=,tag:aTp2mFv9ysyRboDuAhviLg==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:B6SrE3OrQxirafurZAoq/IKkVetUTX+x,iv:YyDTJtEBSaihWmIL2lXH+Wm97j+6BQRz1AsFqmdorOw=,tag:1jCakupbEK4K2xZvcoQbnA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:aEQYtwtNKU9kvel/nijSoVh5rE3t2aoA2TcciBNOG5+uhgISJY76aYriIC+xjQCJgXZWhIFVL5GyaFG4PAAuig==,iv:dHLeYcNFnIGkKIigHIPJ5k4hZHmvrKVc98oHwghjMkg=,tag:NUK8VXaT6Nq/xU7wqSiOUw==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSzVkOTZ3RnVrZ0JvSWxm
        bWsybEZtS0NCRXR2NVZlbU1kN1pkTjZRdmxrCjRUL2ViVnlKNml3dVd5bnFxS2NX
        N1VzbGtLMmczT1dzWjhuWGdGZnd0RncKLS0tIGJMTEppaEtpaHQ4dG1XbHl2VEVk
        cEJ0Z1hUNWE2Z3lvVWFFUklMUkFDWmsKnXtKRd5kTBbTXiprawwTCOJDsbI1o2og
        +tRLAqaKW8pXMA2J1j7eRA3yQfrRUGvXDSY0+4yjRwJ2YY1JdKWuNg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-06T15:16:04Z"
  mac: ENC[AES256_GCM,data:9a5Kcbx86wkHZ372LGyb3BI7yKkiQgZSetM+F/yAQDYp32+p/SVH6IBd3WGEQGBeYxnV/cUowsJAd2dZnpCAvcHsUyw2GuXBtzxux7X5r1ikhbDfeKdFvxmQScdBu07tu5HambLM/RNRJjS09AI6RFGXRo6sfuTh0wNOlGEpMPM=,iv:7BLFEgP1X+cF7c+GdQ10oCZHE4h4ohKXic0gnlPpt7I=,tag:aFs/hMmM29sjCg5o3yMkHQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
