apiVersion: v1
kind: Secret
metadata:
  name: woodpecker-server-data-restic-secret
  namespace: woodpecker
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:p8vew07Be9NJ4vTCMZyUCBlUC6Mv2o5cvuh7HqHnnm6Gx8PxyEjEwFDs8hqCz86PZvi2Veh2Aou2h55OBDoRPD3COz1MEU7SKN1HBWCI4LNDFiyKn860kPShBaKAqAc=,iv:sI/GnmrXJCkcvpSJPGwliwunyDTggSBosBFEc2Ng/N8=,tag:dbGBdHlBbvTlY7A69sSHGg==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:0iQWzWpMqpLPrStQyqqfGcWbS6Mh+rjFa+EwnaX5Q1T200CJue6ArwAPFYM=,iv:LRBEjj/h0RoV1WXh/qgHmoW8yvBEicGjMVnuGtr35/E=,tag:WIfPB/6HPnESkGt20yyuxw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:9ZUWnYVqoExK1WiqyeOhdqcVrwnbWJOt,iv:P36x4NYZIOTIoG9WLKabVXgINFX+5WBmB0uTnGhd2so=,tag:RohJShGOf8QLgh7YzC6p5Q==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:x1UI+ETN2h1Dh6dme2QIRWsNuvq7H8JGNdrbOmsXI0Ozcd6fAGMz1TmmOxk3mXv0Bik4PVTx/c9tPnQmhiLd3Q==,iv:zEuDxQ7KXUfLwtdcVELqlYlVAX9JUg6940ipSrAwBeY=,tag:NSOT2jaXpS5BRfsW0Qxhkw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkb2hjNjZxa0hpMUZFV05u
        QTdMY3ErWFMvMHdhU1FOTWFwMWM5dW5ySVhRCjQ1NFBTRnMyYi9DUFdvNG5ZQUVi
        bWRBQUR3NUVKQzBlQnMyY3pJdkFvNkUKLS0tIGx6b2JGc3lWcE1vYnlVL09XOGtJ
        MU9WdVExYldvQ2JmTExsYzE0RU9ZVEkKNc7GDD3EKwuMsKy5ScGaDhwJd4q5/FlR
        fu+WDoGWeXAWLU3U66HbpRwqG/fh/w6VgOzul4NmUpHvU1YZwlzZAg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-30T15:55:57Z"
  mac: ENC[AES256_GCM,data:JF3BMIE3kyfB6gLOc2+4o+k2kMkmKTsRQfItdpBgXHiPSsi4sTLYmh7nEhk9xmA/htGAOdA+DVKZvxlq+a8Jo9L+L3apU6jYUaLPUojSQI9EWZsKNMkzjCEGGvtQjSQ7WvBSqeDVMblJFsQvDq0nENUhVj3J5AzESfa2LDgnobg=,iv:KZu7atEjUZbJMoXxgosv/OxFzH5E8LVpTLY/lldNNmQ=,tag:MWDSWc30lMp595rGI9/38w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
