apiVersion: v1
kind: Secret
metadata:
  name: woodpecker-server-data-restic-secret
  namespace: woodpecker
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:5auieCfW+gnEOg/JJ1EX4YF11RDIswLum1Mn45l9LMmJEzatGWCH5gMipjJeEmKG5EI7FdqCSdojfSiwBxcezkDqkY0NTChMeB6eGMu7QWd60t/Z7NKA+tqHEjtRhZ8=,iv:O8ZjdgdXIheUhHuDi0o+75qpo0ub5iKy83FvjEoiFPA=,tag:qcGTcpTKGJAfC89Pnzl0kQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:x/jzEFzJHl0KXElhrSldUKkrpOoxxheRnSEzAFUTEDFAAtNVD27/yOq60ls=,iv:esNB4cnxMk1G50O+zvuAPawojHqzL1IijW9QfeZXG10=,tag:wto+5jWIK4l+ZxpC7zh2+w==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:2L5C5GoF1bIKgz/wbjm/pnn8xXnoxKXJ,iv:vEfN9flSgBuy3ePq7WkCz0uRXOaRBQCLJObzP4wjb1s=,tag:i7YfeDpB40xyBsdqCnmLLA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:xInClR6cQtq/86YfPuWDouuUCTQMIaPR1cBkGNkc+JtwuVuDasSR8Zwv/8k2cPXs+OrM/pYZCrDPeYn4kxayZQ==,iv:zdtousohP2A2C9jwBm0swpeAqmJ+iZu/pwMwLauabAw=,tag:l5tOOPyJ7E17mhDhs8dTYg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOWkF2ZXdEVWlnUHp1RWpW
        dXZWQmhYTFpoUUxGdmtpaG1mdXZkMnlvNGxBCmRicHBJejgrWlUyMERuRUtvdFlm
        TnNyNENCbjVpM1RaVTRPc21nRUdQNjAKLS0tIHpFZUpOWXl3NWlDVWc1aWpXZCt5
        M3V5bm5xdzJ0RXQ3bkc1T09WZjZMekkK65NSLY1O0SqWV/VF8jlTWf4MAVtf9yzz
        QB43lXB5KEnziGYumj/k0L8Z+7+MIYR5RiurFb26wdRYiBSrs5g3hA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-28T11:31:41Z"
  mac: ENC[AES256_GCM,data:zNrjfK1s01rC4ggiik2tyCIYNm4XO4nLe44MS2a3etCxYE6EOf9LVnuB3bDzfak8Zm2g6ihktEJovvao3Ll2d4YfOLNRRi+1bRfeqLf6CXKzmruJOyXkp3WpN9EwVE1RZsM4uede59HIvH6JnyXIjLeCS68ogWN09LQweJwB+jM=,iv:G55Xwmu5O3J1bm+Ne+iPzBjjcWzBpy9vcpNKpvyoqLg=,tag:YJ/MLbtE5V9dEAZVh/Jz4A==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
