apiVersion: v1
kind: Secret
metadata:
  name: transmission-config-r2-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:OuU6Vv8DQKBS13qjvpWeS+eJ9Y5HxZkpbaNHJBionAys3phq4r+H5EfRAP9uXDPY2loovRDSjgnYZZyCyYyB7o+lJaI8HxdvvNLA2pKpuV9Ii0G//22q28+p7zzkRHcNNqpCxE8M1i+Nw6o=,iv:PsfVNilJ+1oFxjbIOvD9TuiOIMvIVuHcwDL50/9Lggo=,tag:d32bcliXhA/WjBS6RYqhyQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:2tXGQn4WM5L2KoTdBjJhCADuaUukenj48FyC647QmOok0UBBDpX2o/xUHCE=,iv:BJJa4asQd7i4zlN63kYnN5gk6r7DmnhwKwQO4iSI7NY=,tag:FNql/RJr506pp5cDDhnqcQ==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:mdcZAvp7IoxZL5CCm5Jbof/MktIrLVwAUJUcIDttKhU=,iv:fzL1EPR/Ana4x3/qh8r87NlWa9gXsHqgds9p46dR2UQ=,tag:zo98FKklxMXbNSEheSfAtg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:JokWIuHoyJu+dsptRPWMhMW7IfXRst+aIoF8Uh189K8LFOHH30rjsnRMn/RHug4Vf0PALV8DlEotnLggMlrs0w==,iv:wnZNWwLflio9YHd6zRsb1PSJGdzo06ThqWkDf/BSuFY=,tag:wsNt8haQSTwA9okvmRvanw==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:mrALxg==,iv:X1qQgUOluZdbqp/3Vvn7gTUWxcmwe0Tcte8qltKZIs8=,tag:Zb99n8nrVzBGRrBQcQ5ouQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMEFjcVBMZHlQbndsYktw
        TGEwWmdTK0JSTnZOYUhZYUQxTDN3MEVrY1hrCk1MYlAwZkdqOE9lMUdZLytpM2xP
        bGhCQnphL0lJZkQrZ3g4bU9qaDlkWjgKLS0tIHZESnhXWnVqZlNmQWYwUHZFT2JO
        N2JwOVRZQTF6VzlIc1o4VE8wTXpzRlEKEnAl6I5g+PoKyqVdiuPfRTKKNUofMBvj
        T1VgpsWNTrCJX2TfAlDQAU46nNY/TjRj1fTnUEprBGq/tTSsPi7ueA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-25T09:27:33Z"
  mac: ENC[AES256_GCM,data:B4fSv/tpkQBSDEgNXRPp5XONqUQGMRrQ0TDxbmtNClZbuIdBItiVAOOfneYTTqxWsrc5b4p+stEcneIEecCPcjoLC2vDMsLPcFSqyaA2DwI60sq5x5m1w38sDMGwp5+Lxh8xzhP4h6mpw7+V8CTGlHvGB1rg7KMVB+p0KGP69F8=,iv:ivSgRZkw8kzd+2ww4pjvCmaaFVv95rmm7G/p+UQRf3M=,tag:KHVRyCbsWis97ygTlzLTvg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
