apiVersion: v1
kind: Secret
metadata:
  name: transmission-config-r2-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:0SNUebjqbbhd6Erk8vWZXZ/dFXlWX4g/Y4W63uzG/8O1u7dgt0XpWnt32RM49JZqJYnA0OEej25x/EcIPZVv6DkafrC17zePUeY/uRSpg3GXH3R/fqUqrvgqeYZLkK1QlzWcCXgX9BRyH8w=,iv:/8PxU0KJDCIBKlx/ldwOeKgBFVgrUyIM1emVDNSvZT8=,tag:0oWvFtYn3egXU2PWYcXlxg==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:1VThVUoXVbXCOFVc1inAnOCEqpRwKydzAdx60bXycvam/12reyDro+P/DeA=,iv:ttD1ktC5MlmRWkzm3KJOs/r/34A/IiE2KWm1Vk8csuE=,tag:A69FM1FshtUjvqomUhayCw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:+6cuwDbN/KwwJi45tc5t6TLAlsBklDzUMGn0rlzWeck=,iv:DlqEk465L2ZJ45jJ1yLma8kVGwSgWUDSBxlCX989RiY=,tag:s5y2O8bNUjeRoODcfUdj+g==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:OTxiy5VRULOUE158DpTc3REEAwKbIBRJTqxdUo/0LNtqcO9oHE+s/z2MFxAkYbukNb124nN73F6nzs2ujK/KnQ==,iv:NIhCVT3NfPyD1fAbAfk8RbSFA9i6b/ITTJq+S5PWLTE=,tag:v3wnxjDfEA3WzTlAfBYMCg==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:G/n0ig==,iv:l/1rBkf+dPoDMgpJmdkYmxigeungxgyW01IC47cmUbg=,tag:H1ApNUop8lUs9F/AjmPCPQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdEtFME42K3lkTm1GQkFR
        dVA3c21nT0Qya3ZuTGZGb3Q5TDdGSDhMN0hzCk5ScHlTS1g0dGhLZ3paMlZFaGJI
        ZnNIRGNXeXlJbG9yY0VybFIyekNweEUKLS0tIDlYRld5d0FMdjdjMXdtam92MnZG
        c2JHVDV3dHQrVnk2ZXowQ3VYaWFuTWcKuyZTGzpMxAcm47RgM0RL0I8HIF7BLBwv
        shynVJ2UOncZKrfnnDt+w1FVD+DAxV1WzuT+CEwraqaF6g3b8jDDQQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-24T16:45:42Z"
  mac: ENC[AES256_GCM,data:H/zLRjp+9YERMg3Au/k42KCn5LJMT8JCPgwTAXpB5i25gUUts6YyDnFF7XjhQPrfH9L85QLa7mJVkXGS3RinR3uiCYCAJwhJD/58EwDZ//D2yvlC5lrNyYI2gPr/EWOnR14TG3b/nkiD8pqKtWmJxnpRzoH8+xvhGr41XDOE1PI=,iv:pc9FP74HYwWkTPinBIiLcv/AaUfqi0pBulvO9htnPtM=,tag:O6lo+IJ7krJqKFHhSCUv+g==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
