apiVersion: v1
kind: Secret
metadata:
  name: transmission-config-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:beyAI8NN/oBDkZVwuaSe70hzZrApFl8VYiRONoN15vulut26KFbc9Wcb0jaSeEgSEa7lMnWD4ykGA6DrT5AXQUUo30l+HvkuoiJ7o5s/mkPJqYZZFSDqqfzVQLc=,iv:GUdLIFZnZzu78U0UlfArKuDORnX7HItXcIOtElzJhYw=,tag:ATHH1yEKNEbcKNdvkidfBg==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:CBYCxaCuB80FLqwqkCLtOVGMJ1qgyz32lZniv5Vd3WuKpznHoc0bUsD08jw=,iv:+OvOt1I5EjtlHPiwd+WW2s7ygWCC7xna9Sc4qSNLDiw=,tag:lb5JDQZl1tY8Cv5BYRRz9w==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:OWWgQFIunQSJUGGIeTCq8sVtAzXD3WSN,iv:aeBbN8+uOShdONzBMUxALi4z+EcXxkG6WE5h6wBeGfo=,tag:9AFqkMGRoKYkspmFfGCPcA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:hqzx5G9cwgPtw+dygJ23SnoL+kgNl/ERhlFQPCR9CPvUDKkj5uj3AFY3ZNxiG8qYGXtJbFZug7TWUF6zAyhL4Q==,iv:v8lznLAJGZwZ62ub1y4M+14tN59cThm/u+L9Xp2Xmss=,tag:nuIPUQHc5gDLFTpc9BOuyQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYODRMUlV0QnJ2L3F5NmxV
        YVdJOS9PNng5YWQ2aW9GZGVMZzhmZ1BmeVVzClQzbkIyZG9halJBWHZrcGswamcr
        aC9NZFlNUUlhWjJNZ2NJbXJBNDVtRTgKLS0tIFl5bmdyTnEvbHpGMGpPWlJKQWV1
        emd2VWFKdWNacWJydWMwSFFTQUxKanMKKXxl0xe5f/wuuQSrjVGpYnLOmhWKNk3L
        Z4l0SV0PuAE0uowb1xUVPQAWHdVU/KVu4amcR2dSc6nLWKFIouPN9w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-13T09:58:53Z"
  mac: ENC[AES256_GCM,data:tnRBU33pMJh3r3hr4KeXHiNfKaFJvnl75MJbH0BYV7l8Gu+NPbekH22F77TlZt+chI1Twe8hdi6De2+e/iuWF66bYUGuVvi/IsPuXDdKMRCxQ++tZN1HPFD+E0qOkjwxPDGVuG4OZ4z/w25kDuHw0y3GQFYfKbY5XhC+KkBUduw=,iv:unit4pZdFl7sh1J42f5jh0QPwnJEYy7mIaEP84ZQlsA=,tag:JKQmfqrWEL/VpwkizjQtrQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
