apiVersion: v1
kind: Secret
metadata:
  name: transmission-config-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:leEfIU5SyvhU1/OsLn6TSwZpo9y0hNO+WCRrRRuMjX0sLQsUMnzqXxtwR5uqbGsumo3Hf5Sw1lUcHvncaMePEg==,iv:II3v9MXLG/TEz8zoVjCycR1XG/bai7Hiaf5PUw4KS68=,tag:ZtLfVREYjq0slp78PRg/tQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:D869K0FEprpMsy7qRPErVoy66pjoYj8OiCNko+xnfia8zMkizgiT7hSE6QY=,iv:jPaejaEU1hR29vslZWHsf+o+A9I8/zmWzc9ofA/CT44=,tag:6DhuliRt3sT83sdMKxT2SA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:OstodqD+vC9Fz2orxsZQ0zxklmDMmTZIU9c=,iv:bPJLMtVPGMLTwMnw9GEYIcz3Y1sWqWlFHsIxFmn+oPQ=,tag:8vnJyzzDIw8+oI18BOArTg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:EQ/6LiQgBTlqk3RKZxaCW8q6HT+4YmzOTXUnWb/jn5AXUaJxTKZEQnNi0KJaPqtHvaBaQ5b6ftR4Zx8WkMmpmA==,iv:+95mu02OwCFzb3yls/OaFh2uH2rgl5zPecg68cW5Df0=,tag:UhQTyfvack1HkC+GRlkzMQ==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBic3B0N3JVdXVxUk9YZWhG
        SnZIcDdlNXBmdGxKeERoT3cyNkszRm5IY3hZCjRVd0RjTUxoVnRwTXJGVnVyMzJE
        RUdHTmhCZWZneG50VDhaOWEvOGFvOHcKLS0tIEEyY0JPaDVQQmswSzFWRG1VQmUy
        QXBBSENsTDVFUE1iWm9NZ25GaWRTTWsKihjH8gFTdaZ52xbK8xjBZl8oKnEpScX/
        siR00V0d9HIuqsSei6Rqr7jeLVq9DWlfSz5hlQGn1ynvCYn+o39e/g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T19:07:09Z"
  mac: ENC[AES256_GCM,data:fXE9qhlhP4+aKiCbSvJRTYP3iTHBYGyx5yxMOJmisSlC/pgHa8ZvwbCEs1AI3TBtHHBjxBT/m8VhbrVduiXdYipcnJmo+RnWichbG2JtZQ/hKTY9/FxUMhCa7fzN5LOo8VyAQibUZKrz5VFhUXtBxbB7sHU+fqk2TUHHDznxj6A=,iv:VFI+g8oWISoZAvly8dkwKF4PIgs5KX1/BthXylI2lLs=,tag:0ZKh2xZ7PpLD8HCbj0w0sw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
