apiVersion: v1
kind: Secret
metadata:
  name: transmission-config-r2-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:ftreIU/Ku42CBBvvlgTW/QSewzlwDVt7fGGWeW5x7nRzOo1YlgDXxsetK1igKv45ys4M0Ieom2PrhIvXFpFlCAgUBGIyWURuMVnSG4hQJ2oXuknfYi2PRZqIuNaROyI22AWKNl4BHvg4hes=,iv:vgMA7q9Pa7KGCWi/A3X9FhVg0d1Zcly+2VSLeHYk2qE=,tag:Vio5AuTYzCm275SSVFz0NQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:pgZEEAGu61w4sPrcEeKzRPWtP3/0b7e85f3yAfpNU6KFWbxXreY95zMtUQg=,iv:LToKH8U43Z+6C2VanhIGqQYcwWFiC2Pwg0sMZfhnl/E=,tag:FG7a7jUtueUCOIaPQQ8gmA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:U0phTEr4E8IzOHJethnSy+eHSkSCdPZKWev02upXwAo=,iv:W4DdzYJLlS1OAXHrzO3pqbRGfJIFGGq9x9tGy+vc32w=,tag:dF0rvRaU+0IDHEE5lT7eaw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:m/dEJ2e4OmSBb8JheTsVYlsW1o+2NLmQlpJ2D7bpESbnL2Usvo1M1nslVAXEFYyT39RWZKt1ITTZRlsXdWRA0Q==,iv:nxaxXFKiXZOX7cXd6VcoP/8+URRURmTF7MJ9VOjemkE=,tag:3wCBz7HpBk15negL3+OOzg==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:eVAV0w==,iv:OcZOSWzDJMnKMnEkA/+49jZf0thWh/mqBCDeXkcZ1Fk=,tag:77LLYBvU1WyAwMsp5pvcAw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbXVSQUpCcWFodUxFbU8y
        N3J4Q3R3RzBXUWh4WlJ4VjlGdGdqZmlXOWw4CnRqOVMvT3dweGNaeHkwV0pyWFlG
        QUdpR0Z6a1paOTgzMTBzSGIwSWRiZDgKLS0tIG55bE5FQmRBUTBEN1NuSWtIVzJq
        RU9uOURDdllFbnUxdk8wUkUrKzAyVDAKTTuTwcj8yONNjDyFJJXZvJEB1ATs8tfZ
        7exrKBbukocB3lDevp0T02FRWl7K3RCzZs3wl1fXbK3NWjMn60ojZQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-18T09:43:18Z"
  mac: ENC[AES256_GCM,data:vb/UkTMxbVuNh++7FVdJOfCDw8T/9orzmkytQijFgsM2B8bMPKecru2sDikbIsWtrrIOb0FZsD3LNK2GKO/gYrKZP85i6u+goJFnWqLLdLmvs2Cg7fI9EM1BAo4ICDHrLQnzI/J20/voGfU1B84eKAEnpyY0aZU1qRy4oi2mTxU=,iv:CNQddn2TLkatQFu7bcWbRDN2DgOMvoshzBSpN9sMI0o=,tag:dsoe5s+ECZnGCjf3K5S7iQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
