apiVersion: v1
kind: Secret
metadata:
  name: transmission-config-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:jhetd8b1J59Zowdtq+D+dg/3K+wejLCkHiFebYmQVd/qCMUsXBaTTIrDI1JHSCm/A1QC/MN1F5PbggbMvNgHueq9MalqAxOLNoBzPOfbCVshOABQ8uU=,iv:+a/9BqXU7TOizsp3GqWJfThw/A+GLOT6wnsteWXlV80=,tag:eaAg09pr3+MZ97+WrzRkTg==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:VZSWcfL5nwKTUc4sbmojE4OQQgYg7anUz4amXd0c8TcU94zgl6vd5Iws+ag=,iv:K7DFLat38WcnZMCzdVz2cPzO9ZYWWxbErlxx7dA8gzU=,tag:JNOHENUFBMXC+O3YQ2bUbQ==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:CLN/tDW/ooiIMDXR1bgS4ba5WA5bFVxzM2M=,iv:Cr0o4HYGlj412PUGl7A5f3CTZkRcJ2obxhf2n55mOOg=,tag:MBh6WK1lzW3WkW2CARImRQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ZNOF2+XsCdvk0yTQA0nDeMKVsvqPh4j5T6rdxZNm29WKYdjNLBC3c1egK7GpLc1QMyo2YAs8vspWhRYhjL8HCw==,iv:sc0HJtk8CxyghFPnst9k2ywRsDqovpqsbOYWpcdtCf4=,tag:G9YxIJpRaRxovYAx3BkLOg==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRzJyMi9Kbkp4ZFZwa01t
        QXBSUzFIU0NzbCtpTURFUDlWWVB0S3hBdFFNClBDMzFTbFc1b1UxS3VVdTFaRU9U
        dnF0OGsxVUNyYkVwUFkwNlFtTGVjaFEKLS0tIDhhWXNiWXdqU1dCNnBCYkZIV1J3
        WjJISExiKzNTUEpPWXc3SzVLTnkwS0kKbt1f2OceglCyBKneqiQG8t4a4DWs9Fcz
        pt9637fv4MbVRFZrrBQBTGJ2r8PXwki2S09h4KQrfT/fInsDbqil9Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-20T12:50:07Z"
  mac: ENC[AES256_GCM,data:qmjf81O4in/5tkb2m1YW4bqRVF6lMAOLp/Y0+K7aLjR/Rjo8/GvVkNRDMsmHtm1C3y6KPuDdN+FemlGA8vqIBOP4yosEjvFJuwjzgz8+LRRQxeV6QXWBS8VCyNTarcmemkazsKV7vxjg+0glERtbvkLZhoKocqn+oF+2Nm1SQgM=,iv:1jyZB4gkLhJKgiXEjfgMw9ImFGi5o8hL6hfV2lM7J1Q=,tag:NwEm3SFdxIFwbmzFA3hjLg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
