apiVersion: v1
kind: Secret
metadata:
  name: autobrr-config-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:I+6XHkIuYUuIhYG0h0kC39tTuPCy5PtEcZSFEuO7VWFj10L8G8BIjpbrzVUweLP48jMezm+g2Y1/57tRMaVNyAqmzKZ1nDu9lC3Uo11b+XYB,iv:QQYDhNAvIm5x1B1yKkGYGlYY5/2kSPu69Y8juYl2n6M=,tag:oCqHOw93xzXYlcUHSbNQhw==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:N9Ymm5xVeFr6vQVIjRKkkPzwQ4f8W2HWmyJA2DqGekBRXW7Iz9+COIKg/eg=,iv:L0IWTs3USMS5gwUa9dyAynKOOggXQzCBZB9vbrTF9Dk=,tag:7vdTs9jGdY/NoalnGLx5UA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:p9dAeNsHc0BbsKtwAXr7Sf5bOHLh9LrH6s0=,iv:8RnSS3GYB46n2xdahpyXtNsTTGphPI6JDZQiw6R4I0I=,tag:NtrKshI0Vbb1UIqu7CpZ3g==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:te8NRC+C+7JA1DqdUmlYr8INm+nDvYiqLvytunJcKK3h2NF0KuCUWy/Yp+ooYtyz2llxAeRzTP73r24oO8JiGQ==,iv:I80mLh/5i6qF0D9mvo7ZbYt5NevMeXL9w0b+mXaMvS4=,tag:u0CyKdUotpGzCJrbvFZZHg==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrM3F5YXpPNnMva0QwRml0
        cVFzTENKdG0yOVBsMElNWC81VXlYaFpmN2xJClFmRFhHK0hsYkIyODQySGFLTVBa
        YzZiekFtOVFwbWgzQ0c5dUJVT3ZsSkUKLS0tIDVlY3pnOXZTY1BiNVMxbWxkdlph
        Z0ZuREhFU2c0M1B2Umo2SWF1TytUN1EKhFCEGpRC8clsKGMnW2Kx0guz3qv+G+Hx
        PA+oW28t0DhnVK9UCLU3rRPzgJAwtEedSgF8OiMB46k29QS5QmGR0A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-20T16:34:56Z"
  mac: ENC[AES256_GCM,data:kZkLer5ERbwdWE7kQQTzW/Yf993QhWrOlSVWYnPAo0ew4wdJbl2ukwOEH4QzUOS986g0978oM+26Q5j+bW59/kJe5KKUIn/1YudIZKHWnI4UR35non/GIGW5vK5xfE7lM0y8PsXeiYG1mk+ustPCnYZQD7KpK7WI+I1jrpPM1lc=,iv:ZT0mV6dBDs4d+NI0MlGqnVjAmKVuJTbwX96HTUsx2Kk=,tag:fLAZEpWSsFwJ8UJz5CP1nQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
