apiVersion: v1
kind: Secret
metadata:
  name: autobrr-config-r2-restic-secret
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:qM5bA+WwjkM1qWFFyTeEGKf+33/Dph56ud12aa6ScIXoTowoL+iGfFwKf1IqwN0HFJnIofJpNwcm4fdHTpTNwdoTnQFyjZTp46DL9ZzELF1jHl7Gjgy6zTA9bFP/gt3Z8Gnh4SlT,iv:5qnjUYalC8tgWtScqi4AxSWKS+wKHkJX25JRCgIIPiA=,tag:4wXiwh3/NimUcshKXfOLCQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:Z7FmjGOY87QiBXnxT4S9Y6NpzZClnYchxL1IORy3lv8MmCUnl6EpROlk23g=,iv:8tLvPJzObx3gsrQmuZciv6v2qDGIcrsE80o/wVyX228=,tag:mjs1hNNcsIHP8NLtWU3cEw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:vpOsuQpCKIjpZxnJtZh0dv6K8WCP7E935dQNBAi11VQ=,iv:Jm2EDh/xUWsupVqX0/vZhh37rwF1jGNb59JWBT9cIl0=,tag:U8KkD28qDnRrI/yBKyL+6g==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:N9mbEBApE0ADFuMdy3EBcUXHGPdVXoHWO64a8Cvyh3LI0ufEaG1PvxXfQTmkcGpDEpgGbKVxhYkTY6Bpc8DaRw==,iv:afF6eNpongYqSgUvOXJGVU5NUSqrPRZW5e5mcpt6b94=,tag:ffwbtYPUuFaCkUTXpii5FA==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:8TiylA==,iv:QLQeuJV2vCImPWZSP3D6vikLr9HF08IjCz8lzjbNw5s=,tag:5VhgaAkIwj2eVftTNgp+Fg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Uko4WElJcXJERWtoUUVk
        TG5YMnpQb1dVeTdxT1pJaGs5aGR1cEFpQkEwCjFtZDJVdkVhbHFBcXAra0Foc3RH
        NDJ5b1lsVUFSREtQMWpSdkh1NjVHWFkKLS0tIG1oVDJtSDZoRE9FK3MzQS9DcHo2
        eUpHRkFCUkg4M0VueHFncFhyeG9kamMKZjD1wg7Ge4kp92WDVdL8jlwdhmp4Ghl+
        ACHmb3SxZEcsNIT4Cy3CqJcivGfGwjrVWAnytBehwe98cmzrhMGByw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-24T16:34:59Z"
  mac: ENC[AES256_GCM,data:IE2z/ehl1KSbnCY0IPBStEd0gSKQEoxm44av4+IapyFb7e8GyjYgEiGPH2lxCIAOHExZvVApTkBD7TFCJTD6Hpnq4gHctzc74G82TWR+03NZUwNWJ9UrOJmnq41KAFbCCYYhT3bxlt+f9zkpwzffbPifDS33/3NSvNHkbDa2htk=,iv:pC9kUCMPi5QsErWnsxUR1hICMNIN/YZAjoHsSEhUQcw=,tag:FXI0iQG85alMBfs/vCH5sA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
