apiVersion: v1
kind: Secret
metadata:
  name: autobrr-config-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:q9UEKyQh5KrSVhQGLuRMCVWfictygGmdNpGR//7S3+mNE/wCkNSVEJogsJqXpw/GPBDXPqhzDnP7c+c=,iv:BB1j8atBzB2hITl8nofZdWkF8GmQcPLvtnu9YD/ocmY=,tag:lMVggj6eaYoRiMroBbtmNg==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:pcM8lBlCqCnhFd6Cm02p0EUFJnsghY/GKiFFJsqutFz3z700rX8vASEAo2Y=,iv:kr/lPeVurC+BGHvRI/gVt02m2d7+h+i/3gFqiqXwSJ8=,tag:ybTaAeohybwPWbD3SnIcvQ==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:MtnWyN0w5oR3v4PUEIk0IS/JWzv9rqQBydM=,iv:JYZvelljBelroH9kIuRMKemPAKosVJkLDZRz1uzTn8U=,tag:OIkgO6tq89qXivjLe+Mjhw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:JMMCW5PT0O7RzM3VWsM6LsTvESBDECEuQYVcMbjPb5/DiX7oHv6pe1sk93AuyK28XGbsomTcaz4rqivboFr/1w==,iv:9HO4YS7nLcQ0l0GmmUPYnciF4DxzTus5KxLppzC7wFQ=,tag:a8qbAG4Q3bRsVe5tqOlOtA==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRWpzRXVaTU9rRGszWFJS
        Rk5tUTRCdU9OakhTcE5tbWl0aXhBUVM1cGlZCk9oRTBCUldiUjg2UGhqT3lSWS9M
        RDYzYjZ6UkI3SDBvbXNWK29ZWC9OV28KLS0tIEJYOHBoR1YzeFNtbkxCSjFzalgv
        bXp6NHc1aXhWRFBEZGwwYTBIRTZVTU0KsNBkXB3PWP7Ox6P3fX0hTT5SALN5T9Xx
        qEGXvIxkTRAnwIJ8Qy+oVCjqgpxIjGovtI85v58BPuWzDsIozkHt5w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T15:14:56Z"
  mac: ENC[AES256_GCM,data:gpMa3leQrsz5UmBL8ukh8iZLFpdYG4Ljcht0vqc47337A1q/HPmpk1PZOHtyjv0CxiryBLzuFKXG77ecAgjJ+/qD+I4uF9NvPxZRJ7QU8YNQ7Wpw40Ugg9jW+knOmg/A8UbjDAdUT/OkrgNfGIuE6rd5UVz7N/4e6Za1Az+68rs=,iv:SwjJmT+mJB1udd/0/zkFy6eJbrKvZGpuoRCYc6hLNSo=,tag:AA3DekScCeFJl2ESNeZYPg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
