apiVersion: v1
kind: Secret
metadata:
  name: autobrr-config-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:4Cu4k6zWho1Dc5A8Tq11dqtKqX9q0wgB3oq66wgc02RZcQgcfEJ6DVa3cOWsQuwpO+sg9FDQ+Q4plbgtTIGVaMn03UeSUX/QMI7GcGPkpkrzUS+F6dja,iv:NIbe/wp12cofKszlAnZaJUxUqPvCypy9zHFgZ0b+tCg=,tag:upOydYmnTz5nRkFDT9Bn7w==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:P0T95GtfnToftHnCVh7XmhlmhiH9iC1lcJvQbNrdxSvPi1F/r27+XBYxz5Y=,iv:92+0a+4KqD+h7JQsqghiiG/U+TJTqWbhGtp5H7nQi58=,tag:IM8lcjEvFyJp7UGvM7JGkQ==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:l/X18kCuXYORsg8afD1aDdVMTGOiD5ot,iv:tjDgXyK2iX49vOSymbg72T0WV4SST0506LJSX5i209k=,tag:xYK/OrPCA3cO29mIZjHiqQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:LRIHB0jr4TKu/AfSMoVbLD6YwIbQMD0DZuxSoQ/cJnZQGL2T4m2oDHwuLRQKCEvgCwXEdK8oRAqZMCGApncMeQ==,iv:tlSDEHkbQX/b9rg+O+oP+48KrDQlHC+tdK4jRCgZHzo=,tag:pdrP6n4AFz9nzInrXsWusw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1QW1qM3YvZEliQ2pvNkNR
        a21aOExWazduLzkxV2YxUUh3MzZTQkV6aHowCllvNnVVcThPMW85U01TTzZrNllj
        UTgxdmxmVHRGSjBrTDBNVTZwVTVYZmMKLS0tIFYzYnlvNWEzZDBEZmcyeElvcVJX
        RFhVWmRIRGhjUGdaWjJUZGl6RFRhL2cK6rajvZ6H2IhdYMi7HdmoAHIs40LtyJPk
        Ma5/6i+vbvhHz99j+Cuep+Knza80DShkr1/1sK8sh3Z2sNwA42P2hQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-10T12:46:55Z"
  mac: ENC[AES256_GCM,data:ugVO6dznZOW3T6cEFvTwNnVlkNlT7F6K8MPvW23TYdsC3J09legfJhmx0qDGMaF1ptskEpdL1n3jSd6ulwfQ9nR0reZ4dRvoT3HuoJ4n6K9Sxoy/nACG0Z5/yij+vcdHm1dwGRkjz6S5ojk/hPKi3CDbvhFwhVyjdIBCA7x2Xn8=,iv:elYd4rSxBcGx7V+o2Y2h6/AyFeU/gemnTvm/1gBOOKM=,tag:EChg1nlS9YM6h+d9hiLC+Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
