apiVersion: v1
kind: Secret
metadata:
  name: autobrr-config-r2-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:lv9f2qzSG6ufF5bfK1vFA4yvGwptGcB+QxuQ28oPvODUmYUOnxRBU+ART5/a/O9GxowErBu+3zP9Tnc0kOU8qhzxXaa4TnrEbMx7npLv2bHAmwgDJFXrNeeQIGuvp54Z5Pw4LjFo,iv:3igZFok7EzqwsYcnfJ8rk3Lvp2iOTu+Q51bdHqEOCXc=,tag:ixl5wTEBwelhE/0DgW9J/g==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:WVm/R32HjyH7qiDpiEagKvKGjPDqAEKMKp7dMTJYmYR9+YlJ1XWhMocbG+k=,iv:1iM+cLCIqVXp0B+iNjePUUZX7XaRqyJhMB5YT5XaybI=,tag:7EJ0gT+wQwBp7/5oSiCwag==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:5t7htaeferWHD7oXY1nJox8fW7JBZJ2u54MCKRmpH60=,iv:OZJa8S/8QZhl+49teiNJ2QASInoxaB8j2tTwEuozzcM=,tag:8cnX6rzZcEIcnjVlz4meMw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:HtD75I/LsgD8L/tQqflkSpo5O4rPGojuVNS/Ztp81KymhNvB4Tg3iv6RaZPvYF8YzQqHtUfdsf7j6pB3umcYxg==,iv:WfZZHfETc0dA3RhlbsaAJ5fzdH6gxkNu54YkcfdMf1Q=,tag:zibnXpgkf2uMF+uNKGMsGQ==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:34JBfg==,iv:xIatwdex+mTwVqD/fNUSgp4uaGhIReXhbTYMvWrF/vQ=,tag:S6HjFBqYLWFEmiZuHZQzSQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmblpWenJsVDJhMG15Q2di
        RC95Qm8waVYydC9nZU9teHV5eHhNcWdBOXc0CnN4b3RWZFQxKzFLM1NIS1VtQXl1
        aDdpWWZINXNRUzVNVVRpdVVvTFhhY1kKLS0tIEordVRMaVB0ZDRrWDQrL1dkVkxo
        RmZpSittU1JoYU5UT2ZBc2d0MDFnMzAKt7tORZsVOQ8Qyon7bezfsOC1r9TCvFoc
        WuYRK3mRjmxG7WCVfjHO9UpvBY2ByhuJwKLF1oMCfnzfhAvzcmGbyQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-24T17:01:23Z"
  mac: ENC[AES256_GCM,data:/R3NryNB7w3xovdN2asjQ7lgX1sv0/sQ1AyRtBUGOYoyeP5Nc70+dAY3dM1XCYm4qHynSWH342xITW8ReOiufSNBT2EWxaT9rn0Rh5EW+O0VLuGzCjEVBGQdCf56UuF2ZZG78pQfxBJUQrIuaxJnrYUP+WXJ/dtxL0S6q6uZC0A=,iv:KXFvUvMwzEc38gKz1W+8EYBAuKlR4hT8Vw3ezMNUPOw=,tag:zNhUE8+C+emxY98xVu6DUQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
