apiVersion: v1
kind: Secret
metadata:
  name: autobrr-config-r2-restic-secret
  namespace: downloads
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:jgZuvh/8wJNi3MauyGZZTDUtFkPjTU/ob4GT+PyM8p7lVhyJJKnvmdfVu2JQYWt4l7jL2YCxucirlFsLu7PeOdzyhfYVk0Gl7U3811TYfxCmyCqiJ/fPiqbpr30qJXQUyhnp0Wb1,iv:07Mcnwhuh1+PEWOYswEGDsJBxiFuBMx1bWPO32LcqTQ=,tag:MDVigQpGIL9LJ3qMGitY1Q==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:w56kKwn8Mcf+msDxOuk68/EpF0ro2bhSYQlFHhlUeLm7n1QbJ4vm7dqXhm0=,iv:CY7wgwzwq/rW0jxcyQElDzi7n1o0Cp5Ffn9JquwomJs=,tag:3pExFDeP3rRewxHAfbckrw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:smhKVOXWDO2GmKzwcSdyhwu2UBAnk+LektW4aiEm9XU=,iv:PHaLkgdlJz2yShYekM9ZIE917Hms+8x+dx9P518G+k8=,tag:Sz/MFxkYWcqvqdrVEXuPow==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ZjnpaJuv11gGKGq21/dKd4OlLipS1YPj84c+EdvPNkG9c+E6UX1RCxDuulwOOlcdTKtuAaXXGW+uT0zNAVQMpw==,iv:tWKp1l16jsrP0y5pAtdoH1bVnr/et/6L8kxjreyEkA8=,tag:m/njmTq3MUsTINlBlLVLhw==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:nlmLrQ==,iv:lA2I98w5o3HNxyqQfMbYbE0Rx9J6/krSUa5djLr/k1Q=,tag:7yUA1wtapPG3C4truoLHeQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2aWZ1MzJkTy9YQ0ZEM1Z3
        NWhsYkJyeWFIaDE4bDIxRGR4eVFhS3ZRV1ZZCmp4c0wwVS9jVUhIeUV0ZHY2OGJ2
        eEEzc0VhRjNWTzlvZVNtbHgxUFlUVDQKLS0tIGkzOFF5d0YwNjRGS0lrSUkrMVZq
        K3A3dytkTVVLaGZSOE1ja0hNVzBiS0kKhKgEEL5pjEwU2yBGmyRa03Ox/N+Xx4B0
        F5mZY1jdzPCg4OrL8QbQUX9PRGrQKwQks7nCOGk8AjfYZCwELcPr6Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-24T16:45:42Z"
  mac: ENC[AES256_GCM,data:4ghPdLFfMcmu7Ak2bxwRiW3MXQgvJBQpEu3bTU73zH1IzFy/BDxtJt8DHMkDOZEbL3U1+ZcMd4vo9ZH48FDPyivR90S8vWWuysSDt7AbAo+8bXH9/R8Hm13NN1GzaIHnbKFT7d3I1N1YTvj0QLRf90fjEdV5vJsgwZYZ6HbRAss=,iv:mXIa+dy/ssgPvMC/2lApFDfBQM96xAt4UQcdgmSqLj4=,tag:hqHV8BTQbnmL0OSoXl+4yA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
