apiVersion: v1
kind: Secret
metadata:
  name: pihole-secret
stringData:
  admin-password: ENC[AES256_GCM,data:lvyoEsj2wH+F4oYbIMuCi8IBZwP1uM+C5yWf,iv:eFXNWSw5rNy3bxlfv+DD8XrwNtdsz3uPJLhybnHCKFE=,tag:dbCODuG7vJGIJThJ4ZfKOQ==,type:str]
sops:
  age:
    - recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcnY2a1VrMEU1MW1lUDFo
        UXp5eU9rUFZGSHdvY2lucHdQTU4raVE1V2s0ClVlQUV2cUFoaXg1Q0NXaW1WUWlt
        UWpId1NtUlRZbkxoVy9mZ3hyUGVMSDQKLS0tIElNcjRtTHg1SnA5TXNMYjRsRlMv
        V3gzdm1PNUw3MDZQQXpKZCtFSzBzbXMK51t+FHK30NuzrnfpAb2X+KzrDW5RYmql
        h78mNHjkjhc4zaNedr+4JzZpicfq4ydF7g+GeXe7vnqBeLJ/D499uA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-16T09:49:52Z"
  mac: ENC[AES256_GCM,data:RLGBG61eMRjKECaSJTejNYMXOFB8itGTEcN9DSCZGTaZzCe8Ko273pdhRHM/Qcy66hbZfukK48dSH/HA7dpUlszybeuBTTUV6aEscP9Fy8XTBDLeQQ9WYZS90a2cmixJHdhekYpPc9XPcvh7VET9XJDz+5yeh0ANg3uTYGeqj5w=,iv:Tp3IMHFBoZwSfRGrC5ZMWFmePZXAHshWRHWE9jahE2Y=,tag:mrmWhxBgsJM+taCWVRCEMA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
