apiVersion: v1
kind: Secret
metadata:
  name: pihole-secret
stringData:
  admin-password: ENC[AES256_GCM,data:bFFtUDiKCTk=,iv:xznAl15cUNKDlFcHINdMfCS2u8tv61GSwDgQ3KRWJs0=,tag:KfLXlpeD+YZck2ZwnW3jxg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtaDBGSUh5dExjT0pZWjBE
        aUwrWFkvOGhyTFViUkJPMzR6TEhaMno2YXdjCnRlbTRwZmo1bElRZldTWmtxRHJ4
        WVZJTTFQTUZZUlpVVzhsT2tjUWxtd0EKLS0tIFVHc1VFaFRGN1JoaDhQeEJDV0ZU
        WFhaZ09EUzR6cXdqNE85cTMvR2h0dEUKCxwIISu91/u6IJE7TpV3MarAuech90wQ
        HXZA+MgcbymihV2C/vaDfhCGOYDJDQ/OhIYD+njSUktlzbDyrOgDCw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-13T12:06:13Z"
  mac: ENC[AES256_GCM,data:KkxTCMTki/svdYAnQJ9CGDxi2W+nf+cK8meH5y4hhga3gvcjFCLBPMUyW7bLZzpbBdxRtU/6ynBj3POEXwkajxlFmHa7gUOi9eaTEzR7Ll/gwrM1T4wyuvwBHPufxZQtz9jE4nZPa0Osuu162/o/wnIVPzqS4N6sDoHHYqZZqbo=,iv:+CaDFfI52B5hHXlTnca86e49JpnXHpJ+jb7UhqHjMc4=,tag:lFzdb42ugSSv0a2xB6LGHQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
