apiVersion: v1
kind: Secret
metadata:
  name: pihole-secret
stringData:
  admin-password: ENC[AES256_GCM,data:MLuCRewtxf0=,iv:mA8A4eHSYNb66/t9FWAPA0h9CLYfUp26hrwnIqKXwIo=,tag:ioSW2X+zj2+Pqa2iiIgQ7A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjdUJ0NjZFMDlpSHVNOFBU
        UVg1RFRScG9TY09FSnMxNzBFOWJRZThkaDI4Ck1zaFdRVUhrOFBkcVhhNTBNSFdT
        L3Q0WWRYSVdveGlsQ2NRUlpxYmxqamsKLS0tIGNjSHo4OW10Q0kzY0NLQzFhS0Q1
        eVdqWnNHSFZ2UGc5YXJJZm5vaStMKzAK9rZu2hKBuA01qqV0N+Y9YJzHYyah8frY
        jI7qWv8mh2oHNyMNI7UJz+CSn+jP8gqgeObKfnoPQPrPeQ+TP6+XIw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vmuwa3m333fmewnm9ltl02qg9sa6675qe4459cctyt7mjcfz6a0q5j4fxt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-19T08:18:42Z"
  mac: ENC[AES256_GCM,data:H2f5ySLJZRisZDvOjlGu+vU293WfVlSCSGSCQF+7bpqKy42t9YD+q4J3/69oZjN2yuKhEa9OAX5Ybs0iFAtxgISwIL4hkC+6gnkmTZRcjEetspFnu23wEXTfELFZHH2PXC7XikIcX6mgMVgngIeh9WiNjYcPoTKFX1oLwWbDrlk=,iv:ZyFiLEEPvepxtswiTRlCQgZRJKDCt311BAkTwBVlB1w=,tag:x9XAUquu3360e2aOW+dPUg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
